import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDF01","Box Office vs Rotten Tomatoes: When Audiences and Critics Completely Disagree","Scatter plot of every wide-release film since 2000 — audience score vs critic score — highlighting the biggest disagreements","CHART","US","Scatter plot","entertainment","Rotten Tomatoes: Movie Data via OMDb API (omdbapi.com)",60,78,72,72,55,68,65,82),
mk("HDF02","The Supreme Court Ideology Drift: Every Justices Martin-Quinn Score Since 1937","How each Supreme Court justices ideological positioning has shifted over their tenure — the rightward march visualized","CHART","US","Line chart","law","Martin-Quinn Scores: Supreme Court Database (mqscores.lsa.umich.edu)",65,62,70,72,75,68,72,90),
mk("HDF03","Megachurch Geography: Every US Church With 2000+ Weekly Attendance","Where Americas largest congregations cluster — the Southern megachurch belt, suburban sprawl churches, and satellite campus empires","MAP","US","Dot map","religion","Hartford Institute: Megachurch Database (hirr.hartsem.edu/megachurch)",62,68,72,68,55,80,66,78),
mk("HDF04","The Laugh Map: Which States Produce the Most Stand-Up Comedians Per Capita","Birthplace of every headlining stand-up comedian normalized by state population — New York and New Jersey punch above their weight","MAP","US","State choropleth","humor","Wikipedia: List of Stand-Up Comedians by Nationality + Census (en.wikipedia.org)",55,72,62,75,42,70,78,55),
mk("HDF05","Title IX at 50: Womens Sports Participation Before and After the Law","High school and college female athlete participation from near-zero pre-1972 to 3.4 million — the most successful civil rights law you can graph","CHART","US","Area chart","sports","NCAA: Sports Sponsorship and Participation Report (ncaa.org)",72,75,78,62,58,65,60,85),
mk("HDF06","Death Row Exonerations: Innocent People Freed by State Since 1973","Every death row exoneration mapped by state and cause — DNA evidence, witness recantation, prosecutorial misconduct","MAP","US","State choropleth","law","Death Penalty Information Center: Innocence Database (deathpenaltyinfo.org)",82,72,75,78,85,72,70,88),
mk("HDF07","Streaming Wars Market Share: Monthly Subscriber Counts by Platform 2019-2026","Netflix, Disney+, Amazon, HBO Max, Apple TV+, Peacock — the race for streaming dominance animated month by month","CHART","US","Area chart","entertainment","Antenna Analytics: Streaming Subscriber Reports (antenna.live)",58,78,72,62,65,68,55,75),
mk("HDF08","Missionary Density: Countries With the Most Foreign Religious Missionaries Per Capita","Where religious missionaries concentrate globally — Pacific Islands and sub-Saharan Africa receive the most per capita","MAP","World","World choropleth","religion","Pew Research: Global Religion Data (pewresearch.org/religion)",55,52,65,75,58,72,74,60),
mk("HDF09","The Florida Man Index: Absurd Crime Headlines Per Capita by State","Which states actually produce the most bizarre crime stories per capita when you normalize by population — Florida may not even win","RANK","US","Bar chart","humor","Google News Archive: Crime Headline Frequency Analysis (news.google.com)",50,82,55,80,42,55,82,45),
mk("HDF10","Stadium Subsidy Scorecard: Public Money Spent on Pro Sports Venues Since 1990","Every publicly subsidized NFL, NBA, MLB, and NHL stadium mapped with taxpayer cost and team valuation — the worst deals highlighted","MAP","US","Dot map","sports","Brookings: Sports Stadium Subsidies (brookings.edu)",72,75,72,70,78,75,68,80),
mk("HDF11","Bail Reform Outcomes: Rearrest Rates in Jurisdictions That Eliminated Cash Bail","Comparing rearrest and failure-to-appear rates before and after bail reform in New Jersey, New York, Illinois, and California","CHART","US","Bar chart","law","Vera Institute: Bail Reform Research (vera.org)",65,68,75,72,78,60,70,75),
mk("HDF12","The K-Pop Global Takeover: Billboard Hot 100 Entries by Non-English Artists Since 2000","Tracking the explosion of non-English language hits on the Billboard Hot 100 — from occasional novelty to K-pop dominance","CHART","World","Line chart","entertainment","Billboard: Hot 100 Chart History (billboard.com/charts/hot-100)",58,72,68,72,48,62,70,78),
mk("HDF13","Religious Switching in America: Who Leaves Which Faith and Where They Go","Sankey diagram of religious affiliation changes — Catholic to None, Evangelical to None, None to Buddhist, mapped as flows","CHART","US","Scatter plot","religion","Pew Research: Religious Landscape Study (pewresearch.org/religion/religious-landscape-study)",68,72,70,72,62,68,72,82),
mk("HDF14","Unintentionally Funny Government Spending: The Most Absurd Federal Grants","Real federal grants that sound like jokes — shrimp treadmills, cocaine and quail, drunk mice — mapped by university and amount","MAP","US","Dot map","humor","USAspending.gov: Federal Award Search (usaspending.gov)",58,72,55,85,52,62,82,78),
mk("HDF15","CTE Crisis Map: Confirmed Brain Injury Cases in Former NFL Players by Position","Chronic traumatic encephalopathy diagnoses mapped by playing position — linemen and running backs at highest risk","MAP","US","Dot map","sports","Boston University: CTE Center (bu.edu/cte)",78,72,70,68,82,68,66,72),
mk("HDF16","Mandatory Minimum Sentences: Average Time Served for Drug Offenses by State","How long people actually serve for the same drug offense depending on which state they were convicted in — 10x variation","RANK","US","Bar chart","law","Bureau of Justice Statistics: Prisoners Series (bjs.ojp.gov)",72,68,75,72,80,62,66,82),
mk("HDF17","The Podcast Explosion: Active Shows by Genre and Year Since 2005","Growth of active podcast feeds by genre — true crime, comedy, politics, business — from hobby to industry","CHART","US","Stacked area chart","entertainment","Listen Notes: Podcast Statistics (listennotes.com/podcast-stats)",55,72,68,62,48,65,58,75),
mk("HDF18","Exorcism Demand: Catholic Dioceses That Have Appointed Official Exorcists","Which US Catholic dioceses have a formally appointed exorcist — the surprising modern demand for a medieval practice","MAP","US","Dot map","religion","USCCB: Diocese Directory (usccb.org)",58,62,55,85,60,68,82,52),
mk("HDF19","The Onion vs Reality: Real Headlines That Sound Like Satire","Timeline of real news headlines that were indistinguishable from satire, rated by absurdity score — the line keeps blurring","CHART","US","Scatter plot","humor","Snopes + Major Wire Services: Headline Archive (snopes.com)",55,78,52,82,48,55,85,50),
mk("HDF20","Home Field Advantage Erosion: Winning Percentage at Home by Sport Over 50 Years","Has home field advantage declined in the data era? Win rates at home for NFL, NBA, MLB, NHL tracked since 1975","CHART","US","Line chart","sports","Sports Reference: Historical Game Results (sports-reference.com)",55,68,72,72,52,62,70,88),
mk("HDF21","Public Defender Caseloads: How Many Cases Per Attorney by State","Average cases per public defender — some states at 3-4x the ABA recommended maximum, mapped against conviction rates","MAP","US","Bivariate choropleth","law","Bureau of Justice Statistics: Indigent Defense (bjs.ojp.gov)",75,68,72,72,80,72,68,78),
mk("HDF22","Peak TV Tracker: Number of Original Scripted Series by Year and Platform","The rise and possible fall of Peak TV — original scripted shows exploded from 210 in 2009 to 600+ then started declining","CHART","US","Bar chart","entertainment","FX Research: Peak TV Count (fxnetworks.com)",55,68,72,65,58,62,58,82),
mk("HDF23","The Prosperity Gospel Map: Largest Prosperity Theology Churches by Revenue","Mapping the wealthiest prosperity gospel megachurches — Joel Osteen, Kenneth Copeland, Creflo Dollar — by estimated annual revenue","MAP","US","Dot map","religion","MinistryWatch: Donor Alerts and Ministry Profiles (ministrywatch.com)",68,65,62,72,68,72,72,60),
mk("HDF24","Government Typo Tracker: Most Embarrassing Errors in Official Federal Documents","Real typos and errors in signed legislation, executive orders, and federal regulations — some that accidentally changed the law","CHART","US","Scatter plot","humor","Federal Register: Document Archive (federalregister.gov)",48,65,52,85,48,50,85,55),
mk("HDF25","Draft Pick ROI: Which NFL Draft Positions Actually Produce the Best Players","Expected career approximate value by draft position — the steep dropoff after pick 10 and the surprisingly productive 3rd round","CHART","US","Scatter plot","sports","Pro Football Reference: Draft History (pro-football-reference.com)",55,68,72,68,55,65,62,90),
mk("HDF26","Qualified Immunity Shield: Police Civil Rights Cases Dismissed on Immunity Grounds","Percentage of Section 1983 police misconduct lawsuits dismissed due to qualified immunity by federal circuit — the geographic lottery","MAP","US","State choropleth","law","Reuters: Qualified Immunity Investigation (reuters.com/investigates/special-report/usa-police-immunity)",75,65,68,75,82,72,72,72),
mk("HDF27","Album Sales to Streaming: How Music Revenue Sources Completely Inverted","US music industry revenue by format — vinyl, cassette, CD, downloads, streaming — showing the complete 40-year transformation","CHART","US","Stacked area chart","entertainment","RIAA: Year-End Revenue Statistics (riaa.com/u-s-sales-database)",60,72,75,62,55,72,58,90),
mk("HDF28","Fasting Calendars: When the Worlds Major Religions Abstain From Food","Overlay calendar showing Ramadan, Lent, Yom Kippur, Navratri, Buddhist Vassa — when billions fast simultaneously","CHART","World","Heatmap calendar","religion","Pew Research: Religious Calendar (pewresearch.org/religion)",55,62,68,68,45,72,75,70),
mk("HDF29","State Mascot Menagerie: The Most Popular Official State Animals, Insects, and Fish","Which animals are claimed by the most states — the white-tailed deer is state mammal of 11 states","MAP","US","State choropleth","humor","State Symbols USA: Official State Designations (statesymbolsusa.org)",42,65,68,72,35,70,72,82),
mk("HDF30","Pay Gap in Pro Sports: Minimum vs Maximum Salary by League","The gulf between league minimum and max salaries in NFL, NBA, MLB, NHL, NWSL, and MLS — from $60K to $50M","CHART","US","Bar chart","sports","Spotrac: Contract Database (spotrac.com)",62,72,75,65,60,62,58,85),
mk("HDF31","Wrongful Conviction Compensation: What States Pay the Exonerated","Per-year-of-imprisonment compensation rates for the wrongfully convicted — from $0 in 17 states to $80K in Texas and New Jersey","MAP","US","State choropleth","law","Innocence Project: Compensation Statutes (innocenceproject.org)",80,70,72,78,82,72,68,82),
mk("HDF32","The Reality TV Map: Where Reality Show Contestants Come From","Home states and cities of contestants across 20 major reality franchises — California and the South are wildly overrepresented","MAP","US","Dot map","entertainment","IMDb: Reality TV Cast Credits (imdb.com)",48,72,60,70,42,68,72,55),
mk("HDF33","Americas Churchless Belt: Counties With Zero Congregations Per 1000 Residents","The most unchurched counties in America — Pacific Northwest, rural Nevada, and parts of Appalachia with no nearby church","MAP","US","County choropleth","religion","ASARB: US Religion Census (usreligioncensus.org)",60,65,72,72,55,78,66,80),
mk("HDF34","Autocorrect Crimes: The Most Common Embarrassing Text Message Mistakes by Generation","Survey data on the most cringe autocorrect fails by age group — Gen Z gets ducked, Boomers send mysterious voice texts","CHART","US","Bar chart","humor","YouGov: Mobile Phone Usage Surveys (yougov.com)",52,82,55,78,42,52,78,58),
mk("HDF35","Olympic Host City Debt: How Much Each Host City Spent vs Revenue Generated","Net cost of hosting the Olympics — Montreal took 30 years to pay off, LA 1984 made a profit, Rio is still underwater","CHART","World","Bar chart","sports","Oxford: Olympic Study (eureka.sbs.ox.ac.uk)",65,62,72,72,65,65,70,80),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDF batch)")
