import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCC01","Every Constitutional Amendment That Almost Passed and What America Would Look Like","ERA, DC statehood, balanced budget — the near-misses mapped against public support","CHART","US","Bar chart","law/history","Congress.gov: Amendment proposals (congress.gov); Gallup: Polling (gallup.com); National Archives (archives.gov)",75,72,72,80,72,68,80,72),
mk("HCC02","The Electoral College Distortion: How Much Your Vote Is Worth by State","Votes per electoral vote mapped — Wyoming voters have 3.6x the power of Californians","MAP","US-state","State choropleth","democracy/inequality","Census: Population (census.gov); Electoral vote allocation; MIT: Elections (electionlab.mit.edu)",82,78,82,78,80,78,68,88),
mk("HCC03","Where Qualified Immunity Shields Police From Accountability: Case Dismissal Rates by Circuit","Federal circuit court qualified immunity rulings mapped — the geographic lottery of justice","MAP","US","Special map","law/race","PACER: Court data (pacer.uscourts.gov); Reuters: QI database (reuters.com); DOJ: Civil rights (justice.gov)",82,72,68,80,85,72,80,65),
mk("HCC04","The Demographic Cliff for Gun Ownership: Age Cohort Analysis","Gun ownership rates by generation — Gen Z owns guns at half the rate of Boomers","CHART","US","Bar chart","guns/demographics","Gallup: Gun ownership (gallup.com); Pew: Generational (pewresearch.org); GSS: Firearms (gss.norc.org)",72,72,78,80,72,68,75,72),
mk("HCC05","Where Your Right to Protest Has Been Criminalized Since 2020","Anti-protest laws passed since George Floyd mapped against protest frequency","MAP","US-state","Bivariate choropleth","law/democracy","ACLU: Protest rights (aclu.org); ICNL: US Protest Law Tracker (icnl.org); ACLED: Protest data (acleddata.com)",82,72,72,78,85,75,78,72),
mk("HCC06","The Psychology of Authoritarianism: Which American Communities Score Highest","Authoritarian personality scores mapped by county against education and media consumption","MAP","US-county","County choropleth","psychology/democracy","Stenner: Authoritarianism scale; Pew: Political typology (pewresearch.org); Census: Education (census.gov/acs)",75,72,62,82,75,72,82,55),
mk("HCC07","Middle East Refugee Contributions: Tax Revenue and Business Formation by Host Country","Refugees as economic engines — the data that counters the burden narrative","CHART","World","Bar chart","middle_east/immigration","UNHCR: Refugee economics (unhcr.org); World Bank: Enterprise surveys (worldbank.org); ILO: Labor (ilo.org)",75,68,72,82,70,68,80,68),
mk("HCC08","The Rural Representation Paradox: Counties Losing Population Gaining Political Power","Redistricting giving more per-capita power to shrinking rural districts — mapped","MAP","US-county","Bivariate choropleth","rural/democracy","Census: Population change (census.gov); State redistricting commissions; Ballotpedia: Districts (ballotpedia.org)",80,72,75,78,80,78,78,72),
mk("HCC09","Where the Second Amendment Meets the First: States That Ban Guns at Protests","Armed protest laws mapped against actual armed demonstration incidents","MAP","US-state","Bivariate choropleth","guns/law","Giffords: State laws (giffords.org); ACLED: Armed demonstrations (acleddata.com); NCSL: Protest laws (ncsl.org)",78,68,72,78,82,72,78,72),
mk("HCC10","The Manufacturing Union Collapse in One Animated Chart","Union membership in manufacturing by state 1960-2025 — the decimation visualized","CHART","US-state","Animated choropleth","manufacturing/labor","BLS: Union membership (bls.gov/cps); NLRB: Election data (nlrb.gov); Census: Industry (census.gov)",78,72,78,72,78,78,68,82),
mk("HCC11","Where Entertainment Becomes Propaganda: State-Funded Media Budgets Worldwide","Government media spending per capita mapped against press freedom scores","MAP","World","World choropleth","entertainment/democracy","RSF: Press freedom (rsf.org); UNESCO: Media data (uis.unesco.org); Freedom House: Scores (freedomhouse.org)",75,62,72,78,78,75,78,72),
mk("HCC12","The Sports Scholarship Myth: Only 2% of High School Athletes Get Full Rides","Athletic scholarship rates by sport and division mapped — the odds are brutal","CHART","US","Bar chart","sports/education","NCAA: Scholarship data (ncaa.org); NFHS: Participation (nfhs.org); NCES: College data (nces.ed.gov)",75,82,78,72,70,68,68,80),
mk("HCC13","Every Federal Judge Appointed for Life: Age at Confirmation and Expected Tenure","The lifetime appointment mapped — some judges will serve 40+ years","CHART","US","Scatter plot","law/demographics","FJC: Biographical directory (fjc.gov); Senate.gov: Confirmations (senate.gov); SSA: Actuarial (ssa.gov)",75,68,72,78,78,68,78,80),
mk("HCC14","Where Drug Enforcement Targets Black Communities: Arrest Rates vs Usage Rates by Race","Drug arrest rates vs self-reported usage rates — the enforcement gap mapped by state","CHART","US-state","Bivariate choropleth","drugs/race","FBI: UCR arrests (ucr.fbi.gov); SAMHSA: Usage surveys (samhsa.gov); Census: Demographics (census.gov)",85,72,78,78,88,72,72,78),
mk("HCC15","The Democracy vs Autocracy GDP Race: Which System Delivers More Growth","Democratic vs authoritarian countries GDP growth over 50 years — controlling for oil","CHART","World","Line chart","democracy/economy","V-Dem: Regime type (v-dem.net); World Bank: GDP (worldbank.org); Freedom House: Scores (freedomhouse.org)",75,68,78,78,72,68,72,82),
mk("HCC16","Where Your Library Is Under Threat: Book Challenge Rates and Library Defunding by State","Library funding changes mapped against book challenge rates — the coordinated pattern","MAP","US-state","Bivariate choropleth","education/law","ALA: Challenge data (ala.org); IMLS: Library data (imls.gov); PEN America: Bans (pen.org)",80,78,72,75,80,72,72,75),
mk("HCC17","The Psychology of Conspiracy Geography: QAnon Belief Rates by County","Where conspiracy communities cluster mapped against broadband, church attendance, and education","MAP","US-county","County choropleth","psychology/media","PRRI: QAnon survey (prri.org); Census: Education (census.gov/acs); FCC: Broadband (fcc.gov)",72,72,62,80,72,75,80,58),
mk("HCC18","Middle East Water Wars: The Dam Projects Threatening Downstream Nations","Turkish, Ethiopian, and Iranian dam projects mapped against downstream water dependency","MAP","Middle East","Special map","middle_east/environment","FAO: AQUASTAT (fao.org/aquastat); World Bank: Water (worldbank.org); NASA: Satellite imagery (nasa.gov)",80,60,72,78,82,85,78,72),
mk("HCC19","Where Gun Laws Change After Mass Shootings and Where They Dont","State legislative response within 12 months of mass shootings — mapped over 20 years","CHART","US-state","Scatter plot","guns/politics","Giffords: State laws (giffords.org); GVA: Mass shootings (gunviolencearchive.org); NCSL: Bills (ncsl.org)",82,72,75,78,82,70,75,72),
mk("HCC20","The Rural Newspaper Crisis: Counties With Zero Local News Coverage","News deserts mapped against voter turnout and government accountability metrics","MAP","US-county","County choropleth","rural/media","UNC: News deserts (usnewsdeserts.com); MIT: Elections (electionlab.mit.edu); Census: Demographics (census.gov)",80,75,72,78,78,78,75,75),
mk("HCC21","Every State Where Its Legal to Fire Someone for Being Gay — and the Economic Impact","Employment discrimination laws mapped against LGBTQ economic contribution by state","MAP","US-state","Bivariate choropleth","law/economy","MAP: State laws (lgbtmap.org); EEOC: Charges (eeoc.gov); Census: Same-sex households (census.gov)",80,75,75,72,80,72,72,72),
mk("HCC22","The Demographics of Who Serves on Juries vs Who Gets Judged","Jury demographics compared to defendant demographics by federal district","CHART","US","Bar chart","demographics/law","Administrative Office: Court data (uscourts.gov); Census: Demographics (census.gov); USSC: Sentencing (ussc.gov)",82,72,72,80,82,68,78,62),
mk("HCC23","Where Drug Prices Fund Political Campaigns: Pharma Donations by Congressional District","Pharmaceutical PAC money mapped against drug pricing votes","MAP","US-state","State choropleth","drugs/politics","OpenSecrets: Pharma contributions (opensecrets.org); GovTrack: Voting (govtrack.us); CMS: Drug prices (cms.gov)",80,72,75,78,80,72,72,78),
mk("HCC24","The Gun Waiting Period Map: What 3 Days Does to Impulse Violence","States with waiting periods vs without mapped against impulsive firearm deaths","CHART","US-state","Scatter plot","guns/health","RAND: Waiting period research (rand.org); CDC: Suicide data (wonder.cdc.gov); Giffords: State laws (giffords.org)",82,72,78,78,80,68,72,78),
mk("HCC25","Where Sports Teams Divide Cities Along Racial Lines: Fan Base Demographics","Team fandom mapped by zip code reveals persistent residential segregation","MAP","US-metro","Dot map","sports/race","Morning Consult: Fandom (morningconsult.com); Census: Demographics (census.gov/acs); SBJ: Fan surveys (sportsbusinessjournal.com)",72,75,65,78,72,72,80,58),
mk("HCC26","The Manufacturing Pollution Legacy: Superfund Sites Cluster Where Factories Were","Historical manufacturing mapped against current EPA Superfund sites — the toxic inheritance","MAP","US-county","Bivariate choropleth","manufacturing/environment","EPA: Superfund sites (epa.gov/superfund); BLS: Historical manufacturing (bls.gov); Census: Demographics (census.gov)",80,72,75,78,78,80,72,82),
mk("HCC27","Middle East Gender Gap: Countries Where Women Outearn Men in Specific Sectors","Surprising data on female earnings in MENA tech, healthcare, and education","CHART","Middle East","Bar chart","middle_east/gender","ILO: Wage data (ilo.org); World Bank: Gender (worldbank.org); World Economic Forum: Gender gap (weforum.org)",68,62,68,85,62,65,82,68),
mk("HCC28","Where the Psychology of Loss Aversion Shapes Entire Economies","Counties where economic decline triggers disproportionate political response — the math of grievance","XREF","US-county","Scatter plot","psychology/economy","BEA: Income change (bea.gov); MIT: Elections (electionlab.mit.edu); Kahneman: Prospect theory research",72,72,62,82,72,68,85,55),
mk("HCC29","The Democracy Backslide Index: US States Ranked on 15 Democratic Health Metrics","Voter access, press freedom, gerrymandering, judicial independence — composite score by state","RANK","US-state","Ranked list","democracy/law","Brennan Center: State democracy (brennancenter.org); V-Dem: Subnational (v-dem.net); MIT: Elections (electionlab.mit.edu)",78,72,75,72,78,70,75,68),
mk("HCC30","The Entertainment Censorship Map: What Gets Banned or Restricted by Country","Film, music, and internet content restrictions mapped globally against economic freedom","MAP","World","World choropleth","entertainment/law","MPAA: Rating systems; Freedom House: FOTN (freedomhouse.org); RSF: Press freedom (rsf.org); UNESCO: Cultural (uis.unesco.org)",72,65,70,75,72,78,75,72),
mk("HCC31","Where Demographic Change Triggers Hate Crimes: The Diversity-Threat Hypothesis","Counties with fastest demographic shifts mapped against hate crime spike timing","XREF","US-county","Scatter plot","demographics/crime","FBI: Hate crime (ucr.fbi.gov); Census: Demographic change (census.gov); ADL: Hate incidents (adl.org)",82,70,68,82,85,72,80,68),
mk("HCC32","The Gun Industry Marketing Pivot: From Hunting to Self-Defense in Ad Spending","Ad content analysis showing the shift from sport to fear-based marketing","CHART","US","Line chart","guns/media","Kantar: Ad data; NSSF: Industry marketing (nssf.org); Violence Policy Center: Research (vpc.org)",72,68,65,80,72,65,82,60),
mk("HCC33","Rural Americas Volunteer Fire Department Crisis: Response Times Getting Longer","Volunteer firefighter shortages mapped against response times and structure fires","MAP","US-county","County choropleth","rural/infrastructure","NFPA: Fire department data (nfpa.org); USFA: Fire statistics (usfa.fema.gov); Census: Rural (census.gov)",78,75,72,72,78,78,72,72),
mk("HCC34","Where the Psychology of Nostalgia Drives Voting: Make America Great Again County by County","Counties where perceived decline exceeds actual decline mapped against voting patterns","XREF","US-county","Bivariate choropleth","psychology/politics","Gallup: Satisfaction (gallup.com); BEA: Economic data (bea.gov); MIT: Elections (electionlab.mit.edu)",75,78,62,82,75,75,82,62),
mk("HCC35","The Law of the Internet: How Section 230 Shaped Every Platform You Use","Timeline of Section 230 cases mapped against platform growth and content moderation spending","CHART","US","Line chart","law/technology","Court cases: Section 230 database; SEC: Tech company filings (sec.gov); Stanford: Internet observatory (stanford.edu)",72,72,68,75,70,68,78,68),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCC ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCC batch)")
