import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDC01","The Surveillance State Scorecard: Government Surveillance Capability by Country","Combined score of CCTV density, phone tapping authority, internet monitoring, facial recognition, and social credit systems","MAP","World","World choropleth","technology","Freedom House: Freedom on the Net (freedomhouse.org/report/freedom-net)",72,68,75,78,80,80,72,78),
mk("HDC02","AI Job Displacement Risk Map: Which Jobs Are Most Automatable by Metro Area","Percentage of jobs at high risk of automation by metro area, based on occupation mix and AI capability","MAP","US","Dot map","technology","McKinsey: Future of Work (mckinsey.com/featured-insights/future-of-work)",78,82,72,78,80,78,72,72),
mk("HDC03","The Data Center Boom: Where Americas Cloud Actually Lives","Every major data center in the US mapped with capacity, energy consumption, and water usage","MAP","US","Dot map","technology","Data Center Map: Colocation Directory (datacentermap.com)",65,62,75,72,62,85,68,78),
mk("HDC04","Facial Recognition Bans vs. Deployments: The City-by-City Battleground","Cities that have banned government facial recognition vs. those actively deploying it, mapped","MAP","US","Dot map","technology","ACLU: Face Recognition Technology (aclu.org/issues/privacy-technology/surveillance-technologies/face-recognition-technology)",72,68,72,78,78,80,72,72),
mk("HDC05","The Digital Divide Is an Income Divide: Home Broadband by Income Quintile","Broadband subscription rates by household income quintile, showing the class structure of internet access","CHART","US","Bar chart","technology","Pew: Internet/Broadband Fact Sheet (pewresearch.org/internet/fact-sheet/internet-broadband)",72,78,80,72,72,68,65,85),
mk("HDC06","Who Trains the AI: Global Distribution of Data Labeling Workers","Where the millions of workers who label training data for AI models actually live — Kenya, India, Philippines, Venezuela","MAP","World","World choropleth","technology","TIME: Inside the AI Labeling Industry (time.com)",72,62,72,82,72,78,82,65),
mk("HDC07","Americas CCTV Map: Estimated Surveillance Cameras Per Capita by City","Estimated public and private surveillance cameras per 1,000 residents by major US city","RANK","US","Bar chart","technology","Comparitech: Surveillance Camera Statistics (comparitech.com/vpn-privacy/the-worlds-most-surveilled-cities)",68,72,72,78,72,72,72,68),
mk("HDC08","The Algorithmic Sentencing Experiment: COMPAS Scores vs. Actual Recidivism by Race","Comparison of algorithmic risk assessment scores to actual recidivism outcomes, showing racial bias in predictive policing","XREF","US","Scatter plot","technology","ProPublica: Machine Bias (propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing)",82,68,72,82,82,68,78,72),
mk("HDC09","E-Waste Geography: Where Americas Old Electronics End Up","Tracking the flow of electronic waste from US collection points to processing facilities in Africa and Asia","MAP","World","Line map","technology","BAN: E-Waste Transparency Project (ban.org/trash-transparency)",72,62,72,78,72,82,72,68),
mk("HDC10","The Undersea Cable Map: The Physical Internet Connecting Continents","Every submarine fiber optic cable connecting the worlds internet, with capacity and ownership","MAP","World","Line map","technology","TeleGeography: Submarine Cable Map (submarinecablemap.com)",62,58,78,78,62,90,72,85),
mk("HDC11","Americas Tech Bro Geography: Software Developer Concentration by Metro","Software developers per capita by metro area, showing the geographic concentration of tech talent","MAP","US","Dot map","technology","BLS: Occupational Employment Statistics (bls.gov/oes)",62,68,78,72,58,80,62,85),
mk("HDC12","The AI Compute Arms Race: GPU Clusters by Country and Company","Estimated AI training compute capacity by country and organization, showing the hardware power structure","RANK","World","Bar chart","technology","Epoch AI: Compute Trends (epochai.org/data/notable-ai-models)",68,55,72,78,72,68,78,68),
mk("HDC13","Deepfake Detection: Countries With Laws vs. Without Any Regulation","Nations that have passed deepfake legislation vs. those with no legal framework for synthetic media","MAP","World","World choropleth","technology","Brookings: Deepfake Regulation (brookings.edu/research/deepfakes-regulation)",68,65,72,78,72,78,72,65),
mk("HDC14","The Password Graveyard: Most Common Passwords Used in Data Breaches by Country","Most frequently appearing passwords in data breaches, showing cultural and linguistic patterns in bad security","MAP","World","World choropleth","technology","Have I Been Pwned: Breach Data Analysis (haveibeenpwned.com)",58,72,68,78,58,75,75,72),
mk("HDC15","The Robot Density Map: Industrial Robots Per Worker by Country","Industrial robot installations per 10,000 manufacturing workers by country — South Korea and Japan lead dramatically","MAP","World","World choropleth","technology","IFR: World Robotics Report (ifr.org/worldrobotics)",68,62,78,78,68,78,72,82),
mk("HDC16","Internet Shutdowns: Governments That Turn Off the Internet","Countries that have imposed government-ordered internet shutdowns, mapped with duration and trigger events","MAP","World","World choropleth","technology","Access Now: KeepItOn Report (accessnow.org/keepiton)",78,62,72,78,82,78,72,78),
mk("HDC17","The Gig Economy Map: Percentage of Workers Doing Gig Work by Metro","Share of workforce earning primary income from gig platforms — Uber, DoorDash, TaskRabbit — by metro area","MAP","US","Dot map","technology","MBO Partners: State of Independence (mbopartners.com/state-of-independence)",68,78,72,72,68,78,68,68),
mk("HDC18","Your Phone Knows Where You Were: Cell Phone Location Data Points Per Day","Average number of location data points your phone transmits per day, and how many companies receive them","CHART","World","Bar chart","technology","NYT: One Nation Tracked (nytimes.com/interactive/2019/12/19/opinion/location-tracking-cell-phone.html)",72,82,72,82,78,68,72,65),
mk("HDC19","The Crypto Ghost Towns: Failed Cryptocurrency Projects Mapped by Origin Country","Geographic distribution of defunct cryptocurrency and blockchain projects, by country of founding team","MAP","World","World choropleth","technology","CoinGecko: Cryptocurrency Historical Data (coingecko.com)",62,62,68,78,62,78,72,68),
mk("HDC20","Americas Cell Tower Forest: Wireless Infrastructure Density vs. Coverage","Cell tower density per square mile by county, showing the infrastructure behind wireless coverage","MAP","US","County choropleth","technology","FCC: Antenna Structure Registration (fcc.gov/antenna-structure-registration)",58,62,72,68,55,85,65,78),
mk("HDC21","The Social Media Body Count: Platform-Linked Youth Deaths","Documented cases of youth deaths linked to social media challenges, cyberbullying, and algorithmic content","CHART","World","Line chart","technology","Social Media Victims Law Center: Case Database (socialmediavictims.org)",88,78,68,78,88,68,72,62),
mk("HDC22","The Electric Grid Vulnerability Map: Power Grid Attack Surface by Region","Cyberattack vulnerability of regional electric grids based on age of infrastructure, SCADA exposure, and redundancy","MAP","US","State choropleth","technology","DOE: Grid Modernization (energy.gov/oe/grid-modernization)",72,65,68,78,78,78,75,65),
mk("HDC23","Who Owns Your Genetic Data: DNA Testing Company Databases by Size","Total genetic profiles held by 23andMe, Ancestry, MyHeritage, and others — the largest biometric databases in history","RANK","World","Bar chart","technology","MIT Technology Review: Consumer Genomics (technologyreview.com)",72,72,72,82,78,68,78,68),
mk("HDC24","The Right to Repair Battleground: States With and Without Electronics Repair Laws","States that have passed right to repair legislation vs. those where manufacturers can still lock out independent repair","MAP","US","State choropleth","technology","US PIRG: Right to Repair Map (uspirg.org/feature/usp/right-repair)",68,78,75,72,68,78,68,72),
mk("HDC25","The Misinformation Pipeline: How False Stories Spread Across Platforms","Flow diagram of how a false claim moves from fringe sites to mainstream social media to news coverage — the amplification chain","CHART","World","Special map","technology","MIT: Spread of True and False News Online (science.sciencemag.org/content/359/6380/1146)",72,72,68,82,75,75,78,68),
mk("HDC26","Autonomous Vehicle Test Miles: Where Self-Driving Cars Are Actually Driving","Miles driven by autonomous vehicles by city and company, showing the geographic concentration of testing","MAP","US","Dot map","technology","CA DMV: Autonomous Vehicle Testing Data (dmv.ca.gov/portal/vehicle-industry-services/autonomous-vehicles)",62,62,75,72,62,82,68,78),
mk("HDC27","The Satellite Swarm: How Many Objects Are in Earth Orbit Over Time","Number of active satellites, defunct satellites, and debris objects in orbit 1957-2025 — the Kessler Syndrome risk","CHART","World","Line chart","technology","ESA: Space Debris Environment Report (esa.int/space_safety/space_debris)",65,58,78,78,72,78,72,82),
mk("HDC28","Digital Literacy by Generation and Country: Who Actually Understands How Tech Works","Ability to evaluate sources, detect phishing, and understand algorithms by age group and country","CHART","World","Bar chart","technology","OECD: PIAAC Digital Problem-Solving (oecd.org/skills/piaac)",68,72,72,78,68,68,72,72),
mk("HDC29","The Ransomware Map: Cyberattack Targets by Sector and Country","Major ransomware attacks mapped by target sector — healthcare, government, education, energy — and country of origin","MAP","World","Dot map","technology","Recorded Future: Ransomware Tracker (recordedfuture.com)",72,65,72,78,78,78,72,72),
mk("HDC30","Americas Tech Tax Dodge: Where Big Tech Reports Revenue vs. Where Users Are","Gap between where tech companies report profits (low-tax jurisdictions) and where their users actually are","XREF","World","Scatter plot","technology","Tax Foundation: Digital Tax Reports (taxfoundation.org/digital-services-tax)",68,65,72,82,72,68,78,68),
mk("HDC31","The Lithium Triangle: Where Battery Minerals Come From","Global distribution of lithium, cobalt, and rare earth mineral production — the geography powering the tech revolution","MAP","World","World choropleth","technology","USGS: Mineral Commodity Summaries (usgs.gov/centers/national-minerals)",68,58,78,78,72,82,72,82),
mk("HDC32","The App Economy: Revenue Per Download by Country","Average revenue per mobile app download by country, showing the purchasing power gap in the digital marketplace","MAP","World","World choropleth","technology","Sensor Tower: App Market Intelligence (sensortower.com)",60,62,72,72,58,78,68,72),
mk("HDC33","Your Smart TV Is Watching You: Data Collection Points in a Modern Living Room","Number of data-collecting devices and data points transmitted per hour in an average smart home","CHART","US","Infographic","technology","Northeastern University: Smart Home Privacy (moniotrlab.ccis.neu.edu)",72,82,68,82,72,72,78,62),
mk("HDC34","The Code Geography: Most Popular Programming Languages by Country","Dominant programming language by country based on GitHub contributions — revealing cultural tech preferences","MAP","World","World choropleth","technology","GitHub: Octoverse (octoverse.github.com)",58,58,72,72,55,80,68,78),
mk("HDC35","Americas Internet Speed Inequality: Download Speed by Income Bracket","Average internet download speed by household income bracket within the same metro area — you get the internet you can afford","CHART","US","Bar chart","technology","Ookla: Speedtest Intelligence (speedtest.net/insights)",72,82,78,78,72,68,68,72),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDC batch)")
