import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDS01","The Inequality Spiral: Ratio of CEO Pay to Median Worker Pay by Company","CEOs making 300-1000x their median employee — the most extreme ratios at Americas largest publicly traded companies","RANK","US","Bar chart","inequality","AFL-CIO: Executive Paywatch (aflcio.org/paywatch) + SEC Proxy Filings",72,78,75,72,72,55,62,85),
mk("HDS02","Flood Insurance Gap: Homes in Flood Zones Without Coverage by County","The $1T+ uninsured flood exposure — homes in FEMA-designated flood zones where nobody has flood insurance","MAP","US","County choropleth","environment","FEMA: National Flood Insurance Program (fema.gov/flood-insurance) + First Street Foundation",72,72,72,72,75,78,60,82),
mk("HDS03","Heat Death Inequality: Who Dies in Heat Waves by Income and Housing Type","Heat kills the poor — mortality during heat events mapped against air conditioning access, housing quality, and neighborhood tree canopy","MAP","US","Bivariate choropleth","climate","CDC: Heat-Related Mortality (cdc.gov) + EPA Heat Island Data",78,72,68,72,78,72,65,78),
mk("HDS04","The Homeless Student Count: Children Experiencing Homelessness Enrolled in Public Schools by District","1.3 million students identified as homeless by schools — doubled up, in shelters, in cars, or unsheltered, mapped by district","MAP","US","County choropleth","poverty","DOE: Education for Homeless Children and Youth (nche.ed.gov)",85,72,72,68,80,72,58,85),
mk("HDS05","Carbon Footprint by Income: Tons of CO2 Emitted by Household Income Percentile","The top 10% of earners produce 3-5x the carbon emissions of the bottom 50% — the climate inequality nobody addresses","CHART","US","Bar chart","inequality","Oxfam: Carbon Inequality (oxfam.org) + EPA Household Carbon Footprint Calculator",72,72,72,78,72,58,72,78),
mk("HDS06","Toxic Release Inventory: Pounds of Pollutants Released by Facility Near Communities","Every factory and facility that reports toxic chemical releases — mapped against nearby population density and demographics","MAP","US","Dot map","environment","EPA: Toxics Release Inventory (epa.gov/toxics-release-inventory-tri-program)",72,65,72,68,78,80,58,90),
mk("HDS07","Climate Adaptation Spending: Which Countries Invest Most in Resilience vs Mitigation","The growing gap between climate adaptation needs and actual spending — developing nations receiving a fraction of whats needed","CHART","World","Bar chart","climate","UNEP: Adaptation Gap Report (unep.org/adaptation-gap-report)",62,52,68,72,72,58,68,78),
mk("HDS08","Diaper Need: Families That Cannot Afford Enough Diapers for Their Children by State","The hidden cost of parenting in poverty — 1 in 3 families struggle to afford diapers, with no federal assistance program","MAP","US","State choropleth","poverty","National Diaper Bank Network (nationaldiaperbanknetwork.org)",82,78,68,72,72,65,65,68),
mk("HDS09","Wealth Concentration Timeline: Share of National Wealth Held by Top 1% Since 1900","The U-curve of inequality — from Gilded Age concentration to mid-century compression back to modern extreme concentration","CHART","US","Line chart","inequality","World Inequality Database: wid.world",68,68,78,68,72,58,58,90),
mk("HDS10","Superfund Site Cleanup: The 1,300+ Contaminated Sites and Their Remediation Status","Every EPA Superfund site in America — how many are cleaned up, in progress, or essentially abandoned, mapped with contamination type","MAP","US","Dot map","environment","EPA: Superfund Site Information (epa.gov/superfund/search-superfund-sites)",72,62,72,68,78,80,58,90),
mk("HDS11","Climate Refugee Projections: Populations Expected to Migrate Due to Climate by 2050","World Bank estimates of 216 million internal climate migrants by 2050 — which regions produce refugees and where they go","MAP","World","World choropleth","climate","World Bank: Groundswell Report (worldbank.org/en/topic/climatechange/groundswell)",75,58,68,72,80,78,68,78),
mk("HDS12","Internet Cost as Barrier: Low-Income Families Without Home Internet by School District","The homework gap — families where kids cant do online schoolwork because they cant afford internet, mapped by district","MAP","US","County choropleth","poverty","Census Bureau: Household Pulse Survey Internet Access (census.gov)",72,78,72,65,68,72,58,82),
mk("HDS13","Inherited Wealth Share: Percentage of Billionaire Wealth That Was Inherited vs Self-Made by Country","The myth of the self-made billionaire — what percentage of extreme wealth in each country was inherited, not earned","MAP","World","World choropleth","inequality","UBS/PwC: Billionaire Report (ubs.com/billionaires-report) + Forbes",65,68,72,75,65,65,72,78),
mk("HDS14","Coal Ash Contamination: Unlined Coal Ash Ponds Leaching Toxins Into Groundwater","Every coal ash disposal site in the US — the toxic legacy of coal power contaminating water supplies near communities","MAP","US","Dot map","environment","EPA: Coal Combustion Residuals (epa.gov/coalash) + Earthjustice",72,62,68,72,78,78,62,80),
mk("HDS15","Wet Bulb Temperature Danger Zone: Places That Will Become Lethal in Heat Waves by 2050","Where combined heat and humidity will exceed human survivability thresholds — the Persian Gulf and South Asia most at risk","MAP","World","World choropleth","climate","Mora et al: Deadly Heat (nature.com/articles/nclimate3322)",78,62,68,78,85,78,72,75),
mk("HDS16","Tax Refund Lending: Percentage of Low-Income Tax Filers Using Refund Anticipation Products","The predatory tax prep industry — where H&R Block and Liberty Tax charge the poor to access their own refund money early","MAP","US","State choropleth","poverty","NCLC: National Consumer Law Center Tax Time Reports (nclc.org)",68,72,72,72,68,62,65,75),
mk("HDS17","Opportunity Zone Map: Which Census Tracts Were Designated and Who Actually Benefited","The 2017 tax break intended for poor communities — where the money actually went, often to luxury developments in already-gentrifying areas","MAP","US","County choropleth","inequality","Urban Institute: Opportunity Zones (urban.org/policy-centers/metropolitan-housing-and-communities-policy-center/projects/opportunity-zones)",68,62,72,78,72,78,70,80),
mk("HDS18","PFAS Cleanup Costs: Estimated Remediation Expense for Forever Chemical Contamination by State","The multi-billion dollar bill for cleaning up PFAS — which states face the largest liability and whos paying for it","MAP","US","State choropleth","environment","ITRC: PFAS Technical Resources (pfas-1.itrcweb.org) + State EPA data",68,62,68,72,75,68,62,72),
mk("HDS19","Cooling Center Access: Distance to Nearest Public Cooling Center During Heat Emergencies","Where people without AC can go when temperatures become dangerous — mapped against heat vulnerability and transit access","MAP","US","Dot map","climate","City government cooling center locators + CDC Heat and Health Tracker (ephtracking.cdc.gov)",72,72,68,65,72,78,65,72),
mk("HDS20","Benefit Clawback Rates: Effective Tax Rate on the Next Dollar Earned for Welfare Recipients","The poverty trap quantified — where earning $1 more costs $2 in lost benefits, creating marginal rates exceeding 100%","CHART","US","Line chart","poverty","CBO: Effective Marginal Tax Rates (cbo.gov) + Urban Institute TRIM Model",75,72,72,78,75,58,72,80),
mk("HDS21","The Racial Homeownership Gap: Black vs White Homeownership Rate by Metro 1960-2024","The homeownership gap hasnt budged in 60 years — 75% white vs 45% Black, with metros where the gap is widest","CHART","US","Line chart","inequality","Census Bureau: Housing Vacancy and Homeownership Survey (census.gov/housing/hvs)",78,72,75,68,78,62,58,90),
mk("HDS22","Industrial Livestock Pollution: Animal Feeding Operations and Downstream Water Quality","CAFOs that produce more waste than cities — mapped against downstream water quality violations and fish kills","MAP","US","Bivariate choropleth","environment","EPA: CAFO Regulations + NPDES Permits (epa.gov/npdes/animal-feeding-operations)",72,58,68,72,75,78,68,78),
mk("HDS23","Arctic Shipping Routes: The Opening of Northwest and Northeast Passages to Commercial Traffic","Ice-free shipping days per year through Arctic passages — doubling every decade as sea ice retreats","MAP","World","Line map","climate","NSR Information Office (arctic-lio.com) + NSIDC Sea Ice Data",58,48,68,75,68,82,72,78),
mk("HDS24","Unbanked and Underbanked Map: Households Without Full Financial Services by Census Tract","Where people cash checks at liquor stores — the geography of financial exclusion at the neighborhood level","MAP","US","County choropleth","poverty","FDIC: National Survey of Unbanked and Underbanked Households (fdic.gov/analysis/household-survey)",72,72,72,68,68,78,60,85),
mk("HDS25","Social Mobility by ZIP Code: Probability of Moving From Bottom to Top Income Quintile","The American Dream has a ZIP code — Raj Chettys data showing where upward mobility is possible and where its nearly nonexistent","MAP","US","County choropleth","inequality","Opportunity Insights: The Opportunity Atlas (opportunityinsights.org)",78,75,72,72,78,82,68,90),
mk("HDS26","Brownfield Redevelopment: Contaminated Sites Converted to Productive Use by State","The success stories of environmental cleanup — former gas stations, factories, and dumps turned into parks, housing, and businesses","MAP","US","Dot map","environment","EPA: Brownfields Program (epa.gov/brownfields)",58,58,72,65,55,78,68,82),
mk("HDS27","Billion-Dollar Weather Events: NOAA-Tracked Climate Disasters Per Year Since 1980","The acceleration of expensive climate disasters — from 3-4 per year in the 1980s to 20+ per year now, totaling $150B+ annually","CHART","US","Line chart","climate","NOAA: Billion-Dollar Weather and Climate Disasters (ncei.noaa.gov/access/billions)",72,68,78,68,78,62,55,92),
mk("HDS28","Predatory Lending Geography: High-Interest Loan Locations Per Capita by ZIP Code","Where payday lenders, title loan shops, and check cashers cluster — always in low-income communities, often near military bases","MAP","US","Dot map","poverty","CFPB: Payday Lending Data (consumerfinance.gov) + FDIC",75,72,72,72,78,78,62,82),
mk("HDS29","CEO-to-Median-Worker Pay Ratio: Every S&P 500 Company Ranked by Internal Pay Gap","The companies with the most extreme internal inequality — from 5:1 ratios at some tech firms to 2000:1 at retailers","RANK","US","Bar chart","inequality","AFL-CIO: Executive Paywatch (aflcio.org/paywatch) + SEC Proxy Filings",68,72,75,72,68,55,62,88),
mk("HDS30","Environmental Justice Screening: Communities Scoring Highest for Cumulative Pollution Burden","The most environmentally burdened communities in America — cumulative exposure to pollution, poverty, and health risks","MAP","US","County choropleth","environment","EPA: EJScreen (ejscreen.epa.gov) + CalEnviroScreen",75,68,72,68,78,78,62,85),
mk("HDS31","Climate Insurance Retreat: Where Homeowners Insurance Companies Are Refusing to Write Policies","The insurance crisis — where State Farm, Allstate, and others have stopped selling policies due to climate risk, leaving homeowners exposed","MAP","US","State choropleth","climate","NAIC: Market Share Reports (naic.org) + State insurance commissioner data",72,78,72,72,78,72,65,78),
mk("HDS32","Food Stamp Stigma: SNAP Participation Rate Among Eligible Households by State","Many people who qualify for food stamps dont take them — participation rates range from 55% to 100% depending on the state","MAP","US","State choropleth","poverty","USDA: SNAP Participation Rates (fns.usda.gov/usamap)",72,72,72,68,65,72,62,85),
mk("HDS33","Billionaire Tax Rate: Effective Tax Rate Paid by Americas Wealthiest vs Median Worker","The true tax rate of billionaires — when you count unrealized gains, Buffett pays a lower rate than his secretary, and the data proves it","CHART","US","Bar chart","inequality","ProPublica: Secret IRS Files (propublica.org/article/the-secret-irs-files-trove-of-never-before-seen-records-reveal-how-the-wealthiest-avoid-income-tax)",78,78,75,78,78,55,68,78),
mk("HDS34","Air Quality Index History: Number of Unhealthy Air Days Per Year by Metro Since 2000","The cities where breathing is getting worse — AQI unhealthy days increasing due to wildfires despite emissions improvements","CHART","US","Line chart","environment","EPA: Air Quality System (aqs.epa.gov/aqsweb)",68,72,72,68,72,62,55,90),
mk("HDS35","Managed Retreat: Communities That Have Been Relocated Due to Climate Change","The places that gave up — communities in Louisiana, Alaska, and the Outer Banks that relocated entirely due to rising seas and erosion","MAP","US","Dot map","climate","Georgetown Climate Center: Managed Retreat Toolkit (georgetownclimate.org)",78,62,68,78,78,80,78,72),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDS batch)")
