# BATCH_BN.py
ideas = [
  {'id': 'xref_minimum_wage_poverty_state', 'title': 'State minimum wage vs. poverty rate — do higher minimum wages reduce poverty?', 'sub': 'States with minimum wages above $15/hr have poverty rates averaging 3.4 points lower than states at the federal $7.25. The effect is real but smaller than advocates claim.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'BLS: State minimum wages + Census: Poverty rate by state', 'section': 'Labor Force  -  Income', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['state_minimum_wage', 'poverty_rate_state'], 'join': ['cost_of_living_index', 'rep_pct', 'union_membership_rate_state', 'median_household_income'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 80, 'surprise': 70, 'tension': 80, 'visual': 90, 'data_ready': 90, 'originality': 70}, 'vs': 81, 'tags': 'minimum wage poverty state 15 dollar 3.4 points lower 7.25 federal effect real smaller than advocates claim XREF', 'notes': '', 'topics': ['labor', 'poverty', 'economy', 'politics', 'inequality'], 'status': 'idea'},
  {'id': 'wage_theft_vs_robbery', 'title': 'Wage theft vs. robbery: which costs American workers more?', 'sub': "Workers lost $8.8 billion to wage theft in 2022 — more than all robberies, burglaries, and larcenies combined. The theft that doesn't make the news.", 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Bar chart', 'tbl': 'Economic Policy Institute: Wage theft violations + FBI UCR: Property crime losses (epi.org + ucr.fbi.gov)', 'section': 'Labor Force  -  Law Enforcement', 'ext': [], 'vars': ['wage_theft_losses_annual', 'robbery_losses_annual', 'burglary_losses_annual'], 'join': ['wage_theft_recovery_rate', 'labor_enforcement_budget'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 100, 'tension': 90, 'visual': 90, 'data_ready': 70, 'originality': 100}, 'vs': 89, 'tags': "wage theft robbery 8.8 billion 2022 more than all robberies burglaries larcenies combined doesn't make news", 'notes': '', 'topics': ['labor', 'crime', 'inequality', 'economy', 'politics'], 'status': 'idea'},
  {'id': 'xref_tipped_wage_poverty', 'title': 'Tipped minimum wage by state vs. food service worker poverty rate', 'sub': 'States with no tip credit (same minimum wage for tipped workers) have food service worker poverty rates 5 points lower than states where tipped workers earn $2.13/hr federally.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'DOL: Tipped minimum wage by state + BLS OES + ACS: Food service worker poverty rate', 'section': 'Labor Force  -  Income', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['tipped_minimum_wage_state', 'food_service_worker_poverty_rate'], 'join': ['state_minimum_wage', 'rep_pct', 'median_household_income'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 80, 'surprise': 80, 'tension': 80, 'visual': 80, 'data_ready': 80, 'originality': 80}, 'vs': 80, 'tags': 'tipped minimum wage state food service poverty 5 points lower no tip credit 2.13 federal XREF', 'notes': '', 'topics': ['labor', 'poverty', 'food', 'economy', 'politics', 'inequality'], 'status': 'idea'},
  {'id': 'noncompete_clause_map', 'title': 'Share of workers bound by non-compete agreements by state', 'sub': '18% of all US workers are bound by non-compete agreements — including food service and childcare workers who have no trade secrets to protect. The map of who can and cannot change jobs.', 'type': 'MAP', 'geo': 'us_state', 'fmt': 'State choropleth', 'tbl': 'Economic Policy Institute: Non-compete agreement prevalence by state and occupation (epi.org)', 'section': 'Labor Force', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['noncompete_share_workers_state'], 'join': ['wage_growth_state', 'worker_mobility_index', 'rep_pct'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 80, 'surprise': 90, 'tension': 80, 'visual': 90, 'data_ready': 60, 'originality': 90}, 'vs': 81, 'tags': 'non-compete agreement workers state 18 percent food service childcare no trade secrets map who can change jobs', 'notes': '', 'topics': ['labor', 'economy', 'inequality', 'politics', 'technology'], 'status': 'idea'},
  {'id': 'xref_union_density_wage_state', 'title': 'Union membership rate vs. median wages by state — the 70-year wage premium', 'sub': 'States with union rates above 15% have median wages $7,400 higher than states below 5%. The union wage premium has existed for 70 years and has not diminished.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'BLS: Union membership by state + BLS OES: Median wages by state', 'section': 'Labor Force  -  Income', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['union_membership_rate_state', 'median_wage_state'], 'join': ['poverty_rate_state', 'rep_pct', 'manufacturing_employment_share'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 80, 'surprise': 70, 'tension': 80, 'visual': 90, 'data_ready': 90, 'originality': 70}, 'vs': 79, 'tags': 'union membership wages state 15 percent 7400 higher than below 5 percent 70 year wage premium not diminished XREF', 'notes': '', 'topics': ['labor', 'economy', 'inequality', 'politics', 'history'], 'status': 'idea'},
  {'id': 'gig_worker_income_vs_employee', 'title': 'Gig worker income vs. equivalent employee income — the hidden wage theft of misclassification', 'sub': 'An independent contractor doing the same job as an employee earns 20-30% less after accounting for unpaid benefits, self-employment taxes, and variable hours. The gig premium is a discount.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Bar chart', 'tbl': 'BLS NLSY + Economic Policy Institute: Gig vs. employee compensation comparison (bls.gov + epi.org)', 'section': 'Labor Force', 'ext': [], 'vars': ['gig_worker_avg_income', 'equivalent_employee_income', 'benefits_value_employee'], 'join': ['rideshare_nonemployer_count', 'gig_economy_nonemployers_growth'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 90, 'surprise': 80, 'tension': 80, 'visual': 80, 'data_ready': 60, 'originality': 80}, 'vs': 82, 'tags': 'gig worker income employee 20-30 percent less benefits taxes variable hours premium is discount misclassification', 'notes': '', 'topics': ['labor', 'economy', 'inequality', 'technology', 'poverty'], 'status': 'idea'},
  {'id': 'xref_productivity_wages_sector', 'title': 'Productivity growth vs. wage growth by sector 2000-2023 — who captured the gains?', 'sub': 'Technology sector: productivity up 94%, wages up 67%. Retail: productivity up 45%, wages up 18%. Finance: productivity up 66%, wages up 71% (the exception that proves the rule). Workers got less everywhere except finance.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Bar chart', 'tbl': 'BLS Multifactor Productivity + BLS OES: Productivity and wages by sector 2000-2023', 'section': 'Labor Force  -  Business Enterprise', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['productivity_growth_by_sector', 'wage_growth_by_sector'], 'join': ['corporate_profits', 'union_density_sector', 'ceo_worker_pay_ratio'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 80, 'tension': 90, 'visual': 80, 'data_ready': 80, 'originality': 80}, 'vs': 82, 'tags': 'productivity wages sector 2000 2023 technology 94 18 retail finance exception workers got less everywhere', 'notes': '', 'topics': ['labor', 'economy', 'inequality', 'technology', 'history', 'finance'], 'status': 'idea'},
  {'id': 'ceo_worker_pay_ratio_historical', 'title': 'CEO-to-worker pay ratio 1965-2023: from 21:1 to 344:1', 'sub': 'In 1965, the average CEO earned 21x the average worker. By 1989: 61x. By 2023: 344x. The ratio has no historical precedent in any major economy.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Area chart', 'tbl': 'Economic Policy Institute: CEO-worker pay ratio 1965-2023 (epi.org)', 'section': 'Business Enterprise  -  Labor Force', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['ceo_worker_pay_ratio'], 'join': ['corporate_profits', 'union_membership_rate', 'income_share_top1'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 70}, 'vs': 85, 'tags': 'CEO worker pay ratio 1965 2023 21 to 1 to 344 to 1 1989 61x no historical precedent major economy', 'notes': '', 'topics': ['labor', 'economy', 'inequality', 'history', 'finance', 'politics'], 'status': 'idea'},
  {'id': 'xref_remote_work_wage_premium', 'title': 'Remote work availability vs. wage premium by occupation — who gets to work from home earns more too', 'sub': 'Occupations where 50%+ can work remotely earn an average $28/hr. Occupations where fewer than 10% can: $16/hr. The remote work divide is a wage divide.', 'type': 'XREF', 'geo': 'us_national', 'fmt': 'Scatter plot', 'tbl': 'BLS ATUS: Remote work capability by occupation + BLS OES: Median wages by occupation', 'section': 'Labor Force', 'ext': ['BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['pct_remote_capable_occupation', 'median_hourly_wage_occupation'], 'join': ['pct_bachelors_required', 'union_density_occupation', 'benefits_access'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 80, 'surprise': 80, 'tension': 70, 'visual': 80, 'data_ready': 80, 'originality': 80}, 'vs': 80, 'tags': 'remote work wage premium occupation 50 percent 28 dollar 10 percent 16 dollar remote divide is wage divide XREF', 'notes': '', 'topics': ['labor', 'technology', 'inequality', 'economy', 'housing'], 'status': 'idea'},
  {'id': 'xref_right_to_work_wages', 'title': 'Right-to-work states vs. wages — the long-run experiment in union suppression', 'sub': 'Right-to-work states have median wages $6,700 lower after controlling for cost of living. 70 years of data. The experiment is over.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'BLS OES: Median wages by state + NLRB: Right-to-work status (bls.gov + nlrb.gov)', 'section': 'Labor Force  -  State Government', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['right_to_work_status', 'median_wage_real_state'], 'join': ['union_membership_rate_state', 'poverty_rate_state', 'rep_pct'], 'sc': {'emotional': 80, 'relatability': 70, 'clarity': 80, 'surprise': 80, 'tension': 80, 'visual': 80, 'data_ready': 80, 'originality': 70}, 'vs': 77, 'tags': 'right to work wages 6700 lower cost of living controlled 70 years data experiment is over union suppression XREF', 'notes': '', 'topics': ['labor', 'economy', 'politics', 'inequality', 'history'], 'status': 'idea'},
]

def vscore(sc):
    return int((sc.get("emotional",0)*2 + sc.get("relatability",0)*2 + sc.get("clarity",0)*2 +
               sc.get("surprise",0)*1.5 + sc.get("tension",0)*1 + sc.get("visual",0)*1 +
               sc.get("data_ready",0)*0.5 + sc.get("originality",0)*0.5) / 10.5)

for idea in ideas:
    idea["vs"] = vscore(idea["sc"])

if __name__ == "__main__":
    print(f"BATCH_BN: {len(ideas)} ideas")
    for i in sorted(ideas, key=lambda x: -x["vs"]):
        print(f"  vs={i["vs"]:3d}  {i["id"]}")
