import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDP01","Ballot Drop Box Battles: States That Added or Removed Drop Boxes Since 2020","The post-2020 fight over ballot drop boxes mapped — states that expanded access vs those that restricted or eliminated them","MAP","US","State choropleth","democracy","Voting Rights Lab: Ballot Access Tracker (votingrightslab.org)",65,68,72,65,75,72,62,82),
mk("HDP02","Nitazene Emergence: The Next-Generation Synthetic Opioid Appearing in Drug Supplies","Geographic spread of nitazenes — synthetic opioids 10-40x more potent than fentanyl — detected in toxicology reports","MAP","US","Dot map","drugs","DEA: Emerging Threat Reports (dea.gov) + CDC: State Unintentional Drug Overdose Reporting System",72,55,65,80,82,72,72,65),
mk("HDP03","Vertical Farming Installations: Indoor Agriculture Facilities by Country and Crop Type","The global vertical farming map — from leafy greens in Singapore to strawberries in Japan, with investment amounts","MAP","World","Dot map","agriculture","USDA: Urban Agriculture Data (usda.gov) + Association for Vertical Farming (vertical-farming.net)",52,48,68,72,55,78,72,70),
mk("HDP04","Visa Lottery Odds: Diversity Visa Selection Rates by Country of Origin","Your chances of winning the green card lottery vary wildly by nationality — from 1-in-15 for some countries to 1-in-500 for others","CHART","World","Bar chart","immigration","DOS: Diversity Visa Program Statistics (travel.state.gov/content/travel/en/us-visas/immigrate/diversity-visa-program)",58,62,72,75,58,58,68,88),
mk("HDP05","Voter Purge Rates: Registrations Removed From Rolls by State and Method","How aggressively states clean voter rolls — millions purged per year, with wildly different criteria and error rates","MAP","US","State choropleth","democracy","Brennan Center: Voter Purge Data (brennancenter.org)",68,65,72,72,78,72,65,82),
mk("HDP06","Cocaine Purity Trends: Average Street-Level Purity by US Region Over Time","How cocaine purity has risen dramatically since 2015 — higher purity, lower price, and the geographic variation across markets","CHART","US","Line chart","drugs","DEA: National Drug Threat Assessment (dea.gov/documents/2024/05/ndta)",58,52,68,72,68,58,65,72),
mk("HDP07","Farmland Conversion: Acres of Agricultural Land Lost to Development Per Year by State","How fast Americas farmland is being paved over — states losing thousands of acres per year to suburban sprawl","MAP","US","State choropleth","agriculture","USDA: National Resources Inventory (nrcs.usda.gov/nri) + American Farmland Trust (farmland.org)",68,62,72,68,72,78,62,85),
mk("HDP08","Immigration Court Backlog: Pending Cases Per Judge by Jurisdiction","The 3+ million case immigration court backlog — some judges carry 4,000+ pending cases, average wait times exceed 4 years","MAP","US","Dot map","immigration","TRAC: Immigration Court Backlog (trac.syr.edu/phptools/immigration/court_backlog)",72,62,72,72,78,72,58,85),
mk("HDP09","Foreign Election Interference: Documented Attempts to Influence Elections by Country","Every documented case of foreign interference in national elections since 2000 — Russia, China, Iran, and others mapped by target","MAP","World","World choropleth","democracy","Stanford Internet Observatory: Foreign Influence Operations (cyber.fsi.stanford.edu)",65,55,68,72,78,72,72,72),
mk("HDP10","Counterfeit Pill Deaths: Fatalities From Fake Prescription Pills Containing Fentanyl","Deaths from pills bought on the street that turned out to contain fentanyl — the deceptive packaging killing people who think theyre taking Percocet","CHART","US","Line chart","drugs","DEA: One Pill Can Kill (dea.gov/onepill) + CDC WONDER",82,68,68,72,82,58,62,78),
mk("HDP11","Organic Farming Growth: Certified Organic Acreage by State and Crop Category","The expansion of organic agriculture in America — from niche to 5.5 million acres, but still only 1% of total farmland","MAP","US","State choropleth","agriculture","USDA: Organic Integrity Database (organic.ams.usda.gov/integrity/Search)",55,58,72,62,52,72,58,88),
mk("HDP12","H-1B Visa Concentration: Employers Sponsoring the Most Temporary Workers by Metro","Where H-1B workers cluster — the tech corridor from San Jose to Seattle and the consulting firms that sponsor thousands each","MAP","US","Dot map","immigration","USCIS: H-1B Employer Data Hub (uscis.gov/tools/reports-and-studies/h-1b-employer-data-hub)",55,58,72,65,58,72,58,90),
mk("HDP13","Campaign Finance by Small Donor Share: Which Politicians Are Funded by the People vs PACs","Percentage of campaign funds from small-dollar donors vs large donors and PACs — the money map of political independence","CHART","US","Bar chart","democracy","FEC: Campaign Finance Data (fec.gov/data) + OpenSecrets (opensecrets.org)",65,68,72,68,72,58,62,88),
mk("HDP14","Tranq Dope Geography: Xylazine-Fentanyl Combination Spread Across US Drug Markets","The geographic march of xylazine contamination in the fentanyl supply — from Kensington Philadelphia to nationwide","MAP","US","Dot map","drugs","ONDCP: Xylazine Response (whitehouse.gov/ondcp) + CDC Health Alert Network",72,58,62,75,80,75,68,72),
mk("HDP15","Farm Suicide Rate: Agricultural Worker Deaths by Suicide Compared to Other Occupations","Farmers die by suicide at rates 3-5x the general population — the mental health crisis in agriculture mapped against farm income","MAP","US","State choropleth","agriculture","CDC: Suicide Among Agriculture Workers (cdc.gov/mmwr) + USDA Farm Income Data",85,62,68,72,82,68,65,72),
mk("HDP16","Climate Migration Within the US: Domestic Movers Citing Weather or Climate as Reason","Americans moving away from wildfire zones, flood plains, and hurricane paths — the internal climate migration already happening","MAP","US","Line map","immigration","Census Bureau: Current Population Survey Migration Supplement (census.gov)",68,72,72,72,68,78,72,72),
mk("HDP17","State Legislature Composition: Percentage of Seats Held by Each Party Over 50 Years","The partisan sorting of state legislatures — from competitive in most states to one-party dominance in nearly all","CHART","US","Line chart","democracy","NCSL: State Partisan Composition (ncsl.org/about-state-legislatures/partisan-composition)",62,62,75,65,62,62,58,90),
mk("HDP18","Marijuana Potency Escalation: Average THC Content in Cannabis Products by Year","THC content in commercially sold cannabis went from 4% in 1995 to 20%+ in flower and 80%+ in concentrates by 2024","CHART","US","Line chart","drugs","NIDA: Potency Monitoring Program (nida.nih.gov)",58,68,72,72,62,55,62,82),
mk("HDP19","Water Rights Conflicts: States With Active Agricultural Water Disputes","Where farmers are fighting over water — the Colorado River compact, Ogallala pumping limits, and California vs everyone","MAP","US","Special map","agriculture","Bureau of Reclamation: Water Operations (usbr.gov/uc/water) + State water boards",68,55,68,68,78,78,68,78),
mk("HDP20","Birthright Citizenship Map: Countries That Grant Citizenship by Birth on Their Soil","Jus soli vs jus sanguinis — which countries automatically grant citizenship to anyone born there vs those requiring parental citizenship","MAP","World","World choropleth","immigration","CIA World Factbook: Citizenship (cia.gov/the-world-factbook)",55,58,75,72,58,72,62,88),
mk("HDP21","Lobbying Spending by Industry: Which Sectors Spend Most to Influence Congress","The lobbying leaderboard — pharmaceutical, tech, finance, and energy spending mapped against legislative outcomes","CHART","US","Bar chart","democracy","OpenSecrets: Lobbying Data (opensecrets.org/federal-lobbying)",65,62,72,68,72,58,58,90),
mk("HDP22","Drug Overdose Reversal Access: States With Standing Orders for Over-the-Counter Naloxone","Where you can buy Narcan without a prescription — state naloxone access laws mapped against overdose death rates","MAP","US","Bivariate choropleth","drugs","PDAPS: Prescription Drug Abuse Policy System (pdaps.org) + CDC WONDER",72,68,72,62,72,72,58,82),
mk("HDP23","Regenerative Agriculture Adoption: Farms Using Cover Crops and No-Till by County","The quiet soil health revolution — where farmers are adopting regenerative practices and what percentage of cropland is covered","MAP","US","County choropleth","agriculture","USDA: Census of Agriculture Conservation Practices (nass.usda.gov/AgCensus)",55,48,68,68,55,75,68,82),
mk("HDP24","Immigration Detention Facility Map: Every ICE Detention Center by Type and Capacity","Every facility used to detain immigrants — federal, private, county jails with ICE contracts — mapped with capacity and average stay","MAP","US","Dot map","immigration","ICE: Online Detainee Locator + DHS OIG Reports (ice.gov)",72,58,72,65,78,78,62,82),
mk("HDP25","Ballot Access Barriers: How Hard It Is for Third-Party Candidates to Get on the Ballot by State","Signature requirements, filing fees, and deadlines that keep independent and third-party candidates off ballots — the two-party lock mapped","MAP","US","State choropleth","democracy","Ballot Access News: State Requirements (ballot-access.org)",58,58,72,72,68,72,68,85),
mk("HDP26","Drug Price vs Research Cost: Pharmaceutical Company R&D Spending vs Revenue by Drug","The industry claims high prices fund research — but marketing spending exceeds R&D at most major pharma companies","XREF","World","Scatter plot","drugs","SEC: Pharmaceutical Company 10-K Filings + GlobalData (globaldata.com)",68,68,72,78,72,58,68,80),
mk("HDP27","Crop Insurance Payouts: Federal Crop Insurance Claims by County and Disaster Type","Where USDA crop insurance money flows — the counties that receive the most disaster payments, dominated by drought and flooding","MAP","US","County choropleth","agriculture","USDA: RMA Crop Insurance Data (rma.usda.gov/data-tools/summary-of-business)",58,52,72,65,62,78,58,90),
mk("HDP28","Migrant Worker Contribution: GDP Impact of Immigrant Labor by Industry Sector","How much of each industrys output depends on immigrant labor — agriculture at 75%, construction at 30%, tech at 25%","CHART","US","Bar chart","immigration","CBO: The Economic and Fiscal Effects of Immigration (cbo.gov) + BLS Foreign-Born Workers",62,62,75,72,62,58,62,82),
mk("HDP29","Revolving Door Tracker: Former Congress Members Now Registered Lobbyists","How many ex-lawmakers cash in — the percentage of departing Congress members who become lobbyists, by party and committee","CHART","US","Bar chart","democracy","OpenSecrets: Revolving Door (opensecrets.org/revolving)",68,65,72,72,72,55,65,85),
mk("HDP30","Supervised Injection Sites: Where Safe Consumption Facilities Exist or Are Proposed","The global map of supervised injection facilities — from Vancouver to Sydney to New Yorks first US sites, with overdose prevention data","MAP","World","Dot map","drugs","Drug Policy Alliance: Supervised Consumption Services (drugpolicy.org)",65,55,68,72,68,72,72,72),
mk("HDP31","Average Farm Age: Mean Age of Farm Operators by State and Trend Over 30 Years","Americas farmers keep getting older — average age now 58 and rising, with young farmer entry rates declining in most states","MAP","US","State choropleth","agriculture","USDA: Census of Agriculture Demographics (nass.usda.gov/AgCensus)",65,58,72,68,68,68,62,90),
mk("HDP32","Refugee Resettlement Capacity: Annual Admissions vs Presidential Ceiling by Year","The collapse and partial rebuilding of US refugee resettlement — from 200K annual capacity to under 15K and the slow recovery","CHART","US","Area chart","immigration","State Department: Refugee Processing Center (wrapsnet.org)",72,58,72,68,72,62,58,88),
mk("HDP33","Congressional Term Length: Average Years Served by Members of Congress Over Time","How Congress went from citizen legislators to career politicians — average tenure nearly tripled since the founding era","CHART","US","Line chart","democracy","Congressional Research Service: Member Service Data (fas.org/sgp/crs)",58,62,75,65,62,55,62,90),
mk("HDP34","Drug Take-Back Events: Pounds of Unused Medication Collected by DEA by State","Annual DEA drug take-back day results — how much unused medication Americans are sitting on and which states participate most","MAP","US","State choropleth","drugs","DEA: National Prescription Drug Take Back Day (dea.gov/takebackday)",52,62,68,62,52,68,58,82),
mk("HDP35","Pollinator-Dependent Crops: Agricultural Products That Require Bee Pollination by Value","The $15B crops that depend on pollinators — almonds, apples, blueberries — mapped against honeybee colony health by state","MAP","US","Bivariate choropleth","agriculture","USDA: Pollinator Research (ars.usda.gov/research/pollinator-health) + Census of Agriculture",62,55,72,68,65,78,68,82),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDP batch)")
