import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCK01","The Medicaid Expansion Map: States That Said No and the Deaths That Followed","Estimated excess deaths in non-expansion states since 2014 — the cost of politics","MAP","US-state","Bivariate choropleth","health/politics","KFF: Medicaid expansion (kff.org); CDC: Mortality (wonder.cdc.gov); Census: Insurance (census.gov/acs)",88,78,78,78,88,75,72,78),
mk("HCK02","Where Deregulated Power Grids Kill: Texas Winter Storm Deaths Mapped","ERCOT grid failure deaths mapped against infrastructure spending and executive bonuses","MAP","US-state","Special map","energy/law","ERCOT: Grid data (ercot.com); Texas DSHS: Mortality data; ASCE: Infrastructure (infrastructurereportcard.org)",85,78,75,78,88,78,75,72),
mk("HCK03","The Human Cost of For-Profit Prisons: Mortality and Violence Rates vs Public Facilities","Death rates in private vs public prisons mapped by state — the profit motive kills","CHART","US-state","Bar chart","law/health","BJS: Mortality in correctional (bjs.gov); SEC: Private prison filings (sec.gov); DOJ: Conditions (justice.gov)",85,72,72,80,85,68,75,72),
mk("HCK04","Where Gun Access During Mental Health Crises Turns Survivable Moments Into Deaths","States with extreme risk protection orders mapped against crisis-period firearm suicides","MAP","US-state","Bivariate choropleth","guns/psychology","Everytown: Red flag laws (everytownresearch.org); CDC: Suicide (wonder.cdc.gov); RAND: ERPOs (rand.org)",85,75,72,78,85,72,75,75),
mk("HCK05","The Cost of Inaction on Climate: Annual Disaster Deaths and Damages by State","Climate-attributable deaths and dollar losses mapped — the bill is already due","MAP","US-state","State choropleth","climate/economy","NOAA: Billion-dollar disasters (ncei.noaa.gov); CDC: Heat deaths (wonder.cdc.gov); FEMA: Declarations (fema.gov)",82,78,78,75,82,78,68,80),
mk("HCK06","Where Maternal Mortality Is a Policy Choice: States With Abortion Bans vs Maternal Death Rates","Post-Dobbs maternal mortality changes mapped — early data from restrictive states","MAP","US-state","Bivariate choropleth","health/law","CDC: Maternal mortality (cdc.gov); Guttmacher: Abortion laws (guttmacher.org); WHO: Maternal health (who.int)",88,78,75,82,90,72,72,68),
mk("HCK07","The Opioid Crisis Was Manufactured: Purdue Pharma Sales Territory Map vs Overdose Deaths","Marketing intensity mapped against subsequent overdose mortality by county — the correlation is damning","XREF","US-county","Bivariate choropleth","drugs/crime","CDC: Overdose (wonder.cdc.gov); DEA: ARCOS (deadiversion.usdoj.gov); Court documents: Purdue marketing data",88,78,72,85,88,78,78,75),
mk("HCK08","Where Lead Poisoning Was a Policy Choice: Cities That Knew About Lead Pipes and Did Nothing","Known lead contamination mapped against child blood lead levels — Flint wasnt unique","MAP","US-metro","Dot map","health/infrastructure","EPA: Lead data (epa.gov); CDC: Lead surveillance (cdc.gov); Reuters: Lead testing (reuters.com)",85,80,72,80,85,78,72,75),
mk("HCK09","The Cost of Not Expanding Broadband: Economic Output Lost in Rural Counties","GDP foregone per unconnected household mapped — the digital divide has a price tag","MAP","US-county","County choropleth","rural/economy","FCC: Broadband (fcc.gov); BEA: County GDP (bea.gov); NTIA: Broadband equity (ntia.gov)",78,75,72,72,72,78,70,75),
mk("HCK10","Middle East Civilian Casualties: Every Documented Death in US-Involved Conflicts Since 2001","Airwars data mapped by year, country, and operation — the human cost of intervention","MAP","Middle East","Dot map","middle_east/war","Airwars: Casualty data (airwars.org); ACLED: Conflict (acleddata.com); UNAMA/UNAMI: Reports",85,62,68,78,88,78,72,72),
mk("HCK11","Where Workplace Deaths Are Preventable: OSHA Inspection Rates vs Fatality Rates","States with fewer inspectors have more deaths — the enforcement gap mapped","MAP","US-state","Bivariate choropleth","labor/law","BLS: Fatal injuries (bls.gov/iif); OSHA: Inspections (osha.gov); AFL-CIO: Death on the Job (aflcio.org)",82,75,75,78,82,72,72,78),
mk("HCK12","The Vaccine Refusal Map: Where Preventable Disease Outbreaks Cluster","Exemption rates mapped against measles and pertussis outbreaks — the consequence zones","MAP","US-county","Bivariate choropleth","health/education","CDC: Vaccination coverage (cdc.gov); State health depts: Exemption data; WHO: Outbreak (who.int)",82,78,78,78,80,78,68,78),
mk("HCK13","Where Lack of Health Insurance Kills: Uninsured Deaths by State and County","Estimated deaths attributable to uninsurance mapped — 45K+ Americans per year","MAP","US-state","State choropleth","health/poverty","Census: Insurance (census.gov/acs); AJPH: Uninsurance mortality (ajph.org); KFF: Coverage (kff.org)",85,78,75,78,85,72,68,75),
mk("HCK14","The Cost of Mass Incarceration: $182 Billion Per Year Mapped by What Else It Could Fund","Annual prison spending per state mapped against equivalent education, healthcare, or infrastructure spending","CHART","US-state","Bar chart","crime/finance","Vera: Incarceration costs (vera.org); BJS: Corrections (bjs.gov); NCES: Spending (nces.ed.gov)",82,78,78,78,80,68,72,78),
mk("HCK15","Where Climate Denialism Has a Body Count: Heat Deaths in States That Blocked Climate Policy","States blocking climate action mapped against heat-related mortality trends","MAP","US-state","Bivariate choropleth","climate/politics","CDC: Heat deaths (wonder.cdc.gov); NCSL: Climate legislation (ncsl.org); NOAA: Temperature (noaa.gov)",82,72,72,80,85,72,78,72),
mk("HCK16","The Human Cost of the War on Drugs: 50 Years of Incarceration Mapped","Cumulative drug war prisoners by race and decade — the generational damage quantified","CHART","US","Area chart","drugs/race","BJS: Drug offenders (bjs.gov); Sentencing Project: Drug war (sentencingproject.org); Census: Demographics (census.gov)",85,72,75,78,85,72,72,78),
mk("HCK17","Where Factory Pollution Causes Cancer: Manufacturing Sites and Cancer Cluster Overlaps","EPA TRI facilities mapped against elevated cancer incidence by census tract","MAP","US-county","Bivariate choropleth","manufacturing/health","EPA: TRI (epa.gov/tri); NCI: Cancer statistics (cancer.gov); CDC: Environmental health (cdc.gov)",82,72,72,78,82,78,72,72),
mk("HCK18","The Eviction Crisis Body Count: Health Outcomes After Forced Displacement","Eviction rates mapped against subsequent ER visits, mortality, and homelessness by county","XREF","US-county","Scatter plot","housing/health","Princeton Eviction Lab (evictionlab.org); CDC: Health (cdc.gov); HUD: Homelessness (hudexchange.info)",82,80,68,78,82,72,75,68),
mk("HCK19","Where Police Use of Force Kills Disproportionately: Race-Adjusted Fatality Rates","Police killings per million population by race and department — the disparity mapped","CHART","US-metro","Bar chart","law/race","Mapping Police Violence (mappingpoliceviolence.us); Census: Demographics (census.gov); FBI: UCR (ucr.fbi.gov)",85,72,75,78,88,70,70,78),
mk("HCK20","The Cost of Student Debt on Health: Borrowers With Worse Mental and Physical Outcomes","Student loan burden correlated with depression, delayed healthcare, and chronic stress by state","XREF","US-state","Scatter plot","education/health","Federal Reserve: Student loans (newyorkfed.org); Gallup: Wellbeing (gallup.com); CDC: BRFSS (cdc.gov/brfss)",78,82,68,78,72,68,72,68),
mk("HCK21","Where Air Pollution Kills Children: Pediatric Asthma Rates Near Industrial Zones","Childhood asthma hospitalization rates mapped against proximity to pollution sources","MAP","US-county","Bivariate choropleth","children/environment","CDC: Asthma (cdc.gov/asthma); EPA: AQI (epa.gov/aqi); Census: Demographics (census.gov)",85,82,72,78,82,78,72,75),
mk("HCK22","The Sports Head Injury Coverup Timeline: What Leagues Knew and When","CTE research suppression mapped against league revenue and player injury settlements","CHART","US","Line chart","sports/health","BU CTE Center (bu.edu/cte); NFL: Settlement data; NCAA: Concussion policy; JAMA: Research (jamanetwork.com)",82,72,68,80,82,68,75,68),
mk("HCK23","Where Religious Exemptions Let Children Die: States Without Medical Neglect Laws","Faith healing exemptions mapped against preventable child deaths from treatable conditions","MAP","US-state","State choropleth","religion/children","CHILD: Religious exemptions (childrenshealthcare.org); CDC: Child mortality (cdc.gov); NCSL: Laws (ncsl.org)",85,72,72,82,88,72,78,68),
mk("HCK24","The Psychology of Hopelessness Mapped: Deaths of Despair by County","Suicide, overdose, and alcoholic liver disease combined — the geography of giving up","MAP","US-county","County choropleth","psychology/health","CDC: WONDER (wonder.cdc.gov); Case & Deaton: Deaths of despair research; Census: Demographics (census.gov)",88,78,75,78,85,80,72,80),
mk("HCK25","Where Cutting Education Budgets Shows Up in Crime Rates 15 Years Later","State education spending mapped against subsequent crime rate changes — the investment gap","XREF","US-state","Scatter plot","education/crime","NCES: Spending (nces.ed.gov); FBI: UCR (ucr.fbi.gov); BJS: Crime trends (bjs.gov)",78,72,72,80,75,68,78,72),
mk("HCK26","The Middle East Sanctions Death Toll: Civilian Mortality Under Economic Blockades","Excess child mortality in sanctioned MENA countries — Iraq, Iran, Syria, Yemen mapped","CHART","Middle East","Bar chart","middle_east/health","UNICEF: Child mortality (unicef.org); WHO: Mortality (who.int); World Bank: Health (worldbank.org)",85,62,72,80,85,68,78,72),
mk("HCK27","Where Deregulated Nursing Homes Kill: Staffing Ratios vs Patient Mortality by State","States that allow lower staffing mapped against nursing home death rates","MAP","US-state","Bivariate choropleth","health/law","CMS: Nursing home compare (cms.gov); KFF: Staffing (kff.org); GAO: Quality reports (gao.gov)",82,78,75,78,82,72,70,78),
mk("HCK28","The Human Cost of Americas Crumbling Bridges: Near-Miss and Collapse Incidents Mapped","Bridge failures and weight-restricted detours mapped against deferred maintenance spending","MAP","US","Dot map","infrastructure/transportation","FHWA: NBI (fhwa.dot.gov); NTSB: Bridge investigations (ntsb.gov); ASCE: Bridge data (infrastructurereportcard.org)",78,75,72,78,78,80,70,78),
mk("HCK29","Where Gun Access During Domestic Violence Escalation Turns Abuse Into Murder","Intimate partner homicide rates mapped against gun restriction laws for DV offenders","MAP","US-state","Bivariate choropleth","guns/gender","FBI: SHR (ucr.fbi.gov); Giffords: DV gun laws (giffords.org); CDC: IPV data (cdc.gov)",85,78,75,78,88,72,72,78),
mk("HCK30","The Environmental Racism Body Count: Excess Deaths in Minority-Heavy Pollution Zones","Life expectancy gaps in communities near TRI facilities mapped by racial composition","MAP","US-county","Bivariate choropleth","environment/race","EPA: EJScreen (epa.gov/ejscreen); CDC: Life expectancy (cdc.gov); Census: Demographics (census.gov)",85,75,72,80,85,78,75,75),
mk("HCK31","Where Poverty Kills Babies: Infant Mortality Rates by County Income","The richest and poorest counties have 3x different infant death rates — same country","MAP","US-county","Bivariate choropleth","poverty/health","CDC: Infant mortality (cdc.gov); Census: Income (census.gov/acs); HRSA: Perinatal (hrsa.gov)",88,80,78,78,85,78,68,80),
mk("HCK32","The Prescription Drug Death Pipeline: Overdose Deaths Traced to Marketing Regions","Pharmaceutical marketing territory maps overlaid with overdose mortality — the product kills its customers","XREF","US-county","Bivariate choropleth","drugs/economy","DEA: ARCOS (deadiversion.usdoj.gov); CDC: Overdose (wonder.cdc.gov); Court documents: Pharma marketing",85,72,72,82,85,78,78,72),
mk("HCK33","Where Climate Change Already Displaced Americans: Internal Migration From Disaster Zones","County-level outmigration following floods, fires, and hurricanes mapped 2017-2025","MAP","US-county","Dot map","climate/demographics","IRS: SOI migration (irs.gov); FEMA: Declarations (fema.gov); Census: Population change (census.gov)",80,78,72,78,80,78,75,75),
mk("HCK34","The Rural Ambulance Crisis: Response Times Over 30 Minutes in 800+ Counties","EMS response time mapped against cardiac survival rates — minutes equal lives","MAP","US-county","County choropleth","rural/health","NEMSIS: EMS data (nemsis.org); CDC: Cardiac (cdc.gov); NREMT: Provider shortage (nremt.org)",85,78,75,78,82,80,72,72),
mk("HCK35","Where Americas Children Go Hungry: Food Insecurity Among Kids by School District","Child food insecurity rates mapped against free lunch participation and SNAP gaps","MAP","US-county","County choropleth","children/food","USDA: Food insecurity (ers.usda.gov); Feeding America: Map the Meal Gap (feedingamerica.org); Census: Child poverty (census.gov)",85,85,78,72,82,78,68,80),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCK ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCK batch)")
