import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDI01","The Poverty Line Is a Lie: What the Federal Poverty Level Actually Buys by Metro","Monthly budget breakdown for a family of four at the FPL in San Francisco vs Jackson MS vs Omaha — same income, wildly different lives","XREF","US","Bar chart","poverty","Census Bureau: Supplemental Poverty Measure (census.gov/topics/income-poverty/supplemental-poverty-measure)",78,82,75,72,72,62,72,85),
mk("HDI02","Nuclear Power Revival: Every Reactor Under Construction or Planned Worldwide","Global map of nuclear reactors being built — China leading with 20+, plus SMR projects in the US, UK, and Canada","MAP","World","Dot map","energy","IAEA: Power Reactor Information System (pris.iaea.org)",58,48,72,68,62,80,65,90),
mk("HDI03","Bridge Condition Scorecard: Structurally Deficient Bridges by State","Percentage of highway bridges rated structurally deficient in each state — West Virginia at 20%, some states under 3%","MAP","US","State choropleth","infrastructure","FHWA: National Bridge Inventory (fhwa.dot.gov/bridge/nbi)",68,72,78,68,72,78,58,92),
mk("HDI04","Rent Burden Map: Share of Renters Spending 30%+ of Income on Housing by County","Where the rent is most crushing — counties where over half of all renters are cost-burdened","MAP","US","County choropleth","housing","Census Bureau: ACS Housing Data (data.census.gov)",75,85,78,62,72,78,55,90),
mk("HDI05","Payday Lender Density: Predatory Lending Locations vs Bank Branches by ZIP Code","Where payday lenders outnumber banks — the financial services desert mapped against median income","MAP","US","Bivariate choropleth","poverty","CFPB: Payday Lending Data + FDIC Branch Data (consumerfinance.gov)",75,72,72,72,78,78,68,80),
mk("HDI06","The Solar Boom: Residential Solar Installation Rate by State 2015 vs 2025","Explosion of rooftop solar across the US — California still leads but Texas, Florida, and the Southeast are surging","MAP","US","Bivariate choropleth","energy","EIA: Monthly Solar Photovoltaic Module Shipments (eia.gov)",58,65,72,65,52,75,58,85),
mk("HDI07","Lead Pipe Map: Estimated Homes Still Connected to Lead Water Lines by City","Cities with the most remaining lead service lines — Chicago alone has 400K, plus Newark, Detroit, Milwaukee","MAP","US","Dot map","infrastructure","EPA: Lead Service Line Inventories (epa.gov/ground-water-and-drinking-water/lead-service-line-inventories)",78,72,72,72,80,78,62,78),
mk("HDI08","Tiny Home Zoning: Cities That Legalized Accessory Dwelling Units","Map of cities and states that have legalized ADUs and tiny homes — the slow-motion housing policy revolution","MAP","US","Dot map","housing","AARP: ADU Legislation Tracker (aarp.org/livable-communities)",58,68,72,65,52,70,68,75),
mk("HDI09","SNAP Benefit Adequacy: Maximum Monthly Food Stamp Allotment vs Actual Grocery Costs","How far SNAP benefits stretch in each state — the gap between maximum allotment and what a healthy diet actually costs locally","XREF","US","Bar chart","poverty","USDA: SNAP Data Tables + BLS Food Price Index (fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap)",72,78,75,68,72,58,62,85),
mk("HDI10","The Grid Reliability Map: Power Outage Hours Per Customer by Utility","Annual average outage duration by utility service area — which power companies keep the lights on and which dont","MAP","US","County choropleth","energy","EIA: Annual Electric Power Industry Report (eia.gov/electricity/data/eia861)",68,78,75,68,65,75,60,88),
mk("HDI11","Dam Safety Grades: High-Hazard Dams With Poor Condition Ratings by State","Every dam rated both high-hazard potential and poor or unsatisfactory condition — thousands of potential failures nationwide","MAP","US","Dot map","infrastructure","ASCE: Infrastructure Report Card + NID (infrastructurereportcard.org)",72,62,68,72,82,78,65,82),
mk("HDI12","Zillow vs Reality: Zestimate Accuracy by Metro — Where the Algorithm Gets It Most Wrong","Median absolute error of Zillow Zestimates by metro area — some markets off by 7%+, others within 2%","RANK","US","Bar chart","housing","Zillow: Zestimate Accuracy Table (zillow.com/z/zestimate)",55,72,72,75,52,58,72,82),
mk("HDI13","Working Poor: Families Below Poverty Line Where at Least One Adult Works Full-Time","Percentage of poor families with a full-time worker by state — the myth of poverty as laziness demolished in one map","MAP","US","State choropleth","poverty","Census Bureau: ACS Poverty Status by Work Experience (data.census.gov)",80,78,75,72,75,72,65,88),
mk("HDI14","Wind Power Installed Capacity: Megawatts by County Across the US","Every wind turbine cluster in America mapped by installed capacity — the wind corridor from Texas to the Dakotas","MAP","US","County choropleth","energy","EIA: Wind Energy Data (eia.gov/electricity/monthly)",55,52,75,58,48,82,55,92),
mk("HDI15","Sewer Overflow Events: Combined Sewer Overflow Discharges by City and Year","Cities that dump raw sewage into rivers during heavy rain — the disgusting infrastructure problem nobody talks about","MAP","US","Dot map","infrastructure","EPA: Combined Sewer Overflow Control Policy (epa.gov/npdes/combined-sewer-overflows)",68,62,65,78,72,72,72,75),
mk("HDI16","The Missing Middle: Homes Priced $200K-$350K as Share of Market by Metro","The vanishing starter home — metros where the middle of the housing market has been squeezed out from both ends","CHART","US","Bar chart","housing","Redfin: Housing Market Data (redfin.com/news/data-center)",72,82,72,72,68,62,62,80),
mk("HDI17","Extreme Poverty Persistence: US Census Tracts in Deep Poverty for 30+ Consecutive Years","Places where poverty concentrated in 1990 and never left — persistent poverty tracts in the Delta, Reservations, inner cities, and Appalachia","MAP","US","County choropleth","poverty","USDA: Persistent Poverty Counties (ers.usda.gov/topics/rural-economy-population/rural-poverty-well-being)",82,68,72,65,78,80,65,88),
mk("HDI18","Geothermal Potential: Untapped Underground Heat Resources by Region","Map of geothermal energy potential across the US — the western states sitting on enormous unused clean energy reserves","MAP","US","Special map","energy","NREL: Geothermal Prospector (nrel.gov/gis/geothermal)",58,48,68,72,58,80,72,78),
mk("HDI19","Water Main Breaks: Annual Pipe Failures Per 100 Miles by City","Which cities have the leakiest water infrastructure — some losing 30%+ of treated water to broken pipes underground","RANK","US","Bar chart","infrastructure","AWWA: State of the Water Industry (awwa.org)",65,68,72,72,68,62,65,75),
mk("HDI20","Corporate Landlord Map: Single-Family Homes Owned by Institutional Investors by Metro","Where Wall Street owns the neighborhood — metros where corporate landlords own 5%+ of all single-family rental homes","MAP","US","Dot map","housing","CoreLogic: Single-Family Investor Activity (corelogic.com)",75,78,72,75,78,72,68,75),
mk("HDI21","Benefits Cliff: Where Earning One More Dollar Costs Thousands in Lost Aid","Effective marginal tax rates over 100% — the income levels where working more actually makes families poorer due to lost benefits","CHART","US","Line chart","poverty","CBO: Effective Marginal Tax Rates (cbo.gov)",78,78,72,78,75,60,72,82),
mk("HDI22","Battery Storage Boom: Grid-Scale Energy Storage Installations by State","Megawatt-hours of battery storage deployed by state — California and Texas dominating but the map is changing fast","MAP","US","State choropleth","energy","EIA: Battery Storage in the United States (eia.gov/analysis/studies/electricity/batterystorage)",55,48,72,65,55,72,62,85),
mk("HDI23","School Building Age: Average Public School Construction Year by District","Which districts are teaching kids in buildings from the 1950s — the map of Americas crumbling school infrastructure","MAP","US","County choropleth","infrastructure","DOE: Condition of Americas Public School Facilities (nces.ed.gov)",68,72,72,65,65,72,62,78),
mk("HDI24","Eviction Filing Rate: Landlord-Initiated Evictions Per 100 Renter Households by City","Which cities evict renters at the highest rates — Richmond, Phoenix, and Houston in the hundreds per day","MAP","US","Dot map","housing","Eviction Lab: Princeton University (evictionlab.org)",78,75,72,68,80,72,62,85),
mk("HDI25","The Utility Shutoff Map: Households That Had Power or Water Disconnected by State","Where utilities cut off essential services for nonpayment — states without shutoff protections vs those with moratoriums","MAP","US","State choropleth","poverty","NEADA: National Energy Assistance Directors Association (neada.org)",78,75,72,68,78,72,62,72),
mk("HDI26","Fossil Fuel Subsidies: Government Support for Oil, Gas, and Coal by Country","Annual subsidies — both direct payments and tax breaks — that governments give to fossil fuel companies, dwarfing renewable support","RANK","World","Bar chart","energy","IMF: Fossil Fuel Subsidies Data (imf.org/en/Topics/climate-change/energy-subsidies)",68,58,72,75,72,62,68,85),
mk("HDI27","Levee Risk: Miles of Levee With Unacceptable Risk Rating by State","The nations flood protection infrastructure graded — thousands of miles of levees rated as unacceptable by the Army Corps","MAP","US","State choropleth","infrastructure","USACE: National Levee Database (levees.sec.usace.army.mil)",72,62,68,72,80,75,62,82),
mk("HDI28","Manufactured Housing Concentration: Mobile Home Parks as Share of Housing Stock by County","Where manufactured housing is the dominant housing type — rural South, Appalachia, and parts of the Southwest at 20%+","MAP","US","County choropleth","housing","Census Bureau: ACS Housing Type Data (data.census.gov)",58,68,72,68,55,78,62,90),
mk("HDI29","The Poverty Penalty: How Much More Low-Income Households Pay for Basic Services","The poor pay more per unit for banking, insurance, groceries, and utilities than affluent households — the data quantified","CHART","US","Bar chart","poverty","Brookings: The High Cost of Being Poor (brookings.edu)",78,78,72,78,72,58,72,72),
mk("HDI30","Peak Oil Demand: When Each Country Is Projected to Hit Maximum Fossil Fuel Consumption","Projected year of peak oil demand by country — some already past it, others decades away, the global transition timeline","CHART","World","Line chart","energy","IEA: World Energy Outlook (iea.org/reports/world-energy-outlook)",62,52,68,72,68,65,70,78),
mk("HDI31","Broadband Affordability: Monthly Internet Cost as Share of Median Income by Country","Where internet access is a luxury vs a utility — the US among the most expensive per Mbps in the developed world","RANK","World","Bar chart","infrastructure","ITU: ICT Price Baskets (itu.int/en/ITU-D/Statistics)",65,72,72,68,62,58,62,82),
mk("HDI32","Conversion Therapy Ban Map: Where LGBTQ Youth Are Protected From Harmful Practices","States and cities that have banned conversion therapy for minors — the patchwork of protection across the US","MAP","US","State choropleth","housing","Movement Advancement Project: Conversion Therapy Laws (lgbtmap.org)",72,68,72,62,72,72,62,82),
mk("HDI33","Child Poverty After Government Transfers: How Much the Safety Net Reduces Child Poverty by State","Child poverty rate before vs after government benefits — states where transfers cut child poverty by half vs barely at all","XREF","US","Bar chart","poverty","Census Bureau: SPM by State (census.gov/topics/income-poverty/supplemental-poverty-measure)",78,72,75,68,72,62,62,85),
mk("HDI34","Stranded Assets: Fossil Fuel Infrastructure That May Never Earn Back Its Investment","Coal plants, pipelines, and refineries at risk of becoming stranded assets as the energy transition accelerates — mapped with investment value","MAP","World","Dot map","energy","Carbon Tracker: Stranded Assets (carbontracker.org)",62,48,65,75,72,75,75,72),
mk("HDI35","Americas Unfunded Infrastructure Gap: What It Would Cost to Fix Everything by Category","The $2.6 trillion gap between what we spend and what we need on roads, bridges, water, schools, and broadband — broken down by category","CHART","US","Bar chart","infrastructure","ASCE: Infrastructure Report Card (infrastructurereportcard.org)",68,72,78,65,72,62,58,88),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDI batch)")
