import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCH01","POV: You Were Born in the Wrong Zip Code","Side-by-side life outcome comparison for two zip codes 5 miles apart — the opportunity gap in one image","CHART","US-county","Infographic","inequality/geography","Opportunity Atlas (opportunityatlas.org); Census: ACS (census.gov/acs); CDC: Health (cdc.gov)",88,88,80,82,82,78,78,78),
mk("HCH02","I Mapped Every Dollar Bill in Your Wallet and Where It Goes","Average household spending breakdown animated as money flows to corporations, government, and banks","CHART","US","Special map","economy/finance","BLS: Consumer Expenditure (bls.gov/cex); Federal Reserve: Flow of Funds (federalreserve.gov); Census: Income (census.gov)",75,88,72,72,60,78,78,72),
mk("HCH03","This Map Shows Why Your Rent Is So High and Its Not What You Think","Zoning restrictions vs housing supply deficit mapped — single-family zoning is the bottleneck","MAP","US-metro","Bivariate choropleth","housing/law","Zillow: Rent (zillow.com); Census: Building permits (census.gov); National Zoning Atlas (zoningatlas.org)",82,88,75,78,80,78,72,72),
mk("HCH04","Tell Me Your State and Ill Tell You When You Die","Life expectancy variation by state animated over 40 years — the divergence is terrifying","MAP","US-state","Animated choropleth","health/geography","IHME: Life expectancy (healthdata.org); CDC: NVSS (cdc.gov); Census: Demographics (census.gov)",88,85,78,78,82,82,72,85),
mk("HCH05","Every American Should See This Map of Where Their Tax Dollars Actually Go","Federal spending by category animated pie chart with state-level breakdown","CHART","US","Special map","economy/politics","USASpending: Federal budget (usaspending.gov); OMB: Budget (whitehouse.gov/omb); Tax Policy Center (taxpolicycenter.org)",78,85,78,72,68,72,65,85),
mk("HCH06","This Chart Made Me Rethink Everything About College","Degree ROI by major and school type mapped — some degrees have negative lifetime value","CHART","US","Scatter plot","education/economy","DOE: College Scorecard (collegescorecard.ed.gov); Georgetown: CEW (cew.georgetown.edu); Census: Earnings (census.gov)",82,88,78,80,78,72,72,80),
mk("HCH07","I Overlaid Every School Shooting With the Closest Gun Store and Now I Cant Sleep","K-12 school shootings proximity-mapped to nearest FFL — the clustering is eerie","MAP","US","Dot map","guns/education","K-12 School Shooting Database (chds.us); ATF: FFL data (atf.gov); NCES: Schools (nces.ed.gov)",88,78,68,82,88,80,78,68),
mk("HCH08","This Is What $15/Hour Rents You in Every US City","Affordable housing for minimum wage workers mapped — spoiler: almost nowhere","MAP","US-metro","Bar chart","housing/labor","NLIHC: Out of Reach (nlihc.org); BLS: Minimum wage (bls.gov); Census: Fair market rent (census.gov)",85,90,80,72,78,72,65,85),
mk("HCH09","One Chart That Explains Why Nobody Can Afford Anything Anymore","Wages vs costs of housing, healthcare, education, and food since 1980 — the scissors graph","CHART","US","Line chart","economy/prices","BLS: CPI (bls.gov/cpi); Census: Income (census.gov); Federal Reserve: Data (fred.stlouisfed.org)",88,90,82,78,82,70,62,88),
mk("HCH10","I Asked AI to Find the Most Unfair Map in America and It Found This","Composite unfairness index of 15 metrics by county — the result is devastating","MAP","US-county","County choropleth","inequality/data","Census: ACS (census.gov/acs); CDC: Health (cdc.gov); FBI: UCR (ucr.fbi.gov); USDA: Food (ers.usda.gov)",82,82,72,78,80,80,78,72),
mk("HCH11","The Scariest Timeline Youll See Today: Americas Antibiotic Resistance Map","Drug-resistant infections mapped by hospital and region — the post-antibiotic future","MAP","US-state","State choropleth","health/science","CDC: AR Threats (cdc.gov/drugresistance); WHO: AMR (who.int); IDSA: Resistance data (idsociety.org)",82,72,72,82,82,72,78,75),
mk("HCH12","I Mapped What Your City Would Look Like Under 3 Feet of Sea Level Rise","Major US coastal metros with 3-foot rise overlay — real estate value at risk","MAP","US-metro","Special map","climate/housing","NOAA: Sea level (tidesandcurrents.noaa.gov); Climate Central: Surging Seas (sealevel.climatecentral.org); Zillow: Values (zillow.com)",85,78,72,80,82,88,72,78),
mk("HCH13","This Chart Shows How Much of Your Life You Spend Working vs Living","Time use breakdown by country — Americans work 200+ more hours per year than Europeans","CHART","World","Bar chart","labor/international","OECD: Time use (oecd.org); BLS: ATUS (bls.gov/tus); ILO: Working time (ilo.org)",80,88,78,75,72,68,68,82),
mk("HCH14","I Put Every Billionaires Tax Rate Next to Yours and Lost My Mind","Effective tax rates by income percentile — the line goes down when it should go up","CHART","US","Line chart","finance/inequality","ProPublica: Secret IRS Files (propublica.org); IRS: SOI (irs.gov); Tax Policy Center (taxpolicycenter.org)",88,85,80,82,85,68,72,78),
mk("HCH15","This Is What Gerrymandering Looks Like From Space","The most gerrymandered districts overlaid on satellite imagery — the absurdity is visual","MAP","US-state","Special map","democracy/geography","PlanScore: District scores (planscore.org); Census: TIGER districts (census.gov); ESRI: Satellite imagery",78,72,75,78,78,88,72,80),
mk("HCH16","Every American City That Used to Have a Trolley System: A Tragedy in Maps","Before and after the Great American Streetcar Conspiracy — 1920s vs today","MAP","US-metro","Special map","transportation/history","Transit History: Streetcar data; BTS: Transit (bts.gov); Census: Historical (census.gov)",78,78,72,80,75,85,78,72),
mk("HCH17","I Overlaid Redlining Maps From 1930 With Current Home Values and Holy Crap","The 90-year persistence of racial housing policy — same neighborhoods, same disparities","MAP","US-metro","Bivariate choropleth","housing/race","Mapping Inequality: HOLC (dsl.richmond.edu); Zillow: Home values (zillow.com); Census: Demographics (census.gov)",88,80,78,82,85,82,72,82),
mk("HCH18","The Map That Proves Your Commute Is Killing You — Literally","Commute time correlated with all-cause mortality by county — 45 minutes is the threshold","XREF","US-county","Scatter plot","transportation/health","Census: Commute (census.gov/acs); CDC: Mortality (wonder.cdc.gov); Gallup: Wellbeing (gallup.com)",82,88,72,80,78,70,75,72),
mk("HCH19","I Ranked All 50 States by How Hard They Make It to Vote","Composite voting access score: registration, ID, early voting, mail-in, polling hours","RANK","US-state","Ranked list","democracy/law","Brennan Center: Voter access (brennancenter.org); NCSL: Election laws (ncsl.org); MIT: Elections (electionlab.mit.edu)",80,78,78,72,80,68,70,80),
mk("HCH20","This Map of Where Your Amazon Package Was Made Will Ruin Your Day","Country of origin for top 100 Amazon products traced to factory locations — the global supply chain","MAP","World","Line map","trade/manufacturing","Census: Import data (census.gov/trade); UN Comtrade: Trade data (comtrade.un.org); Amazon: Product data",72,82,65,75,68,78,78,62),
mk("HCH21","I Compared Police Budgets to Teacher Budgets in Every US City and Im Done","Per-capita police spending vs per-pupil education spending — the priority map","MAP","US-metro","Scatter plot","law/education","Census: Government finance (census.gov/govs); NCES: Spending (nces.ed.gov); FBI: UCR (ucr.fbi.gov)",82,80,78,78,82,68,70,80),
mk("HCH22","The Map TikTok Doesnt Want You to See: Where User Data Flows","Data center locations, government data request volumes, and content moderation mapped","MAP","World","Line map","technology/international","Transparency reports: Tech companies; Cloudflare Radar: Internet (radar.cloudflare.com); BIS: Data flows (bis.org)",72,75,62,78,72,75,80,58),
mk("HCH23","This Animation of Wealth Inequality Since 1980 Broke My Brain","Top 1% vs bottom 50% wealth share animated year by year — the crossover point hits hard","CHART","US","Animated line chart","inequality/history","Federal Reserve: DFA (federalreserve.gov); World Inequality Database (wid.world); Census: Income (census.gov)",88,82,80,82,85,75,72,85),
mk("HCH24","I Mapped Every Food Desert in America and Then Overlaid Fast Food Density","Where grocery stores wont go, McDonalds thrives — the food access inversion","MAP","US-county","Bivariate choropleth","food/health","USDA: Food access (ers.usda.gov); Census: Retail (census.gov); CDC: Obesity (cdc.gov)",82,82,78,78,78,80,72,80),
mk("HCH25","Your Grandparents Could Buy a House on One Income — This Chart Shows What Changed","Median home price to median income ratio 1960-2025 — the dream died around 2002","CHART","US","Line chart","housing/history","Census: Median home price (census.gov); BLS: Wages (bls.gov); Federal Reserve: Mortgage (fred.stlouisfed.org)",88,90,82,78,82,68,65,85),
mk("HCH26","I Compared CEO Pay to Worker Pay in Every Industry and I Need to Sit Down","CEO-to-median worker pay ratios by sector — the range is 50:1 to 1500:1","CHART","US","Bar chart","inequality/labor","AFL-CIO: Exec paywatch (aflcio.org); BLS: OES (bls.gov/oes); SEC: Proxy filings (sec.gov)",85,85,78,80,82,68,68,82),
mk("HCH27","This Map of Americas Lead Pipes Will Make You Check Your Faucet","Known lead service lines mapped against child blood lead levels — the correlation is direct","MAP","US-county","Bivariate choropleth","health/infrastructure","EPA: Lead service lines (epa.gov); CDC: Lead data (cdc.gov); Census: Housing age (census.gov)",85,85,75,78,82,80,72,75),
mk("HCH28","I Tracked Where Billionaires Money Goes During Elections and Its Worse Than You Think","Top 100 political donors mapped against legislation outcomes they funded","CHART","US","Special map","democracy/finance","OpenSecrets: Top donors (opensecrets.org); FEC: Contributions (fec.gov); GovTrack: Voting (govtrack.us)",82,78,72,80,82,72,75,75),
mk("HCH29","The Wildfire Risk Map Your Insurance Company Hopes You Never See","Fire risk mapped against insurance premium changes and non-renewal zones","MAP","US-county","Bivariate choropleth","climate/housing","USFS: Wildfire risk (fs.usda.gov); FEMA: Risk (hazards.fema.gov); NAIC: Insurance data (naic.org)",82,82,75,78,80,82,72,78),
mk("HCH30","I Put Every Country on a Chart of Freedom vs Happiness and the Result Was Unexpected","Democracy index vs happiness index — authoritarian countries arent automatically miserable","CHART","World","Scatter plot","democracy/psychology","EIU: Democracy (eiu.com); WHR: Happiness (worldhappiness.report); Freedom House: Scores (freedomhouse.org)",72,72,72,85,68,68,82,80),
mk("HCH31","This Map Shows Where Americas Bridges Are Literally Falling Apart","Structurally deficient bridges mapped with daily traffic volume — risk x exposure","MAP","US-county","Dot map","infrastructure/transportation","FHWA: NBI (fhwa.dot.gov); BTS: Traffic (bts.gov); ASCE: Bridge data (infrastructurereportcard.org)",80,78,78,72,78,82,68,85),
mk("HCH32","The Chart That Shows Why Your Parents Generation Had It Easier — With Receipts","College cost, home price, healthcare, and wages all indexed to 1975 — the divergence is criminal","CHART","US","Line chart","economy/history","BLS: CPI (bls.gov/cpi); Census: Historical income (census.gov); College Board: Tuition (collegeboard.org); FRED (fred.stlouisfed.org)",88,90,80,80,82,68,65,88),
mk("HCH33","I Mapped Every Toxic Release Site in America and Then Colored It by Neighborhood Income","TRI facilities mapped against surrounding census tract income — the pattern is stark","MAP","US","Dot map","environment/race","EPA: TRI (epa.gov/toxics-release-inventory); Census: ACS (census.gov/acs); EJScreen: EJ data (epa.gov/ejscreen)",82,75,75,78,82,80,72,82),
mk("HCH34","Your State Thinks This Is a Living Wage (Its Not) — The Real Cost of Living Map","MIT Living Wage vs state minimum wage vs actual median wage — the triple gap","MAP","US-state","Bar chart","labor/prices","MIT: Living Wage (livingwage.mit.edu); DOL: Minimum wage (dol.gov); BLS: OES (bls.gov/oes)",85,88,80,75,80,70,68,85),
mk("HCH35","The Most Depressing Chart in American History: Healthcare Costs vs Every Other Expense Since 1960","Healthcare inflation vs general inflation vs wage growth — the jaws of financial death","CHART","US","Line chart","health/economy","CMS: NHE (cms.gov); BLS: CPI-Medical (bls.gov); Census: Income (census.gov); FRED (fred.stlouisfed.org)",88,85,82,78,82,68,68,88),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCH ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCH batch)")
