import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCU01","The Loneliness Epidemic Mapped: Social Isolation Rates by County","Percentage of adults who report having no close friends, mapped by county and correlated with population density","MAP","US","County choropleth","psychology","Cigna: Loneliness and the Workplace Survey (cigna.com/newsroom/news-releases)",85,82,72,78,82,80,72,68),
mk("HCU02","Americas Therapist Desert: Mental Health Providers Per Capita by County","Counties with fewer than 1 mental health professional per 5,000 residents, mostly rural","MAP","US","County choropleth","psychology","HRSA: Health Professional Shortage Areas (data.hrsa.gov/topics/health-workforce)",82,78,78,72,82,82,68,82),
mk("HCU03","The Happiness U-Curve: Life Satisfaction by Age Across Countries","The universal U-shaped happiness curve — satisfaction dips in your 40s and rebounds in your 60s — by country","CHART","World","Line chart","psychology","World Happiness Report: Age and Wellbeing (worldhappiness.report)",72,82,75,78,68,72,72,78),
mk("HCU04","Dunning-Kruger Nation: Self-Assessed vs. Actual Competence by Field","How Americans rate their own abilities vs. objective measures — driving, financial literacy, geography knowledge","CHART","US","Bar chart","psychology","PISA: Self-Assessment Data (oecd.org/pisa)",68,82,72,82,65,68,82,68),
mk("HCU05","The Attention Economy: Average Human Attention Span vs. Content Length Over Time","Declining average attention span plotted against shrinking average article length, video duration, and song intro length","CHART","World","Line chart","psychology","Microsoft: Attention Span Research (advertising.microsoft.com)",72,85,72,78,68,70,72,65),
mk("HCU06","Seasonal Affective Geography: Depression Rates by Latitude and Sunlight Hours","Correlation between annual sunlight hours and depression diagnosis rates by state","XREF","US","Scatter plot","psychology","CDC: BRFSS Mental Health Data (cdc.gov/brfss)",75,78,75,72,72,72,72,78),
mk("HCU07","The Trust Collapse: Percentage of Americans Who Trust Institutions Over Time","Trust in government, media, religious institutions, corporations, and science from 1970 to present","CHART","US","Line chart","psychology","Gallup: Confidence in Institutions (news.gallup.com/poll/1597/confidence-institutions.aspx)",78,80,78,72,78,70,68,85),
mk("HCU08","The Cognitive Bias Atlas: Which Biases Dominate Decision-Making by Domain","Mapping the most prevalent cognitive biases in healthcare, finance, criminal justice, and politics","CHART","World","Treemap","psychology","Kahneman: Cognitive Bias Research Meta-Analysis (scholar.google.com)",65,72,68,78,62,75,82,55),
mk("HCU09","Screen Time and Adolescent Mental Health: The Inflection Point","Teen depression, anxiety, and suicide rates plotted against smartphone adoption — the 2012 inflection","XREF","US","Scatter plot","psychology","CDC: Youth Risk Behavior Survey (cdc.gov/yrbs)",85,78,72,75,85,70,72,78),
mk("HCU10","The Nostalgia Index: When Americans Think the Country Was at Its Best","What decade Americans of different ages consider Americas peak era — the psychology of national nostalgia","CHART","US","Bar chart","psychology","Pew: American Nostalgia Survey (pewresearch.org/politics)",68,82,72,78,65,70,78,72),
mk("HCU11","Decision Fatigue in the Justice System: Parole Decisions Before and After Lunch","The famous study showing parole grant rates drop from 65% to near 0% before meals, then reset after eating","CHART","World","Line chart","psychology","PNAS: Extraneous Factors in Judicial Decisions (pnas.org/content/108/17/6889)",72,72,68,88,72,70,82,72),
mk("HCU12","The Empathy Gap Map: Self-Reported Empathy Scores by State","State-level empathy scores from psychological surveys, showing geographic variation in emotional responsiveness","MAP","US","State choropleth","psychology","Journal of Personality: Geographic Variation in Empathy (onlinelibrary.wiley.com)",68,72,65,78,65,78,78,62),
mk("HCU13","Sleep Deprivation Nation: Average Sleep by County and Its Consequences","Counties where average adult sleep is under 6 hours, overlaid with accident rates and health outcomes","MAP","US","County choropleth","psychology","CDC: BRFSS Sleep Data (cdc.gov/sleep/data-and-statistics)",78,82,75,72,75,80,68,78),
mk("HCU14","The Placebo Effect Is Getting Stronger: Drug Trial Placebo Response Over Time","Rising placebo response rates in clinical trials over decades, especially in the US — making drug approval harder","CHART","World","Line chart","psychology","McGill: Placebo Studies (mcgill.ca/placebo-studies)",65,62,68,88,68,68,85,72),
mk("HCU15","Fear Index: What Americans Are Most Afraid of by Generation","Top fears by generation — Gen Z fears climate and AI, Boomers fear government and crime, all fear healthcare costs","CHART","US","Bar chart","psychology","Chapman University: Survey of American Fears (chapman.edu/wilkinson/research-centers/babbie-center/survey-american-fears)",72,82,72,75,68,70,72,72),
mk("HCU16","The Bystander Effect Mapped: Response Rates to Public Emergencies by City Size","How city size correlates with likelihood of strangers intervening in emergencies — the urban bystander problem","XREF","US","Scatter plot","psychology","APA: Bystander Intervention Meta-Analysis (apa.org/pubs/journals)",70,72,68,78,72,68,80,58),
mk("HCU17","Deaths of Despair: The Geography of Suicide, Overdose, and Alcoholism","County-level deaths of despair rates — the Case-Deaton phenomenon mapped in granular detail","MAP","US","County choropleth","psychology","CDC: WONDER Multiple Cause of Death (wonder.cdc.gov)",88,78,78,72,88,82,68,82),
mk("HCU18","The Gratification Delay Test: Marshmallow Test Results Predict Adult Outcomes","How performance on delayed gratification tests in childhood correlates with income, health, and education decades later","CHART","World","Scatter plot","psychology","Mischel: Marshmallow Test Longitudinal Data (psychology.columbia.edu)",68,72,68,82,65,68,78,68),
mk("HCU19","Imposter Syndrome by Profession: Who Feels Like a Fraud","Rates of self-reported imposter syndrome across professions — highest in academia, medicine, and tech","RANK","World","Bar chart","psychology","International Journal of Behavioral Science: Impostor Phenomenon (paulineroseclance.com)",68,82,72,78,62,68,72,65),
mk("HCU20","The Grief Gap: Average Bereavement Leave vs. Time to Process Loss","Employer-offered bereavement leave (average 3 days) vs. psychological research on grief timelines (6-12 months)","CHART","US","Bar chart","psychology","SHRM: Bereavement Leave Survey (shrm.org/resourcesandtools)",80,82,72,78,78,68,72,72),
mk("HCU21","Conspiracy Theory Geography: Where Conspiratorial Thinking Is Highest","State-level conspiracy belief rates — flat earth, QAnon, moon landing, vaccine microchip — correlated with trust metrics","MAP","US","State choropleth","psychology","PRRI: American Values Survey (prri.org/research)",72,72,68,80,72,78,75,65),
mk("HCU22","The Burnout Map: Worker Burnout Rates by Industry and State","Self-reported burnout rates by industry — healthcare, education, and tech lead — mapped by state concentration","MAP","US","State choropleth","psychology","Gallup: State of the Global Workplace (gallup.com/workplace)",78,85,72,72,75,78,68,72),
mk("HCU23","How Color Affects Spending: The Psychology of Retail Store Design","How store color schemes, music tempo, and scent affect purchase amounts — the invisible manipulation of retail","CHART","World","Bar chart","psychology","Journal of Consumer Psychology: Sensory Marketing (myscp.org)",62,78,68,82,58,72,78,58),
mk("HCU24","The Name Bias: Resume Callback Rates by First Name","Identical resumes with different names — callback rates showing persistent racial and gender bias in hiring","CHART","US","Bar chart","psychology","NBER: Are Emily and Greg More Employable (nber.org/papers/w9873)",82,78,75,78,82,68,72,75),
mk("HCU25","Americas ACE Epidemic: Adverse Childhood Experiences by State","Prevalence of adverse childhood experiences — abuse, neglect, household dysfunction — by state","MAP","US","State choropleth","psychology","CDC: ACE Study Data (cdc.gov/violenceprevention/aces)",85,78,72,72,85,78,68,78),
mk("HCU26","The Paradox of Choice: Countries With More Consumer Options vs. Reported Satisfaction","Number of product choices in grocery stores correlated with consumer satisfaction scores by country","XREF","World","Scatter plot","psychology","Schwartz: Paradox of Choice Research (swarthmore.edu/SocSci/bschwar1)",65,72,68,82,62,68,82,62),
mk("HCU27","Learned Helplessness in Education: Student Agency Scores by School Funding Level","How student sense of control over outcomes varies with school funding levels — the psychology of resource deprivation","XREF","US","Scatter plot","psychology","PISA: Student Agency and School Resources (oecd.org/pisa)",78,72,68,78,75,68,78,65),
mk("HCU28","The Social Comparison Trap: Instagram Usage vs. Body Image Dissatisfaction by Country","Country-level Instagram penetration plotted against body image dissatisfaction rates, especially among teen girls","XREF","World","Scatter plot","psychology","Royal Society: Social Media and Mental Health (royalsociety.org)",80,78,68,75,78,68,72,68),
mk("HCU29","The Compliance Curve: How Quickly People Obey Authoritarian Orders","Milgram experiment replication results across countries and decades — obedience rates havent changed much","CHART","World","Bar chart","psychology","APA: Milgram Replication Studies (apa.org/pubs/journals)",72,68,68,82,78,68,78,72),
mk("HCU30","Americas Anxiety Timeline: Anxiety Disorder Diagnoses by Year and Age Group","Anxiety diagnosis rates over time, stratified by age — the steepest rise is in 18-25 year olds since 2010","CHART","US","Line chart","psychology","NIMH: Mental Health Statistics (nimh.nih.gov/health/statistics)",82,82,78,72,80,70,68,82),
mk("HCU31","The Peak-End Rule in Action: How We Remember Experiences vs. How We Live Them","How humans remember vacations, medical procedures, and meals — moment-to-moment experience vs. retrospective rating","CHART","World","Line chart","psychology","Kahneman: Peak-End Rule Research (scholar.google.com)",62,72,68,82,58,68,82,62),
mk("HCU32","Moral Foundations by Political Affiliation: The Psychology Behind the Partisan Divide","Jonathan Haidts moral foundations — care, fairness, loyalty, authority, sanctity — scored by political leaning","CHART","US","Bar chart","psychology","YourMorals.org: Moral Foundations Survey Data (yourmorals.org)",72,72,72,78,72,70,78,72),
mk("HCU33","The Hedonic Treadmill Visualized: Lottery Winners vs. Paraplegics One Year Later","The classic finding that life satisfaction returns to baseline after extreme positive and negative events","CHART","World","Line chart","psychology","Brickman: Hedonic Adaptation Study (scholar.google.com)",68,75,68,85,65,68,82,65),
mk("HCU34","Anchoring Bias in Real Estate: How Listing Price Warps Everyones Valuation","How the initial listing price anchors all subsequent bids and appraisals regardless of actual property value","CHART","US","Scatter plot","psychology","Journal of Economic Psychology: Anchoring in Real Estate (sciencedirect.com/journal/journal-of-economic-psychology)",68,78,72,82,65,68,78,68),
mk("HCU35","The Friendship Recession: Average Number of Close Friends Over Time","Average number of close friends reported by Americans, 1990 vs. 2000 vs. 2010 vs. 2024 — a dramatic collapse","CHART","US","Bar chart","psychology","Survey Center on American Life: Friendship Survey (americansurveycenter.org)",82,88,78,78,80,68,72,75),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCU batch)")
