import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCF01","What Americans Pay for Healthcare vs What Everyone Else Gets","US spending per capita vs OECD outcomes — we pay double for worse results","CHART","World","Scatter plot","health/international","OECD: Health spending (oecd.org); WHO: Outcomes (who.int); CMS: NHE (cms.gov)",88,82,82,78,80,68,65,88),
mk("HCF02","US Paid Parental Leave vs Every Other Developed Country: The One Chart","Zero mandated weeks vs 14-52 weeks elsewhere — the US alone at the bottom","CHART","World","Bar chart","labor/international","OECD: Family policy (oecd.org); ILO: Maternity (ilo.org); DOL: FMLA data (dol.gov)",85,85,85,72,78,68,62,88),
mk("HCF03","Where Americans Work More Hours for Less Pay Than Europeans With the Same Job","Same occupation, same output, different hours and pay — mapped by country and role","CHART","World","Bar chart","labor/international","OECD: Hours worked (oecd.org); ILO: Wages (ilo.org); BLS: Productivity (bls.gov)",82,85,78,78,78,68,70,82),
mk("HCF04","The Global Gun Chart That Silences Every Argument: Civilian Deaths per 100K","US is the outlier among wealthy nations by a factor of 25 — the chart speaks","CHART","World","Bar chart","guns/international","IHME: GBD (healthdata.org); Small Arms Survey (smallarmssurvey.org); UNODC: Homicide (unodc.org)",85,75,85,75,82,68,62,88),
mk("HCF05","US Child Poverty Rate vs Every OECD Country Before and After Government Transfers","Before transfers we rank middle of pack — after transfers we rank dead last","CHART","World","Bar chart","children/international","OECD: Child poverty (oecd.org); LIS: Income study (lisdatacenter.org); Census: CPS (census.gov)",88,82,80,82,82,68,70,85),
mk("HCF06","The Global Democracy Ranking: Where America Actually Falls on 50 Metrics","US ranks 29th in the EIU Democracy Index — the specific metrics we fail on","RANK","World","Ranked list","democracy/international","EIU: Democracy Index (eiu.com); V-Dem: Indices (v-dem.net); Freedom House: Scores (freedomhouse.org)",78,72,78,80,78,68,72,85),
mk("HCF07","What $100 of Insulin Costs in Every Country on Earth","The US price is not just higher — its in a different universe from every other nation","CHART","World","Bar chart","drugs/international","RAND: Insulin prices (rand.org); WHO: Essential medicines (who.int); PharmacyChecker: Prices (pharmacychecker.com)",88,82,85,82,82,68,65,85),
mk("HCF08","US Infrastructure Grade vs Countries That Spend Less: The Embarrassing Comparison","Countries spending half what we do with better bridges, rail, and broadband","CHART","World","Bar chart","infrastructure/international","ASCE: Report card (infrastructurereportcard.org); WEF: Competitiveness (weforum.org); OECD: Infrastructure (oecd.org)",80,78,78,78,78,68,70,82),
mk("HCF09","The Math Achievement Gap: US Students vs the World Since 2000","PISA scores animated over time — the US decline is gradual but relentless","CHART","World","Line chart","education/international","OECD: PISA (oecd.org/pisa); NCES: TIMSS (nces.ed.gov); IEA: Education (iea.nl)",78,78,80,75,75,68,65,88),
mk("HCF10","What Incarceration Looks Like From Space: US Prison Population vs Rest of World","4% of world population, 20% of world prisoners — the global comparison","CHART","World","Bar chart","crime/international","World Prison Brief (prisonstudies.org); BJS: Corrections (bjs.gov); UNODC: Crime (unodc.org)",85,72,82,78,85,68,65,88),
mk("HCF11","US Maternal Mortality vs Every Country With Comparable Wealth: Getting Worse Not Better","The only wealthy nation where maternal death rates are rising — mapped over time","CHART","World","Line chart","health/gender","WHO: Maternal mortality (who.int); CDC: MMWR (cdc.gov); OECD: Health (oecd.org)",88,82,80,80,85,68,68,85),
mk("HCF12","What a Month of Daycare Costs Worldwide: The US Childcare Premium","US parents pay 4-10x what other developed nations charge — the map of family burden","CHART","World","Bar chart","children/international","OECD: Family database (oecd.org); ChildCare Aware: Data (childcareaware.org); ILO: Care economy (ilo.org)",85,88,80,78,78,68,65,82),
mk("HCF13","The Global Broadband Speed and Price Map: What You Get Per Dollar","Speed per dollar mapped globally — US ranks 15th in speed, 1st in price","CHART","World","Scatter plot","technology/international","Ookla: Speedtest (speedtest.net); Cable.co.uk: Broadband pricing; ITU: ICT data (itu.int)",75,82,78,78,72,68,68,82),
mk("HCF14","US Life Expectancy Is Falling While Everyone Elses Is Rising: The Divergence","The moment the US trendline separated from peer nations — and why","CHART","World","Line chart","health/international","OECD: Life expectancy (oecd.org); WHO: Mortality (who.int); CDC: NVSS (cdc.gov)",88,80,82,80,85,68,68,88),
mk("HCF15","What Teachers Earn vs National Average Income: The Global Respect Gap","Teacher salary as % of national average by country — the US ranks near the bottom","CHART","World","Bar chart","education/international","OECD: Education at a Glance (oecd.org); UNESCO: Teacher data (uis.unesco.org); BLS: OES (bls.gov/oes)",80,82,78,75,75,68,68,82),
mk("HCF16","US Vacation Days vs the Rest of the World: The Burnout Map","0 mandated vacation days vs 20-30 elsewhere — US workers are the exhausted outlier","CHART","World","Bar chart","labor/international","CEPR: Vacation study (cepr.net); ILO: Working conditions (ilo.org); OECD: Better life (oecd.org)",82,88,82,72,72,68,62,85),
mk("HCF17","The Global College Cost Comparison: What a Degree Costs in Every OECD Country","US tuition is 2-50x higher than peer nations — some charge nothing","CHART","World","Bar chart","education/international","OECD: Education spending (oecd.org); College Board: Trends (collegeboard.org); UNESCO: Education (uis.unesco.org)",85,85,82,78,78,68,65,85),
mk("HCF18","Where Americas Middle Class Would Rank Globally: The Median Income Map","US median household income placed on the global wealth distribution — still top 10% worldwide","CHART","World","Bar chart","economy/international","World Bank: Income (worldbank.org); LIS: Cross-national (lisdatacenter.org); Census: Income (census.gov)",72,78,75,78,62,68,72,82),
mk("HCF19","US Mass Shooting Frequency vs Every Other Wealthy Nation Combined","Combined mass shooting deaths in all OECD nations vs US alone — the ratio is staggering","CHART","World","Bar chart","guns/international","GVA: Mass shootings (gunviolencearchive.org); UNODC: Homicide (unodc.org); Small Arms Survey (smallarmssurvey.org)",85,72,82,78,85,68,65,82),
mk("HCF20","What Americans Think European Healthcare Is Like vs What It Actually Is","Wait times, satisfaction, outcomes — survey perception vs actual data","CHART","World","Bar chart","health/psychology","Commonwealth Fund: Mirror (commonwealthfund.org); OECD: Health (oecd.org); Gallup: Healthcare (gallup.com)",75,78,72,82,68,68,78,78),
mk("HCF21","The Global Homelessness Comparison: Rate Per 100K in Every OECD Country","US homeless rate benchmarked against countries with universal housing policies","CHART","World","Bar chart","housing/international","OECD: Affordable housing (oecd.org); HUD: AHAR (hudexchange.info); FEANTSA: EU data (feantsa.org)",82,78,78,75,78,68,68,78),
mk("HCF22","US Workers Compensation vs European Social Safety Nets: The Recovery Gap","What happens when you get hurt at work in the US vs Germany vs Sweden","CHART","World","Bar chart","labor/international","DOL: Workers comp (dol.gov); OECD: Social spending (oecd.org); ILO: Social protection (ilo.org)",78,80,75,78,72,68,72,78),
mk("HCF23","What $1000 in Medical Debt Does to Americans vs Citizens of Other Rich Countries","Medical bankruptcy rates globally — the US is the only country where this exists","CHART","World","Bar chart","health/finance","Commonwealth Fund: Affordability (commonwealthfund.org); WHO: Financial protection (who.int); KFF: Medical debt (kff.org)",85,85,78,80,80,68,72,78),
mk("HCF24","The Global Rail Map: Passenger Miles Per Capita and Americas Last Place","US rail investment per capita vs China, Japan, EU — the infrastructure choice visualized","CHART","World","Bar chart","transportation/international","UIC: Rail statistics (uic.org); BTS: Transport (bts.gov); World Bank: Infrastructure (worldbank.org)",75,72,78,75,72,72,68,85),
mk("HCF25","US Police Killings Per Capita vs Every OECD Nation: Not Even Close","The US rate is 30-50x higher than peer nations — the law enforcement comparison","CHART","World","Bar chart","law/international","Mapping Police Violence (mappingpoliceviolence.us); UNODC: Homicide (unodc.org); Fatal Encounters (fatalencounters.org)",85,72,78,78,88,68,68,78),
mk("HCF26","The Global Inequality Comparison: Gini Coefficients Since 1980","US inequality rising while Europes holds steady — the divergence animated","CHART","World","Line chart","inequality/international","World Bank: Gini (worldbank.org); LIS: Income study (lisdatacenter.org); OECD: Inequality (oecd.org)",80,72,78,75,78,68,68,85),
mk("HCF27","What Electoral Democracy Looks Like in Every Country: Turnout vs Representation","Voter turnout mapped against proportionality of representation — the US scores poorly on both","CHART","World","Scatter plot","democracy/international","IDEA: Turnout (idea.int); V-Dem: Proportionality (v-dem.net); Gallagher Index data",72,68,75,75,72,68,72,82),
mk("HCF28","US CEO-to-Worker Pay Ratio vs Every Other Country That Tracks It","399:1 in the US vs 20:1 in Japan — the global comparison of executive excess","CHART","World","Bar chart","inequality/international","AFL-CIO: Executive paywatch (aflcio.org); OECD: Wages (oecd.org); ILO: Wage report (ilo.org)",82,82,80,80,80,68,68,82),
mk("HCF29","The Global Drug Policy Scorecard: Decriminalization vs Criminalization Outcomes","Every approach tried by every country scored on addiction, death, and crime outcomes","RANK","World","Ranked list","drugs/international","EMCDDA: Policy (emcdda.europa.eu); UNODC: World Drug Report (unodc.org); Transform Drug Policy (tdpf.org.uk)",78,68,78,78,72,68,75,78),
mk("HCF30","Americas Crumbling Bridges Benchmarked: Structurally Deficient Rate vs Europe and Asia","US bridge condition compared to nations that invest half as much — embarrassing","CHART","World","Bar chart","infrastructure/international","FHWA: NBI (fhwa.dot.gov); WEF: Infrastructure (weforum.org); OECD: Transport (oecd.org)",78,75,78,75,75,70,68,82),
mk("HCF31","What Women Earn vs Men in Every Country: The Global Gender Pay Gap Map","Gender pay gap mapped globally with US state-level detail inset","MAP","World","World choropleth","gender/international","OECD: Gender wage gap (oecd.org); World Bank: Gender (worldbank.org); BLS: Earnings (bls.gov)",80,78,78,72,75,78,65,85),
mk("HCF32","The Global Environmental Performance Index: Where the US Actually Ranks","Air, water, biodiversity, climate policy — US rank on each subindex","RANK","World","Ranked list","environment/international","Yale: EPI (epi.yale.edu); WHO: Environment (who.int); OECD: Environment (oecd.org)",72,68,78,75,72,68,68,85),
mk("HCF33","US Military Spending vs the Next 10 Countries Combined: The Annual Ritual Chart","Updated every year and still just as shocking — 2025 numbers","CHART","World","Bar chart","military/international","SIPRI: Military expenditure (sipri.org); DOD: Budget (defense.gov); World Bank: GDP (worldbank.org)",78,72,82,72,72,68,60,88),
mk("HCF34","What Poverty Looks Like in America vs What It Looks Like in Europe: Same Metric Different Outcome","Using the same relative poverty definition — US poverty is deeper and more persistent","CHART","World","Bar chart","poverty/international","OECD: Poverty rates (oecd.org); LIS: Income (lisdatacenter.org); Census: SPM (census.gov)",82,78,78,78,78,68,72,82),
mk("HCF35","The Global Food Waste Map: What Gets Thrown Away by Country Per Capita","US wastes 2x the global average — mapped with hunger rates for the irony","CHART","World","Bar chart","food/international","FAO: Food waste (fao.org); USDA: Food loss (ers.usda.gov); UNEP: Food waste index (unep.org)",78,78,78,75,72,68,68,82),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCF ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCF batch)")
