import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCB01","Waffle House Density Predicts Hurricane Recovery Speed Better Than FEMA Models","The Waffle House Index is real — mapped against FEMA declaration timelines","XREF","US-state","Scatter plot","food/environment","Waffle House: Locations; FEMA: Declarations (fema.gov); NOAA: Hurricane data (noaa.gov)",70,78,62,88,60,68,88,62),
mk("HCB02","Where Divorce Lawyers Outnumber Marriage Counselors","Family law attorney vs therapist ratios by metro — the market reveals preferences","MAP","US-metro","Dot map","law/psychology","ABA: Lawyer data (americanbar.org); SAMHSA: Provider data (samhsa.gov); BLS: OES (bls.gov/oes)",68,78,65,80,65,68,82,65),
mk("HCB03","The Gun Paradox: Counties Where Gun Ownership Rose and Crime Fell — and Vice Versa","Both narratives are true somewhere — the full data shows geography is the variable","MAP","US-county","Bivariate choropleth","guns/crime","RAND: Gun ownership (rand.org); FBI: UCR (ucr.fbi.gov); CDC: Mortality (wonder.cdc.gov)",78,72,72,82,78,78,80,70),
mk("HCB04","Where Religious Communities Have the Longest Life Expectancy","Seventh-Day Adventists in Loma Linda live 10 years longer — mapped with Blue Zone data","MAP","World","Dot map","religion/health","Blue Zones: Longevity data (bluezones.com); IHME: Life expectancy (healthdata.org); Pew: Religion (pewresearch.org)",72,75,68,82,60,72,78,65),
mk("HCB05","The Middle East Peace Dividend: What 1% of Military Spending Could Build","Infrastructure, education, and healthcare that could be funded by minor defense cuts — mapped","CHART","Middle East","Bar chart","middle_east/economy","SIPRI: Military spending (sipri.org); World Bank: Sector spending (worldbank.org); UNDP: Development (undp.org)",78,62,75,78,72,68,78,72),
mk("HCB06","Where Psychologists Cluster: Mental Health Provider Maps Mirror Inequality","Therapists per capita by county mapped against need indicators — the inverse care law","MAP","US-county","Bivariate choropleth","psychology/inequality","HRSA: Provider data (hrsa.gov); CDC: PLACES (cdc.gov/places); Census: Income (census.gov)",80,78,72,75,78,78,72,75),
mk("HCB07","The Manufacturing Nostalgia Index: States Where Made in America Sentiment Is Highest vs Actual Manufacturing","Polling on manufacturing pride vs actual sector size — the gap reveals cultural identity","CHART","US-state","Scatter plot","manufacturing/psychology","Gallup: Manufacturing poll (gallup.com); BLS: Manufacturing share (bls.gov); Pew: Economic attitudes (pewresearch.org)",68,72,65,80,65,68,82,60),
mk("HCB08","Rural Americas Unexpected Broadband Winners: Small Towns That Got Fiber Before Big Cities","Municipal broadband successes mapped — Chattanooga, Wilson NC, and others","MAP","US-county","Dot map","rural/infrastructure","BroadbandNow: Coverage (broadbandnow.com); FCC: Broadband (fcc.gov); ILSR: Municipal networks (muninetworks.org)",72,75,72,78,65,72,75,72),
mk("HCB09","The Sports Curse: Cities That Built Stadiums and Got Poorer","Economic outcomes for metro areas 10 years after major stadium construction","CHART","US-metro","Scatter plot","sports/economy","Brookings: Stadium research (brookings.edu); BEA: Metro GDP (bea.gov); Census: Income (census.gov)",78,78,72,78,75,68,78,70),
mk("HCB10","Where Entertainment Spending Reveals Economic Anxiety","Counties where entertainment spending dropped before economic indicators declined — leading indicator","CHART","US-county","Line chart","entertainment/economy","BEA: PCE (bea.gov); Census: Retail (census.gov); BLS: CPI (bls.gov)",68,72,68,78,68,65,78,65),
mk("HCB11","The Democracy Paradox: Countries With Highest Voter Turnout Have Lowest Trust in Government","Turnout vs trust mapped globally — compulsory voting countries are the outlier","CHART","World","Scatter plot","democracy/international","IDEA: Voter turnout (idea.int); Gallup: World Poll trust (gallup.com); V-Dem: Democracy (v-dem.net)",72,68,72,82,72,68,80,78),
mk("HCB12","Where Your Zip Code Predicts Your Blood Pressure","Hypertension rates mapped at census tract level against walkability and food access","MAP","US-county","County choropleth","health/geography","CDC: PLACES (cdc.gov/places); Walk Score: Walkability (walkscore.com); USDA: Food access (ers.usda.gov)",78,82,72,72,68,78,68,78),
mk("HCB13","The Drug Price Paradox: Countries That Regulate Prices Spend Less AND Get Better Outcomes","Healthcare spending vs outcomes for regulated vs unregulated drug markets","CHART","World","Scatter plot","drugs/international","OECD: Health spending (oecd.org); WHO: Health outcomes (who.int); Commonwealth Fund: Comparison (commonwealthfund.org)",80,72,78,78,75,68,72,82),
mk("HCB14","Where Demographics Predicts Water Crisis: The Population-Aquifer Mismatch","Fast-growing counties overlaid with declining aquifer levels — the collision course mapped","MAP","US-county","Bivariate choropleth","demographics/environment","USGS: Groundwater (usgs.gov); Census: Population growth (census.gov); NASA: GRACE (nasa.gov)",82,72,75,80,82,80,78,75),
mk("HCB15","The Gun Culture Map: How Hunting License Rates Predict Political Lean","Hunting licenses per capita by county as a near-perfect political predictor","MAP","US-county","Bivariate choropleth","guns/politics","USFWS: Hunting licenses (fws.gov); MIT: Elections (electionlab.mit.edu); Census: Demographics (census.gov)",68,72,72,78,68,78,72,82),
mk("HCB16","Where Law Enforcement Uses Predictive Policing and What the Data Shows","Cities with predictive policing mapped against arrest rate changes and racial disparities","MAP","US-metro","Dot map","law/technology","ACLU: Policing tech (aclu.org); ProPublica: Machine bias (propublica.org); BJA: Grants (bja.ojp.gov)",80,72,68,78,82,72,78,62),
mk("HCB17","The Psychology of Political Yard Signs: Density Predicts Turnout Not Outcomes","Sign density by precinct mapped against actual vote margins — it means less than you think","CHART","US-county","Scatter plot","psychology/democracy","Academic: Yard sign studies; MIT: Elections (electionlab.mit.edu); Census: Demographics (census.gov)",62,72,62,80,58,65,82,52),
mk("HCB18","Middle East Internet Freedom: The Countries Where VPN Usage Reveals Censorship","VPN adoption rates mapped against government internet restrictions and press freedom","MAP","Middle East","World choropleth","middle_east/technology","Freedom House: FOTN (freedomhouse.org); Surfshark: VPN index (surfshark.com); RSF: Press freedom (rsf.org)",75,62,70,78,78,72,78,72),
mk("HCB19","The Manufacturing Renaissance Is Women-Led: Female Factory Employment Growing 3x Faster","Women entering advanced manufacturing while men leave — the gender flip mapped","CHART","US-state","Bar chart","manufacturing/gender","BLS: CPS (bls.gov/cps); Census: ACS industry (census.gov/acs); Deloitte: Manufacturing women (deloitte.com)",72,70,72,82,65,68,82,68),
mk("HCB20","Rural Americas Quiet Immigration Boom: Meatpacking Towns That Became Majority-Minority","Small towns transformed by immigrant labor — mapped with economic outcomes","MAP","US-county","Dot map","rural/immigration","Census: ACS demographics (census.gov/acs); BLS: Food manufacturing (bls.gov); USDA: Rural economy (ers.usda.gov)",78,75,72,78,72,72,78,72),
mk("HCB21","Where Your Sports Team Loses Money but Your Owners Net Worth Goes Up","The franchise appreciation game — team operating losses vs owner wealth gains","CHART","US","Scatter plot","sports/finance","Forbes: Team valuations (forbes.com); Bloomberg: Billionaire index (bloomberg.com); SEC: Filings (sec.gov)",72,78,68,80,72,65,80,65),
mk("HCB22","The Entertainment Gentrification Map: Neighborhoods That Got a Venue and Lost Affordability","Live music venue openings correlated with rent increases in surrounding blocks","MAP","US-metro","Dot map","entertainment/housing","Zillow: Rent data (zillow.com); Yelp: Venue data (yelp.com); Census: ACS housing (census.gov/acs)",72,78,65,75,68,72,78,60),
mk("HCB23","Every Country Where Drug Possession Is a Death Sentence and What Happens to Usage Rates","Draconian penalties mapped against actual drug use — deterrence doesnt deter","CHART","World","Scatter plot","drugs/law","UNODC: Drug laws (unodc.org); Harm Reduction Intl: Death penalty (hri.global); WHO: Drug use (who.int)",80,65,75,80,82,68,78,78),
mk("HCB24","The Demographic Crossover: US Counties Where Deaths Now Outnumber Births","Natural decrease counties mapped — spreading from rural Appalachia outward since 2010","MAP","US-county","Animated choropleth","demographics/geography","CDC: Vital statistics (cdc.gov); Census: Natural change (census.gov); USDA: Rural (ers.usda.gov)",78,72,78,78,78,80,72,82),
mk("HCB25","Where Guns Are Worth More Than Cars: Firearm Asset Value Per Household by State","Estimated civilian firearms value mapped against other household assets","CHART","US-state","Bar chart","guns/economy","ATF: Manufacturing data (atf.gov); NSSF: Market data (nssf.org); Federal Reserve: SCF (federalreserve.gov)",68,72,68,78,65,68,78,62),
mk("HCB26","The Law of Diminishing Democracy: How Money in Politics Reduces Voter Turnout","Campaign spending per capita inversely correlated with turnout — mapped by state","CHART","US-state","Scatter plot","law/democracy","OpenSecrets: Spending (opensecrets.org); MIT: Turnout (electionlab.mit.edu); FEC: Data (fec.gov)",75,72,70,78,75,68,78,72),
mk("HCB27","The Psychology of Screen Time: Hours Per Day Mapped Against Sleep, BMI, and Happiness","The dose-response curve that applies to every age group — mapped by state","CHART","US-state","Scatter plot","psychology/health","Nielsen: Screen time (nielsen.com); CDC: BRFSS (cdc.gov/brfss); Gallup: Wellbeing (gallup.com)",72,85,68,72,65,68,72,68),
mk("HCB28","Middle East Food Security: Countries That Import 90%+ of Their Calories","Food import dependency mapped against population growth and water scarcity","MAP","Middle East","Bar chart","middle_east/food","FAO: Food balance (fao.org); World Bank: Import data (worldbank.org); AQUASTAT: Water (fao.org/aquastat)",78,62,72,78,78,72,75,78),
mk("HCB29","Where Manufacturing Workers Vote: The Factory Floor Political Realignment 2000-2024","Manufacturing county voting shifts mapped election by election — the full realignment story","MAP","US-county","Animated choropleth","manufacturing/politics","BLS: Manufacturing employment (bls.gov); MIT: Elections (electionlab.mit.edu); Census: Industry (census.gov)",78,72,72,75,78,80,72,78),
mk("HCB30","The Rural Paradox: Americas Happiest Counties Are Also Its Poorest","Self-reported happiness mapped against income by county — money buys less than community","CHART","US-county","Scatter plot","rural/psychology","Gallup: Wellbeing (gallup.com); Census: Income (census.gov); USDA: Rural codes (ers.usda.gov)",75,82,65,85,65,68,82,62),
mk("HCB31","Where Sports Participation Predicts College Graduation Rates","High school athletic participation correlated with degree completion by county","CHART","US-county","Scatter plot","sports/education","NFHS: Participation (nfhs.org); NCES: Graduation (nces.ed.gov); Census: Education (census.gov/acs)",68,72,65,72,60,65,72,65),
mk("HCB32","The Entertainment Immigration Pipeline: How Bollywood and Nollywood Talent Flows to Hollywood","Creative worker visa data mapped by origin country and destination metro","MAP","World","Line map","entertainment/immigration","USCIS: Visa data (uscis.gov); BLS: Arts employment (bls.gov); UNESCO: Cultural industries (uis.unesco.org)",65,62,62,75,58,72,80,60),
mk("HCB33","Where Drug Courts Save Money: Cost Per Person vs Incarceration by State","Drug court spending vs prison spending per drug offender — the ROI mapped","CHART","US-state","Scatter plot","drugs/law","NADCP: Drug court data (nadcp.org); BJS: Corrections costs (bjs.gov); Vera: Cost of corrections (vera.org)",78,72,78,72,72,68,72,75),
mk("HCB34","The Demographic Destiny of American Religion: Projecting Church Membership to 2050","Current age-cohort data extrapolated — the math of religious decline","CHART","US","Line chart","demographics/religion","PRRI: Religion survey (prri.org); Pew: Projections (pewresearch.org); GSS: Religious attendance (gss.norc.org)",72,72,72,78,72,68,75,70),
mk("HCB35","Where Gun Dealers Outnumber Grocery Stores: The American Retail Landscape","ATF licensee count vs SNAP retailer count by county — a jarring comparison map","MAP","US-county","Bivariate choropleth","guns/food","ATF: FFL data (atf.gov); USDA: SNAP retailers (fns.usda.gov); Census: Retail (census.gov)",78,78,72,82,72,78,78,80),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCB ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCB batch)")
