import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCN01","Every Supreme Court Decision That Overruled a Previous One: The Constitutional Reversals Map","Timeline of overturned precedents mapped against public opinion at the time — the court vs the people","CHART","US","Line chart","law/history","Supreme Court: Decisions (supremecourt.gov); Gallup: Public opinion (gallup.com); SCOTUSblog: Overrulings (scotusblog.com)",78,72,75,80,78,68,78,78),
mk("HCN02","Middle East Internet Penetration: How Online Access Reshaped Regional Politics","Internet usage mapped against protest frequency and press freedom changes since 2010","XREF","Middle East","Line chart","middle_east/technology","ITU: Internet data (itu.int); Freedom House: FOTN (freedomhouse.org); ACLED: Protest (acleddata.com)",72,58,68,78,72,68,78,75),
mk("HCN03","The Demographics of Americas Homeless Population: Who They Actually Are","Age, race, veteran status, family structure of homeless population mapped by metro — not who you think","CHART","US-metro","Bar chart","demographics/poverty","HUD: AHAR (hudexchange.info); VA: Homeless veterans (va.gov); Census: Demographics (census.gov)",82,78,78,78,78,68,72,78),
mk("HCN04","Where Mandatory Minimum Sentences Create Maximum Injustice: The Federal Sentencing Map","Identical charges with wildly different sentences by federal district — the geographic lottery","MAP","US","Special map","law/race","USSC: Sentencing data (ussc.gov); BJS: Federal sentencing (bjs.gov); FAMM: Mandatory minimums (famm.org)",82,72,72,80,85,72,78,72),
mk("HCN05","Middle East Christian Communities: The Disappearing Populations Nobody Discusses","Christian population decline mapped by country since 1900 — from 20% to 5% of the region","MAP","Middle East","Line chart","middle_east/religion","Pew: Religious composition (pewresearch.org); CIA: World Factbook (cia.gov); Open Doors: Persecution (opendoorsusa.org)",75,60,72,82,72,70,80,72),
mk("HCN06","The Demographics of Americas Jury Pool vs Americas Prison Population","Who serves on juries vs who gets sentenced — the representation gap by federal district","CHART","US","Bar chart","demographics/law","Administrative Office: Jury data (uscourts.gov); BJS: Prisoners (bjs.gov); Census: Demographics (census.gov)",82,72,72,82,82,68,78,65),
mk("HCN07","Where Debtors Prisons Still Exist: States That Jail People for Not Paying Fines","Courts issuing arrest warrants for unpaid fines mapped against poverty rates","MAP","US-state","Bivariate choropleth","law/poverty","ACLU: Debtors prisons (aclu.org); DOJ: Ferguson report model; Census: Poverty (census.gov/acs); Fines and Fees Justice Center (finesandfeesjusticecenter.org)",85,78,72,82,85,72,78,65),
mk("HCN08","Middle East Nuclear Ambitions: Every Country With a Nuclear Program Mapped","Civilian and military nuclear programs in MENA mapped with timeline and status","MAP","Middle East","Special map","middle_east/science","IAEA: Country profiles (iaea.org); NTI: Threat assessment (nti.org); SIPRI: Nuclear forces (sipri.org)",72,55,72,78,78,78,72,78),
mk("HCN09","The Demographics of Gun Violence Victims: Who Dies and Where","Firearm death demographics by age, race, gender, and type mapped at state level","CHART","US-state","Bar chart","demographics/guns","CDC: WONDER (wonder.cdc.gov); GVA: Incident data (gunviolencearchive.org); Census: Demographics (census.gov)",82,75,78,72,82,68,65,85),
mk("HCN10","Where Environmental Laws Have No Teeth: EPA Enforcement Actions Per Violation by State","Enforcement-to-violation ratios mapped — some states inspect but never punish","MAP","US-state","State choropleth","law/environment","EPA: ECHO (echo.epa.gov); GAO: Enforcement reports (gao.gov); State environmental agencies",78,68,72,78,78,72,72,75),
mk("HCN11","Middle East Refugee-to-Citizen: Countries That Naturalized Refugees vs Those That Didnt","Palestinian, Syrian, Iraqi refugee naturalization mapped by host country policy","MAP","Middle East","Bar chart","middle_east/immigration","UNHCR: Refugee statistics (unhcr.org); UNRWA: Palestinian data (unrwa.org); World Bank: Migration (worldbank.org)",75,60,72,78,72,68,78,72),
mk("HCN12","The Demographics of Who Owns America: Landowner Demographics vs Population Demographics","95% of private land is owned by White Americans — the ownership gap mapped","MAP","US-state","Bivariate choropleth","demographics/housing","USDA: Land ownership (nass.usda.gov); Census: Demographics (census.gov); American Indian Land Tenure Foundation",82,72,72,82,82,78,78,68),
mk("HCN13","Every State Where You Can Be Fired for No Reason: The At-Will Employment Map","Employment at-will vs just-cause states mapped against worker complaint rates","MAP","US-state","State choropleth","law/labor","DOL: Employment law (dol.gov); NELP: Worker protections (nelp.org); EEOC: Charges (eeoc.gov)",78,82,78,72,78,72,68,80),
mk("HCN14","Middle East Cultural Exports: Music, Film, and Art That the World Doesnt Know About","Cultural output mapped by country — Irans cinema, Lebanons music, UAEs art scene","MAP","Middle East","Dot map","middle_east/entertainment","UNESCO: Cultural industries (uis.unesco.org); IMDB: Production data (imdb.com); Spotify: Streaming (spotify.com)",62,55,62,78,55,68,80,60),
mk("HCN15","The Demographics of Americas Caregivers: 53 Million Unpaid Workers","Caregiver demographics mapped by state — age, gender, income, hours of unpaid labor","MAP","US-state","State choropleth","demographics/labor","AARP: Caregiving survey (aarp.org); BLS: Unpaid work (bls.gov/tus); Census: Demographics (census.gov)",78,82,72,72,72,68,68,72),
mk("HCN16","Where Tenant Protection Laws Are Weakest: The Renter Rights Map","Eviction protections, rent control, habitability standards mapped by state","MAP","US-state","State choropleth","law/housing","NCSL: Tenant laws (ncsl.org); Princeton Eviction Lab (evictionlab.org); NLIHC: Renter data (nlihc.org)",78,82,75,72,78,72,68,75),
mk("HCN17","Middle East Trade Routes: Ancient Silk Road Paths vs Modern Commerce Corridors","Historical and modern trade routes overlaid — some paths are 3000 years old and still in use","MAP","Middle East","Line map","middle_east/trade","World Bank: Trade (worldbank.org); UN Comtrade (comtrade.un.org); Archaeological surveys",68,55,65,80,62,85,82,68),
mk("HCN18","The Demographics of Americas Teachers vs Americas Students: The Representation Crisis","Teacher race/gender demographics vs student demographics by state — the gap widening","CHART","US-state","Bar chart","demographics/education","NCES: Teacher demographics (nces.ed.gov); Census: School enrollment (census.gov); Brookings: Teacher diversity (brookings.edu)",78,75,75,75,75,68,68,80),
mk("HCN19","Where Solitary Confinement Is Torture by Another Name: Usage Rates by State Prison","Solitary usage mapped against mental health outcomes and international human rights standards","MAP","US-state","Bar chart","law/health","BJS: Special housing (bjs.gov); ASCA-Liman: Solitary report; Vera: Isolation data (vera.org); UN: Mandela Rules",82,68,72,80,85,68,78,68),
mk("HCN20","Middle East Gender Paradox: Countries Where Women Graduate College at Higher Rates Than Men","Female university completion rates mapped — several MENA countries exceed 60%","CHART","Middle East","Bar chart","middle_east/gender","UNESCO: Education (uis.unesco.org); World Bank: Gender (worldbank.org); QS: University data (qs.com)",68,58,72,85,58,68,80,78),
mk("HCN21","The Demographics of Americas Firefighters: Who Protects Your Community","Firefighter demographics mapped against community demographics — rural volunteer crisis visible","MAP","US-state","Bar chart","demographics/rural","NFPA: Firefighter demographics (nfpa.org); USFA: Data (usfa.fema.gov); Census: Demographics (census.gov)",68,72,68,68,62,68,68,72),
mk("HCN22","Where Wage Theft Exceeds All Other Property Crime Combined: The Stolen Wages Map","Wage theft dollar amounts by state mapped against robbery, burglary, and larceny combined","CHART","US-state","Bar chart","law/labor","DOL: WHD (dol.gov/whd); EPI: Wage theft (epi.org); FBI: UCR (ucr.fbi.gov)",82,80,75,85,82,68,78,72),
mk("HCN23","Middle East Diaspora Remittances: Money Flowing Home From Abroad","Remittance flows to MENA countries mapped by source — the invisible foreign aid","MAP","Middle East","Line map","middle_east/finance","World Bank: Remittances (worldbank.org); IMF: Balance of payments (imf.org); Central banks: Data",72,58,72,75,62,78,72,78),
mk("HCN24","The Demographics of Climate Vulnerability: Who Lives in Americas Flood and Fire Zones","Racial and income demographics of populations in FEMA high-risk zones","MAP","US-county","Bivariate choropleth","demographics/climate","FEMA: Risk (hazards.fema.gov); Census: Demographics (census.gov); Climate Central: Risk (climatecentral.org)",82,75,72,78,80,78,72,75),
mk("HCN25","Where Americas Patent System Favors the Rich: Innovation Geography and Access to IP Law","Patent filing rates mapped against inventor income and access to patent attorneys","MAP","US-metro","Scatter plot","law/technology","USPTO: Patent data (uspto.gov); ABA: IP lawyers (americanbar.org); Census: Income (census.gov)",72,65,68,78,68,68,80,72),
mk("HCN26","Middle East Archaeological Heritage at Risk: Ancient Sites in Conflict Zones","UNESCO heritage sites mapped against conflict intensity — civilization being erased","MAP","Middle East","Dot map","middle_east/history","UNESCO: Heritage (whc.unesco.org); ASOR: Cultural heritage (asor.org); ACLED: Conflict (acleddata.com)",78,58,68,80,78,82,80,72),
mk("HCN27","The Demographics of Americas Electorate vs Americas Population: Who Votes and Who Doesnt","Voting population demographics vs total population demographics by state — the participation gap","MAP","US-state","Bar chart","demographics/democracy","Census: CPS Voting (census.gov); MIT: Elections (electionlab.mit.edu); Pew: Voter demographics (pewresearch.org)",78,75,78,72,75,68,68,82),
mk("HCN28","Where Civil Asset Forfeiture Lets Police Take Your Property Without a Conviction","State forfeiture laws mapped against seizure amounts and conviction rates","MAP","US-state","Bivariate choropleth","law/finance","IJ: Forfeiture (ij.org); DOJ: Equitable sharing (justice.gov); State AG: Forfeiture reports",82,78,72,82,85,72,78,68),
mk("HCN29","Middle East Startup Scene: The Tech Hubs Nobody in Silicon Valley Knows About","Dubai, Tel Aviv, Cairo, Riyadh startup ecosystems mapped with funding and talent data","MAP","Middle East","Dot map","middle_east/technology","MAGNiTT: Startups (magnitt.com); Crunchbase: Funding (crunchbase.com); Startup Genome: Ecosystems (startupgenome.com)",65,55,68,78,55,72,78,68),
mk("HCN30","The Demographics of Americas Immigrants: Where They Come From and What They Do","Immigrant origin mapped against occupation, education, and income — the full picture","MAP","US-state","Bar chart","demographics/immigration","Census: ACS nativity (census.gov/acs); BLS: Foreign-born workers (bls.gov); DHS: Immigration (dhs.gov)",72,72,75,68,62,72,65,82),
mk("HCN31","Where the Right to Counsel Doesnt Exist: Public Defender Caseloads That Guarantee Injustice","Public defender caseloads by state mapped against case outcomes — 500+ cases per attorney","MAP","US-state","Bar chart","law/inequality","BJS: Indigent defense (bjs.gov); NLADA: Defender data (nlada.org); ABA: Standards (americanbar.org)",82,72,72,80,82,68,75,68),
mk("HCN32","Middle East Renewable Energy Potential: Solar Irradiance That Could Power the Entire World","Solar energy potential mapped — MENA receives enough sunlight to power global demand 100x over","MAP","Middle East","Special map","middle_east/energy","IRENA: Solar atlas (irena.org); World Bank: Solar (globalsolaratlas.info); IEA: Renewables (iea.org)",72,55,72,82,62,82,78,78),
mk("HCN33","The Demographics of Who Crosses the Border: The Data vs the Political Narrative","Actual demographics of border crossers mapped — age, family status, country of origin","CHART","US","Bar chart","demographics/immigration","CBP: Encounter data (cbp.gov); Census: Foreign-born (census.gov); Migration Policy Institute (migrationpolicy.org)",78,72,78,80,78,68,72,78),
mk("HCN34","Where Every Dollar of Court Fines and Fees Goes: The Revenue Map of Justice","Municipal court revenue mapped against local budgets — some cities fund 30%+ of operations from fines","MAP","US-metro","Dot map","law/finance","DOJ: Ferguson model; Census: Government finance (census.gov/govs); Fines and Fees Justice Center (finesandfeesjusticecenter.org)",80,75,72,80,80,72,78,68),
mk("HCN35","Middle East in 2050: Population, Water, Energy, and Climate Projections on One Map","Composite future-state map of MENA — the convergence of every crisis","MAP","Middle East","Special map","middle_east/climate","UN Population (population.un.org); World Bank: Climate (worldbank.org); FAO: Water (fao.org); IEA: Energy (iea.org)",78,58,68,80,78,82,80,68),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCN ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCN batch)")
