import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDL01","Local News Deserts: Counties With No Newspaper or Local TV Station","The 1,800+ US counties that have lost all local news coverage — mapped against voter turnout and municipal corruption rates","MAP","US","County choropleth","media","Northwestern: Medill Local News Initiative (localnewsinitiative.northwestern.edu)",75,72,72,72,78,78,68,85),
mk("HDL02","Government Data Quality: How Complete and Accurate Federal Datasets Are by Agency","Audit scores for data quality across federal agencies — which departments publish reliable data and which are flying blind","RANK","US","Bar chart","data","OMB: Federal Data Strategy Progress Reports (strategy.data.gov)",55,48,72,72,65,55,72,72),
mk("HDL03","The Real Price of a Big Mac: Purchasing Power Parity Illustrated Through Burgers","Big Mac Index updated — what a burger costs in local currency vs USD reveals which currencies are over or undervalued","MAP","World","World choropleth","prices","The Economist: Big Mac Index (economist.com/big-mac-index)",55,78,78,68,48,68,58,88),
mk("HDL04","Military Recruitment Crisis: Branches Missing Enlistment Targets by Year","Which military branches are falling short of recruiting goals — the Army missing by 25% while the Marines still fill their ranks","CHART","US","Bar chart","military","DOD: Military Recruitment Data (defense.gov/Spotlights/Recruiting)",65,62,72,68,72,58,62,82),
mk("HDL05","Newspaper Circulation Collapse: Daily Print Circulation Since 1950 by Market Size","The death curve of print journalism — from 60M daily papers in 1960 to under 20M today, accelerating since 2005","CHART","US","Line chart","media","Pew Research: State of the News Media (pewresearch.org/journalism)",68,65,75,62,68,62,58,88),
mk("HDL06","Open Data Index: Countries Ranked by Government Data Transparency","Which governments publish the most usable open data — completeness, timeliness, and machine readability scored by country","RANK","World","Horizontal bar chart","data","Open Knowledge Foundation: Global Open Data Index (index.okfn.org/place)",52,45,72,65,55,58,65,82),
mk("HDL07","Insulin Price Timeline: Cost Per Vial in the US vs Canada, UK, and Germany Since 2000","The divergence of insulin pricing — US prices rose 1000% while the same product stayed flat everywhere else","CHART","World","Line chart","prices","RAND: Insulin Price Comparison (rand.org)",82,78,75,72,80,62,58,85),
mk("HDL08","US Military Bases Worldwide: Every Installation by Country and Branch","The 750+ US military installations across 80 countries — the physical footprint of American global power projection","MAP","World","Dot map","military","DOD: Base Structure Report (acq.osd.mil/eie/bsr.html)",62,52,72,68,65,85,62,88),
mk("HDL09","Misinformation Superspreaders: Accounts Responsible for Most Shared False Claims","The concentration of viral misinformation — a tiny number of accounts generate the majority of false claim engagement","CHART","US","Bar chart","media","MIT Media Lab: Spread of True and False News Online (science.sciencemag.org)",68,68,68,78,75,58,72,70),
mk("HDL10","Census Response Rates: Who Fills Out the Census and Who Doesnt by Tract","Self-response rates for the 2020 Census mapped at the tract level — the geography of civic participation and statistical invisibility","MAP","US","County choropleth","data","Census Bureau: 2020 Census Response Rates (2020census.gov/en/response-rates)",55,62,72,65,58,78,60,92),
mk("HDL11","Shrinkflation Tracker: Products That Got Smaller While Prices Stayed the Same","Documented cases of shrinkflation by product category — toilet paper, chips, cereal, candy bars — the hidden price increase","CHART","US","Bar chart","prices","Bureau of Labor Statistics: CPI Quantity Adjustments (bls.gov/cpi)",62,85,72,72,65,55,68,70),
mk("HDL12","Veteran Suicide Rate: Former Service Members Who Die by Suicide Per Day by State","The 17-per-day veteran suicide crisis mapped by state and military branch — the invisible cost of Americas wars","MAP","US","State choropleth","military","VA: National Veteran Suicide Prevention Annual Report (mentalhealth.va.gov/suicide_prevention)",85,68,72,65,85,72,58,85),
mk("HDL13","Social Media News Sources: Where Americans Get Their News by Platform and Age","The complete disaggregation of news consumption — TikTok for Gen Z, Facebook for Boomers, X for political junkies","CHART","US","Stacked bar chart","media","Pew Research: Social Media and News (pewresearch.org/journalism/fact-sheet/social-media-and-news)",58,78,72,65,58,62,55,82),
mk("HDL14","FOIA Backlog: Freedom of Information Request Processing Times by Agency","How long federal agencies take to respond to FOIA requests — some with 5+ year backlogs of unfulfilled requests","RANK","US","Bar chart","data","FOIA.gov: Annual FOIA Reports (foia.gov)",62,55,72,72,68,55,68,85),
mk("HDL15","EpiPen vs the World: US Price for Emergency Allergy Medication Compared Globally","A two-pack costs $650 in the US vs $40 in Australia — the most extreme pharmaceutical price divergence story","CHART","World","Bar chart","prices","GAO: Drug Pricing Reports (gao.gov)",78,78,72,75,78,55,60,82),
mk("HDL16","Military Spouse Unemployment: The Career Penalty of Frequent Relocation","Military spouse unemployment rate at 22% vs 3.5% national average — the hidden cost of service mapped by installation","MAP","US","Dot map","military","DOD: Military Family Readiness (militaryonesource.mil)",72,68,68,72,68,68,68,78),
mk("HDL17","Journalist Safety Index: Countries Where Reporters Are Most Likely to Be Killed","Murder, imprisonment, and disappearance of journalists by country — Mexico, the Philippines, and Afghanistan as the deadliest","MAP","World","World choropleth","media","Reporters Without Borders: World Press Freedom Index (rsf.org/en/ranking)",78,55,72,62,82,72,62,88),
mk("HDL18","The Surveillance Footprint: Government Requests for User Data by Tech Company","How many user data requests Google, Apple, Meta, and Microsoft receive from governments worldwide — the compliance rate varies wildly","CHART","World","Bar chart","data","Google: Transparency Report (transparencyreport.google.com/user-data/overview)",65,68,68,72,75,58,70,85),
mk("HDL19","Concert Ticket Price Explosion: Average Face Value vs Resale Price by Era","How concert tickets went from $30 in 2000 to $250+ in 2024 — the Live Nation/Ticketmaster monopoly effect","CHART","US","Line chart","prices","Pollstar: Year-End Touring Statistics (pollstar.com)",62,82,72,68,68,55,58,78),
mk("HDL20","PTSD Rates by Conflict: Post-Traumatic Stress Among Veterans by War Era","PTSD prevalence among veterans of Vietnam, Gulf War, Iraq, and Afghanistan — the changing understanding and diagnosis of combat trauma","CHART","US","Bar chart","military","VA: PTSD National Center (ptsd.va.gov)",78,65,72,65,75,58,60,82),
mk("HDL21","AI-Generated Content Flood: Estimated Percentage of Web Content Produced by AI by Category","How much of the internet is now AI-generated — estimates by content type from product reviews to news articles to social media","CHART","World","Bar chart","media","NewsGuard: AI-Generated News Tracking (newsguardtech.com)",62,68,65,78,72,55,75,60),
mk("HDL22","Data Breach Severity: Records Exposed Per Incident by Industry and Year","The escalation of data breaches — from millions of records in 2010 to billions per year, with healthcare and finance hit hardest","CHART","World","Area chart","data","Have I Been Pwned: Breach Database (haveibeenpwned.com) + Identity Theft Resource Center (idtheftcenter.org)",68,72,68,68,72,62,62,82),
mk("HDL23","The Wedding Industrial Complex: Average Cost of a Wedding by State","From $15K in Utah to $60K+ in New Jersey — how much Americans spend on weddings mapped against median household income","MAP","US","State choropleth","prices","The Knot: Real Weddings Study (theknot.com/content/average-wedding-cost)",55,78,72,65,52,68,58,78),
mk("HDL24","Overseas Contingency Operations: Where US Troops Are Currently Deployed","Active US military deployments worldwide — from major bases in Germany and Japan to smaller presences across Africa and the Middle East","MAP","World","Dot map","military","DMDC: Defense Manpower Data Center (dmdc.osd.mil)",58,52,72,62,65,82,58,88),
mk("HDL25","Deepfake Detection: Volume of AI-Manipulated Media Detected Online by Category","Growth of deepfake content online — from political manipulation to non-consensual pornography — detection rates by platform","CHART","World","Line chart","media","Sensity AI: Deepfake Landscape Report (sensity.ai)",65,62,62,78,78,58,75,65),
mk("HDL26","Weather Station Coverage: Gaps in Climate Monitoring Infrastructure by Region","Where weather and climate monitoring stations are sparse or absent — the blind spots in our understanding of global weather","MAP","World","Dot map","data","WMO: Observing Systems Capability Analysis (oscar.wmo.int)",55,45,68,72,62,78,72,78),
mk("HDL27","Childcare Cost vs College Tuition: Annual Daycare Costs by State Compared to In-State Tuition","In most states daycare now costs more than public university tuition — the comparison that shocks every new parent","XREF","US","Bar chart","prices","DOL: National Database of Childcare Prices (dol.gov/agencies/wb/topics/childcare/price-database)",78,85,75,72,72,58,62,85),
mk("HDL28","Private Military Contractors: Estimated Personnel Employed by US Military Contractors Abroad","The shadow military — estimated contractor headcount in Iraq, Afghanistan, Syria, and Africa often exceeding uniformed troop levels","CHART","World","Bar chart","military","CRS: Department of Defense Contractor and Troop Levels (fas.org/sgp/crs)",65,52,68,75,72,62,72,72),
mk("HDL29","Paywall Proliferation: Percentage of Top News Sites Behind Paywalls by Year","The shrinking pool of free quality journalism — from mostly free in 2010 to 80%+ paywalled by 2025","CHART","US","Line chart","media","Reuters Institute: Digital News Report (reutersinstitute.politics.ox.ac.uk)",62,75,72,68,65,58,62,75),
mk("HDL30","The Algorithmic Feed: How Much of Social Media Content Is Recommended vs Followed","Percentage of Instagram, TikTok, X, and YouTube content that comes from accounts you dont follow — the algorithm taking over","CHART","World","Bar chart","data","Meta/TikTok: Transparency Reports + Pew Research (pewresearch.org/internet)",58,72,68,72,62,55,68,70),
mk("HDL31","Generic Drug Price Spikes: Off-Patent Medications With Sudden Price Increases","Drugs that should be cheap but arent — sudden 500%+ price spikes on generic medications with limited competition","CHART","US","Line chart","prices","AARP: Rx Price Watch (aarp.org/rxpricewatch)",75,78,72,78,78,58,65,78),
mk("HDL32","Military Equipment Surplus: What the Pentagon Sends to Local Police Departments","The 1033 Program — military-grade equipment transferred to local police by department, from MRAPs to grenade launchers","MAP","US","Dot map","military","DLA: 1033 Program LESO Property Transfer (dla.mil/DispositionServices/Offers/Reutilization/LawEnforcement/PublicInformation)",68,65,68,78,75,75,70,85),
mk("HDL33","Trust in Media: Confidence in News Organizations by Country and Political Orientation","The partisan trust gap — Democrats and Republicans now live in completely different media realities, compared globally","CHART","World","Bar chart","media","Reuters Institute: Digital News Report Trust Data (reutersinstitute.politics.ox.ac.uk)",68,72,72,68,72,58,62,82),
mk("HDL34","Public Records Fees: What States Charge Citizens to Access Government Documents","Some states provide records free while others charge per-page fees that make transparency unaffordable — the access gap mapped","MAP","US","State choropleth","data","MuckRock: State FOIA Fee Comparison (muckrock.com)",58,62,72,72,68,68,68,78),
mk("HDL35","College Textbook Price Inflation: Textbook Costs vs CPI Since 1980","Textbook prices rose 1,000% since 1980 — 3x faster than general inflation and 4x faster than medical care costs","CHART","US","Line chart","prices","BLS: CPI for College Textbooks (bls.gov/cpi) + GAO Textbook Report (gao.gov)",68,78,75,72,68,55,58,88),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDL batch)")
