import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDR01","Antibiotic Prescription Rates: Unnecessary Antibiotic Use by State and Condition","States where doctors prescribe antibiotics for viral infections at 3x the rate of others — fueling resistance one Z-pack at a time","MAP","US","State choropleth","health","CDC: Antibiotic Use in the United States (cdc.gov/antibiotic-use)",68,72,72,72,68,68,62,85),
mk("HDR02","The Slave Trade Mapped: Every Known Transatlantic Voyage With Origin and Destination","12.5 million people shipped across the Atlantic — every documented slave voyage plotted from African port to American destination","MAP","World","Line map","history","SlaveVoyages: Trans-Atlantic Slave Trade Database (slavevoyages.org)",85,62,68,68,82,85,65,90),
mk("HDR03","PFAS Contamination Map: Forever Chemicals Detected in US Drinking Water by System","Where PFAS chemicals have been found in public water supplies — the scope of contamination covering 100+ million Americans","MAP","US","Dot map","science","EPA: PFAS Monitoring Data (epa.gov/pfas) + EWG PFAS Map (ewg.org/interactive-maps/pfas_contamination)",78,78,72,72,82,78,62,82),
mk("HDR04","The Interstate Highway System: Miles Built Per Year During the Eisenhower-Era Construction Boom","The building of Americas 48,000 mile highway system animated year by year — the most expensive public works project in history","CHART","US","Line chart","transportation","FHWA: Highway History (fhwa.dot.gov/infrastructure/history)",55,62,78,62,48,72,58,90),
mk("HDR05","Long COVID Prevalence: Adults Still Experiencing Symptoms 12+ Months After Infection","The lingering pandemic — percentage of adults reporting long COVID symptoms by state, mapped against vaccination rates","MAP","US","Bivariate choropleth","health","CDC: Household Pulse Survey Long COVID (census.gov/data/experimental-data-products/household-pulse-survey)",72,78,68,68,72,72,58,78),
mk("HDR06","Colonial Boundaries vs Modern Borders: How European Map-Drawing Created Todays Conflicts","Overlay of colonial-era boundaries drawn by European powers with current national borders and active conflict zones","MAP","World","Special map","history","Michalopoulos & Papaioannou: The Long-Run Effects of the Scramble for Africa (nber.org)",72,55,65,72,78,85,78,80),
mk("HDR07","Microplastics in Human Blood: Detected Concentrations by Study Location and Year","The accumulating evidence of microplastics in human tissue — blood, lungs, placenta, brain — mapped by study and concentration","CHART","World","Scatter plot","science","Environment International: Microplastics in Human Blood Studies (sciencedirect.com)",72,72,62,82,78,58,78,68),
mk("HDR08","Train Derailment Frequency: Railroad Accidents by Type and Carrier Per Year","How often trains derail in America — the data behind East Palestine, broken down by carrier, cargo type, and cause","MAP","US","Dot map","transportation","FRA: Railroad Accident/Incident Reporting (railroads.dot.gov/data-research)",68,68,72,68,75,78,62,85),
mk("HDR09","Maternal Healthcare Deserts: Counties With No OB-GYN or Birthing Hospital","Where women have zero access to maternity care — 36% of US counties lack a hospital with obstetric services","MAP","US","County choropleth","health","March of Dimes: Maternity Care Deserts Report (marchofdimes.org)",82,72,72,68,80,78,58,85),
mk("HDR10","Pandemics Ranked: Every Major Epidemic Since 1900 by Death Toll and Duration","From the 1918 flu to COVID-19 — death toll, geographic spread, and response time compared across 12 major outbreaks","RANK","World","Bar chart","history","Our World in Data: Pandemics (ourworldindata.org/pandemics)",72,65,75,68,72,62,65,88),
mk("HDR11","Light Speed Communication Lag: How Long a Message Takes to Reach Every Planet","The tyranny of the speed of light — from 1.3 seconds to the Moon to 20+ hours to Voyager, visualized as a timeline","CHART","World","Bar chart","science","NASA: Deep Space Network (eyes.nasa.gov/dsn/dsn.html)",48,52,78,72,42,72,72,90),
mk("HDR12","Pothole Damage Claims: Vehicle Repair Costs From Road Damage by State","How much potholes cost American drivers — an estimated $3B annually in vehicle repairs, concentrated in freeze-thaw states","MAP","US","State choropleth","transportation","AAA: Pothole Damage Survey (newsroom.aaa.com)",58,82,72,65,58,68,55,78),
mk("HDR13","Healthcare Cost Variation: Price for the Same Procedure at Hospitals in the Same City","An MRI costs $400 at one hospital and $4,000 at another across town — the incomprehensible pricing variation mapped","MAP","US","Dot map","health","CMS: Hospital Price Transparency Data (cms.gov/hospital-price-transparency)",78,82,72,78,78,68,68,78),
mk("HDR14","Nuclear Close Calls: Every Known Incident Where Nuclear War Was Nearly Triggered","From Able Archer to Petrov to the 1995 Norwegian rocket incident — the terrifyingly thin margin mapped by event and year","CHART","World","Scatter plot","history","Chatham House: Too Close for Comfort (chathamhouse.org)",78,62,68,82,88,65,78,72),
mk("HDR15","Ocean Plastic Accumulation: The Five Major Garbage Patches Mapped by Density","Plastic concentration in the five oceanic gyres — the Great Pacific Garbage Patch is just the most famous of five","MAP","World","Special map","science","Ocean Cleanup: Plastic Tracker (theoceancleanup.com)",72,62,68,68,72,82,62,78),
mk("HDR16","E-Bike and E-Scooter Injuries: Emergency Room Visits From Micromobility by City","The injury toll of the micromobility revolution — ER visits from e-bikes and e-scooters rising 70%+ per year in major cities","MAP","US","Dot map","transportation","CPSC: Micromobility Injury Data (cpsc.gov) + NEISS",62,72,68,68,65,68,62,75),
mk("HDR17","Measles Resurgence: Outbreaks in Previously Eliminated Countries Since 2018","The return of measles to countries that had eliminated it — mapped against vaccination rate decline hotspots","MAP","World","Dot map","health","WHO: Measles and Rubella Surveillance (who.int/immunization/monitoring_surveillance)",78,68,72,72,78,72,58,82),
mk("HDR18","Empires at Maximum Extent: The Largest Land Empires in History Compared","Mongol, British, Russian, Spanish, Qing, and Umayyad empires overlaid at their maximum territorial extent — who ruled the most?","MAP","World","Special map","history","Various: Historical Atlas Data (geacron.com + worldhistory.org)",58,58,72,65,52,88,68,85),
mk("HDR19","Antibiotic Resistance Map: Drug-Resistant Infections by Pathogen and Country","Where superbugs are winning — countries with the highest rates of antibiotic-resistant infections by organism type","MAP","World","World choropleth","science","WHO: Global Antimicrobial Resistance Surveillance (who.int/glass/data)",72,58,68,72,80,72,68,78),
mk("HDR20","Cargo Theft Corridors: Freight Stolen In Transit by Route and Product Type","Where trucks get robbed — cargo theft hotspots concentrated along I-10, I-95, and I-80, with electronics and food the top targets","MAP","US","Line map","transportation","CargoNet: Theft Intelligence (cargonet.com) + FBI Cargo Theft Reports",58,55,68,72,68,78,68,72),
mk("HDR21","Dentist Desert: Counties Where There Are Fewer Than 1 Dentist Per 5000 People","The oral health access map — communities where children go years without seeing a dentist because there isnt one nearby","MAP","US","County choropleth","health","HRSA: Health Professional Shortage Areas (data.hrsa.gov/tools/shortage-area)",72,72,72,65,68,78,58,85),
mk("HDR22","Lost Civilizations Rediscovered: Major Archaeological Sites Found Using Lidar Since 2010","How laser scanning from aircraft revealed hidden cities — Angkor, Maya megacities, Amazonian settlements invisible to the naked eye","MAP","World","Dot map","history","National Geographic: Lidar Archaeology (nationalgeographic.com)",62,55,68,82,52,85,82,72),
mk("HDR23","Soil Carbon Potential: How Much CO2 Farmland Could Sequester With Better Practices","The untapped carbon sink under our feet — estimated sequestration potential by agricultural region if regenerative practices were adopted","MAP","US","County choropleth","science","Soil Health Institute: Soil Carbon Data (soilhealthinstitute.org)",58,48,68,72,58,72,72,72),
mk("HDR24","Pedestrian Death Crisis: Pedestrians Killed by Cars Per 100K by Metro Area","The SUV-driven pedestrian fatality spike — deaths up 75% since 2009, concentrated in Sunbelt metros designed without sidewalks","MAP","US","Dot map","transportation","GHSA: Pedestrian Traffic Fatalities (ghsa.org/resources/Pedestrians)",78,75,72,68,78,72,62,85),
mk("HDR25","Physician Burnout Rate: Percentage of Doctors Reporting Burnout by Specialty","Which medical specialties are burning out fastest — emergency medicine and critical care at 60%+, with rural doctors even higher","RANK","US","Bar chart","health","Medscape: National Physician Burnout Survey (medscape.com)",72,65,72,65,72,55,58,78),
mk("HDR26","The Columbian Exchange: Plants, Animals, and Diseases That Crossed the Atlantic After 1492","What moved between Old World and New World — from potatoes and tomatoes east to smallpox and horses west, with population impact","MAP","World","Line map","history","Nunn & Qian: The Columbian Exchange (Journal of Economic Perspectives)",62,62,72,72,58,78,72,82),
mk("HDR27","Earthquake Early Warning Coverage: Where You Get Seconds of Warning Before Shaking","ShakeAlert and global earthquake early warning systems — which populations are covered and how many seconds of notice they receive","MAP","World","Dot map","science","USGS: ShakeAlert (shakealert.org) + JMA (jma.go.jp)",62,62,72,72,68,78,68,78),
mk("HDR28","Wrong-Way Driver Incidents: Fatal Crashes From Drivers Going the Wrong Direction by State","The geography of wrong-way crashes — disproportionately late-night, alcohol-involved, and concentrated on certain highway designs","MAP","US","State choropleth","transportation","NHTSA: FARS Wrong-Way Driving Data (nhtsa.gov/research-data/fatality-analysis-reporting-system)",62,65,68,72,72,68,65,80),
mk("HDR29","STI Surge Map: Syphilis, Gonorrhea, and Chlamydia Rates Hitting All-Time Highs by State","The alarming STI resurgence — congenital syphilis up 900% since 2012, with geographic hotspots in the South and Southwest","MAP","US","State choropleth","health","CDC: STD Surveillance Reports (cdc.gov/std/statistics)",72,68,72,72,78,72,55,88),
mk("HDR30","Sunken History: The Most Significant Shipwrecks by Century and Ocean","Major shipwrecks mapped across the worlds oceans — from Spanish galleons to Titanic to modern container ships","MAP","World","Dot map","history","NOAA: Automated Wreck and Obstruction Information System (nauticalcharts.noaa.gov/data/wrecks-and-obstructions)",55,58,68,68,52,82,72,82),
mk("HDR31","Volcanic Winter Risk: Supervolcanoes and Their Projected Climate Impact if They Erupted","The handful of supervolcanoes capable of triggering global cooling — Yellowstone, Campi Flegrei, Toba — with eruption probability estimates","MAP","World","Dot map","science","Global Volcanism Program: Smithsonian (volcano.si.edu)",68,55,65,82,78,80,75,72),
mk("HDR32","Grade Crossing Deaths: Fatalities at Railroad Crossings by State and Crossing Type","Where train-vehicle collisions kill people — the most dangerous railroad crossings and which states fail to upgrade them","MAP","US","Dot map","transportation","FRA: Highway-Rail Crossing Accident Data (railroads.dot.gov)",68,62,72,65,72,78,58,88),
mk("HDR33","Air Quality Inequality: PM2.5 Exposure Disparity by Race Within the Same Metro","Communities of color breathe 56% more PM2.5 pollution than the overall population in the same metro — the intra-city air quality gap","MAP","US","Bivariate choropleth","health","EPA: Environmental Justice Screening Tool (ejscreen.epa.gov)",78,68,72,72,78,72,65,82),
mk("HDR34","The Age of Exploration Routes: Every Major Voyage of Discovery From 1400-1600","Columbus, Magellan, da Gama, Zheng He, and dozens more — their actual sailing routes mapped against wind patterns and currents","MAP","World","Line map","history","Various: Historical Maritime Routes (geacron.com + worldhistory.org)",55,55,72,62,48,85,68,85),
mk("HDR35","Fungal Threat Emergence: Drug-Resistant Fungal Infections Spreading in the US","Candida auris and other resistant fungi spreading across US healthcare facilities — the next pandemic threat nobody is watching","MAP","US","Dot map","science","CDC: Fungal Diseases Data (cdc.gov/fungal/candida-auris)",72,58,65,80,78,68,78,72),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDR batch)")
