# BATCH_BH.py
ideas = [
  {'id': 'us_manufacturing_job_loss_decade', 'title': 'US manufacturing jobs by decade 1950-2023: the arc of the American working class', 'sub': '19M manufacturing jobs at peak (1979). 12.9M today. Not just automation — the trade deals, the offshoring, the geography of who got left behind.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Area chart', 'tbl': 'BLS CES: Manufacturing employment by year 1939-2023 (bls.gov)', 'section': 'Labor Force', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['manufacturing_employment'], 'join': ['manufacturing_wage_index', 'opioid_death_rate_national', 'trade_deficit_goods'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 70, 'tension': 90, 'visual': 90, 'data_ready': 100, 'originality': 60}, 'vs': 84, 'tags': 'manufacturing jobs decade 1950 2023 arc American working class 19M peak 1979 12.9M today automation trade', 'notes': '', 'topics': ['labor', 'economy', 'history', 'trade', 'poverty', 'inequality'], 'status': 'idea'},
  {'id': 'us_union_membership_collapse', 'title': 'Union membership rate: 35% in 1954, 10% today — the 70-year wage war', 'sub': 'At peak, 1 in 3 American workers was in a union. Today: 1 in 10. The correlation with wage stagnation for the bottom 50% is not coincidental.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Area chart', 'tbl': 'BLS Union Members Summary: Union membership rate by year (bls.gov)', 'section': 'Labor Force', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['union_membership_rate', 'union_member_count'], 'join': ['median_wage_growth', 'income_share_top10', 'corporate_profits'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 70, 'tension': 90, 'visual': 90, 'data_ready': 100, 'originality': 70}, 'vs': 84, 'tags': 'union membership 35 percent 1954 10 percent today 70 year wage war bottom 50 stagnation correlation', 'notes': '', 'topics': ['labor', 'economy', 'history', 'inequality', 'politics'], 'status': 'idea'},
  {'id': 'us_homeownership_rate_arc', 'title': 'US homeownership rate 1940-2023: the rise, the crash, and the millennial lockout', 'sub': '1940: 44%. 1960: 62%. 2004 peak: 69.2%. 2016 trough: 62.9%. 2023: 65.9%. The American Dream in one 80-year line.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Line chart', 'tbl': 'Census Housing Vacancies and Homeownership Survey: Homeownership rate by year (census.gov)', 'section': 'Housing', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['homeownership_rate_national'], 'join': ['median_home_price', 'mortgage_rate', 'median_household_income', 'avg_new_car_price'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 90, 'surprise': 70, 'tension': 80, 'visual': 90, 'data_ready': 100, 'originality': 60}, 'vs': 83, 'tags': 'homeownership rate 1940 2023 rise crash millennial lockout 69 peak 2004 2016 trough American Dream 80 years', 'notes': '', 'topics': ['housing', 'history', 'economy', 'inequality', 'labor'], 'status': 'idea'},
  {'id': 'federal_minimum_wage_real', 'title': 'Federal minimum wage in real dollars 1968-2024: peak was 1968, everything since is a decline', 'sub': "$1.60 in 1968 = $14.20 in 2024 dollars. Today's $7.25 = $4.08 in 1968 dollars. The inflation-adjusted story the headline number hides.", 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Line chart', 'tbl': 'BLS + FRED: Federal minimum wage + CPI deflator 1938-2024 (dol.gov + fred.stlouisfed.org)', 'section': 'Labor Force', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['federal_minimum_wage_nominal', 'federal_minimum_wage_real_2024'], 'join': ['corporate_profits', 'labor_productivity_index', 'income_share_top10'], 'sc': {'emotional': 90, 'relatability': 90, 'clarity': 90, 'surprise': 90, 'tension': 90, 'visual': 90, 'data_ready': 100, 'originality': 70}, 'vs': 89, 'tags': 'minimum wage real dollars 1968 2024 peak decline 1.60 equals 14.20 today 7.25 equals 4.08 inflation hidden story', 'notes': '', 'topics': ['labor', 'economy', 'history', 'inequality', 'politics', 'poverty'], 'status': 'idea'},
  {'id': 'us_prison_population_arc', 'title': 'US prison population 1925-2023: the most dramatic expansion of incarceration in the history of any democracy', 'sub': '1925: 100K prisoners. 1975: 250K. 2008 peak: 2.3 million. 2023: 1.9 million. The arc of mass incarceration.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Area chart', 'tbl': 'BJS National Prisoner Statistics: US prison and jail population 1925-2023 (bjs.ojp.gov)', 'section': 'Law Enforcement', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['prison_population_total', 'prison_population_rate'], 'join': ['violent_crime_rate', 'poverty_rate_national', 'drug_arrest_rate', 'race_incarceration_disparity'], 'sc': {'emotional': 90, 'relatability': 70, 'clarity': 90, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 90, 'originality': 70}, 'vs': 83, 'tags': 'US prison population 1925 2023 2.3 million peak 2008 mass incarceration dramatic expansion democracy history', 'notes': '', 'topics': ['crime', 'race', 'history', 'inequality', 'politics', 'poverty'], 'status': 'idea'},
  {'id': 'us_health_spending_outcomes_arc', 'title': 'US health spending vs. life expectancy 1980-2023: spending tripled, outcomes plateaued', 'sub': 'Per capita health spending: $1,100 (1980) to $13,500 (2023). Life expectancy: 73.7 to 77.5 years. A 12x spending increase bought 4 years.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Dual axis line chart', 'tbl': 'OECD Health Data + CMS: National Health Expenditure Accounts + CDC: Life expectancy (cms.gov + cdc.gov)', 'section': 'Health', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['per_capita_health_spending', 'life_expectancy_national'], 'join': ['health_insurance_cpi', 'hospital_services_cpi', 'uninsured_rate'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 90, 'tension': 80, 'visual': 90, 'data_ready': 90, 'originality': 80}, 'vs': 86, 'tags': 'health spending life expectancy 1980 2023 tripled plateaued 1100 to 13500 73 to 77 12x increase bought 4 years', 'notes': '', 'topics': ['health', 'economy', 'history', 'inequality', 'politics'], 'status': 'idea'},
  {'id': 'us_college_tuition_arc', 'title': 'College tuition 1971-2024 vs. inflation, wages, and home prices — everything else is cheaper', 'sub': 'Tuition: up 1,400% since 1971. Home prices: up 750%. Wages: up 440%. CPI: up 744%. The only thing in America that got more expensive than a house.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Multi-line chart', 'tbl': 'NCES: Average tuition and fees 1971-2024 + BLS CPI + FHFA: Home price index (nces.ed.gov + bls.gov + fhfa.gov)', 'section': 'Education', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['avg_tuition_fees_national', 'college_tuition_cpi', 'all_items_cpi', 'home_price_index_national', 'median_wage_national'], 'join': ['student_loans_outstanding', 'pct_bachelors'], 'sc': {'emotional': 90, 'relatability': 90, 'clarity': 90, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 90, 'originality': 70}, 'vs': 87, 'tags': 'college tuition 1971 2024 1400 percent inflation wages home prices more expensive than house 1971 compared', 'notes': '', 'topics': ['education', 'economy', 'history', 'inequality', 'housing', 'labor'], 'status': 'idea'},
  {'id': 'us_corporate_tax_rate_arc', 'title': 'US corporate tax rate 1909-2024: from 0% to 52% and back to 21%', 'sub': 'The federal corporate tax rate peaked at 52.8% in 1969. After the 2017 Tax Cuts and Jobs Act: 21%. The full history of who pays.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Area chart', 'tbl': 'Tax Foundation: Historical US corporate tax rates 1909-2024 (taxfoundation.org)', 'section': 'Business Enterprise', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['corporate_tax_rate_statutory', 'effective_corporate_tax_rate'], 'join': ['corporate_profits', 'income_share_top10', 'gdp_growth_rate'], 'sc': {'emotional': 80, 'relatability': 70, 'clarity': 90, 'surprise': 80, 'tension': 80, 'visual': 80, 'data_ready': 90, 'originality': 70}, 'vs': 80, 'tags': 'corporate tax rate 1909 2024 0 to 52 back to 21 percent history who pays 2017 Tax Cuts Jobs Act peak 1969', 'notes': '', 'topics': ['economy', 'history', 'inequality', 'politics', 'finance', 'labor'], 'status': 'idea'},
  {'id': 'us_poverty_rate_arc', 'title': 'US official poverty rate 1959-2023: nearly 65 years of progress that stopped', 'sub': '1959: 22.4% in poverty. 1973: 11.1% — the all-time low. 2023: 11.1% — still the same. 50 years of the War on Poverty produced exactly nothing after 1973.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Area chart', 'tbl': 'Census Bureau: Historical poverty rates 1959-2023 (census.gov/topics/income-poverty)', 'section': 'Income Expenditures', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['poverty_rate_national', 'poverty_rate_child', 'poverty_rate_elderly'], 'join': ['pct_on_snap', 'median_household_income', 'gini_coefficient'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 90, 'tension': 90, 'visual': 90, 'data_ready': 100, 'originality': 80}, 'vs': 88, 'tags': 'poverty rate 1959 2023 65 years 22 to 11 stopped 1973 all-time low same 50 years War on Poverty nothing after', 'notes': '', 'topics': ['poverty', 'history', 'economy', 'politics', 'inequality', 'race'], 'status': 'idea'},
  {'id': 'healthcare_us_vs_world_spending_outcomes', 'title': 'US healthcare spending vs. peer nations: 2x the cost, lower outcomes', 'sub': 'US spends $13,500 per capita. Germany: $7,500. France: $6,700. Japan: $5,100. US life expectancy: 77.5. Germany: 81.7. The most expensive failure in modern government.', 'type': 'CHART', 'geo': 'worldwide', 'fmt': 'Scatter plot', 'tbl': 'OECD Health Statistics: Per capita health spending + life expectancy by country (stats.oecd.org)', 'section': 'Health  -  International Statistics', 'ext': ['World Bank Open Data: GDP, population, income by country (data.worldbank.org  free API)'], 'vars': ['per_capita_health_spending', 'life_expectancy'], 'join': ['gdp_per_capita', 'uninsured_rate', 'hospital_beds_per_1000'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 90, 'originality': 60}, 'vs': 85, 'tags': 'US healthcare spending vs world 2x cost lower outcomes Germany France Japan peer nations expensive failure government', 'notes': '', 'topics': ['health', 'economy', 'international', 'history', 'inequality', 'politics'], 'status': 'idea'},
  {'id': 'us_gdp_growth_vs_wage_growth', 'title': 'US GDP per capita vs. median wage 1979-2023: the great uncoupling', 'sub': "GDP per capita: up 115% since 1979. Median wage: up 13%. Productivity: up 64%. The economy grew. The workers didn't.", 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Dual axis line chart', 'tbl': 'BEA: GDP per capita + BLS: Median weekly earnings + BLS: Productivity index (bea.gov + bls.gov)', 'section': 'Income Expenditures  -  Labor Force', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['gdp_per_capita_real', 'median_weekly_earnings_real', 'labor_productivity_index'], 'join': ['corporate_profits', 'union_membership_rate', 'income_share_top10'], 'sc': {'emotional': 90, 'relatability': 90, 'clarity': 90, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 100, 'originality': 70}, 'vs': 88, 'tags': "GDP per capita median wage 1979 2023 uncoupling 115 percent 13 percent productivity economy grew workers didn't", 'notes': '', 'topics': ['labor', 'economy', 'history', 'inequality', 'politics'], 'status': 'idea'},
  {'id': 'us_life_expectancy_covid_impact', 'title': 'US life expectancy 1900-2023: every dip tells a story — Spanish flu, WWII, COVID', 'sub': '1918: life expectancy fell from 51 to 39 in one year. 2020-2021: fell from 78.8 to 76.1 — the largest two-year drop since 1943.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Area chart', 'tbl': 'CDC NCHS + Berkeley Mortality Database: US life expectancy at birth 1900-2023', 'section': 'Health', 'ext': [], 'vars': ['life_expectancy_national'], 'join': ['covid_deaths_national', 'opioid_death_rate_national', 'infant_mortality_rate'], 'sc': {'emotional': 90, 'relatability': 90, 'clarity': 90, 'surprise': 80, 'tension': 80, 'visual': 90, 'data_ready': 90, 'originality': 70}, 'vs': 86, 'tags': 'life expectancy 1900 2023 Spanish flu WWII COVID 1918 51 to 39 2020 78.8 to 76.1 largest drop 1943', 'notes': '', 'topics': ['health', 'history', 'population', 'economy'], 'status': 'idea'},
  {'id': 'us_debt_ceiling_arc', 'title': 'US national debt as % of GDP 1792-2024: every war, every recession, every tax cut', 'sub': '1946: 119% of GDP (WWII peak). 1981: 31% (modern low). 2024: 123% (new record). Every spike has a name.', 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Area chart', 'tbl': 'US Treasury + CBO: Federal debt as % of GDP 1792-2024 (fiscaldata.treasury.gov)', 'section': 'Federal Government', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['federal_debt_pct_gdp'], 'join': ['federal_deficit_pct_gdp', 'gdp_growth_rate', 'tax_revenue_pct_gdp'], 'sc': {'emotional': 80, 'relatability': 70, 'clarity': 90, 'surprise': 70, 'tension': 80, 'visual': 80, 'data_ready': 100, 'originality': 60}, 'vs': 78, 'tags': 'national debt GDP 1792 2024 WWII 119 percent 1981 31 low 2024 123 record every war recession tax cut named', 'notes': '', 'topics': ['economy', 'history', 'politics', 'military', 'inequality'], 'status': 'idea'},
]

def vscore(sc):
    return int((sc.get("emotional",0)*2 + sc.get("relatability",0)*2 + sc.get("clarity",0)*2 +
               sc.get("surprise",0)*1.5 + sc.get("tension",0)*1 + sc.get("visual",0)*1 +
               sc.get("data_ready",0)*0.5 + sc.get("originality",0)*0.5) / 10.5)

for idea in ideas:
    idea["vs"] = vscore(idea["sc"])

if __name__ == "__main__":
    print(f"BATCH_BH: {len(ideas)} ideas")
    for i in sorted(ideas, key=lambda x: -x["vs"]):
        print(f"  vs={i["vs"]:3d}  {i["id"]}")
