import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCE01","The Opportunity Atlas Reimagined: Where Upward Mobility Died Between 1980 and 2020","Chetty data animated — watching the map of mobility darken over 40 years","MAP","US-county","Animated choropleth","inequality/geography","Opportunity Atlas: Mobility data (opportunityatlas.org); Census: Income (census.gov); IRS: SOI (irs.gov)",85,82,78,80,82,82,75,85),
mk("HCE02","The First Job Map: What Teenagers Earn in Their First Job by County","Minimum wage vs actual teen employment wages — the gap reveals local labor markets","MAP","US-county","County choropleth","labor/children","BLS: Youth employment (bls.gov); Census: ACS earnings (census.gov/acs); DOL: Minimum wage (dol.gov)",72,85,72,68,62,78,70,78),
mk("HCE03","Where a DUI Ruins Your Life vs Costs a Fine: Sentencing Disparities for Identical Crimes","First-offense DUI outcomes mapped by state and county — justice by geography","MAP","US-state","State choropleth","law/geography","NHTSA: DUI data (nhtsa.gov); BJS: Sentencing (bjs.gov); NCSL: DUI laws (ncsl.org)",80,82,72,78,82,72,75,72),
mk("HCE04","The School Funding Lottery: Per-Pupil Spending Variation Within the Same State","Adjacent districts spending $8K vs $22K per student — the zip code education gap","MAP","US-county","County choropleth","education/inequality","NCES: Per-pupil spending (nces.ed.gov); Census: School district finance (census.gov/govs); EdBuild: Funding (edbuild.org)",85,82,80,78,82,78,72,85),
mk("HCE05","Where Your Address Determines Your Air Quality","PM2.5 levels mapped at census tract level against income and race — environmental racism visualized","MAP","US-county","Dot map","environment/race","EPA: Air quality (epa.gov/outdoor-air-quality-data); Census: Demographics (census.gov); EJScreen: EJ data (epa.gov/ejscreen)",82,78,75,75,80,80,68,82),
mk("HCE06","The Daycare Desert: Counties Where Childcare Costs More Than Rent","Childcare costs as % of median income mapped — some counties above 40%","MAP","US-county","County choropleth","children/economy","DOL: Childcare costs (dol.gov); Census: ACS (census.gov/acs); ChildCare Aware: Data (childcareaware.org)",85,88,78,75,80,78,68,78),
mk("HCE07","Where Your Commute Steals Your Life: Hours Lost Per Year by Metro","Annual commute hours mapped against median income — time poverty is real","MAP","US-metro","Bar chart","transportation/labor","Census: ACS commute (census.gov/acs); BLS: ATUS (bls.gov/tus); INRIX: Traffic data (inrix.com)",78,88,78,72,72,72,68,82),
mk("HCE08","The Dental Desert Map: Where Americas Teeth Go Untreated","Counties with zero dentists per 10K people mapped against income and insurance rates","MAP","US-county","County choropleth","health/rural","HRSA: Dental HPSA (hrsa.gov); ADA: Dentist data (ada.org); Census: Insurance (census.gov/acs)",78,80,75,72,72,78,68,78),
mk("HCE09","Where Being Black Costs an Extra $300K Over a Lifetime","The racial wealth gap decomposed by county — housing, wages, education, inheritance","MAP","US-county","County choropleth","race/economy","Federal Reserve: SCF (federalreserve.gov); Census: Wealth (census.gov); Brookings: Racial wealth (brookings.edu)",85,78,72,80,85,78,75,72),
mk("HCE10","The Small Business Survival Map: Startup Failure Rates by County and Industry","Where new businesses die fastest mapped against local conditions","MAP","US-county","County choropleth","economy/geography","Census: Business Dynamics Statistics (census.gov/bds); SBA: Small business (sba.gov); BLS: QCEW (bls.gov)",75,80,72,72,68,78,70,80),
mk("HCE11","Where Maternity Care Has Vanished: Counties That Lost Their Last OB-GYN","52% of US counties have zero OB-GYNs — mapped against birth rates and maternal mortality","MAP","US-county","County choropleth","health/gender","ACOG: Workforce data (acog.org); HRSA: Provider shortage (hrsa.gov); CDC: Maternal mortality (cdc.gov)",85,80,78,78,85,78,72,78),
mk("HCE12","The Internet Application Gap: Where Slow Broadband Kills College Applications","Broadband speed mapped against college application rates — the digital admissions barrier","XREF","US-county","Scatter plot","education/technology","FCC: Broadband (fcc.gov); NCES: College enrollment (nces.ed.gov); Common App: Application data (commonapp.org)",78,78,68,78,72,68,78,65),
mk("HCE13","Where Eviction Is an Epidemic: Eviction Filing Rates by County","Some counties evict 10% of renters annually — mapped against poverty and race","MAP","US-county","County choropleth","housing/law","Princeton Eviction Lab: Filing data (evictionlab.org); Census: ACS housing (census.gov/acs); HUD: Rental data (huduser.gov)",85,82,78,78,85,80,72,78),
mk("HCE14","The Sports Scholarship Geography: Where Athletic Talent Gets Recruited From","College athletic recruiting mapped by high school — talent pipelines visible","MAP","US-county","Dot map","sports/geography","NCAA: Recruiting data (ncaa.org); NFHS: Participation (nfhs.org); MaxPreps: Athlete data (maxpreps.com)",68,72,65,68,58,72,72,62),
mk("HCE15","Where Student Debt Exceeds Median Income: The Underwater Graduate Map","Student loan balances vs local median income by county — the ROI geography of college","MAP","US-county","Bivariate choropleth","education/finance","Federal Reserve: Student loan (newyorkfed.org); Census: Income (census.gov/acs); DOE: College scorecard (collegescorecard.ed.gov)",82,85,78,78,80,78,72,80),
mk("HCE16","The Grocery Price Map: What $100 of Groceries Actually Buys by Metro","Purchasing power of food dollars mapped — Hawaii pays 2x the national average","MAP","US-metro","Bar chart","food/prices","BLS: CPI food (bls.gov/cpi); USDA: Food prices (ers.usda.gov); Census: Regional prices (census.gov)",75,88,80,72,65,72,65,82),
mk("HCE17","Where Your Ambulance Response Time Could Kill You","EMS response times mapped against cardiac survival rates — the golden hour geography","MAP","US-county","County choropleth","health/infrastructure","NEMSIS: EMS data (nemsis.org); CDC: Cardiac data (cdc.gov); NREMT: Provider data (nremt.org)",85,82,75,78,82,80,72,72),
mk("HCE18","The Manufacturing Apprenticeship Desert: Where On-the-Job Training Disappeared","Registered apprenticeship programs per manufacturing worker by state — Germany vs US comparison","CHART","US-state","Bar chart","manufacturing/education","DOL: Apprenticeship (apprenticeship.gov); BLS: Manufacturing (bls.gov); OECD: VET data (oecd.org)",72,70,72,75,68,68,75,72),
mk("HCE19","Where the Psychology of Learned Helplessness Maps Onto Economic Data","Counties with persistent poverty mapped against locus-of-control survey data — the despair geography","XREF","US-county","Bivariate choropleth","psychology/poverty","USDA: Persistent poverty (ers.usda.gov); Gallup: Wellbeing (gallup.com); Census: Poverty (census.gov/acs)",78,75,62,80,75,75,82,58),
mk("HCE20","The Entertainment Access Gap: Live Performance Venues Per Capita by Metro","NYC has 100x more venues per capita than rural metros — the cultural opportunity gap","MAP","US-metro","Bar chart","entertainment/geography","BLS: Arts employment (bls.gov); Yelp: Venue data; Census: Metro population (census.gov)",65,72,68,68,58,68,72,65),
mk("HCE21","Where Your Ballot Gets Rejected: Mail-in Vote Rejection Rates by County Demographics","Rejection rates correlated with race and age — the quiet disenfranchisement mapped","MAP","US-county","Bivariate choropleth","democracy/race","EAC: Election data (eac.gov); MIT: Elections (electionlab.mit.edu); Census: Demographics (census.gov)",82,72,72,80,85,75,78,68),
mk("HCE22","The Rural Veterinarian Crisis: Counties Where Your Animals Cant Get Care","Vet shortage areas mapped — food supply chain vulnerability nobody discusses","MAP","US-county","County choropleth","rural/agriculture","AVMA: Workforce data (avma.org); USDA: Census of Agriculture (nass.usda.gov); HRSA: Shortage areas (hrsa.gov)",70,68,68,72,62,72,78,68),
mk("HCE23","Where Gun Suicides Spike After Job Losses: The Employment-Despair-Firearms Pipeline","Unemployment increases mapped against firearm suicide timing by county — the lag is 6-18 months","XREF","US-county","Scatter plot","guns/labor","CDC: Suicide data (wonder.cdc.gov); BLS: LAUS (bls.gov/lau); RAND: Gun ownership (rand.org)",85,72,68,82,85,68,80,72),
mk("HCE24","The Middle East Education Explosion: University Enrollment Tripled in 20 Years","MENA higher education growth mapped — the fastest-educating region on earth","CHART","Middle East","Bar chart","middle_east/education","UNESCO: Education data (uis.unesco.org); World Bank: Education (worldbank.org); QS: University rankings (qs.com)",68,58,72,82,58,68,78,78),
mk("HCE25","Where Demographics Predict School Closures: The 5-Year Warning Map","Birth rate declines mapped against projected school enrollment shortfalls by district","MAP","US-county","Bivariate choropleth","demographics/education","CDC: Birth data (cdc.gov); NCES: Enrollment (nces.ed.gov); Census: Projections (census.gov)",78,75,72,78,78,78,75,72),
mk("HCE26","The Drug Recovery Desert: Counties Where Treatment Capacity Meets 10% of Demand","SAMHSA treatment slots vs estimated need by county — the massive gap mapped","MAP","US-county","Bivariate choropleth","drugs/health","SAMHSA: Treatment locator (samhsa.gov); CDC: Overdose (wonder.cdc.gov); Census: Demographics (census.gov)",82,78,72,78,82,78,72,72),
mk("HCE27","Where Your Religion Predicts Your Politics Better Than Your Income","Religious attendance correlated with voting stronger than income in specific counties","XREF","US-county","Scatter plot","religion/politics","ARDA: Religious census (thearda.com); MIT: Elections (electionlab.mit.edu); Census: Income (census.gov/acs)",72,72,68,80,72,68,75,72),
mk("HCE28","The Sports Injury Economy: What Youth Sports Injuries Cost American Families","ER visits, surgery costs, and lost parent work hours by sport — the hidden price tag","CHART","US","Bar chart","sports/health","CDC: NEISS injury data (cpsc.gov); HCUP: Hospital costs (hcup-us.ahrq.gov); Safe Kids: Sports (safekids.org)",78,82,72,72,68,68,70,72),
mk("HCE29","Where Voting Takes the Longest: Wait Times by County Demographics","Average wait time to vote mapped against race and income — the lines are not equal","MAP","US-county","Bivariate choropleth","democracy/race","MIT: Elections (electionlab.mit.edu); Brennan Center: Voting (brennancenter.org); Census: Demographics (census.gov)",82,78,75,78,85,75,72,68),
mk("HCE30","The Manufacturing Workers Health Crisis: Injury and Illness Rates by Industry Subsector","Which manufacturing jobs are most dangerous — mapped against pay and union status","CHART","US","Scatter plot","manufacturing/health","BLS: Injuries (bls.gov/iif); OSHA: Inspections (osha.gov); BLS: OES wages (bls.gov/oes)",75,72,72,72,72,68,68,78),
mk("HCE31","Where Childrens Mental Health Services Dont Exist","Counties with zero child psychiatrists mapped against youth depression rates","MAP","US-county","Bivariate choropleth","children/psychology","HRSA: Child mental health (hrsa.gov); CDC: Youth risk behavior (cdc.gov/yrbs); AACAP: Workforce (aacap.org)",85,82,72,78,82,78,72,68),
mk("HCE32","The Law Enforcement Training Gap: Police Academy Hours by State vs Barber Licensing Hours","It takes more training to cut hair than carry a gun in most states — the comparison mapped","CHART","US-state","Bar chart","law/education","IADLEST: Academy data (iadlest.org); BLS: Licensing (bls.gov); State licensing boards",78,78,78,85,78,68,78,75),
mk("HCE33","Where Rent Eats Your Paycheck: Rent-to-Income Ratio by Metro for Service Workers","Median rent vs service-sector wages — the metros where working means drowning","MAP","US-metro","Bar chart","housing/labor","Census: ACS rent (census.gov/acs); BLS: OES service (bls.gov/oes); NLIHC: Out of Reach (nlihc.org)",82,88,78,72,80,72,65,82),
mk("HCE34","The Global Democracy Recession Mapped Year by Year","V-Dem democracy scores animated 2005-2025 — watching the world get less free","MAP","World","Animated choropleth","democracy/international","V-Dem: Democracy indices (v-dem.net); Freedom House: Trends (freedomhouse.org)",80,68,75,78,82,82,72,82),
mk("HCE35","Where Your County Ranks in the Opportunity Index: All 3000+ Counties Scored","Composite of income mobility, school quality, health, safety, and broadband — one number per county","RANK","US-county","County choropleth","inequality/geography","Opportunity Atlas (opportunityatlas.org); Census: ACS (census.gov/acs); CDC: Health (cdc.gov); FCC: Broadband (fcc.gov)",82,82,78,72,78,82,68,82),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCE ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCE batch)")
