# BATCH_BF.py
ideas = [
  {'id': 'topn_most_federally_dependent_states', 'title': 'Top 20 states ranked by federal dependency ratio: money in vs. taxes paid', 'sub': 'For every $1 Mississippi sends to Washington, it gets $2.34 back. For New Jersey: $0.77. The full ranking of who funds whom.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'Tax Foundation + BEA: Federal spending received vs. taxes paid by state (taxfoundation.org + bea.gov)', 'section': 'Federal Government', 'ext': [], 'vars': ['federal_spending_received_per_tax_dollar'], 'join': ['rep_pct', 'total_transfers_per_capita', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 100, 'surprise': 90, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 80}, 'vs': 89, 'tags': 'federal dependency ratio states money in taxes paid Mississippi New Jersey ranked list who funds whom', 'notes': '', 'topics': ['politics', 'economy', 'inequality', 'elections', 'social insurance'], 'status': 'idea'},
  {'id': 'topn_worst_teacher_pay_outcomes', 'title': 'Top 20 states with the worst teacher pay relative to cost of living', 'sub': "Mississippi's $54K teacher salary buys less than Wyoming's $64K when adjusted for housing costs. The real-pay ranking tells a different story.", 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'NCES: Teacher salary by state + BLS: Regional Price Parities by state (bls.gov)', 'section': 'Education', 'ext': [], 'vars': ['avg_teacher_salary_real_adjusted', 'avg_teacher_salary'], 'join': ['expenditure_per_pupil', 'pct_bachelors', 'rep_pct'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 100, 'surprise': 80, 'tension': 80, 'visual': 90, 'data_ready': 80, 'originality': 80}, 'vs': 84, 'tags': 'teacher pay cost of living adjusted real salary ranking Mississippi Wyoming worst states education', 'notes': '', 'topics': ['education', 'labor', 'inequality', 'economy'], 'status': 'idea'},
  {'id': 'topn_most_dangerous_jobs', 'title': 'Top 20 most dangerous jobs in America by fatality rate per 100,000 workers', 'sub': 'Logging: 111 deaths per 100K. Fishing: 132. Roofing: 51. The jobs that are genuinely likely to kill you, ranked.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'BLS Census of Fatal Occupational Injuries: Fatality rate by occupation (bls.gov/iif)', 'section': 'Labor Force', 'ext': [], 'vars': ['fatality_rate_per_100k_workers', 'total_fatal_injuries_occupation'], 'join': ['median_occupational_wage', 'union_density_occupation'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 100, 'surprise': 80, 'tension': 70, 'visual': 90, 'data_ready': 90, 'originality': 70}, 'vs': 83, 'tags': 'dangerous jobs fatality rate logging fishing roofing 100K workers ranked list occupational injury death', 'notes': '', 'topics': ['labor', 'health', 'economy', 'inequality'], 'status': 'idea'},
  {'id': 'topn_highest_property_tax_states', 'title': 'States ranked by effective property tax rate — New Jersey #1 at 2.2%, Hawaii #50 at 0.26%', 'sub': 'Your home value means almost nothing. Your ZIP code determines your tax bill. The full state ranking.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'Tax Foundation: Effective property tax rate by state + Census: Median home value by state', 'section': 'State Government', 'ext': [], 'vars': ['effective_property_tax_rate', 'median_property_tax_bill'], 'join': ['home_price_index_2024', 'median_household_income', 'expenditure_per_pupil'], 'sc': {'emotional': 70, 'relatability': 90, 'clarity': 100, 'surprise': 70, 'tension': 60, 'visual': 90, 'data_ready': 90, 'originality': 60}, 'vs': 80, 'tags': 'property tax rate states New Jersey Hawaii ZIP code determines tax bill ranking effective rate', 'notes': '', 'topics': ['housing', 'economy', 'education', 'inequality', 'politics'], 'status': 'idea'},
  {'id': 'topn_biggest_hospital_systems', 'title': 'Top 20 largest US hospital systems by number of beds and revenue', 'sub': 'HCA Healthcare: 183 hospitals, $60B revenue. CommonSpirit: 143 hospitals. The consolidated healthcare industrial complex, ranked.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'AHA Annual Survey: Hospital systems by size and revenue (aha.org)', 'section': 'Health', 'ext': [], 'vars': ['hospital_beds_system', 'system_revenue', 'hospital_count_system'], 'join': ['per_capita_health_spending', 'uninsured_rate'], 'sc': {'emotional': 70, 'relatability': 70, 'clarity': 100, 'surprise': 70, 'tension': 70, 'visual': 90, 'data_ready': 80, 'originality': 70}, 'vs': 78, 'tags': 'largest hospital systems HCA CommonSpirit beds revenue healthcare consolidated industrial complex ranked', 'notes': '', 'topics': ['health', 'economy', 'inequality', 'labor'], 'status': 'idea'},
  {'id': 'topn_opioid_death_counties', 'title': 'Top 50 US counties by opioid overdose death rate per 100,000', 'sub': 'McDowell County, WV: 95 deaths per 100K. The geography of the crisis, concentrated.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'CDC WONDER: Drug overdose mortality by county (wonder.cdc.gov)', 'section': 'Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['opioid_death_rate_county'], 'join': ['poverty_rate_county', 'manufacturing_job_loss_pct', 'median_household_income'], 'sc': {'emotional': 100, 'relatability': 80, 'clarity': 100, 'surprise': 80, 'tension': 100, 'visual': 100, 'data_ready': 90, 'originality': 70}, 'vs': 91, 'tags': 'opioid overdose death rate county top 50 McDowell West Virginia crisis geography concentrated ranked', 'notes': '', 'topics': ['health', 'drugs', 'poverty', 'labor', 'race', 'inequality'], 'status': 'idea'},
  {'id': 'topn_highest_rent_burden_metros', 'title': 'Top 30 US metros where residents spend the most of their income on rent', 'sub': 'Miami: 35% of income to rent. Los Angeles: 33%. Boston: 31%. The rent-burdened cities ranked — and some surprises in the middle.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'ACS 5-year: Gross rent as % of household income by metro (census.gov)', 'section': 'Housing', 'ext': [], 'vars': ['pct_income_on_rent', 'median_rent_metro', 'median_income_metro'], 'join': ['home_price_index_metro', 'population_growth_metro'], 'sc': {'emotional': 90, 'relatability': 90, 'clarity': 100, 'surprise': 70, 'tension': 80, 'visual': 100, 'data_ready': 90, 'originality': 60}, 'vs': 87, 'tags': 'rent burden metros income percentage Miami Los Angeles Boston ranked list housing affordability', 'notes': '', 'topics': ['housing', 'economy', 'labor', 'inequality', 'poverty'], 'status': 'idea'},
  {'id': 'topn_gun_deaths_per_capita', 'title': 'States ranked by firearm death rate per 100,000 — all causes combined', 'sub': 'Mississippi: 28.6 per 100K. Hawaii: 3.4. The 8x gap within one country, ranked clearly.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'CDC WISQARS: Firearm mortality by state and cause (cdc.gov/injury)', 'section': 'Law Enforcement', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['firearm_death_rate_per_100k', 'firearm_homicide_rate', 'firearm_suicide_rate'], 'join': ['gun_ownership_pct', 'rep_pct', 'poverty_rate_state'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 100, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 90, 'originality': 60}, 'vs': 87, 'tags': 'firearm death rate states ranked Mississippi 28.6 Hawaii 3.4 8x gap gun deaths per capita', 'notes': '', 'topics': ['guns', 'health', 'crime', 'politics', 'inequality', 'race'], 'status': 'idea'},
  {'id': 'topn_states_most_incarcerated', 'title': 'States ranked by incarceration rate per 100,000 residents', 'sub': "Louisiana: 684 per 100K — still the world's highest incarceration rate despite 20 years of reform talk. The US in global context.", 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'BJS National Prisoner Statistics: Incarceration rate by state (bjs.ojp.gov)', 'section': 'Law Enforcement', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['incarceration_rate_per_100k'], 'join': ['poverty_rate_state', 'rep_pct', 'violent_crime_rate', 'pct_black_population'], 'sc': {'emotional': 90, 'relatability': 70, 'clarity': 100, 'surprise': 70, 'tension': 90, 'visual': 90, 'data_ready': 90, 'originality': 60}, 'vs': 83, 'tags': 'incarceration rate states ranked Louisiana 684 per 100K world highest reform talk US global context', 'notes': '', 'topics': ['crime', 'race', 'inequality', 'politics', 'poverty', 'history'], 'status': 'idea'},
  {'id': 'topn_most_unequal_cities', 'title': 'Top 20 most economically unequal US cities by Gini coefficient', 'sub': 'New York, Atlanta, Miami, New Orleans. The cities of maximum inequality are not the poorest — they are the ones where the gap is widest.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'ACS 5-year: Gini coefficient and income distribution by metro and city (census.gov)', 'section': 'Income Expenditures', 'ext': [], 'vars': ['gini_coefficient_city', 'income_share_top10_city', 'income_share_bottom40_city'], 'join': ['median_household_income', 'poverty_rate', 'race_composition'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 100, 'surprise': 70, 'tension': 80, 'visual': 90, 'data_ready': 90, 'originality': 70}, 'vs': 83, 'tags': 'most unequal cities Gini coefficient New York Atlanta Miami New Orleans gap widest not poorest ranked', 'notes': '', 'topics': ['inequality', 'economy', 'race', 'housing', 'poverty'], 'status': 'idea'},
  {'id': 'topn_lowest_life_expectancy_counties', 'title': 'Top 50 US counties with the lowest life expectancy', 'sub': 'Oglala Lakota County, SD: 66.8 years — lower than Bangladesh. McDowell County, WV: 67.1. The third-world life expectancy hidden inside America.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'IHME Global Burden of Disease: US county-level life expectancy (healthdata.org)', 'section': 'Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['life_expectancy_county'], 'join': ['poverty_rate_county', 'opioid_death_rate_county', 'uninsured_rate_county', 'race_composition_county'], 'sc': {'emotional': 100, 'relatability': 70, 'clarity': 100, 'surprise': 90, 'tension': 100, 'visual': 100, 'data_ready': 80, 'originality': 80}, 'vs': 90, 'tags': 'lowest life expectancy counties Oglala Lakota 66.8 McDowell WV Bangladesh third world inside America hidden', 'notes': '', 'topics': ['health', 'poverty', 'race', 'inequality', 'drugs', 'history'], 'status': 'idea'},
  {'id': 'topn_most_evictions_cities', 'title': 'Top 20 US cities with the highest eviction filing rates', 'sub': "Richmond, VA: 11% of renters face eviction annually. Memphis: 9%. Charleston, SC: 7%. The eviction geography of America's housing crisis.", 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'Princeton Eviction Lab: Eviction filing and judgment rates by city (evictionlab.org)', 'section': 'Housing', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['eviction_filing_rate', 'eviction_judgment_rate'], 'join': ['poverty_rate', 'rent_burden_pct', 'race_composition', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 100, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 70}, 'vs': 87, 'tags': 'evictions cities Richmond VA Memphis Charleston eviction filing rate annual renters housing crisis geography', 'notes': '', 'topics': ['housing', 'poverty', 'inequality', 'race', 'labor'], 'status': 'idea'},
  {'id': 'topn_states_most_remote_workers', 'title': 'States ranked by share of workforce working remotely 2023', 'sub': 'Vermont: 28% remote. Colorado: 24%. Mississippi: 8%. The remote work geography that reshuffled American demographics.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'BLS ATUS + ACS 5-year: Remote work share by state 2023 (bls.gov + census.gov)', 'section': 'Labor Force', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['pct_remote_workers'], 'join': ['broadband_access_pct', 'median_household_income', 'pct_bachelors', 'population_growth_state'], 'sc': {'emotional': 70, 'relatability': 90, 'clarity': 100, 'surprise': 70, 'tension': 50, 'visual': 90, 'data_ready': 80, 'originality': 70}, 'vs': 80, 'tags': 'remote work share state ranked Vermont Colorado Mississippi 2023 reshuffled American demographics geography', 'notes': '', 'topics': ['labor', 'technology', 'housing', 'economy', 'population'], 'status': 'idea'},
  {'id': 'topn_most_uninsured_counties', 'title': 'Top 50 US counties by uninsured rate', 'sub': 'Kenedy County, TX: 48% uninsured. Zavala County, TX: 42%. The map of where health insurance is a luxury. Almost entirely Texas and the Deep South.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'Census SAHIE: Small Area Health Insurance Estimates by county (census.gov/programs-surveys/sahie)', 'section': 'Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['uninsured_rate_county'], 'join': ['poverty_rate_county', 'medicaid_expansion_state', 'rep_pct_county', 'pct_hispanic_county'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 100, 'surprise': 80, 'tension': 90, 'visual': 100, 'data_ready': 90, 'originality': 70}, 'vs': 88, 'tags': 'uninsured counties top 50 Kenedy Zavala Texas 48 42 percent health insurance luxury Deep South ranked', 'notes': '', 'topics': ['health', 'poverty', 'race', 'politics', 'inequality'], 'status': 'idea'},
  {'id': 'topn_highway_miles_per_capita', 'title': 'States ranked by highway miles per capita — who built the most road per person?', 'sub': 'Montana: 4.2 miles of road per person. New Jersey: 0.04. The inverse of density, rendered as infrastructure.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'FHWA Highway Statistics: Total road mileage by state (fhwa.dot.gov)', 'section': 'Transportation', 'ext': [], 'vars': ['highway_miles_per_capita'], 'join': ['population_density', 'state_gdp_per_capita', 'energy_consumption_per_capita'], 'sc': {'emotional': 50, 'relatability': 70, 'clarity': 100, 'surprise': 80, 'tension': 30, 'visual': 90, 'data_ready': 100, 'originality': 70}, 'vs': 72, 'tags': 'highway miles per capita state Montana 4.2 New Jersey 0.04 inverse density infrastructure road ranked', 'notes': '', 'topics': ['transportation', 'infrastructure', 'geography', 'economy', 'energy'], 'status': 'idea'},
]

def vscore(sc):
    return int((sc.get("emotional",0)*2 + sc.get("relatability",0)*2 + sc.get("clarity",0)*2 +
               sc.get("surprise",0)*1.5 + sc.get("tension",0)*1 + sc.get("visual",0)*1 +
               sc.get("data_ready",0)*0.5 + sc.get("originality",0)*0.5) / 10.5)

for idea in ideas:
    idea["vs"] = vscore(idea["sc"])

if __name__ == "__main__":
    print(f"BATCH_BF: {len(ideas)} ideas")
    for i in sorted(ideas, key=lambda x: -x["vs"]):
        print(f"  vs={i["vs"]:3d}  {i["id"]}")
