import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDM01","Civil Asset Forfeiture: Property Seized by Police Without Criminal Conviction by State","How much property law enforcement confiscates from people never charged with a crime — the states where policing for profit thrives","MAP","US","State choropleth","law","Institute for Justice: Policing for Profit (ij.org/report/policing-for-profit)",78,68,72,78,82,72,72,80),
mk("HDM02","Americas Oldest Towns: Continuously Inhabited Settlements by Founding Date","The oldest places in America — from Pueblo communities predating Columbus to the first European settlements at St. Augustine and Santa Fe","MAP","US","Dot map","demographics","NPS: National Register of Historic Places (nps.gov/subjects/nationalregister)",55,65,72,68,48,80,68,85),
mk("HDM03","Silencer Sales Surge: Registered Firearm Suppressors by State Since 2012","Legally owned suppressors went from 360K to 4.7M in a decade — the fastest growing segment of the firearms market mapped by state","MAP","US","State choropleth","guns","ATF: National Firearms Registration and Transfer Record (atf.gov)",55,52,68,78,62,68,68,82),
mk("HDM04","Yemeni Humanitarian Crisis: Civilian Casualties and Aid Access Blockades by Province","The worlds worst humanitarian disaster by the numbers — coalition airstrikes, famine zones, and cholera outbreaks mapped by Yemeni governorate","MAP","Middle East","Special map","middle_east","ACLED: Yemen Data Project (acleddata.com) + OCHA (reliefweb.int)",82,52,65,65,85,80,68,78),
mk("HDM05","Plea Bargain Nation: Percentage of Criminal Cases Resolved Without Trial by Jurisdiction","97% of federal cases and 94% of state cases end in plea bargains — the map of where trial by jury has effectively vanished","MAP","US","State choropleth","law","BJS: Federal Justice Statistics + State Court Processing Statistics (bjs.ojp.gov)",68,65,75,80,78,68,72,82),
mk("HDM06","Ancestry Self-Identification: Most Common Ethnic Heritage Claimed by County","What Americans call themselves on the Census ancestry question — German, Irish, American, Mexican, English — the identity map","MAP","US","County choropleth","demographics","Census Bureau: ACS Ancestry Data (data.census.gov)",55,72,72,68,48,82,65,92),
mk("HDM07","Concealed Carry Permit Density: Active CCW Permits Per Capita by State","From permitless carry states to shall-issue to may-issue — active concealed carry permits per 100 adults mapped","MAP","US","State choropleth","guns","Crime Prevention Research Center: Concealed Carry Permit Holders (crimeresearch.org)",55,62,72,65,65,72,55,82),
mk("HDM08","Iranian Protest Map: Location and Scale of Anti-Regime Demonstrations Since 2009","Major Iranian protests mapped by city from the Green Movement through Mahsa Amini — the recurring geography of dissent","MAP","Middle East","Dot map","middle_east","ACLED: Iran Protest Data (acleddata.com)",78,55,65,68,82,78,72,72),
mk("HDM09","Prosecutorial Discretion: Charging Rates for Similar Offenses Across District Attorneys","How the same crime gets charged differently depending on which DA handles it — the lottery of local prosecution","MAP","US","County choropleth","law","Measures for Justice: County-Level Criminal Justice Data (measuresforjustice.org)",68,65,72,78,78,72,72,72),
mk("HDM10","Twin Cities and Name Collisions: Americas Most Duplicated City Names","How many Springfields, Clintons, Fairviews, and Washingtons exist — the most overused place names in America mapped","MAP","US","Dot map","demographics","USGS: Geographic Names Information System (geonames.usgs.gov)",42,68,65,72,38,75,72,90),
mk("HDM11","3D-Printed Gun Seizures: Homemade Firearms Made With 3D Printers Recovered by Year","The emerging threat of 3D-printed firearms — law enforcement recoveries rising sharply from near zero in 2018","CHART","US","Line chart","guns","ATF: Privately Made Firearms Report (atf.gov)",65,55,65,78,78,62,72,68),
mk("HDM12","Kurdish Population Divided: The Stateless Nation Spread Across Four Countries","Estimated Kurdish population in Turkey, Iraq, Iran, and Syria — the 30+ million people without a nation-state","MAP","Middle East","Special map","middle_east","CIA World Factbook + Kurdish Institute (institutkurde.org)",72,55,68,68,75,82,68,70),
mk("HDM13","Solitary Confinement Map: Inmates Held in Isolation for 22+ Hours Per Day by State","How many prisoners are in solitary right now — states where thousands sit in prolonged isolation despite evidence it causes permanent harm","MAP","US","State choropleth","law","Solitary Watch: National Database (solitarywatch.org) + Yale Law (law.yale.edu)",80,62,68,72,82,68,72,70),
mk("HDM14","Where the Census Missed: Differential Undercount by Race and Age in 2020","The 2020 Census overcounted white adults by 1.6% and undercounted Black and Hispanic populations — the distortion in federal funding","CHART","US","Bar chart","demographics","Census Bureau: 2020 Post-Enumeration Survey (census.gov/coverage_measurement)",68,62,72,78,72,58,68,88),
mk("HDM15","School Shooting Lockdown Drills: States That Require Active Shooter Drills and Their Frequency","Where children practice hiding from gunmen — mandatory drill requirements by state and the debate over their psychological impact","MAP","US","State choropleth","guns","Everytown: Active Shooter Drill Policies (everytown.org)",78,75,68,65,78,68,62,75),
mk("HDM16","Normalization Treaties Map: Arab States That Recognize Israel Before and After Abraham Accords","The shifting diplomatic map of the Middle East — from Egypt and Jordan standing alone to the UAE, Bahrain, Morocco, and Sudan normalizing","MAP","Middle East","World choropleth","middle_east","CFR: Abraham Accords (cfr.org)",58,48,72,65,68,78,65,85),
mk("HDM17","Fines and Fees: Revenue From Traffic Tickets and Court Fees as Share of City Budget","Cities that fund themselves through fining residents — Ferguson was the wake-up call but hundreds of cities depend on fine revenue","MAP","US","Dot map","law","Fines and Fees Justice Center (finesandfeesjusticecenter.org)",72,72,72,75,78,72,70,75),
mk("HDM18","Vanishing Ethnic Enclaves: Chinatowns, Little Italys, and Koreatowns That Have Shrunk or Disappeared","Historical ethnic neighborhoods mapped against their current ethnic composition — gentrification eating cultural geography","MAP","US","Dot map","demographics","Census Bureau: ACS Tract-Level Ancestry + Historical Records (data.census.gov)",68,68,68,68,62,78,72,78),
mk("HDM19","Bump Stock Inventory: Estimated Devices in Civilian Hands Before and After the Ban","How many bump stocks were sold before the 2019 ban and how many were surrendered — the compliance gap estimated","CHART","US","Bar chart","guns","ATF: Bump Stock Rule Compliance Data (atf.gov)",58,55,65,72,72,55,65,60),
mk("HDM20","Strait of Hormuz Traffic: Oil Tanker Movements Through the Worlds Most Critical Chokepoint","Daily tanker traffic through the strait that 20% of global oil passes through — the vulnerability of the worlds energy supply","CHART","Middle East","Line chart","middle_east","EIA: Strait of Hormuz Oil Flow (eia.gov/international)",62,48,72,68,78,75,68,85),
mk("HDM21","Jury Representation: How Jury Pools Differ From Community Demographics by County","Juries that dont look like their communities — underrepresentation of minorities, young people, and low-income residents in jury pools","MAP","US","Bivariate choropleth","law","National Center for State Courts: Jury Demographics (ncsc.org)",68,62,72,72,75,68,72,68),
mk("HDM22","Commute Pattern Shift: Where Americans Live vs Where They Work Post-Remote Work","How remote work rewired commuting — counties that gained residential population while losing commuter inflow","MAP","US","Bivariate choropleth","demographics","Census Bureau: LEHD Origin-Destination Employment Statistics (lehd.ces.census.gov)",58,72,72,68,55,75,68,85),
mk("HDM23","Straw Purchase Pipeline: Where Guns Bought Legally End Up Used in Crimes in Other States","Gun trafficking corridors — weapons purchased in lax-law states recovered at crime scenes in strict-law states, the iron pipeline","MAP","US","Line map","guns","ATF: Firearms Trace Data (atf.gov/resource-center/firearms-trace-data)",72,58,70,72,80,78,68,80),
mk("HDM24","Israeli Settlement Expansion: Built-Up Area in the West Bank by Year Since 1967","Growth of Israeli settlements in the West Bank measured in square kilometers of built-up area over time","CHART","Middle East","Area chart","middle_east","Peace Now: Settlement Watch (peacenow.org.il/en/settlements-watch)",72,48,68,65,82,72,65,78),
mk("HDM25","Cash Bail System: Percentage of Jail Population Held Pretrial Because They Cant Afford Bail","The map of pretrial detention — counties where 70%+ of jail inmates havent been convicted, theyre just too poor to leave","MAP","US","County choropleth","law","Prison Policy Initiative: Pretrial Detention (prisonpolicy.org/research/pretrial_detention)",78,72,72,75,80,72,68,78),
mk("HDM26","Last Names of America: Most Common Surnames by County","The surname geography of the US — where Garcia dominates the Southwest, Nguyen clusters in coastal metros, and Smith covers everything else","MAP","US","County choropleth","demographics","Census Bureau: Frequently Occurring Surnames (census.gov/topics/population/genealogy/data/2010_surnames.html)",48,72,72,65,38,82,68,90),
mk("HDM27","Domestic Violence and Gun Ownership: States With vs Without Firearm Surrender Laws","States that require domestic abusers to surrender firearms vs those that dont — mapped against intimate partner homicide rates","MAP","US","Bivariate choropleth","guns","National Domestic Violence Hotline + Giffords (thehotline.org + giffords.org)",78,68,72,68,82,72,68,75),
mk("HDM28","Water Infrastructure Age: Average Water Pipe Installation Year by US City","How old is the water infrastructure under your feet — cities still running pipes installed before World War I","MAP","US","Dot map","middle_east","AWWA: Buried No Longer Report (awwa.org)",65,68,72,72,68,72,65,75),
mk("HDM29","Elected Judges vs Appointed: How States Select Their Judiciary","The patchwork of judicial selection — partisan election, nonpartisan election, legislative appointment, gubernatorial appointment, merit selection","MAP","US","State choropleth","law","Brennan Center: Judicial Selection (brennancenter.org/our-work/research-reports/judicial-selection)",55,58,72,68,65,72,65,88),
mk("HDM30","Dying Towns Census: Incorporated Places That Lost 50%+ Population Since Their Peak","Americas most dramatically shrinking towns — formerly thriving communities now at half or less of their peak population","MAP","US","Dot map","demographics","Census Bureau: Decennial Census Historical Population Tables (data.census.gov)",72,65,72,68,70,78,65,88),
mk("HDM31","AR-15 Ownership Estimates: Semiautomatic Rifle Prevalence by State","Estimated modern sporting rifles in civilian hands by state — the 20+ million AR-platform weapons in America","MAP","US","State choropleth","guns","NSSF: Firearms Production Data + Survey Estimates (nssf.org)",58,58,68,65,72,68,58,65),
mk("HDM32","Qatars Migrant Worker Deaths: Construction Fatalities During World Cup Stadium Builds","Reported migrant worker deaths during Qatars World Cup infrastructure construction — the human cost of hosting a tournament","CHART","Middle East","Bar chart","middle_east","Guardian: Qatar Migrant Worker Deaths Investigation (theguardian.com)",82,55,65,72,85,65,68,72),
mk("HDM33","Statute of Limitations for Sexual Assault: Time Limits for Filing Criminal Charges by State","Where survivors can still seek justice and where the clock has run out — the wildly inconsistent patchwork of SOL laws","MAP","US","State choropleth","law","RAINN: State Law Database (rainn.org/state-law-database)",75,68,72,68,78,72,65,82),
mk("HDM34","Language Isolate Towns: Small Communities Where Unusual Languages Survived","Places where Basque, Gullah, Louisiana French, Texas Czech, or Pennsylvania Dutch persisted in isolation — the linguistic pockets of America","MAP","US","Dot map","demographics","Endangered Languages Project (endangeredlanguages.com) + Census Language Data",58,62,62,78,52,78,82,62),
mk("HDM35","School Resource Officers and Arrests: Student Arrest Rates in Schools With vs Without Police","Do police in schools make kids safer or just arrest them? Student arrest rates compared between SRO and non-SRO schools by district","XREF","US","Bar chart","guns","DOJ: Cops in Schools (ojp.gov) + DOE: Civil Rights Data Collection (ocrdata.ed.gov)",72,68,72,75,78,58,72,75),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDM batch)")
