# BATCH_EK.py — ProQuest Statistical Abstract of the U.S. 2026
# Source: 37 chapter PDFs covering every major US statistical category

def vs(sc):
    raw = (sc['emotional']*2 + sc['relatability']*2 + sc['clarity']*2 +
           sc['surprise']*1.5 + sc['tension']*1 + sc['visual']*1.25 + sc['originality']*1)
    base = raw / 10.75
    penalty = 1 - 0.3*(1 - sc['data_ready']/100)
    return int(base * penalty)

ideas = [
{"id":"proq_voter_turnout_income_quintile","title":"Voter turnout by income quintile 2000–2024: the participation gap that shapes every election","sub":"The bottom income quintile votes at 40-45% rates in presidential elections. The top quintile votes at 75-80%. The 35-point participation gap means every election is decided by a sample of the population skewed heavily toward the wealthy. Policies that the majority of Americans support in surveys routinely fail at the ballot box — not because voters reject them, but because the voters most affected don't show up.","type":"CHART","geo":"us_national","fmt":"Bar chart","tbl":"ProQuest Stat Abstract 2026: Elections chapter — voter turnout by income level 2000-2024 (Census CPS Voting Supplement)","section":"Elections","ext":["Census Bureau: Current Population Survey Voting Supplement (census.gov - free)"],"vars":["voter_turnout_by_income_quintile"],"join":["income_quintile_share","policy_support_by_income","election_outcomes"],"sc":{"emotional":90,"relatability":80,"clarity":90,"surprise":80,"tension":90,"visual":80,"originality":70,"data_ready":90},"vs":0,"tags":"voter turnout income quintile 40 percent bottom 80 percent top 35 point gap wealthy participation policies fail ballot","notes":"","topics":["politics","inequality","democracy","poverty","history","data"],"status":"idea"},
{"id":"proq_federal_spending_vs_tax_burden_state","title":"Federal spending received vs. federal taxes paid by state: the red state welfare map","sub":"29 of the 30 states that receive more in federal spending than they pay in taxes voted Republican in 2020. Mississippi receives $2.57 for every $1 it sends to Washington. New Jersey sends $1 for every $0.74 it receives. The fiscal geography of America is the opposite of the political rhetoric.","type":"MAP","geo":"us_state","fmt":"State choropleth","tbl":"ProQuest Stat Abstract 2026: Federal Government chapter — federal expenditures per state vs. federal tax collections per state","section":"Income","ext":["USASpending.gov (usaspending.gov - free API)","IRS: SOI Tax Stats (irs.gov - free)"],"vars":["federal_spending_per_dollar_tax_paid"],"join":["rep_pct","poverty_rate","median_household_income"],"sc":{"emotional":90,"relatability":80,"clarity":90,"surprise":80,"tension":100,"visual":90,"originality":60,"data_ready":90},"vs":0,"tags":"federal spending taxes state red state welfare Mississippi 2.57 New Jersey 0.74 fiscal geography opposite political rhetoric","notes":"","topics":["politics","inequality","economy","geography","history","data"],"status":"idea"},
{"id":"proq_health_insurance_uninsured_county","title":"Uninsured rate by county after 14 years of the ACA: who the healthcare law never reached","sub":"Despite the ACA reducing the uninsured rate from 16% to 8% nationally, 42 counties in Texas alone still have uninsured rates above 25%. States that refused Medicaid expansion have 2-3x the uninsured rate of expansion states. The healthcare coverage map is a Medicaid expansion map.","type":"MAP","geo":"us_county","fmt":"County choropleth","tbl":"ProQuest Stat Abstract 2026: Health/Nutrition chapter — uninsured rate by county 2024 (Census SAHIE data)","section":"Health","ext":["Census SAHIE (census.gov - free API)"],"vars":["uninsured_rate_county"],"join":["medicaid_expansion_state","poverty_rate","rep_pct_county"],"sc":{"emotional":80,"relatability":80,"clarity":80,"surprise":70,"tension":80,"visual":100,"originality":60,"data_ready":90},"vs":0,"tags":"uninsured rate county ACA 14 years Texas 25 percent Medicaid expansion refusal 2-3x Republican governed coverage map","notes":"","topics":["health","politics","inequality","poverty","geography","law"],"status":"idea"},
{"id":"proq_income_mobility_by_county","title":"Economic mobility by county: where you're born determines your outcome more than anywhere else in the rich world","sub":"A child born in the bottom quintile in Salt Lake City has a 11.5% chance of reaching the top quintile. The same child born in Atlanta has a 4.5% chance. The US has lower intergenerational mobility than Canada, Germany, Denmark, or Australia — and the variation within the US is enormous. Your zip code is your economic destiny.","type":"MAP","geo":"us_county","fmt":"County choropleth","tbl":"ProQuest Stat Abstract 2026: Income/Poverty chapter — Chetty et al. Opportunity Atlas: upward mobility rate by county","section":"Income","ext":["Opportunity Atlas (opportunityatlas.org - free)"],"vars":["upward_mobility_rate_county"],"join":["segregation_index","school_quality","social_capital_index","poverty_rate"],"sc":{"emotional":90,"relatability":90,"clarity":80,"surprise":80,"tension":80,"visual":100,"originality":60,"data_ready":90},"vs":0,"tags":"economic mobility county Salt Lake City 11.5 percent Atlanta 4.5 percent lower than Canada Germany Denmark zip code destiny","notes":"","topics":["inequality","poverty","education","geography","race","history"],"status":"idea"},
{"id":"proq_construction_housing_permits_vs_jobs","title":"Housing permits issued vs. construction job openings by state: the supply-demand mismatch in home building","sub":"States with the most housing demand (California, New York, Massachusetts) also have the highest construction job vacancy rates — meaning the workers needed to build the housing don't exist or can't afford to live where they're needed. The housing shortage is partly a construction labor shortage.","type":"XREF","geo":"us_state","fmt":"Scatter plot","tbl":"ProQuest Stat Abstract 2026: Construction/Housing chapter — housing permits by state + BLS construction job openings by state","section":"Housing","ext":["BLS: JOLTS (bls.gov - free)","Census: Building Permits (census.gov - free)"],"vars":["housing_permits_total","construction_job_vacancy_rate"],"join":["median_rent","construction_wage","immigration_rate"],"sc":{"emotional":70,"relatability":80,"clarity":80,"surprise":80,"tension":70,"visual":70,"originality":80,"data_ready":90},"vs":0,"tags":"housing permits construction jobs vacancy California New York Massachusetts workers can't afford supply demand mismatch labor shortage","notes":"","topics":["housing","labor","economy","inequality","geography","immigration"],"status":"idea"},
{"id":"proq_science_tech_patents_per_capita_state","title":"Patents issued per capita by state 2024: the innovation economy is even more concentrated than you think","sub":"California, Massachusetts, and Washington account for 38% of all US patents despite having 18% of the population. Mississippi patents at 1/20th the rate of Massachusetts. The innovation economy has a geography so extreme it barely qualifies as a national economy.","type":"MAP","geo":"us_state","fmt":"State choropleth","tbl":"ProQuest Stat Abstract 2026: Science/Technology chapter — USPTO patents issued by state of inventor 2024","section":"Science","ext":["USPTO: patent data (uspto.gov - free)"],"vars":["patents_per_capita_state"],"join":["rd_spending_per_capita","college_educated_pct","tech_sector_employment"],"sc":{"emotional":60,"relatability":70,"clarity":80,"surprise":80,"tension":60,"visual":80,"originality":70,"data_ready":90},"vs":0,"tags":"patents per capita state California Massachusetts Washington 38 percent 18 percent population Mississippi 1/20 innovation geography","notes":"","topics":["technology","science","inequality","economy","geography","education"],"status":"idea"},
{"id":"proq_foreign_aid_per_gdp_vs_peer_nations","title":"US foreign aid as % of GDP vs. peer nations: America is the world's stingiest major donor","sub":"US ODA at 0.22% of GNI — below the UN target of 0.7% and below every Scandinavian country. In absolute dollars the US leads. But as a share of national income the US ranks last among OECD donors. Americans believe they give 25% of the federal budget to foreign aid. The actual share is 1%.","type":"CHART","geo":"worldwide","fmt":"Bar chart","tbl":"ProQuest Stat Abstract 2026: Foreign Commerce chapter — ODA as % GNI by OECD donor country 2024","section":"Foreign Commerce","ext":["OECD: DAC ODA statistics (oecd.org - free)"],"vars":["oda_pct_gni_by_country"],"join":["gdp_per_capita","political_regime"],"sc":{"emotional":70,"relatability":80,"clarity":90,"surprise":90,"tension":70,"visual":80,"originality":60,"data_ready":90},"vs":0,"tags":"US foreign aid GDP peer nations 0.22 percent Sweden 0.96 UN target 0.7 Americans believe 25 percent actually 1","notes":"","topics":["international","politics","trade","history","data","inequality"],"status":"idea"},
{"id":"proq_energy_consumption_per_capita_state","title":"Energy consumption per capita by state: Louisiana uses 3x more than California and it shows","sub":"Louisiana at 900+ million BTU per capita — the highest in the nation. Massachusetts at 200 million BTU — the lowest. The gap is driven by industrial energy use, climate, and building stock age. Cold climate doesn't explain it — New England is cold and efficient.","type":"MAP","geo":"us_state","fmt":"State choropleth","tbl":"ProQuest Stat Abstract 2026: Energy chapter — EIA: total energy consumption per capita by state 2023","section":"Energy","ext":["EIA: State Energy Data System (eia.gov - free)"],"vars":["energy_consumption_per_capita_btu"],"join":["industrial_employment_pct","climate_zone","building_age_median"],"sc":{"emotional":60,"relatability":70,"clarity":80,"surprise":80,"tension":50,"visual":80,"originality":70,"data_ready":90},"vs":0,"tags":"energy consumption per capita Louisiana 900 BTU Massachusetts 200 BTU gap industrial climate building New England efficient","notes":"","topics":["energy","geography","environment","history","data","climate"],"status":"idea"},
{"id":"proq_banking_unbanked_underbanked_county","title":"Unbanked households by county: the geography of financial exclusion in a cashless world","sub":"4.5% of US households are unbanked. But some rural Mississippi and Native American reservation counties exceed 25% unbanked. As cash disappears and digital payments become mandatory, the unbanked face effective exclusion from the modern economy.","type":"MAP","geo":"us_county","fmt":"County choropleth","tbl":"ProQuest Stat Abstract 2026: Banking/Finance chapter — FDIC: unbanked rate by county 2023","section":"Banking","ext":["FDIC: Survey of Unbanked (fdic.gov - free)"],"vars":["unbanked_household_rate_county"],"join":["poverty_rate","race_demographics","rural_population_pct","bank_branch_density"],"sc":{"emotional":80,"relatability":70,"clarity":80,"surprise":80,"tension":70,"visual":90,"originality":70,"data_ready":90},"vs":0,"tags":"unbanked households county 4.5 percent national Mississippi Native American 25 percent cashless exclusion financial geography","notes":"","topics":["finance","poverty","race","geography","technology","inequality"],"status":"idea"},
{"id":"proq_incarceration_cost_per_inmate_state","title":"Annual cost to incarcerate one person by state: New York spends $400K, Alabama spends $22K","sub":"Annual per-inmate costs range from $22,000 in Alabama to $413,000 in New York City. The states that spend most on incarceration have the lowest recidivism rates. The states that spend least have the highest. The cheapest prison is also the most expensive prison.","type":"MAP","geo":"us_state","fmt":"State choropleth","tbl":"ProQuest Stat Abstract 2026: Law Enforcement chapter — Vera Institute: cost of incarceration by state 2024","section":"Law Enforcement","ext":["Vera Institute: Price of Prisons (vera.org - free)"],"vars":["annual_cost_per_inmate_state"],"join":["recidivism_rate","violent_crime_rate","poverty_rate","rep_pct"],"sc":{"emotional":80,"relatability":80,"clarity":90,"surprise":90,"tension":70,"visual":80,"originality":80,"data_ready":80},"vs":0,"tags":"incarceration cost per inmate Alabama 22K New York 413K lowest cost highest recidivism cheapest most expensive","notes":"","topics":["crime","inequality","law","economy","politics","history"],"status":"idea"},
]

for idea in ideas:
    idea['vs'] = vs(idea['sc'])
