import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCM01","How Much of Your Paycheck Disappears Before You See It: The Deduction Breakdown by State","Federal tax, state tax, FICA, health premium — whats left mapped by income and state","CHART","US-state","Bar chart","finance/labor","IRS: Tax tables (irs.gov); BLS: Benefits (bls.gov); KFF: Premiums (kff.org)",78,90,80,72,72,68,65,85),
mk("HCM02","What Your Grocery Cart Costs in Every Metro: The Basket Price Index","Same 40 items priced across 100 metros — the true cost of living in groceries","MAP","US-metro","Bar chart","food/prices","BLS: CPI food (bls.gov/cpi); USDA: Food prices (ers.usda.gov); Census: Regional (census.gov)",75,90,82,68,65,70,65,82),
mk("HCM03","Where Your Car Insurance Costs More Than Your Car Payment","Auto insurance premiums by state mapped against median car payment — the crossover states","MAP","US-state","Bivariate choropleth","transportation/prices","NAIC: Auto insurance (naic.org); Bankrate: Car payments (bankrate.com); Census: Income (census.gov)",72,88,78,72,68,72,68,78),
mk("HCM04","The Tipping Point: Where a $5 Tip Is Generous vs Where Its an Insult","Tipping expectations mapped by metro — adjusted for cost of living","CHART","US-metro","Bar chart","food/economy","Square: Tipping data; BLS: Food service wages (bls.gov); Census: Dining (census.gov)",62,88,68,68,55,65,72,65),
mk("HCM05","What a Single ER Visit Costs in Every State: The Medical Surprise Bill Map","Average ER cost for the same complaint mapped — $500 in one state, $5000 in another","MAP","US-state","State choropleth","health/prices","HCUP: ER costs (hcup-us.ahrq.gov); CMS: Claims data (cms.gov); KFF: Surprise billing (kff.org)",82,88,78,78,78,72,68,78),
mk("HCM06","Where Childcare Costs More Than College Tuition: The Family Budget Breaker","Annual daycare vs annual in-state tuition by state — daycare wins in 28 states","CHART","US-state","Bar chart","children/prices","ChildCare Aware: Costs (childcareaware.org); College Board: Tuition (collegeboard.org); Census: Income (census.gov)",82,88,80,78,78,68,68,82),
mk("HCM07","How Far Your Dollar Goes: Purchasing Power Parity Across US Metros","$100K salary purchasing power mapped — $100K in SF is $55K in Mississippi","MAP","US-metro","Bar chart","economy/geography","BEA: RPP (bea.gov/data/prices-inflation/regional); Census: Income (census.gov); BLS: CPI (bls.gov)",78,88,80,72,65,72,65,85),
mk("HCM08","Where Your Uber Surge Pricing Reveals Real Transportation Deserts","Ride-share surge frequency mapped against transit availability — when you have no options, you pay more","MAP","US-metro","Dot map","transportation/inequality","Uber: Movement data; NTD: Transit (transit.dot.gov); Census: Commute (census.gov)",72,82,65,72,65,72,78,58),
mk("HCM09","The Subscription Trap: How Much Americans Spend Monthly on Services They Forgot About","Average subscription spending by income and age group mapped — $200+/month for most","CHART","US","Bar chart","finance/technology","Federal Reserve: Consumer spending; BLS: CEx (bls.gov/cex); West Monroe: Survey data",68,88,72,72,58,65,72,62),
mk("HCM10","Where Your Pizza Costs What Your Grandparents Paid for a Week of Groceries","Food price inflation animated 1970-2025 — the same meals across 55 years of prices","CHART","US","Line chart","food/history","BLS: CPI food (bls.gov/cpi); USDA: Food prices (ers.usda.gov); Census: Income (census.gov)",78,88,78,75,72,68,72,82),
mk("HCM11","The Parking Tax: What You Actually Pay Per Year to Store Your Car","Total parking costs including property tax subsidy by metro — $5K-$15K per car per year","CHART","US-metro","Bar chart","transportation/prices","Parking Today: Rate survey; Census: Housing (census.gov); BLS: CPI (bls.gov)",72,85,72,78,65,68,78,65),
mk("HCM12","Where Your Electricity Bill Will Double by 2030: Grid Upgrade Cost Projections","Projected rate increases by utility mapped against current costs — the coming shock","MAP","US-state","State choropleth","energy/prices","EIA: Rate projections (eia.gov); FERC: Rate cases (ferc.gov); DOE: Grid costs (energy.gov)",78,85,72,78,78,72,68,72),
mk("HCM13","How Much Free Time You Actually Have: Hours Per Week After Work, Sleep, Commute, and Chores","Discretionary time by state accounting for all obligations — some states get 3 hours/day","CHART","US-state","Bar chart","labor/health","BLS: ATUS (bls.gov/tus); Census: Commute (census.gov); Gallup: Wellbeing (gallup.com)",75,88,72,72,68,68,72,72),
mk("HCM14","The Wedding Industrial Complex Mapped: What Marriages Cost by Metro","Average wedding cost mapped against local median income — 5 months salary in some metros","MAP","US-metro","Bar chart","finance/geography","The Knot: Wedding cost survey; Census: Income (census.gov); BLS: CPI (bls.gov)",65,82,72,68,55,68,68,68),
mk("HCM15","Where Your Water Bill Tripled: Municipal Water Rate Increases Since 2010","Cities with the steepest water cost increases mapped against pipe replacement needs","MAP","US-metro","Bar chart","infrastructure/prices","Circle of Blue: Water rates (circleofblue.org); EPA: Water infrastructure (epa.gov); AWWA: Rates (awwa.org)",78,82,75,72,72,72,68,78),
mk("HCM16","What $1 Million Buys in Every US City: The Million-Dollar Home Map","The house you get for $1M in SF vs Memphis vs Boise — the visual absurdity","MAP","US-metro","Special map","housing/prices","Zillow: Listings (zillow.com); Redfin: Data (redfin.com); Census: Housing (census.gov)",72,85,72,72,62,78,70,72),
mk("HCM17","The Hidden Fee Economy: What Average Americans Pay in Junk Fees Per Year","Bank fees, late fees, service fees, convenience fees — the $3,500/year fee tax mapped","CHART","US","Bar chart","finance/inequality","CFPB: Fee data (consumerfinance.gov); Federal Reserve: Consumer (federalreserve.gov); Pew: Banking (pewresearch.org)",78,88,72,78,72,68,72,72),
mk("HCM18","Where College ROI Goes Negative: Degrees That Leave You Poorer Than No Degree","Negative-ROI degree programs mapped by institution — the education debt trap","MAP","US","Dot map","education/finance","DOE: College Scorecard (collegescorecard.ed.gov); Georgetown: CEW (cew.georgetown.edu); Federal Reserve: Student loans (newyorkfed.org)",80,85,78,80,78,72,72,78),
mk("HCM19","The Noise Pollution Map: Where Americas Cities Are Too Loud to Think","Decibel levels mapped at neighborhood level against property values and health","MAP","US-metro","Dot map","health/housing","NPS: Sound maps (nps.gov); BTS: Noise exposure (bts.gov); Census: Housing (census.gov)",68,78,65,72,62,78,78,65),
mk("HCM20","What Retirement Actually Costs in Every State: The Savings Gap Map","Required retirement savings vs actual median savings by state — the shortfall mapped","MAP","US-state","Bivariate choropleth","finance/geography","Federal Reserve: SCF (federalreserve.gov); BLS: CPI regional (bls.gov); Census: Income (census.gov)",80,85,78,72,78,72,65,78),
mk("HCM21","The Dating Geography of America: Where Singles Cluster and Where They Dont","Single adult ratios by metro mapped against median age and dating app usage","MAP","US-metro","Bar chart","population/geography","Census: Marital status (census.gov/acs); Pew: Online dating (pewresearch.org)",62,82,68,68,52,68,68,78),
mk("HCM22","Where Your Amazon Prime Delivery Takes 3 Days Instead of 1: The Fulfillment Gap","Same-day vs multi-day delivery zones mapped against population density","MAP","US","Special map","economy/rural","MWPVL: Amazon logistics (mwpvl.com); Census: Population density (census.gov)",62,80,68,68,55,75,72,65),
mk("HCM23","The Pet Economy Map: What Americans Spend on Their Animals by Metro","Annual pet spending per household mapped — some metros average $3K+ per year","CHART","US-metro","Bar chart","economy/geography","APPA: Pet spending (americanpetproducts.org); BLS: CEx (bls.gov/cex); Census: Households (census.gov)",58,80,68,65,50,65,68,68),
mk("HCM24","Where Your Phone Plan Costs Double: Cell Service Pricing by Rural vs Urban","Same carrier, same plan, different experience — coverage quality mapped against price","MAP","US","Bivariate choropleth","technology/rural","FCC: Mobile coverage (fcc.gov); Consumer Reports: Cell service; Ookla: Speed (opensignal.com)",70,82,72,68,65,72,68,68),
mk("HCM25","The Student Loan Payment Map: Average Monthly Payment vs Average Monthly Rent by State","For millions, student loans ARE a second rent payment — the double burden mapped","MAP","US-state","Bivariate choropleth","education/housing","Federal Reserve: Student loans (newyorkfed.org); Census: Rent (census.gov/acs); DOE: Scorecard (collegescorecard.ed.gov)",82,88,78,75,78,72,65,80),
mk("HCM26","What a Funeral Costs in Every State: The Death Economy Mapped","Average funeral and burial costs mapped — $7K-$15K range, plus the hidden fees","MAP","US-state","State choropleth","economy/geography","NFDA: Funeral costs (nfda.org); FTC: Funeral rule (ftc.gov); BLS: CPI funerals (bls.gov)",72,78,72,72,62,68,72,72),
mk("HCM27","The Invisible Tax of Being Poor: Extra Costs Low-Income Households Pay for Everything","Check cashing fees, laundromat costs, no-bulk-buying penalty — the poverty premium mapped","CHART","US","Bar chart","poverty/inequality","Brookings: Poverty premium (brookings.edu); CFPB: Consumer data (consumerfinance.gov); Census: Income (census.gov)",85,85,75,80,78,68,72,72),
mk("HCM28","Where Daylight Saving Time Costs You Sleep: The Health Impact by Time Zone Position","Counties on the western edge of time zones permanently jet-lagged — mapped against health","XREF","US-county","Bivariate choropleth","health/geography","CDC: BRFSS sleep (cdc.gov/brfss); Census: Time zones; AASM: Sleep research (aasm.org)",65,78,60,80,58,72,82,60),
mk("HCM29","The Gig Economy Map: Where Side Hustles Are Survival Not Choice","Gig worker concentration mapped against cost of living — necessity-driven gig work zones","MAP","US-metro","Bivariate choropleth","labor/poverty","Census: Nonemployer statistics (census.gov); BLS: Contingent workers (bls.gov); IRS: 1099 data (irs.gov)",78,82,72,72,72,72,72,68),
mk("HCM30","What Your Commute Really Costs: Gas + Wear + Time + Health per Year by Metro","Total commute cost including health impact priced out by metro area — $10K-$25K/year","CHART","US-metro","Bar chart","transportation/economy","AAA: Driving costs (aaa.com); Census: Commute (census.gov/acs); BLS: CPI (bls.gov)",78,88,75,72,68,68,72,72),
mk("HCM31","Where Tipping Culture Has Gone Insane: Tip Screen Requests vs Service Quality","Tip prompt frequency by business type mapped against customer satisfaction","CHART","US","Bar chart","economy/psychology","Square: Payment data; BLS: Food service (bls.gov); Bankrate: Tipping survey (bankrate.com)",65,85,65,72,60,65,75,58),
mk("HCM32","The Property Tax Shock Map: Where Assessments Jumped 30%+ in One Year","Rapid reassessment counties mapped against home price changes — the tax surprise","MAP","US-county","County choropleth","housing/finance","Census: Property tax (census.gov); Lincoln Institute: Property tax (lincolninst.edu); ATTOM: Tax data (attomdata.com)",78,82,75,72,72,75,68,75),
mk("HCM33","Where Americas Busiest Emergency Rooms Have the Longest Waits","ER wait times by hospital mapped against community uninsurance rates — the correlation","MAP","US-metro","Dot map","health/infrastructure","CMS: Hospital compare (cms.gov); CDC: NHAMCS (cdc.gov/nchs); Census: Insurance (census.gov)",78,82,72,72,72,72,65,78),
mk("HCM34","The Monthly Budget Squeeze: How Average Household Spending Changed 2019 to 2025","Every budget category change mapped — where the inflation squeeze hurts most","CHART","US","Bar chart","economy/prices","BLS: CEx (bls.gov/cex); BLS: CPI (bls.gov/cpi); Federal Reserve: Consumer (federalreserve.gov)",78,90,78,72,72,68,62,82),
mk("HCM35","Where Your Health Insurance Deductible Exceeds Your Savings: The Medical Bankruptcy Setup","High-deductible plan enrollment mapped against household savings — the gap is catastrophic","MAP","US-state","Bivariate choropleth","health/finance","KFF: Employer benefits (kff.org); Federal Reserve: SCF (federalreserve.gov); Census: Insurance (census.gov)",85,88,78,78,80,72,68,78),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCM ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCM batch)")
