import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCA01","Where NRA Money Goes: Every Congressional District Ranked by Gun Lobby Donations","Donations per representative mapped against gun legislation voting records","MAP","US-state","State choropleth","guns/politics","OpenSecrets: NRA contributions (opensecrets.org); GovTrack: Voting records (govtrack.us); FEC: Campaign finance (fec.gov)",82,72,78,78,82,78,72,82),
mk("HCA02","The Bail Industry Mapped: Private Bail Bond Revenue by State","States that banned commercial bail vs those where its a billion-dollar industry","MAP","US-state","State choropleth","law/finance","Census: Government finance (census.gov); DOJ: Pretrial data (bja.ojp.gov); Insurance Dept: Bail bond data",80,72,72,78,80,75,78,68),
mk("HCA03","Where Pharmaceutical Companies Spend More on Marketing Than Research","Drug company marketing-to-R&D ratios mapped against prescription rates by state","CHART","US-state","Scatter plot","drugs/finance","SEC: Pharma filings (sec.gov); CMS: Prescription data (cms.gov); Statista: Pharma marketing (statista.com)",80,78,75,80,78,68,75,72),
mk("HCA04","The Psychology of Scarcity: How Growing Up Poor Changes Brain Architecture","fMRI studies mapped against childhood poverty rates — the neuroscience of inequality","CHART","US","Scatter plot","psychology/poverty","NIH: Neuroscience research (nih.gov); Census: Child poverty (census.gov); APA: Research (apa.org)",82,78,62,85,75,65,85,55),
mk("HCA05","Every Dollar Middle Eastern Sovereign Wealth Funds Have Invested in America","Saudi, UAE, Qatari, Kuwaiti investments in US real estate, tech, and sports — mapped","MAP","US-metro","Dot map","middle_east/finance","SWFI: Sovereign wealth (swfinstitute.org); SEC: 13F filings (sec.gov); Real Capital Analytics (rcanalytics.com)",78,68,72,80,78,78,80,68),
mk("HCA06","The Manufacturing Subsidy Race: What States Pay Per Factory Job to Lure Companies","Tax incentives per job created by state — some paying $500K+ per position","CHART","US-state","Bar chart","manufacturing/finance","Good Jobs First: Subsidy tracker (goodjobsfirst.org); BLS: Manufacturing jobs (bls.gov)",78,72,78,80,78,70,75,75),
mk("HCA07","Rural Americas Hidden Wealth: Natural Resource Extraction Revenue That Leaves Town","Oil, gas, timber, and mining revenue by county vs what stays in the local economy","MAP","US-county","Bivariate choropleth","rural/economy","BLM: Revenue data (blm.gov); Census: County income (census.gov); EIA: Production (eia.gov)",80,72,72,78,78,78,78,72),
mk("HCA08","Where Your Sports Betting Losses Go: The Gambling Revenue Flow","Tax revenue from sports gambling by state — who benefits and who doesnt","MAP","US-state","State choropleth","sports/finance","AGA: Gaming revenue (americangaming.org); Tax Foundation: Gaming taxes (taxfoundation.org); NASPL: Data (naspl.org)",72,80,75,70,68,72,70,78),
mk("HCA09","The Entertainment Industrys Political Donations: Hollywood vs Silicon Valley vs Wall Street","Campaign contributions by industry and party mapped over 30 years","CHART","US","Area chart","entertainment/politics","OpenSecrets: Industry contributions (opensecrets.org); FEC: Data (fec.gov)",70,68,72,72,68,68,72,80),
mk("HCA10","Where Democracy Costs the Most Per Vote: Election Spending Per Registered Voter","Campaign spending per voter by state — some states 10x more expensive than others","MAP","US-state","State choropleth","democracy/finance","FEC: Campaign finance (fec.gov); Census: Voter registration (census.gov); OpenSecrets: Spending (opensecrets.org)",75,75,78,75,72,75,72,82),
mk("HCA11","The Demographic Dividend: Countries Where Young Populations Drive Economic Growth","Youth bulge + education investment = GDP growth — the formula mapped globally","MAP","World","World choropleth","demographics/economy","UN Population: Age structure (population.un.org); World Bank: GDP growth (worldbank.org); UNESCO: Education (uis.unesco.org)",72,65,72,75,68,78,72,82),
mk("HCA12","Where Drug Companies Test Their Products: Clinical Trial Sites vs Population Diversity","Trial locations mapped against demographic representation — who gets studied","MAP","US-county","Dot map","drugs/demographics","ClinicalTrials.gov: Trial data (clinicaltrials.gov); Census: Demographics (census.gov); FDA: Diversity data (fda.gov)",78,72,68,80,75,75,80,72),
mk("HCA13","The Psychology of Charitable Giving: Which States Give the Most Per Dollar of Income","Low-income states give a higher percentage — but to different causes than wealthy states","CHART","US-state","Scatter plot","psychology/finance","IRS: SOI charitable (irs.gov/statistics); Giving USA: Philanthropy (givingusa.org); Census: Income (census.gov)",72,78,72,80,65,68,75,80),
mk("HCA14","Every Gun Manufacturer in America: Where They Are and Where Their Products End Up","Production facilities mapped with flow lines to crime gun recovery locations","MAP","US","Line map","guns/manufacturing","ATF: Manufacturing data (atf.gov); ATF: Trace data (atf.gov); BLS: Employment (bls.gov)",78,68,72,78,78,82,78,78),
mk("HCA15","The Rural Banking Desert: Counties That Lost Their Last Bank Branch","Bank branch closures mapped against payday lender proliferation","MAP","US-county","Bivariate choropleth","rural/finance","FDIC: Branch data (fdic.gov); CFPB: Payday lending (consumerfinance.gov); Census: Demographics (census.gov)",82,78,72,78,78,78,75,78),
mk("HCA16","Where Law Firms Make More Than Hospitals: Legal Industry Revenue by Metro","Legal services GDP per capita mapped — NYC, DC, and Delaware dominate","MAP","US-metro","Bar chart","law/economy","BEA: GDP by industry (bea.gov); Census: CBP (census.gov); BLS: OES legal (bls.gov/oes)",68,65,72,72,60,68,72,78),
mk("HCA17","The Middle East Tech Boom: Startup Funding That Nobody Covers","VC investment in MENA startups 2015-2025 — the growth curve rivals Southeast Asia","CHART","Middle East","Line chart","middle_east/technology","MAGNiTT: MENA VC data (magnitt.com); Crunchbase: Funding (crunchbase.com); World Bank: Tech indicators (worldbank.org)",68,58,70,82,62,68,80,72),
mk("HCA18","The Sports Gender Pay Gap by Country: Women Athletes Earnings as % of Mens","FIFA, tennis, basketball, soccer — some countries closing the gap, most arent","CHART","World","Bar chart","sports/gender","Forbes: Athlete pay (forbes.com); FIFA: Prize money (fifa.com); IOC: Revenue sharing (olympics.com)",78,75,78,72,75,68,70,72),
mk("HCA19","Where Entertainment Workers Cant Afford to Live Where They Work","Housing cost burden for arts/entertainment employees by metro — LA and NYC are impossible","MAP","US-metro","Scatter plot","entertainment/housing","BLS: OES (bls.gov/oes); Zillow: Housing costs (zillow.com); Census: ACS (census.gov/acs)",78,82,72,72,72,68,72,72),
mk("HCA20","The Manufacturing Tax Break That Costs More Than It Creates","State-by-state analysis of manufacturing incentives vs actual revenue generated","CHART","US-state","Bar chart","manufacturing/economy","Good Jobs First: Subsidies (goodjobsfirst.org); Census: ASM (census.gov); Tax Foundation: Revenue (taxfoundation.org)",78,72,78,78,75,68,75,72),
mk("HCA21","Where Gun Violence Costs Taxpayers the Most: The Emergency Room Bill","Firearm injury treatment costs by state — taxpayers fund 75% through Medicaid","CHART","US-state","Bar chart","guns/health","HCUP: Hospital costs (hcup-us.ahrq.gov); CMS: Medicaid data (cms.gov); Everytown: Cost data (everytownresearch.org)",82,78,78,78,80,68,72,75),
mk("HCA22","The Psychology of Housing: How Your Neighborhood Design Affects Your Mental Health","Walkability scores correlated with depression and anxiety rates by metro","XREF","US-metro","Scatter plot","psychology/housing","Walk Score: Walkability (walkscore.com); CDC: PLACES mental health (cdc.gov/places); Census: ACS (census.gov)",72,80,65,78,62,68,80,68),
mk("HCA23","Every US Law That Treats Corporations as People — Timeline and Impact","Citizens United, Santa Clara County, Hobby Lobby — the legal evolution mapped against spending","CHART","US","Line chart","law/democracy","Supreme Court: Decisions (supremecourt.gov); OpenSecrets: Corporate spending (opensecrets.org); FEC: Data (fec.gov)",78,72,72,78,80,68,78,72),
mk("HCA24","The Demographics of Who Serves: Military Enlistment by County Income and Race","Recruiting draws disproportionately from low-income rural counties — mapped","MAP","US-county","Bivariate choropleth","demographics/military","DOD: Recruiting data (defense.gov); Census: Income (census.gov); Demographics (census.gov)",80,72,75,75,78,78,72,75),
mk("HCA25","Where Drug Overdoses Peak: Time of Day, Day of Week, Month by State","Temporal patterns in overdose deaths — the data shows when intervention windows exist","CHART","US-state","Area chart","drugs/health","CDC: WONDER (wonder.cdc.gov); SAMHSA: Treatment data (samhsa.gov); EMS: Response data (nemsis.org)",78,72,72,75,78,70,72,75),
mk("HCA26","The Rural Digital Divide Costs: Economic Output Lost to Bad Internet","GDP foregone per capita in counties with sub-25mbps broadband — the opportunity cost mapped","MAP","US-county","County choropleth","rural/technology","FCC: Broadband (fcc.gov/broadbandmap); BEA: County GDP (bea.gov); Census: Business (census.gov)",78,78,72,75,72,78,75,70),
mk("HCA27","Middle East Religious Diversity: The Map Most Westerners Have Never Seen","Sunni, Shia, Christian, Druze, Yazidi, Jewish populations at sub-national level","MAP","Middle East","Special map","middle_east/religion","Pew: Religious composition (pewresearch.org); CIA: World Factbook (cia.gov); Joshua Project: People groups (joshuaproject.net)",70,62,72,80,68,85,78,72),
mk("HCA28","The Sports Industrial Complex: How Much Each State Spends on High School Athletics","Per-student athletic spending mapped against academic spending — priorities revealed","CHART","US-state","Scatter plot","sports/education","NFHS: Participation (nfhs.org); NCES: Per-pupil spending (nces.ed.gov); State athletics associations",75,78,72,75,72,68,72,68),
mk("HCA29","Where Psychological Therapy Is a Luxury: Therapist Density by County Income","Wealthy counties have 8x more therapists per capita than poor counties","MAP","US-county","Bivariate choropleth","psychology/poverty","HRSA: Provider data (hrsa.gov); SAMHSA: Treatment locator (samhsa.gov); Census: Income (census.gov/acs)",82,80,72,78,78,78,72,72),
mk("HCA30","The Gun Industrys Economic Footprint: Jobs, Revenue, and Political Influence by State","NSSF economic impact data mapped against lobbying spending and legislation","MAP","US-state","State choropleth","guns/economy","NSSF: Industry stats (nssf.org); OpenSecrets: Lobbying (opensecrets.org); BLS: Employment (bls.gov)",72,68,75,72,70,75,70,78),
mk("HCA31","The Law of Consequences: States That Legalized Weed and What Happened to Alcohol Sales","Cannabis legalization mapped against alcohol consumption changes — substitution effect is real","CHART","US-state","Scatter plot","drugs/economy","NIAAA: Alcohol sales (niaaa.nih.gov); Tax Foundation: Cannabis revenue (taxfoundation.org); BLS: Beverage sales (bls.gov)",72,78,72,80,68,68,78,72),
mk("HCA32","Where Entertainment Replaces Manufacturing: Counties That Pivoted to Tourism Economies","Former factory towns that became tourist destinations — economic transformation mapped","MAP","US-county","Dot map","entertainment/manufacturing","BEA: Industry GDP (bea.gov); BLS: Sector employment (bls.gov); Census: CBP (census.gov)",72,72,68,75,65,72,78,70),
mk("HCA33","The Democracy Deserts: Counties Where Only One Party Fields Candidates","Places where the election is effectively decided in the primary — mapped","MAP","US-county","County choropleth","democracy/politics","Ballotpedia: Candidate data (ballotpedia.org); MIT: Elections (electionlab.mit.edu)",78,72,75,72,75,78,72,72),
mk("HCA34","The Demographics of Who Homeschools and Why the Reasons Are Changing","Homeschool rates by state mapped against religious affiliation and school quality","MAP","US-state","Bivariate choropleth","demographics/education","NCES: Homeschool data (nces.ed.gov); Census: Education (census.gov/acs); NHERI: Research (nheri.org)",70,75,68,75,65,72,72,68),
mk("HCA35","The Manufacturing Comeback Nobody Noticed: Battery and EV Factory Boom by County","IRA-funded manufacturing investments mapped — $200B in new factories since 2022","MAP","US-county","Dot map","manufacturing/energy","DOE: Clean energy investments (energy.gov); BLS: Manufacturing (bls.gov); White House: Investing in America (whitehouse.gov)",78,72,78,78,72,80,72,78),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCA ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCA batch)")
