# BATCH_BL.py
ideas = [
  {'id': 'obesity_rate_county_map', 'title': "Adult obesity rate by county 2023 — the geography of America's largest chronic illness", 'sub': 'Humphreys County, MS: 53% obese. Summit County, CO: 13%. The 40-point gap follows the same geography as poverty, food access, and walkability.', 'type': 'MAP', 'geo': 'us_county', 'fmt': 'County choropleth', 'tbl': 'CDC PLACES: Adult obesity prevalence by county (cdc.gov/places)', 'section': 'Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['obesity_rate_county'], 'join': ['poverty_rate_county', 'nearest_grocery_miles', 'pedestrian_fatality_rate', 'food_insecurity_rate'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 90, 'surprise': 70, 'tension': 70, 'visual': 100, 'data_ready': 80, 'originality': 60}, 'vs': 82, 'tags': 'adult obesity county Humphreys Mississippi 53 Summit Colorado 13 40 point gap poverty food access walkability', 'notes': '', 'topics': ['health', 'food', 'poverty', 'inequality', 'transportation', 'geography'], 'status': 'idea'},
  {'id': 'xref_food_desert_obesity', 'title': 'Food desert prevalence vs. obesity rate by county — the access-outcome link', 'sub': 'Counties with the lowest supermarket access have obesity rates 8-12 points higher. You cannot eat your way to health from a Dollar General.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'USDA ERS Food Access Research Atlas + CDC PLACES: Obesity by county', 'section': 'Health  -  Agriculture', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['food_desert_share_county', 'obesity_rate_county'], 'join': ['poverty_rate_county', 'median_household_income', 'dollar_general_per_10k'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 80, 'surprise': 70, 'tension': 80, 'visual': 90, 'data_ready': 80, 'originality': 70}, 'vs': 79, 'tags': 'food desert obesity county access outcome 8-12 points higher supermarket cannot eat health Dollar General XREF', 'notes': '', 'topics': ['health', 'food', 'poverty', 'inequality', 'agriculture'], 'status': 'idea'},
  {'id': 'cancer_rate_industrial_county', 'title': 'Cancer incidence rate near petrochemical facilities by county — Cancer Alley and beyond', 'sub': 'St. John the Baptist Parish, LA: cancer rate 800% higher than the national average. The EPA map of industrial cancer clusters that overlaps perfectly with race and poverty.', 'type': 'MAP', 'geo': 'us_county', 'fmt': 'County choropleth', 'tbl': 'CDC Cancer Statistics + EPA: Toxics Release Inventory facility locations (cdc.gov + epa.gov)', 'section': 'Health  -  Energy', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['cancer_incidence_rate_county', 'toxic_release_nearby'], 'join': ['pct_black_county', 'poverty_rate_county', 'rep_pct_county'], 'sc': {'emotional': 100, 'relatability': 70, 'clarity': 80, 'surprise': 90, 'tension': 100, 'visual': 100, 'data_ready': 70, 'originality': 90}, 'vs': 87, 'tags': 'cancer incidence petrochemical facility Louisiana 800 percent higher Cancer Alley EPA race poverty cluster map', 'notes': '', 'topics': ['health', 'environment', 'race', 'inequality', 'energy', 'poverty'], 'status': 'idea'},
  {'id': 'xref_healthcare_access_mortality', 'title': 'Hospital beds per capita vs. preventable mortality rate by county', 'sub': 'Counties with fewer hospital beds per resident have dramatically higher rates of preventable death — death from conditions that are survivable with timely care.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'AHA: Hospital beds by county + CDC Wonder: Preventable mortality by county', 'section': 'Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['hospital_beds_per_capita_county', 'preventable_mortality_rate_county'], 'join': ['poverty_rate_county', 'rural_population_pct', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 70, 'tension': 90, 'visual': 90, 'data_ready': 70, 'originality': 70}, 'vs': 81, 'tags': 'hospital beds preventable mortality county fewer beds higher preventable death survivable timely care access XREF', 'notes': '', 'topics': ['health', 'rural', 'poverty', 'inequality', 'infrastructure'], 'status': 'idea'},
  {'id': 'xref_air_quality_race', 'title': 'Air pollution exposure vs. race by county — who breathes the dirty air', 'sub': 'Black and Hispanic Americans are exposed to 25-40% higher concentrations of particulate matter than white Americans — even controlling for income. The pollution lines run along racial, not economic, geography.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'EPA AQS + EJScreen: Air quality index by county + ACS: Race composition by county', 'section': 'Health  -  Geography', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['pm25_annual_avg_county', 'pct_nonwhite_county'], 'join': ['poverty_rate_county', 'industrial_facility_count', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 70, 'clarity': 70, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 80}, 'vs': 80, 'tags': 'air pollution race county Black Hispanic 25-40 percent higher particulate matter race not income geography dirty air XREF', 'notes': '', 'topics': ['health', 'race', 'environment', 'inequality', 'poverty'], 'status': 'idea'},
  {'id': 'mental_health_provider_shortage_map', 'title': 'Mental health provider shortage areas by county — where help is unavailable', 'sub': 'More than 160 million Americans live in a Mental Health Professional Shortage Area. The map looks exactly like the opioid crisis map. The cause and the treatment are both missing.', 'type': 'MAP', 'geo': 'us_county', 'fmt': 'County choropleth', 'tbl': 'HRSA Health Professional Shortage Areas: Mental health by county (hrsa.gov/shortage-areas)', 'section': 'Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['mental_health_shortage_area_score', 'mental_health_providers_per_100k'], 'join': ['opioid_death_rate_county', 'suicide_rate_county', 'poverty_rate_county'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 80, 'tension': 90, 'visual': 100, 'data_ready': 90, 'originality': 70}, 'vs': 84, 'tags': 'mental health provider shortage 160 million Americans shortage area map same as opioid crisis cause treatment missing', 'notes': '', 'topics': ['health', 'drugs', 'poverty', 'rural', 'inequality', 'infrastructure'], 'status': 'idea'},
  {'id': 'xref_fast_food_density_health', 'title': 'Fast food restaurant density vs. chronic disease rate by county', 'sub': 'Counties in the top quintile of fast food density have diabetes rates 4 points higher, hypertension 6 points higher. The food environment predicts health outcomes across ZIP codes.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'USDA ERS Food Environment Atlas: Fast food density by county + CDC PLACES: Chronic disease by county', 'section': 'Health  -  Agriculture', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['fast_food_restaurants_per_10k', 'chronic_disease_rate_county'], 'join': ['obesity_rate_county', 'poverty_rate_county', 'nearest_grocery_miles'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 80, 'surprise': 80, 'tension': 70, 'visual': 90, 'data_ready': 80, 'originality': 70}, 'vs': 81, 'tags': 'fast food density chronic disease county diabetes hypertension 4 6 points higher food environment predicts outcomes XREF', 'notes': '', 'topics': ['health', 'food', 'poverty', 'inequality', 'geography'], 'status': 'idea'},
  {'id': 'xref_insurance_type_health_outcome', 'title': 'Medicaid vs. private insurance vs. uninsured — health outcomes by coverage type and state', 'sub': 'Uninsured adults are 40% more likely to die from preventable causes than privately insured adults in the same income bracket. But Medicaid expansion cut this gap by half in expansion states.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'CDC Behavioral Risk Factor Survey + SHADAC: Health outcomes by insurance type and state', 'section': 'Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['uninsured_rate', 'medicaid_coverage_rate', 'preventable_mortality_rate'], 'join': ['medicaid_expansion_status', 'poverty_rate_state', 'rep_pct'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 70, 'surprise': 80, 'tension': 90, 'visual': 80, 'data_ready': 70, 'originality': 80}, 'vs': 80, 'tags': 'Medicaid private insurance uninsured health outcomes 40 percent more likely die preventable expansion cut gap half XREF', 'notes': '', 'topics': ['health', 'poverty', 'politics', 'inequality', 'race'], 'status': 'idea'},
  {'id': 'heart_disease_map_county', 'title': 'Heart disease mortality rate by county — the geographic heart of the American health crisis', 'sub': 'The Mississippi Delta and Appalachia have heart disease mortality rates 3x the national average. The map overlaps almost perfectly with poverty, food deserts, and healthcare access gaps.', 'type': 'MAP', 'geo': 'us_county', 'fmt': 'County choropleth', 'tbl': 'CDC WONDER: Heart disease mortality by county (wonder.cdc.gov)', 'section': 'Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['heart_disease_mortality_county'], 'join': ['obesity_rate_county', 'diabetes_prevalence_county', 'food_insecurity_rate', 'poverty_rate_county'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 70, 'tension': 80, 'visual': 100, 'data_ready': 90, 'originality': 60}, 'vs': 83, 'tags': 'heart disease mortality county Mississippi Delta Appalachia 3x national poverty food desert healthcare access overlap', 'notes': '', 'topics': ['health', 'poverty', 'food', 'inequality', 'race', 'geography'], 'status': 'idea'},
  {'id': 'xref_walkability_health_outcomes', 'title': 'Walk Score vs. health outcomes by city — walkable cities have healthier residents', 'sub': "Cities in the top quartile of walkability have obesity rates 8 points lower and diabetes rates 4 points lower. Walking isn't optional in these cities — it's built in. The architecture is the intervention.", 'type': 'XREF', 'geo': 'us_city', 'fmt': 'Scatter plot', 'tbl': 'Walk Score: Walkability index by city + CDC PLACES: Chronic disease by city', 'section': 'Health  -  Transportation', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['walk_score_city', 'obesity_rate_city', 'diabetes_rate_city'], 'join': ['transit_ridership', 'median_household_income', 'population_density'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 80, 'surprise': 80, 'tension': 60, 'visual': 90, 'data_ready': 70, 'originality': 80}, 'vs': 80, 'tags': 'walkability health outcomes city Walk Score obesity 8 points diabetes 4 points lower architecture is intervention XREF', 'notes': '', 'topics': ['health', 'transportation', 'infrastructure', 'food', 'inequality', 'geography'], 'status': 'idea'},
]

def vscore(sc):
    return int((sc.get("emotional",0)*2 + sc.get("relatability",0)*2 + sc.get("clarity",0)*2 +
               sc.get("surprise",0)*1.5 + sc.get("tension",0)*1 + sc.get("visual",0)*1 +
               sc.get("data_ready",0)*0.5 + sc.get("originality",0)*0.5) / 10.5)

for idea in ideas:
    idea["vs"] = vscore(idea["sc"])

if __name__ == "__main__":
    print(f"BATCH_BL: {len(ideas)} ideas")
    for i in sorted(ideas, key=lambda x: -x["vs"]):
        print(f"  vs={i["vs"]:3d}  {i["id"]}")
