"""
BATCH_I.py - Run after Batch H
Focus: ProQuest Income/Poverty PDF tables not yet touched,
       novel economic geography, wealth distribution maps,
       and ideas at the intersection of multiple ProQuest sections.

Formula check every vs:
  emotional*2.5 + relatability*2.0 + surprise*1.5 + tension*1.5 + visual*1.0 + data_ready*1.0 + originality*0.5

Run: python BATCH_I.py && python maintain.py && git add . && git commit -m "Batch I: 20 ideas from ProQuest Income/Poverty deeper + novel economic geography" && git push
"""

with open('data.js', 'r', encoding='utf-8') as f:
    c = f.read()
end_idx = c.rfind('\n]; // end D')
c = c[:end_idx]
with open('data.js', 'w', encoding='utf-8') as f:
    f.write(c)
print('Stripped. Appending Batch I...')

ideas = r"""
,{id:"median_household_income_by_county_2024",title:"Median household income by county 2024 - the full income geography of America",sub:"Loudoun County VA: $160K median household income. Teton County WY: $115K. Holmes County MS: $26K. Owsley County KY: $24K. The income map of 3,100 counties shows a country with more internal inequality than most nations have total.",type:"MAP",geo:"us_county",fmt:"County choropleth",tbl:"T727 Income Poverty PDF + ACS",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)"],vars:["median_household_income","pct_under_25k"],join:["pct_on_snap","state_unemployment_rate","rural_population_pct"],sc:{emotional:7,relatability:9,surprise:7,tension:6,visual:10,data_ready:10,originality:4},vs:77,tags:"median household income county 2024 Loudoun VA $160K Teton WY $115K Holmes MS $26K Owsley KY $24K internal inequality 3100 counties"}
,{id:"poverty_rate_by_county_map",title:"Poverty rate by county 2024 - the other America",sub:"Oglala Lakota County SD: 52.6% poverty rate. Kusilvak AK: 48.1%. Starr County TX: 39.4%. The counties with the highest poverty rates are Native American reservations, colonias on the Texas border, and pockets of Appalachia. They share geography but not cause.",type:"MAP",geo:"us_county",fmt:"County choropleth",tbl:"T731 Income Poverty PDF + ACS",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)"],vars:["pct_under_25k","pct_on_snap"],join:["median_household_income","rural_population_pct","pct_on_medicaid"],sc:{emotional:9,relatability:7,surprise:7,tension:8,visual:10,data_ready:10,originality:4},vs:81,tags:"poverty rate county 2024 Oglala SD 52.6% Kusilvak AK 48.1% Starr TX 39.4% Native reservation colonias Appalachia geography cause"}
,{id:"income_by_race_trend_1970_2024",title:"Median household income by race 1970-2024 - the gap that barely closed",sub:"White median income 1970: $52K (2024 dollars). Black: $33K. 2024 - White: $81K. Black: $56K. The gap grew from $19K to $25K in nominal terms over 54 years. In percentage terms it narrowed from 37% to 31% - a 6-point improvement in half a century.",type:"CHART",geo:"us_national",fmt:"Line chart",tbl:"T731 Income PDF - race series",section:"Income",ext:["FRED: any national economic time series (fred.stlouisfed.org - free API)","BLS national data: employment, wages, CPI (bls.gov - free API)"],vars:["median_household_income","pct_under_25k"],join:["total_transfers_per_capita","pct_bachelors","state_unemployment_rate"],sc:{emotional:10,relatability:8,surprise:7,tension:9,visual:8,data_ready:9,originality:5},vs:84,tags:"median household income race 1970 2024 White $52K $81K Black $33K $56K gap $19K $25K 31% narrowed 6 points 54 years"}
,{id:"income_percentile_thresholds_by_state",title:"What income puts you in the top 10% by state - the geography of being rich",sub:"To be in the top 10% of earners in Mississippi: $89K. In New Jersey: $180K. The same income that makes you wealthy in one state makes you middle class in another. The relativity of rich is entirely geographic.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"T727 Income PDF - percentile distribution",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["median_household_income","pct_over_200k"],join:["pct_under_25k","state_gdp_per_capita","real_per_capita_income"],sc:{emotional:7,relatability:9,surprise:8,tension:4,visual:8,data_ready:9,originality:8},vs:77,tags:"top 10% income state Mississippi $89K New Jersey $180K geography rich wealthy middle class relativity entirely geographic"}
,{id:"disposable_income_per_capita_by_state",title:"Real disposable income per capita by state 2024 - after taxes and transfers",sub:"Connecticut: $86K real disposable income per capita. Mississippi: $38K. But when adjusted for cost of living (regional price parities), Mississippi rises to $44K equivalent and Connecticut falls to $74K. The true standard of living map looks different from the nominal map.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"T725 Income PDF - disposable income + BEA RPP",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["disposable_income_per_capita","real_per_capita_income"],join:["median_household_income","housing_cpi","state_local_revenue_per_capita"],sc:{emotional:6,relatability:8,surprise:8,tension:4,visual:8,data_ready:9,originality:8},vs:73,tags:"disposable income per capita state 2024 Connecticut $86K Mississippi $38K adjusted cost living RPP true standard map different nominal"}
,{id:"xref_real_income_vs_price_parity",title:"Real income vs. regional price parities by state - where your dollar actually goes further",sub:"Mississippi ranks 50th in nominal income but 44th in purchasing-power-adjusted income. Hawaii ranks 16th nominally but 49th in real terms. The cost-of-living adjustment completely reorders which states are actually prosperous.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"T723 + T725 Income PDF - BEA regional price parities",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["real_per_capita_income","disposable_income_per_capita"],join:["median_household_income","housing_cpi","state_gdp_per_capita"],sc:{emotional:7,relatability:8,surprise:9,tension:4,visual:7,data_ready:9,originality:8},vs:75,tags:"real income regional price parity state Mississippi 50th 44th Hawaii 16th 49th cost living reorders prosperous dollar further"}
,{id:"teen_birth_rate_by_state_trend",title:"Teen birth rate by state 2024 vs. 1991 - the most dramatic demographic change in modern America",sub:"1991 US teen birth rate: 61.8 per 1,000 girls aged 15-19. 2024: 13.7 - a 78% decline. Mississippi fell from 82 to 19. Even the highest-rate states today are lower than the national average in 1991. The change is so large it barely seems real.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"T86 Health Births PDF",section:"Population",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],vars:["teen_birth_rate","birth_rate_state"],join:["median_household_income","rep_pct","pct_bachelors"],sc:{emotional:7,relatability:8,surprise:10,tension:5,visual:8,data_ready:10,originality:7},vs:80,tags:"teen birth rate state 2024 1991 61.8 13.7 78% decline Mississippi 82 19 dramatic demographic change barely real modern America"}
,{id:"unmarried_birth_rate_by_state",title:"Share of births to unmarried mothers by state 2024 - the family structure map",sub:"Mississippi: 55.3% of births to unmarried mothers. New Mexico: 52.1%. Utah: 18.6%. The unmarried birth rate is the single variable most correlated with childhood poverty rates. It maps to geography, race, and income in ways that resist easy narratives.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"T87 Health Births PDF",section:"Population",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],vars:["pct_births_unmarried","teen_birth_rate"],join:["pct_on_snap","median_household_income","rep_pct"],sc:{emotional:7,relatability:7,surprise:6,tension:7,visual:8,data_ready:10,originality:5},vs:71,tags:"births unmarried mothers state 2024 Mississippi 55.3% New Mexico 52.1% Utah 18.6% childhood poverty correlated geography race income narrative"}
,{id:"mean_age_first_birth_by_race",title:"Mean age at first birth by race 2024 - the diverging clocks of American motherhood",sub:"Asian American women: average 32.1 years at first birth. White: 27.4. Black: 24.8. Hispanic: 24.1. The age-at-first-birth gap between Asian and Black women is 7.3 years - a gap that cascades through education, income, and generational wealth.",type:"CHART",geo:"us_national",fmt:"Bar chart",tbl:"T80 Health Births PDF - age at first birth by race",section:"Population",ext:["FRED: any national economic time series (fred.stlouisfed.org - free API)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],vars:["mean_age_first_birth","total_fertility_rate_by_race"],join:["pct_bachelors","median_household_income","pct_births_unmarried"],sc:{emotional:8,relatability:7,surprise:8,tension:6,visual:7,data_ready:10,originality:7},vs:75,tags:"mean age first birth race 2024 Asian 32.1 White 27.4 Black 24.8 Hispanic 24.1 7.3 gap education income generational wealth cascade"}
,{id:"xref_birth_rate_vs_housing_cost",title:"State birth rate vs. housing cost - why expensive states have fewer babies",sub:"California: fertility rate 1.47, median home price $750K. Utah: fertility rate 1.89, median home price $430K. The correlation between housing cost and fertility is -0.68. Americans aren't having fewer children because of culture - they can't afford them.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"T81 Health PDF + T771 Prices PDF",section:"Population",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","HUD Fair Market Rents + housing data by state/county (huduser.gov - free)"],vars:["fertility_rate_state","birth_rate_state"],join:["home_price_index_2024","housing_cpi","median_household_income"],sc:{emotional:8,relatability:8,surprise:9,tension:6,visual:7,data_ready:10,originality:9},vs:81,tags:"birth rate housing cost state California 1.47 $750K Utah 1.89 $430K correlation -0.68 fewer children can't afford culture"}
,{id:"gini_coefficient_by_state_trend",title:"Income inequality Gini coefficient by state 2024 - the unequal states of America",sub:"New York: 0.516 Gini (most unequal state). Connecticut: 0.498. Utah: 0.419. Alaska: 0.408. The US state with the highest inequality (New York) has a Gini coefficient higher than Brazil's national figure. Within-America inequality is global-scale.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"ACS Gini coefficient + T727",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["median_household_income","pct_over_200k"],join:["pct_under_25k","state_gdp_per_capita","pct_bachelors"],sc:{emotional:8,relatability:7,surprise:8,tension:7,visual:8,data_ready:9,originality:6},vs:77,tags:"Gini coefficient state 2024 New York 0.516 most unequal Connecticut Utah 0.419 Alaska higher than Brazil national within-America global scale"}
,{id:"supplemental_poverty_measure_by_state",title:"Supplemental Poverty Measure vs. official poverty rate by state - the hidden poor",sub:"California official poverty rate: 11.4%. Supplemental (accounts for housing costs and benefits): 15.2%. New Hampshire official: 7.3%. Supplemental: 5.8%. The official poverty rate can be wrong by 4+ points - in either direction.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"T731 + Census SPM data",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["pct_under_25k","pct_on_snap"],join:["median_household_income","housing_cpi","pct_on_medicaid"],sc:{emotional:8,relatability:7,surprise:8,tension:7,visual:8,data_ready:9,originality:8},vs:78,tags:"supplemental poverty measure official state California 11.4% 15.2% New Hampshire 7.3% 5.8% wrong 4 points either direction hidden poor"}
,{id:"xref_state_gdp_per_capita_vs_happiness",title:"State GDP per capita vs. self-reported wellbeing - the wealth-happiness paradox by state",sub:"Louisiana: 48th in GDP per capita, 3rd in self-reported happiness (Gallup). New York: 3rd in GDP, 45th in wellbeing. The GDP-happiness disconnect is not a global phenomenon - it's a domestic one too, and the outliers are the most interesting states.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"BEA state GDP + Gallup wellbeing index",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["state_gdp_per_capita","median_household_income"],join:["church_count","avg_commute_time","rural_population_pct"],sc:{emotional:8,relatability:8,surprise:9,tension:4,visual:7,data_ready:8,originality:9},vs:78,tags:"GDP per capita happiness wellbeing state Louisiana 48th GDP 3rd happiness New York 3rd GDP 45th wellbeing disconnect domestic paradox"}
,{id:"irs_migration_flows_state_to_state",title:"IRS net migration flows between states 2022 - who moved where and what income they brought",sub:"California to Texas: 102,000 households, $11.8B in adjusted gross income. New York to Florida: 89,000 households, $13.1B AGI. The IRS migration data is the only dataset that shows not just who moves, but what they earn.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"IRS SOI migration data",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["irs_net_migration_households","population_pct_change"],join:["home_price_index_2024","median_household_income","housing_permits_total"],sc:{emotional:7,relatability:8,surprise:8,tension:5,visual:9,data_ready:9,originality:8},vs:77,tags:"IRS migration flows state 2022 California Texas 102K $11.8B AGI New York Florida 89K $13.1B who moved income brought earns"}
,{id:"manufacturing_decline_by_county_2000_2020",title:"Manufacturing job loss by county 2000-2020 - the geography of deindustrialization",sub:"Henry County GA (carpet mills): lost 68% of manufacturing jobs. Lawrence County PA (steel): lost 71%. The deindustrialization map is not a national story - it's a hyper-local story of specific industries in specific places that never recovered.",type:"MAP",geo:"us_county",fmt:"County choropleth",tbl:"BLS QCEW + T1064 Manufacturing PDF",section:"Manufactures",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)"],vars:["manufacturing_employment_trend","manufacturing_value_added_state"],join:["median_household_income","opioid_death_rate_by_county","rural_population_pct"],sc:{emotional:9,relatability:7,surprise:7,tension:8,visual:9,data_ready:9,originality:7},vs:80,tags:"manufacturing job loss county 2000 2020 Henry GA 68% Lawrence PA 71% deindustrialization hyper-local specific industry never recovered"}
,{id:"xref_manufacturing_decline_vs_opioid",title:"Manufacturing job loss 2000-2020 vs. opioid death rate by county - the pain economy",sub:"Counties losing 20%+ of manufacturing jobs had opioid death rates 2.1x higher by 2016 than counties with stable manufacturing. The chemical treatment of economic despair mapped at the county level.",type:"XREF",geo:"us_county",fmt:"Scatter plot",tbl:"BLS QCEW + CDC WONDER opioids",section:"Manufactures",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],vars:["manufacturing_employment_trend","per_capita_health_spending"],join:["median_household_income","rural_population_pct","pct_on_snap"],sc:{emotional:10,relatability:7,surprise:8,tension:10,visual:7,data_ready:9,originality:8},vs:87,tags:"manufacturing job loss opioid death rate county 2000 2020 20%+ 2.1x higher 2016 pain economy chemical despair mapped county"}
,{id:"county_population_loss_1950_2020",title:"Counties that lost 20%+ of their population since 1950 - the hollowing of America",sub:"Over 1,000 US counties have fewer people today than they did in 1950. West Virginia: almost every county. Great Plains: a vast belt of depopulation. The map of demographic decline shows exactly where the American economy left people behind.",type:"MAP",geo:"us_county",fmt:"County choropleth",tbl:"T6 Population PDF - county change 1950-2020",section:"Population",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)"],vars:["population_pct_change_1950_2020","rural_population_pct"],join:["manufacturing_employment_trend","median_household_income","farms_count_2022"],sc:{emotional:8,relatability:7,surprise:8,tension:6,visual:10,data_ready:9,originality:7},vs:79,tags:"county population loss 1950 2020 1000 counties fewer people West Virginia Great Plains depopulation demographic decline left behind"}
,{id:"foreign_born_doctors_by_state",title:"Foreign-born physicians as share of all physicians by state",sub:"New Jersey: 46% of doctors are foreign-born. New York: 42%. Montana: 14%. Vermont: 11%. The US healthcare system would collapse without immigrant physicians. The states most hostile to immigration have the fewest immigrant doctors.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"ACS occupation + nativity data",section:"Health",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],vars:["foreign_born_physician_pct","per_capita_health_spending"],join:["net_migration_rate","pct_on_medicaid","median_household_income"],sc:{emotional:9,relatability:7,surprise:9,tension:8,visual:8,data_ready:9,originality:7},vs:83,tags:"foreign born physicians state New Jersey 46% New York 42% Montana 14% healthcare collapse immigration hostile fewest doctors"}
,{id:"xref_missing_men_incarceration_and_mortality",title:"The missing men map - counties where men 25-54 are disproportionately absent",sub:"In McDowell County WV, for every 100 women aged 25-54 there are only 64 men. In Bronx County NY: 79 men per 100 women. The men are missing to incarceration, overdose, and early death. The missing men map is the map of three crises overlaid.",type:"MAP",geo:"us_county",fmt:"County choropleth",tbl:"ACS sex/age + CDC mortality + Vera incarceration",section:"Population",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],vars:["sex_ratio_county","population_pct_change"],join:["violent_crime_rate","median_household_income","rural_population_pct"],sc:{emotional:10,relatability:8,surprise:9,tension:9,visual:9,data_ready:8,originality:10},vs:90,tags:"missing men county 25-54 McDowell WV 64 per 100 women Bronx NY 79 incarceration overdose early death three crises overlaid map"}
,{id:"landline_telephone_usage_by_state",title:"Households still using landline telephones by state 2024",sub:"West Virginia: 36% of households have a landline. Pennsylvania: 34%. Utah: 14%. Alaska: 13%. The landline map is a proxy for age, rurality, and digital transition - and it reveals the places where old infrastructure persists because the new infrastructure hasn't arrived.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"FCC + NTIA internet/phone use survey",section:"Information",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["broadband_access_pct","rural_population_pct"],join:["median_household_income","population_pct_change","median_age"],sc:{emotional:5,relatability:7,surprise:8,tension:2,visual:7,data_ready:8,originality:8},vs:65,tags:"landline telephone households state 2024 West Virginia 36% Pennsylvania 34% Utah 14% Alaska age rurality digital transition old infrastructure"}
"""

with open('data.js', 'a', encoding='utf-8') as f:
    f.write(ideas)
    f.write('\n]; // end D\n')

print('Batch I appended. Now run: python maintain.py')
