import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HBW01","Where Judges Set Bail Higher for the Same Crime","County-level bail amounts for identical charges reveal geography as a sentencing variable","MAP","US-county","County choropleth","law/geography","LJAF: Pretrial bail data (ljaf.org); Census: County demographics (census.gov/acs)",82,78,70,80,85,82,78,72),
mk("HBW02","The Gun Store Next Door: Firearm Retailers per Capita by County","Rural counties with 10x the gun stores per person vs. metro areas — mapped","MAP","US-county","County choropleth","guns/geography","ATF: Federal firearms licensee data (atf.gov); Census: Population estimates (census.gov)",70,72,75,68,72,80,65,85),
mk("HBW03","Where Religion Predicts Your Hospital Options","Counties where the only hospital is faith-based and what services they wont provide","MAP","US-county","County choropleth","religion/health","AHA: Hospital survey (aha.org); CMS: Provider data (cms.gov); NARAL: Healthcare access (naral.org)",85,80,72,82,88,78,80,68),
mk("HBW04","The Psychology of Tipping: Where Americans Tip Most and What It Reveals","State-level tipping averages correlated with social conformity and inequality metrics","CHART","US-state","Scatter plot","psychology/economy","Square: Tipping data (squareup.com); Hofstede: Cultural dimensions (hofstede-insights.com); BLS: Wage data (bls.gov)",72,88,68,75,60,70,78,65),
mk("HBW05","Americas Last Factories: Manufacturing Jobs That Survived Globalization","The 200 counties where manufacturing employment actually grew since 2000","MAP","US-county","County choropleth","manufacturing/economy","BLS: QCEW (bls.gov/qcew); Census: CBP (census.gov/programs-surveys/cbp)",78,75,72,74,70,80,72,82),
mk("HBW06","Rural Hospitals Are Disappearing Faster Than Rural People","Hospital closures vs population decline — hospitals vanishing 3x faster","CHART","US-state","Bar chart","rural/health","UNC: Rural hospital closures (shepscenter.unc.edu); Census: Rural population (census.gov)",88,82,78,78,85,72,75,80),
mk("HBW07","The Middle East Conflict Mapped by American Military Bases","Every US base in the Middle East overlaid with conflict zones and oil infrastructure","MAP","Middle East","Special map","middle_east/military","DOD: Base structure report (defense.gov); ACLED: Conflict data (acleddata.com); EIA: Oil infrastructure (eia.gov)",80,65,72,78,82,88,75,75),
mk("HBW08","Which Sports Fans Are Most Politically Divided","NFL/NBA/MLB fan bases mapped by county and overlaid with 2024 election results","CHART","US-county","Scatter plot","sports/politics","Morning Consult: Sports fandom (morningconsult.com); MIT: Election data (electionlab.mit.edu)",68,82,65,76,72,70,80,62),
mk("HBW09","The Entertainment Desert: Counties With Zero Movie Theaters","180 US counties with no cinema — mapped against income and broadband access","MAP","US-county","County choropleth","entertainment/rural","NATO: Theater count (natoonline.org); FCC: Broadband (fcc.gov/broadbandmap); Census: Income (census.gov)",75,78,72,70,65,80,72,70),
mk("HBW10","Where Your Lawyer Went to Law School Predicts Your Sentence","State supreme court justice law school pedigree correlated with sentencing severity","CHART","US-state","Bar chart","law/education","ABA: Lawyer demographics (americanbar.org); USSC: Sentencing data (ussc.gov); IPEDS: Law school data (nces.ed.gov)",78,70,65,85,80,68,82,58),
mk("HBW11","The Gun Violence Gradient: How Distance From a Gun Store Predicts Shootings","Census tract analysis of proximity to FFLs and firearm incident rates","MAP","US-county","Dot map","guns/crime","ATF: FFL locations (atf.gov); GVA: Gun violence incidents (gunviolencearchive.org); Census: Tract data (census.gov)",82,75,68,80,85,78,76,70),
mk("HBW12","The Mega-Church Economy: Religious Institutions as Local Economic Engines","Counties where churches are top-5 employers — mapped with economic dependency","MAP","US-county","County choropleth","religion/economy","IRS: Tax-exempt organizations (irs.gov/charities); BLS: Employment data (bls.gov); RCMS: Religious census (rcms.org)",72,70,68,80,65,75,82,65),
mk("HBW13","Your Personality Type Predicts Your Zip Code","Big Five personality traits mapped to metro areas — openness clusters on coasts","MAP","US-metro","State choropleth","psychology/geography","Rentfrow: Regional personality (cam.ac.uk); Census: ACS (census.gov/acs)",70,82,62,78,55,72,85,60),
mk("HBW14","The Factory Towns That Flipped: Manufacturing Loss and Political Realignment","Counties that lost 30%+ manufacturing jobs and swung 20+ points politically","MAP","US-county","Bivariate choropleth","manufacturing/politics","BLS: QCEW (bls.gov/qcew); MIT: Election data (electionlab.mit.edu)",82,78,75,76,82,80,74,80),
mk("HBW15","Rural Americas Brain Drain Mapped Year by Year","Animated map of college-educated adults leaving rural counties 2000-2024","MAP","US-county","Animated choropleth","rural/education","Census: ACS education (census.gov/acs); USDA: Rural-urban continuum (ers.usda.gov)",80,78,75,72,78,82,70,78),
mk("HBW16","The Middle East Water Crisis No One Talks About","Countries losing groundwater fastest overlaid with population growth and conflict","MAP","Middle East","World choropleth","middle_east/climate","GRACE: Groundwater (nasa.gov); FAO: AQUASTAT (fao.org/aquastat); ACLED: Conflict (acleddata.com)",85,68,72,82,85,80,78,72),
mk("HBW17","Americas Most Psychologically Stressed Counties","Composite index of mental health provider shortage + overdose + suicide + unemployment","MAP","US-county","County choropleth","psychology/health","HRSA: HPSA (hrsa.gov); CDC: WONDER (wonder.cdc.gov); BLS: Unemployment (bls.gov)",85,82,70,75,80,78,72,78),
mk("HBW18","Which States Let You Sue Your Employer and Which Dont","At-will employment exceptions mapped — states where workers have zero legal recourse","MAP","US-state","State choropleth","law/labor","DOL: Employment law (dol.gov); NELP: Worker protections (nelp.org)",80,85,78,72,80,75,70,80),
mk("HBW19","The Gun Ownership Paradox: States Where More Guns Correlate With Less Crime","Cherry-picked vs full dataset — showing how data framing changes the narrative","CHART","US-state","Scatter plot","guns/data","RAND: Gun ownership (rand.org); FBI: UCR (ucr.fbi.gov); CDC: Mortality (wonder.cdc.gov)",75,72,80,82,78,68,85,78),
mk("HBW20","How Reality TV Reshaped American Geography","Counties that gained tourism after reality show filming — mapped economic impact","MAP","US-county","Dot map","entertainment/economy","BEA: Regional GDP (bea.gov); BLS: Leisure employment (bls.gov); IMDB: Filming locations (imdb.com)",65,78,62,75,55,72,82,55),
mk("HBW21","The Sports Scholarship Pipeline: Where Athletic Talent Becomes Economic Mobility","High school athletic participation mapped to college scholarship awards by county","MAP","US-county","Bivariate choropleth","sports/education","NCES: High school data (nces.ed.gov); NCAA: Scholarship data (ncaa.org); Census: Income mobility (census.gov)",78,80,68,72,70,75,76,62),
mk("HBW22","Where Manufactured Housing Is the Only Housing","Counties where 40%+ of housing stock is mobile homes — mapped with tornado risk","MAP","US-county","Bivariate choropleth","housing/manufacturing","Census: ACS housing (census.gov/acs); NOAA: Tornado data (spc.noaa.gov); FEMA: Declarations (fema.gov)",82,78,72,78,80,80,75,78),
mk("HBW23","The Religious Liberty Map: Where Faith-Based Exemptions Override Civil Rights","States with religious exemption laws mapped against discrimination complaint rates","MAP","US-state","Bivariate choropleth","religion/law","NCSL: Religious liberty laws (ncsl.org); EEOC: Discrimination data (eeoc.gov)",80,72,70,78,85,75,78,72),
mk("HBW24","The Rural Internet Lie: Advertised vs Actual Broadband Speeds","FCC reported speeds vs Ookla measured speeds in rural areas — the gap mapped","MAP","US-county","Bivariate choropleth","rural/technology","FCC: Broadband map (fcc.gov/broadbandmap); Ookla: Speedtest (speedtest.net); NTIA: Broadband data (ntia.gov)",78,82,75,80,78,78,72,75),
mk("HBW25","Middle East Oil Revenue Per Citizen vs Quality of Life","Petrodollars per capita mapped against HDI — the resource curse visualized","CHART","Middle East","Scatter plot","middle_east/economy","World Bank: Oil rents (worldbank.org); UNDP: HDI (hdr.undp.org); EIA: Production (eia.gov)",75,65,78,80,72,70,80,80),
mk("HBW26","The Psychology of Conspiracy: What Your County Believes","Flat earth, anti-vax, QAnon belief rates mapped against education and broadband access","MAP","US-county","County choropleth","psychology/education","PRRI: Belief surveys (prri.org); Census: Education (census.gov/acs); FCC: Broadband (fcc.gov)",72,78,62,80,72,75,82,55),
mk("HBW27","Americas Manufacturing Renaissance Is Happening in 12 Counties","CHIPS Act and IRA investment mapped — nearly all new factories in a handful of places","MAP","US-county","Dot map","manufacturing/geography","White House: CHIPS investments (whitehouse.gov); BLS: Manufacturing employment (bls.gov)",78,72,78,82,72,80,75,72),
mk("HBW28","Where Stand Your Ground Laws Changed Who Gets Killed","Homicide rate changes after SYG adoption — broken down by race of victim","CHART","US-state","Bar chart","guns/race","RAND: SYG research (rand.org); FBI: SHR (ucr.fbi.gov); CDC: Mortality (wonder.cdc.gov)",85,72,75,80,88,70,78,75),
mk("HBW29","The Law Enforcement Desert: Counties With One Deputy Per 1000 Square Miles","Mapped against response times and crime rates — where 911 is just a suggestion","MAP","US-county","County choropleth","law/rural","FBI: LEOKA (ucr.fbi.gov); Census: Law enforcement (census.gov/govs); BJS: LEMAS (bjs.gov)",82,78,72,78,80,82,75,68),
mk("HBW30","The Global Sports Talent Map: Where Olympic Medals Actually Come From","Medal count per capita reveals small nations that dominate per person","MAP","World","World choropleth","sports/international","IOC: Medal database (olympics.com); World Bank: Population (worldbank.org)",68,72,78,72,58,82,70,85),
mk("HBW31","The Entertainment Industry Mapped: Where Americas Content Is Actually Made","Film/TV/music production by county — 4 metros produce 80% of everything","MAP","US-county","Dot map","entertainment/geography","BLS: Arts employment (bls.gov); FilmLA: Production data (filmla.com); RIAA: Label data (riaa.com)",68,72,70,72,58,78,70,72),
mk("HBW32","Every Country the US Has Sanctioned in the Middle East and What Happened Next","Timeline of sanctions overlaid with GDP, mortality, and migration data","XREF","Middle East","Line chart","middle_east/trade","OFAC: Sanctions list (treasury.gov/ofac); World Bank: WDI (worldbank.org); UNHCR: Displacement (unhcr.org)",80,65,72,78,82,72,78,72),
mk("HBW33","The Psychology of Place: How Your States Personality Profile Predicts Its Politics","Aggregate Big Five scores by state vs. voting patterns — neuroticism predicts turnout","CHART","US-state","Scatter plot","psychology/politics","Rentfrow: State personality (cam.ac.uk); MIT: Election data (electionlab.mit.edu); Census: Demographics (census.gov)",70,72,65,82,68,68,85,58),
mk("HBW34","Where Factory Closures Predicted the Opioid Crisis 10 Years Early","Manufacturing job loss 2000-2008 mapped against overdose spike 2010-2020","XREF","US-county","Bivariate choropleth","manufacturing/drugs","BLS: QCEW (bls.gov/qcew); CDC: Drug overdose (wonder.cdc.gov); Census: Employment (census.gov)",88,80,75,85,85,82,80,80),
mk("HBW35","The Rural Grocery Store Crisis: Food Access After the Last Store Closes","Counties that lost their only grocery store since 2010 — mapped with health outcomes","MAP","US-county","County choropleth","rural/food","USDA: Food access (ers.usda.gov); Census: Retail (census.gov/retail); CDC: Diabetes (cdc.gov/diabetes)",85,82,75,75,82,78,72,75),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HBW ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HBW batch)")
