# BATCH_BK.py
ideas = [
  {'id': 'naep_scores_state_map', 'title': "NAEP 8th grade reading scores by state 2023 — America's actual education map", 'sub': 'Massachusetts: 274. West Virginia: 246. The 28-point gap represents roughly 3 grade levels of reading ability between the best and worst states.', 'type': 'MAP', 'geo': 'us_state', 'fmt': 'State choropleth', 'tbl': 'National Center for Education Statistics: NAEP scores by state (nces.ed.gov/nationsreportcard)', 'section': 'Education', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['naep_reading_grade8', 'naep_math_grade8'], 'join': ['expenditure_per_pupil', 'avg_teacher_salary', 'poverty_rate_child', 'rep_pct'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 90, 'surprise': 70, 'tension': 80, 'visual': 100, 'data_ready': 90, 'originality': 60}, 'vs': 81, 'tags': 'NAEP 8th grade reading state Massachusetts 274 West Virginia 246 28 points 3 grade levels education map', 'notes': '', 'topics': ['education', 'inequality', 'poverty', 'politics', 'race'], 'status': 'idea'},
  {'id': 'xref_school_funding_income', 'title': 'Per-pupil school spending vs. community income by district — the rich district advantage', 'sub': 'The wealthiest 10% of school districts spend $2,200 more per pupil than the poorest 10%. In the same state. With the same state constitution guaranteeing equal education.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'NCES: Per-pupil expenditure by school district + ACS: Median household income by school district', 'section': 'Education  -  Income', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['expenditure_per_pupil_district', 'median_household_income_district'], 'join': ['naep_score_district', 'pct_poverty_district', 'teacher_experience_district'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 70, 'surprise': 70, 'tension': 80, 'visual': 90, 'data_ready': 80, 'originality': 70}, 'vs': 77, 'tags': 'school funding income district wealthy 2200 more per pupil poorest same state same constitution equal education', 'notes': '', 'topics': ['education', 'inequality', 'housing', 'race', 'poverty'], 'status': 'idea'},
  {'id': 'xref_teacher_shortage_salary', 'title': 'Teacher vacancy rate vs. salary vs. cost of living by state', 'sub': 'The states with the most teacher vacancies are not always the lowest-paying states. They are the ones where salaries fell furthest behind housing costs. The vacancy is a housing crisis in disguise.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'NCES: Teacher vacancy and shortage data + BLS: Teacher wages by state + BLS Regional Price Parities', 'section': 'Education  -  Housing', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['teacher_vacancy_rate_state', 'avg_teacher_salary_real', 'housing_cost_index'], 'join': ['rep_pct', 'pct_bachelors', 'student_teacher_ratio'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 70, 'surprise': 90, 'tension': 80, 'visual': 80, 'data_ready': 70, 'originality': 90}, 'vs': 79, 'tags': 'teacher vacancy salary cost of living state behind housing costs vacancy is housing crisis disguise XREF', 'notes': '', 'topics': ['education', 'housing', 'labor', 'economy', 'inequality'], 'status': 'idea'},
  {'id': 'xref_chronic_absenteeism_poverty', 'title': 'Chronic absenteeism rate vs. child poverty rate by school district', 'sub': 'After COVID, chronic absenteeism in high-poverty districts reached 40%. In low-poverty districts: 12%. The attendance crisis is a poverty crisis wearing a school uniform.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'NCES: Chronic absenteeism rates by district + ACS: Child poverty rate by school district area', 'section': 'Education  -  Income', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['chronic_absenteeism_rate', 'child_poverty_rate_district'], 'join': ['food_insecurity_rate', 'housing_instability_rate', 'uninsured_rate'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 80, 'tension': 80, 'visual': 90, 'data_ready': 70, 'originality': 80}, 'vs': 82, 'tags': 'chronic absenteeism poverty school district 40 percent 12 percent post-COVID attendance crisis poverty wearing uniform', 'notes': '', 'topics': ['education', 'poverty', 'health', 'inequality', 'race'], 'status': 'idea'},
  {'id': 'college_completion_race_gap', 'title': 'College completion rate by race: the degree gap that compounds every other gap', 'sub': "White adults: 42% with a bachelor's. Black: 29%. Hispanic: 21%. The gap has barely changed in 30 years. At this pace, equality arrives in 2070.", 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Bar chart', 'tbl': 'Census CPS: Educational attainment by race and year 1990-2023 (census.gov)', 'section': 'Education', 'ext': [], 'vars': ['pct_bachelors_white', 'pct_bachelors_black', 'pct_bachelors_hispanic', 'pct_bachelors_asian'], 'join': ['median_earnings_by_education_race', 'homeownership_rate_race'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 70, 'tension': 90, 'visual': 90, 'data_ready': 90, 'originality': 60}, 'vs': 83, 'tags': 'college completion race gap White 42 Black 29 Hispanic 21 barely changed 30 years equality 2070 degree gap', 'notes': '', 'topics': ['education', 'race', 'inequality', 'economy', 'history'], 'status': 'idea'},
  {'id': 'student_loan_debt_by_age', 'title': 'Who holds student debt in America — by age, income, and race', 'sub': "The fastest-growing student debt holders are 50+, paying for degrees they earned 20 years ago or degrees their children couldn't finish. The student loan crisis is not just a millennial story.", 'type': 'CHART', 'geo': 'us_national', 'fmt': 'Bar chart', 'tbl': 'Federal Reserve SCF + New York Fed Consumer Credit Panel: Student debt by age, income, and race', 'section': 'Education  -  Banking Finance Insurance', 'ext': ['FRED: any national economic time series (fred.stlouisfed.org  free API)'], 'vars': ['student_debt_by_age_bracket', 'student_debt_by_income_quartile', 'student_debt_by_race'], 'join': ['student_loans_outstanding', 'default_rate_student_loan'], 'sc': {'emotional': 90, 'relatability': 90, 'clarity': 80, 'surprise': 80, 'tension': 80, 'visual': 80, 'data_ready': 80, 'originality': 80}, 'vs': 83, 'tags': 'student loan debt age income race 50 plus fastest growing 20 years ago not millennial story crisis holds', 'notes': '', 'topics': ['education', 'economy', 'inequality', 'race', 'labor', 'finance'], 'status': 'idea'},
  {'id': 'xref_school_segregation_test_scores', 'title': 'School racial segregation index vs. test score gaps by district — separate and still unequal', 'sub': 'The more racially segregated a school district, the wider the achievement gap. The Brown v. Board premise was correct: separate is not equal. The data 70 years later confirms it.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'Stanford SEDA: School district achievement gaps + UCLA Civil Rights Project: Segregation index by district', 'section': 'Education', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['racial_segregation_index_district', 'achievement_gap_district'], 'join': ['school_funding_gap', 'poverty_rate_district', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 70, 'clarity': 70, 'surprise': 70, 'tension': 90, 'visual': 90, 'data_ready': 70, 'originality': 80}, 'vs': 78, 'tags': 'school segregation test scores district achievement gap Brown v Board separate not equal 70 years confirms XREF', 'notes': '', 'topics': ['education', 'race', 'history', 'inequality', 'politics'], 'status': 'idea'},
  {'id': 'private_school_enrollment_wealth', 'title': 'Private school enrollment share vs. median income by metro — where parents opt out of public schools', 'sub': 'New York City: 30% of students in private/parochial schools. Rural Arkansas: 3%. The opt-out geography correlates perfectly with wealth — and with who votes against public school funding.', 'type': 'XREF', 'geo': 'us_metro', 'fmt': 'Scatter plot', 'tbl': 'NCES: Private school enrollment by metro + ACS: Median household income by metro', 'section': 'Education  -  Income', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['private_school_enrollment_pct', 'median_household_income'], 'join': ['public_school_funding_per_pupil', 'pct_bachelors', 'rep_pct'], 'sc': {'emotional': 70, 'relatability': 70, 'clarity': 80, 'surprise': 70, 'tension': 70, 'visual': 80, 'data_ready': 80, 'originality': 70}, 'vs': 73, 'tags': 'private school enrollment wealth metro New York 30 Arkansas 3 opt-out geography wealth vote against funding', 'notes': '', 'topics': ['education', 'inequality', 'race', 'economy', 'politics'], 'status': 'idea'},
  {'id': 'xref_internet_access_test_scores', 'title': 'Home broadband access vs. student test scores by county — the homework gap', 'sub': 'Children without home internet score 15-20 NAEP points lower. Post-COVID, the homework gap became the biggest driver of the achievement gap — and it is pure infrastructure.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'FCC: Broadband access by county + NAEP: State/district scores (nces.ed.gov)', 'section': 'Education  -  Infrastructure', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['broadband_access_pct', 'naep_score_proxy_county'], 'join': ['poverty_rate_child', 'median_household_income', 'rural_population_pct'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 80, 'surprise': 80, 'tension': 80, 'visual': 90, 'data_ready': 70, 'originality': 90}, 'vs': 82, 'tags': 'home broadband test scores county homework gap 15-20 NAEP points COVID achievement gap pure infrastructure XREF', 'notes': '', 'topics': ['education', 'technology', 'infrastructure', 'poverty', 'inequality'], 'status': 'idea'},
  {'id': 'xref_teacher_turnover_school_poverty', 'title': 'Teacher turnover rate vs. school poverty level — the teachers who stay and the schools that lose them', 'sub': 'Schools where 80%+ of students qualify for free lunch lose 25% of teachers annually. Low-poverty schools: 8%. The schools that need consistency get chaos.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'NCES: Teacher turnover by school poverty level + NCES: Free and reduced lunch eligibility', 'section': 'Education  -  Labor Force', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['teacher_turnover_rate', 'pct_students_free_reduced_lunch'], 'join': ['avg_teacher_salary', 'school_funding_per_pupil', 'chronic_absenteeism_rate'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 80, 'tension': 90, 'visual': 80, 'data_ready': 70, 'originality': 80}, 'vs': 82, 'tags': 'teacher turnover school poverty 80 percent free lunch 25 percent annual turnover 8 low poverty consistency chaos XREF', 'notes': '', 'topics': ['education', 'labor', 'poverty', 'inequality', 'race'], 'status': 'idea'},
]

def vscore(sc):
    return int((sc.get("emotional",0)*2 + sc.get("relatability",0)*2 + sc.get("clarity",0)*2 +
               sc.get("surprise",0)*1.5 + sc.get("tension",0)*1 + sc.get("visual",0)*1 +
               sc.get("data_ready",0)*0.5 + sc.get("originality",0)*0.5) / 10.5)

for idea in ideas:
    idea["vs"] = vscore(idea["sc"])

if __name__ == "__main__":
    print(f"BATCH_BK: {len(ideas)} ideas")
    for i in sorted(ideas, key=lambda x: -x["vs"]):
        print(f"  vs={i["vs"]:3d}  {i["id"]}")
