import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HBX01","The Chart That Ends the Immigration Crime Debate","Immigrant incarceration rates vs native-born by state — the gap is enormous","CHART","US-state","Bar chart","immigration/crime","DOJ: BJS Prisoners (bjs.gov); Census: ACS nativity (census.gov/acs); Cato: Immigration research (cato.org)",82,78,82,78,85,70,72,80),
mk("HBX02","Every Dollar the US Spends in the Middle East vs What It Gets Back","Military aid, oil imports, and trade balance mapped as a Sankey flow","CHART","Middle East","Special map","middle_east/finance","SIPRI: Arms transfers (sipri.org); EIA: Oil trade (eia.gov); Census: Trade data (census.gov/trade)",80,68,75,78,80,82,78,75),
mk("HBX03","The Gun Buyback That Worked: Australias Homicide Rate Before and After","Simple before/after line chart that speaks for itself — 1996 to present","CHART","World","Line chart","guns/international","AIC: Homicide data (aic.gov.au); UNODC: Global homicide (unodc.org)",82,70,85,72,78,68,65,88),
mk("HBX04","Where Religious Attendance Predicts Life Expectancy","Counties with highest church attendance mapped against longevity — its complicated","MAP","US-county","Bivariate choropleth","religion/health","Gallup: Religious attendance (gallup.com); IHME: Life expectancy (healthdata.org)",72,75,65,82,65,78,80,65),
mk("HBX05","The Manufacturing Mirage: Jobs Created by Reshoring vs Jobs Lost to Automation","Net manufacturing employment is flat despite reshoring headlines","CHART","US","Line chart","manufacturing/labor","Reshoring Initiative: Data (reshorenow.org); BLS: Manufacturing employment (bls.gov); Brookings: Automation (brookings.edu)",78,72,78,82,75,68,80,75),
mk("HBX06","Rural Americas Voting Power: How 15% of the Population Controls 50% of the Senate","Population per senator mapped — the most lopsided representation in any democracy","CHART","US-state","Bar chart","rural/democracy","Census: State population (census.gov); Senate.gov: Representation data (senate.gov)",80,78,82,75,80,72,70,85),
mk("HBX07","The Psychology of Your Commute: How Drive Time Predicts Divorce Rate","County commute times correlated with divorce and happiness — 45 min is the cliff","XREF","US-county","Scatter plot","psychology/transportation","Census: ACS commute (census.gov/acs); CDC: Divorce (cdc.gov); Gallup: Wellbeing (gallup.com)",72,85,68,82,68,70,82,65),
mk("HBX08","What Entertainment Jobs Actually Pay: The Gig Economy of Hollywood","Median income for actors, musicians, writers by metro — 80% earn below median wage","CHART","US-metro","Bar chart","entertainment/labor","BLS: OES (bls.gov/oes); Census: ACS (census.gov/acs); SAG-AFTRA: Employment (sagaftra.org)",75,80,72,78,72,68,72,72),
mk("HBX09","Every Mass Shooting in America Mapped by Distance to Nearest Gun Store","Proximity analysis reveals clustering — not causation but a startling pattern","MAP","US","Dot map","guns/geography","GVA: Mass shooting data (gunviolencearchive.org); ATF: FFL locations (atf.gov)",80,72,68,82,82,82,78,72),
mk("HBX10","The Law That Lets Corporations Pick Their Own Judge","Where companies incorporate vs where they operate — Delawares legal monopoly mapped","MAP","US-state","Bivariate choropleth","law/finance","SEC: EDGAR filings (sec.gov); Delaware Courts: Chancery (courts.delaware.gov); Census: CBP (census.gov)",72,68,70,82,78,72,85,72),
mk("HBX11","The Sports Stadium Scam: Public Money In vs Economic Impact Out","Every publicly funded stadium mapped with promised vs actual economic returns","CHART","US-metro","Scatter plot","sports/finance","Brookings: Stadium subsidies (brookings.edu); BEA: Metro GDP (bea.gov); Census: Government finance (census.gov)",80,78,75,78,80,72,76,72),
mk("HBX12","Middle East Refugee Flows: Where 15 Million People Actually Went","Animated flow map of displacement from Syria, Iraq, Yemen, Palestine since 2011","MAP","Middle East","Line map","middle_east/immigration","UNHCR: Refugee data (unhcr.org); IOM: Displacement tracking (iom.int)",85,70,72,75,82,88,72,80),
mk("HBX13","The Religious Sorting of America: How Denominations Cluster Geographically","County-level religious adherence mapped — Baptist belt, Catholic northeast, Mormon west","MAP","US-county","County choropleth","religion/geography","ARDA: Religious census (thearda.com); RCMS: Congregational data (rcms.org); Census: County data (census.gov)",68,72,75,70,58,85,68,85),
mk("HBX14","The Psychology of Wealth: How Your Zip Codes Average Income Changes Your Moral Judgments","Research showing zip code predicts attitudes on fairness and redistribution","CHART","US-state","Scatter plot","psychology/inequality","Pew: Values survey (pewresearch.org); Census: Income (census.gov/acs); World Values Survey (worldvaluessurvey.org)",72,78,65,80,68,68,82,58),
mk("HBX15","The Rural Hospital Death Spiral Explained in One Chart","Revenue per bed declining while fixed costs rise — the math doesnt work below 25 beds","CHART","US","Line chart","rural/finance","AHA: Hospital financial data (aha.org); CMS: Cost reports (cms.gov); HRSA: Rural health (hrsa.gov)",85,78,80,72,82,68,70,78),
mk("HBX16","Where Guns Cross State Lines: The Interstate Firearms Trafficking Map","ATF trace data showing which states export crime guns to which — flow lines mapped","MAP","US-state","Line map","guns/trade","ATF: Firearms trace data (atf.gov); FBI: UCR (ucr.fbi.gov)",82,70,75,80,82,85,75,80),
mk("HBX17","The Manufacturing Belt Became the Rust Belt Became the Opioid Belt","Three-panel animated map showing the same counties across three eras","XREF","US-county","Animated choropleth","manufacturing/history","BLS: Historical employment (bls.gov); CDC: Overdose data (wonder.cdc.gov); Census: Historical (census.gov)",88,80,78,82,85,85,82,78),
mk("HBX18","Every Law That Makes It Harder to Vote Mapped by When It Passed","Timeline map of voter ID laws, registration restrictions, and polling place closures","MAP","US-state","Animated choropleth","law/democracy","NCSL: Voter ID laws (ncsl.org); Leadership Conference: Polling closures (civilrightsproject.ucla.edu); MIT: Election data (electionlab.mit.edu)",82,75,75,75,85,80,72,78),
mk("HBX19","The Sports Betting Map: Where Gambling Revenue Goes vs Where Problem Gambling Lives","States legal gambling revenue mapped against addiction treatment funding","MAP","US-state","Bivariate choropleth","sports/drugs","AGA: Gaming revenue (americangaming.org); SAMHSA: Treatment data (samhsa.gov); NASPL: Lottery data (naspl.org)",75,78,70,78,78,75,78,72),
mk("HBX20","The Psychology of Misinformation: Which Demographics Share the Most Fake News","Age, education, and partisanship mapped against misinformation sharing rates","CHART","US","Bar chart","psychology/media","NYU: Social media research (csmapnyu.org); Pew: News habits (pewresearch.org); MIT: Fake news study (mit.edu)",72,75,68,78,72,68,80,62),
mk("HBX21","Middle East Water Rights: Who Controls the Rivers That Cross Borders","Euphrates, Tigris, Jordan, Nile headwaters mapped with downstream dependency","MAP","Middle East","Special map","middle_east/environment","FAO: AQUASTAT (fao.org/aquastat); World Bank: Water data (worldbank.org); NASA: GRACE (nasa.gov)",78,60,72,80,82,85,80,72),
mk("HBX22","The Entertainment Subsidy: States Giving Tax Breaks to Film vs Funding Schools","Film tax credit spending mapped against per-pupil education spending","CHART","US-state","Scatter plot","entertainment/education","MPAA: Tax incentives (motionpictures.org); NCES: Per-pupil spending (nces.ed.gov); NCSL: Film credits (ncsl.org)",72,72,75,78,75,68,80,72),
mk("HBX23","Where Your Religion Determines Your Zoning Laws","Counties where religious organizations blocked housing, dispensaries, or businesses via zoning","MAP","US-county","Dot map","religion/housing","RLUIPA: DOJ cases (justice.gov); Census: Building permits (census.gov); NIMBY tracking (nimbytracker.com)",75,72,65,80,78,72,82,55),
mk("HBX24","The Rural Broadband Lie: FCC Maps vs Reality on the Ground","Side-by-side comparison of FCC coverage claims vs actual speed test data by county","MAP","US-county","Bivariate choropleth","rural/technology","FCC: Broadband map (fcc.gov/broadbandmap); Ookla: Speedtest (speedtest.net); M-Lab: Internet speed (measurementlab.net)",78,82,78,78,78,80,72,78),
mk("HBX25","The Gun Deaths We Dont Talk About: Suicides Are 60% of All Firearm Deaths","State-level firearm suicide vs homicide — most coverage focuses on the minority","CHART","US-state","Bar chart","guns/health","CDC: WONDER (wonder.cdc.gov); Everytown: Firearm research (everytownresearch.org)",85,75,82,80,82,70,72,85),
mk("HBX26","What Happens to Small Towns When the Prison Closes","Economic impact of prison closures mapped — the towns that were promised prosperity","MAP","US-county","Dot map","law/rural","BJS: Corrections data (bjs.gov); Census: Employment (census.gov); BEA: Personal income (bea.gov)",80,75,70,78,78,75,80,68),
mk("HBX27","The Global Manufacturing Shift in One Animated Chart","Share of world manufacturing by country 1970-2025 — Chinas rise, Americas fall","CHART","World","Animated bar chart","manufacturing/international","World Bank: Manufacturing value added (worldbank.org); UNIDO: Industrial statistics (unido.org)",78,68,80,75,72,78,68,85),
mk("HBX28","Every Sports Team That Got a Taxpayer Stadium and Then Moved Anyway","Teams that took public money, left, and what happened to the city — timeline map","CHART","US-metro","Special map","sports/economy","Brookings: Stadium subsidies (brookings.edu); Team relocation data (sportsbusinessjournal.com)",82,80,72,78,82,75,78,70),
mk("HBX29","The Psychology of Partisanship: Your Brain on Political News","fMRI research showing Democrats and Republicans literally process the same facts differently","CHART","US","Bar chart","psychology/media","Nature: Partisan brain studies (nature.com); Pew: Polarization (pewresearch.org)",72,78,65,82,70,65,82,55),
mk("HBX30","Where Sharia Law Panic Meets Reality: Muslim Population Share by US County","Muslim population share mapped — the disconnect between fear and demographics","MAP","US-county","County choropleth","religion/demographics","Pew: Religious landscape (pewresearch.org); Census: ACS (census.gov/acs); ISPU: Muslim survey (ispu.org)",78,72,75,80,82,78,78,68),
mk("HBX31","The Middle East Arms Race in One Chart","Military spending as % of GDP for every MENA country vs global average since 2000","CHART","Middle East","Line chart","middle_east/military","SIPRI: Military expenditure (sipri.org); World Bank: GDP (worldbank.org)",75,62,78,72,78,70,70,85),
mk("HBX32","Rural Americas Aging Crisis: Counties Where the Median Age Is Over 50","Mapped against healthcare access and immigration — the workforce that isnt coming","MAP","US-county","County choropleth","rural/demographics","Census: ACS age (census.gov/acs); HRSA: Provider shortage (hrsa.gov); USDA: Rural atlas (ers.usda.gov)",80,75,75,72,78,80,70,80),
mk("HBX33","The Law of Unintended Consequences: Three Strikes Sentencing and Its Aftermath","States that adopted three-strikes laws mapped against recidivism and cost outcomes","CHART","US-state","Line chart","law/crime","USSC: Sentencing data (ussc.gov); BJS: Recidivism (bjs.gov); Vera: Incarceration costs (vera.org)",82,72,75,78,80,68,75,78),
mk("HBX34","Where the Entertainment Dollar Goes: The Streaming Economy Mapped","Revenue flow from your $15/mo subscription to content creators by geography","CHART","World","Special map","entertainment/finance","SEC: Streaming company filings (sec.gov); BLS: Media employment (bls.gov); PwC: Media outlook (pwc.com)",68,80,65,72,60,72,78,62),
mk("HBX35","The Manufacturing Paradox: Output Is at Record Highs While Employment Hits Record Lows","US manufacturing output vs employment diverging since 1990 — automation visualized","CHART","US","Line chart","manufacturing/technology","BLS: Manufacturing output (bls.gov); Federal Reserve: Industrial production (fred.stlouisfed.org)",80,72,82,80,75,70,72,88),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HBX ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HBX batch)")
