import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=v*3.0+e*2.5+s*2.0+o*1.75+t*1.75+r*2.0+c*1.5
    base=raw/14.5
    fl=0.85 if min(e,r,c,s,t,v,o)<35 else 1.0
    pen=1.0-0.35*(1.0-dr/100.0)
    vs=int(base*fl*pen)
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("heh01","Lithium Refining Bottleneck","Global lithium refining capacity by country vs. projected EV battery demand through 2035","CHART","world","area-chart","Economy & Trade","IEA: Critical Minerals (iea.org/minerals)",58,52,74,72,68,62,68,85),
mk("heh02","Abandoned Factory Redevelopment","Former manufacturing sites converted to housing, parks, or tech hubs mapped with investment data","MAP","usa","dot-density","Economy & Trade","EPA: Brownfields Data (epa.gov/brownfields)",58,65,68,65,52,74,62,80),
mk("heh03","Whiskey Distillery Boom","Craft whiskey distillery openings per year by state mapped with bourbon trail tourism revenue","MAP","usa","dot-density","Economy & Trade","TTB: Permits + KDA (ttb.gov)",48,62,68,62,42,74,55,82),
mk("heh04","Critical Mineral Mining Permits","Pending and approved critical mineral mine permits in the US mapped with estimated timeline to production","MAP","usa","dot-density","Economy & Trade","USGS: Critical Minerals (usgs.gov/minerals)",55,48,72,70,65,72,66,80),
mk("heh05","Textile Waste Export Map","Used clothing exports from the US and EU by destination country with environmental impact","MAP","world","flow-map","Environment & Climate","UN Comtrade: Textile Waste (comtrade.un.org)",62,58,68,74,65,76,68,82),
mk("heh06","Small Arms Manufacturing Hotspots","Countries producing the most small arms and light weapons mapped with conflict zone exports","MAP","world","flow-map","Conflict & Security","Small Arms Survey (smallarmssurvey.org)",62,48,70,68,74,76,65,80),
mk("heh07","Plastic Recycling Myth","Percentage of plastic actually recycled vs. collected for recycling by type and country","CHART","world","bar-chart","Environment & Climate","OECD: Global Plastics Outlook (oecd.org)",68,72,74,80,72,60,68,85),
mk("heh08","Exvangelical Movement Geography","Google search trends for deconstruction and exvangelical by state mapped with church attendance decline","MAP","usa","bivariate-choropleth","Culture & Religion","Google Trends + Gallup (trends.google.com)",62,65,62,72,58,66,72,75),
mk("heh09","Anti-Conversion Therapy Laws","Countries and states banning conversion therapy mapped with estimated prevalence of practice","MAP","world","choropleth","Culture & Religion","ILGA: State-Sponsored Homophobia (ilga.org)",72,58,70,65,76,66,65,80),
mk("heh10","Religious Trauma Syndrome Awareness","Mental health professionals treating religious trauma by metro area mapped with evangelical density","MAP","usa","bivariate-choropleth","Health & Wellbeing","RTS Research + ARDA (recoveringfromreligion.org)",65,58,60,74,62,62,74,68),
mk("heh11","Papal Visit Economic Impact","Economic activity generated by papal visits to cities worldwide over 30 years","MAP","world","proportional-symbol","Economy & Trade","Vatican Press + Economic Studies (vaticannews.va)",50,52,70,68,42,68,62,75),
mk("heh12","Scientology Real Estate Empire","Properties owned by the Church of Scientology worldwide mapped with assessed value","MAP","world","dot-density","Economy & Trade","Property Records + Press Investigations (tampabay.com)",55,52,62,78,65,72,78,68),
mk("heh13","Halal Food Market Growth","Global halal food market size by country with growth rate and certification infrastructure","MAP","world","choropleth","Economy & Trade","DinarStandard: State of Islamic Economy (dinarstandard.com)",48,52,72,68,45,66,62,80),
mk("heh14","Sunday Alcohol Sales Holdouts","Counties that still restrict Sunday alcohol sales mapped with religious affiliation data","MAP","usa","choropleth","Culture & Religion","NABCA: Alcohol Control States (nabca.org)",48,72,70,68,45,68,58,85),
mk("heh15","Influencer Economy Size by Platform","Creator economy revenue by platform — YouTube, TikTok, Instagram, Twitch — over 5 years","CHART","world","area-chart","Economy & Trade","SignalFire: Creator Economy (signalfire.com)",52,68,72,68,48,58,55,78),
mk("heh16","Deepfake Detection Failures","Documented cases of deepfakes causing real harm — fraud, political, revenge — mapped by country","MAP","world","dot-density","Technology & Data","Sensity AI: Deepfake Reports (sensity.ai)",65,58,65,78,72,66,74,72),
mk("heh17","TV Show Filming Location Tourism","Tourism revenue boost in cities after becoming filming locations for major TV shows","MAP","world","proportional-symbol","Economy & Trade","Film Commissions + Tourism Boards (afci.org)",50,65,68,68,42,72,58,75),
mk("heh18","Award Show Viewership Collapse","Oscar, Grammy, Emmy viewership over 30 years with streaming availability milestones","CHART","usa","line-chart","Media & Information","Nielsen: Award Show Ratings (nielsen.com)",55,72,74,65,55,55,52,88),
mk("heh19","Comic Book Store Survival","Independent comic book stores per capita by metro area mapped with digital comic sales growth","MAP","usa","dot-density","Economy & Trade","Diamond: Comics Distribution (diamondcomics.com)",48,60,65,65,48,68,58,75),
mk("heh20","NFT Market Collapse Timeline","NFT trading volume and average price over time with major project failures marked","CHART","world","area-chart","Technology & Data","Dune Analytics: NFT Data (dune.com)",58,62,72,70,65,58,62,85),
mk("heh21","Local Theater Company Density","Non-profit theater companies per capita by metro area mapped with arts funding levels","MAP","usa","dot-density","Culture & Religion","TCG: Theatre Facts (tcg.org)",48,58,65,60,42,68,55,78),
mk("heh22","Flat Earth Believer Geography","Flat earth conference attendance and social media group membership by metro area","MAP","usa","dot-density","Culture & Religion","FEIC: Conference Data + Social Media Analysis (tfes.org)",42,58,55,82,42,62,78,65),
mk("heh23","Worlds Most Pointless Borders","International borders that run through buildings, bedrooms, and golf courses mapped","MAP","world","dot-density","Politics & Governance","Atlas Obscura: Border Oddities (atlasobscura.com)",38,62,58,85,35,78,85,80),
mk("heh24","Couch to 5K Dropout Curve","Completion rates for popular running apps by week showing where most people quit","CHART","world","area-chart","Health & Wellbeing","Strava: Year in Sport (strava.com)",50,82,72,68,48,58,62,72),
mk("heh25","Gender Reveal Party Damage Map","Property damage and injuries from gender reveal parties mapped by incident type","MAP","usa","dot-density","Public Safety","CPSC + Fire Incident Reports (cpsc.gov)",48,72,58,82,52,65,80,70),
mk("heh26","Passive Aggressive Note Geography","Most common passive aggressive complaint topics by city from apartment review data","MAP","usa","choropleth","Culture & Religion","ApartmentRatings + Yelp (apartmentratings.com)",38,80,55,72,38,58,75,68),
mk("heh27","Americans Who Think Chocolate Milk Comes From Brown Cows","Food misconception survey results by demographic — milk origin, GMO beliefs, organic confusion","CHART","usa","bar-chart","Agriculture & Food","Innovation Center: Consumer Survey (usdairy.com)",42,78,65,85,38,55,78,78),
mk("heh28","Participation Trophy Era Results","Youth sports dropout rates and competitive outcomes before and after participation trophy era by decade","CHART","usa","line-chart","Sports & Recreation","Aspen Institute: Project Play (aspenprojectplay.org)",50,75,62,72,52,55,68,75),
mk("heh29","Ship Recycling Beaches","Ship-breaking yards in South Asia mapped with worker fatality rates and toxic exposure data","MAP","world","dot-density","Labor & Work","NGO Shipbreaking Platform (shipbreakingplatform.org)",72,50,68,72,78,76,70,75),
mk("heh30","Meat Alternative Factory Locations","Plant-based and cultivated meat production facilities by metro area with market share trends","MAP","usa","dot-density","Agriculture & Food","GFI: Company Database (gfi.org)",48,55,70,68,48,68,62,78),
mk("heh31","Wedding Industry Inflation","Average wedding cost by metro area adjusted for inflation over 30 years vs. median income growth","MAP","usa","choropleth","Economy & Trade","The Knot: Real Weddings (theknot.com)",52,78,72,68,55,62,55,82),
mk("heh32","Worlds Most Dangerous Tourist Selfie Spots Revisited","Tourist injury and death rates at viral Instagram spots mapped with safety infrastructure spending","MAP","world","dot-density","Health & Wellbeing","WHO + Tourism Safety Reports (who.int)",55,62,60,78,58,74,72,70),
mk("heh33","Weapons Grade Uranium Stockpile","Countries with weapons-grade highly enriched uranium stockpiles mapped with reduction progress","MAP","world","proportional-symbol","Conflict & Security","IPFM: Fissile Material Stocks (fissilematerials.org)",60,42,70,72,80,70,68,78),
mk("heh34","Fast Fashion Return Landfill Pipeline","Percentage of online fast fashion purchases returned and ultimate destination — resale, landfill, export","CHART","world","bar-chart","Environment & Climate","Optoro: Returns Data (optoro.com)",62,68,70,76,65,58,68,78),
mk("heh35","Murphy Bed Comeback","Murphy bed and micro-apartment furniture sales by metro area mapped with average apartment size decline","MAP","usa","dot-density","Economy & Trade","Resource Furniture + Census Housing (resourcefurniture.com)",42,68,62,72,40,66,68,72),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HEH batch)")
