import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDJ01","The Motherhood Penalty: Earnings Trajectory Before and After First Child by Gender","Womens earnings drop 30% after first child and never fully recover while mens are unaffected — the data across 10 countries","CHART","World","Line chart","gender","Kleven et al: Child Penalties Across Countries (nber.org/papers/w25524)",78,78,75,72,72,62,68,82),
mk("HDJ02","Redlining Legacy: 1930s HOLC Maps vs Modern Neighborhood Health Outcomes","Overlay of historical redlining grades with present-day life expectancy, asthma rates, and tree canopy — the 90-year echo","MAP","US","Bivariate choropleth","race","University of Richmond: Mapping Inequality (dsl.richmond.edu/panorama/redlining)",82,72,72,78,78,82,72,85),
mk("HDJ03","Asylum Processing Times: Average Wait From Application to Decision by Country","How long asylum seekers wait for a decision — from months in Canada to years in the US, UK, and Germany","RANK","World","Bar chart","immigration","UNHCR: Asylum Decisions Statistics (unhcr.org/refugee-statistics)",72,65,72,68,78,58,62,82),
mk("HDJ04","Catalytic Converter Theft Surge: Thefts Per 100K Vehicles by Metro Area","The 2020-2024 catalytic converter theft epidemic mapped — which metros got hit hardest and which vehicles are targeted most","MAP","US","Dot map","crime","NICB: National Insurance Crime Bureau (nicb.org)",58,72,68,72,62,72,68,75),
mk("HDJ05","The Glass Ceiling Index: Women in C-Suite Positions by Industry","Percentage of CEO, CFO, and board positions held by women across 15 industries — tech and finance still lag dramatically","RANK","US","Bar chart","gender","McKinsey: Women in the Workplace (womenintheworkplace.com)",68,72,72,62,68,58,58,82),
mk("HDJ06","Sundown Towns: Historical All-White Communities and Their Demographics Today","Former sundown towns — communities that enforced racial exclusion — mapped against their current racial demographics","MAP","US","Dot map","race","Loewen: Sundown Towns Database (sundown.tougaloo.edu)",80,68,65,78,80,78,78,72),
mk("HDJ07","Deportation Flights: ICE Air Operations Routes and Volume","Flight paths and frequency of ICE deportation flights from detention centers to destination countries — the invisible airline","MAP","US","Line map","immigration","ICE: ERO Annual Report + Flight Tracking Data (ice.gov)",72,58,65,75,80,78,74,70),
mk("HDJ08","Carjacking Hotspots: Vehicle Theft at Gunpoint by City 2019 vs 2024","The carjacking surge mapped — cities where armed vehicle theft doubled or tripled in five years","MAP","US","Dot map","crime","FBI: NIBRS Carjacking Data (crime-data-explorer.fr.cloud.gov)",68,72,68,68,78,72,62,75),
mk("HDJ09","Paternity Leave Uptake: Fathers Who Actually Take Parental Leave by Country","Countries that offer paternity leave vs how many fathers actually use it — Japan offers a year but under 15% take any","RANK","World","Bar chart","gender","OECD: Family Database (oecd.org/els/family/database)",62,72,72,78,58,58,68,82),
mk("HDJ10","Racial Wealth Gap: Median Net Worth by Race and Age Cohort","The staggering wealth gap — white families hold $188K median net worth vs $24K for Black families, and how it compounds with age","CHART","US","Bar chart","race","Federal Reserve: Survey of Consumer Finances (federalreserve.gov/econres/scfindex.htm)",78,72,75,68,78,62,58,88),
mk("HDJ11","Sanctuary Jurisdiction Map: Cities and Counties That Limit ICE Cooperation","Every jurisdiction with policies limiting local law enforcement cooperation with immigration enforcement — the evolving patchwork","MAP","US","County choropleth","immigration","ILRC: Immigrant Legal Resource Center (ilrc.org/local-enforcement-map)",62,62,72,62,72,78,58,82),
mk("HDJ12","Package Theft Epidemic: Porch Piracy Rates by Metro Area","Estimated package thefts per 1000 deliveries by metro — the cities where your Amazon box is most likely to vanish","MAP","US","Dot map","crime","C+R Research: Package Theft Statistics (crresearch.com)",55,82,65,68,58,68,62,65),
mk("HDJ13","Period Poverty: Percentage of Menstruating People Who Cant Afford Supplies by Country","The hidden cost of menstruation — countries where significant portions of women and girls cant afford pads or tampons","MAP","World","World choropleth","gender","Plan International: Period Poverty Reports (plan-international.org)",75,68,68,72,68,68,72,65),
mk("HDJ14","Police Use of Force: Officer-Involved Shootings Per 10K Arrests by Department","Which police departments use lethal force most frequently when adjusted for arrest volume — the 10x variation between cities","MAP","US","Dot map","race","Mapping Police Violence: MPV Database (mappingpoliceviolence.us)",78,68,72,72,85,75,65,82),
mk("HDJ15","Visa Overstays vs Border Crossings: How People Actually Become Undocumented","Breakdown of how unauthorized immigrants enter the US — visa overstays consistently outnumber illegal border crossings","CHART","US","Bar chart","immigration","DHS: Entry/Exit Overstay Report (dhs.gov)",65,62,78,78,68,58,68,82),
mk("HDJ16","Retail Theft Reality Check: Actual Shoplifting Rates vs Corporate Shrinkage Claims","What the data actually shows about retail theft vs what retailers claim — the gap between narrative and evidence","CHART","US","Bar chart","crime","National Retail Federation: Retail Security Survey (nrf.com) vs FBI UCR (ucr.fbi.gov)",62,72,72,78,65,58,72,72),
mk("HDJ17","The Pink Tax Quantified: Price Difference for Identical Products Marketed to Women","Price comparison of functionally identical products — razors, shampoo, deodorant — in mens vs womens versions by category","CHART","US","Bar chart","gender","NYC DCA: From Cradle to Cane Cost of Being a Female Consumer (nyc.gov)",68,82,72,68,65,55,62,78),
mk("HDJ18","Environmental Racism: Proximity of Toxic Sites to Majority-Minority Neighborhoods","Distance from EPA Superfund sites and TRI facilities to communities by racial composition — the pattern is unmistakable","MAP","US","Bivariate choropleth","race","EPA: EJScreen Environmental Justice Tool (ejscreen.epa.gov)",78,65,70,72,80,78,65,85),
mk("HDJ19","Remittance Corridors: Money Sent Home by Immigrants by Origin-Destination Pair","Largest remittance flows — US to Mexico, Gulf States to India, UK to Nigeria — mapped as proportional flow lines","MAP","World","Line map","immigration","World Bank: Bilateral Remittance Matrix (worldbank.org/en/topic/migrationremittancesdiasporaissues)",62,62,72,68,55,78,68,85),
mk("HDJ20","Hate Crime Reporting Gap: Agencies That Submit vs Dont Submit Hate Crime Data to FBI","Over 40% of police agencies dont report hate crime data to the FBI — the massive gap in what we actually know","MAP","US","County choropleth","crime","FBI: Hate Crime Statistics (crime-data-explorer.fr.cloud.gov)",72,62,68,78,78,72,68,78),
mk("HDJ21","Maternal Mortality by Race: Pregnancy-Related Deaths Per 100K Births Across Demographics","Black women die in childbirth at 3x the rate of white women — the gap that persists even controlling for income and education","CHART","US","Bar chart","gender","CDC: Pregnancy Mortality Surveillance (cdc.gov/reproductivehealth/maternal-mortality)",85,72,75,68,82,58,60,88),
mk("HDJ22","Tribal Land Loss: Native American Reservation Acreage From Treaty Boundaries to Today","How much land Indigenous nations lost — original treaty boundaries vs current reservation boundaries overlaid","MAP","US","Special map","race","Native Land Digital: Territory Map (native-land.ca)",82,62,68,72,82,85,72,75),
mk("HDJ23","TPS Holders Map: Temporary Protected Status Recipients by Country of Origin and US Location","Where TPS holders from El Salvador, Honduras, Haiti, Ukraine, and Venezuela live across the US","MAP","US","Dot map","immigration","USCIS: Temporary Protected Status (uscis.gov/humanitarian/temporary-protected-status)",62,58,72,62,65,72,62,80),
mk("HDJ24","Organized Retail Crime: Multi-Store Theft Ring Busts by Metro Area","Major organized retail crime ring takedowns mapped — the difference between individual shoplifting and coordinated theft operations","MAP","US","Dot map","crime","ORAL: Organized Retail Crime Association (orcagroup.org)",58,62,65,70,68,72,66,65),
mk("HDJ25","Gender Pay Gap by Occupation: Cents on the Dollar for Same Job Title","The pay gap isnt just about career choice — within the same occupation, women earn 82-95 cents on the dollar depending on field","CHART","US","Bar chart","gender","BLS: Median Weekly Earnings by Occupation and Sex (bls.gov/cps/cpsaat39.htm)",72,78,78,62,68,58,55,90),
mk("HDJ26","School Segregation Rebound: How Resegregated Are Americas Public Schools","Exposure index showing how racially isolated students have become since the end of court-ordered desegregation","CHART","US","Line chart","race","UCLA: Civil Rights Project (civilrightsproject.ucla.edu)",78,68,72,72,78,65,68,85),
mk("HDJ27","Naturalization Wait Times: Average Processing Time for Citizenship by USCIS Office","How long it takes to become a US citizen depending on which office handles your case — 6 months in some, 2+ years in others","MAP","US","Dot map","immigration","USCIS: Processing Time Information (egov.uscis.gov/processing-times)",65,68,72,68,65,68,58,85),
mk("HDJ28","The Murder Clearance Crisis: Percentage of Homicides Solved by Police Department","Murder solve rates have plummeted from 90% in 1965 to under 50% nationally — and some cities clear fewer than 20% of cases","MAP","US","Dot map","crime","Murder Accountability Project (murderdata.org)",78,68,72,78,82,72,68,85),
mk("HDJ29","Femicide Map: Countries With the Highest Rates of Women Killed by Intimate Partners","Femicide rates per 100K women by country — the nations where being female is most dangerous","MAP","World","World choropleth","gender","UN Women: Global Database on Violence Against Women (evaw-global-database.unwomen.org)",82,62,68,65,82,72,62,78),
mk("HDJ30","Racial Disparities in School Discipline: Suspension Rates by Race and School District","Black students suspended at 3-4x the rate of white students in the same districts — the discipline gap mapped","MAP","US","Bivariate choropleth","race","DOE: Civil Rights Data Collection (ocrdata.ed.gov)",75,68,72,68,78,72,62,88),
mk("HDJ31","Border Wall Coverage: Physical Barriers Along the US-Mexico Border by Type and Year Built","Mile-by-mile map of what type of barrier exists along the 1,954-mile border — wall, fence, vehicle barrier, or nothing","MAP","US","Line map","immigration","CBP: Border Barrier Status (cbp.gov)",60,62,75,62,68,82,58,82),
mk("HDJ32","Recidivism Roulette: Re-Arrest Rates by State and Crime Type Within 5 Years","How likely someone is to be rearrested within 5 years of release varies wildly by state — from 40% to 80%","MAP","US","State choropleth","crime","Bureau of Justice Statistics: Recidivism Studies (bjs.ojp.gov)",68,62,72,68,72,68,65,82),
mk("HDJ33","Womens Suffrage Timeline: When Women Won the Right to Vote in Every Country","Year women gained full voting rights by country — from New Zealand in 1893 to Saudi Arabia in 2015","MAP","World","World choropleth","gender","UN Women: Progress of the Worlds Women (unwomen.org)",72,62,78,65,62,78,58,92),
mk("HDJ34","The Apology Map: States That Have Formally Apologized for Slavery or Jim Crow","Which US states have passed formal resolutions apologizing for slavery and segregation — fewer than you think","MAP","US","State choropleth","race","State Legislature Archives: Formal Apology Resolutions (various state legislature sites)",72,62,65,75,68,72,72,72),
mk("HDJ35","DACA Population Map: Where Dreamers Live and Work Across the US","Geographic distribution of DACA recipients by metro area — concentrated in California, Texas, Illinois, and New York","MAP","US","Dot map","immigration","USCIS: DACA Population Data (uscis.gov/tools/reports-and-studies)",68,68,72,58,65,75,58,85),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDJ batch)")
