import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDH01","Democracy in Retreat: Countries That Became Less Democratic Since 2010","V-Dem democracy index change 2010-2024 — which nations backslid the most, from Hungary and Turkey to India and Tunisia","MAP","World","World choropleth","democracy","V-Dem: Varieties of Democracy Dataset (v-dem.net)",72,62,72,68,78,78,65,88),
mk("HDH02","Permafrost Thaw Map: Ground Temperature Change Across the Arctic Since 1980","How much permafrost has warmed at monitoring stations across Alaska, Siberia, Canada, and Scandinavia — the ticking carbon bomb","MAP","World","Dot map","climate","Global Terrestrial Network for Permafrost: GTN-P (gtnp.arcticportal.org)",72,52,68,72,80,78,72,80),
mk("HDH03","Drone Warfare Atlas: Countries Where the US Has Conducted Drone Strikes","Every confirmed US drone strike location across Pakistan, Yemen, Somalia, Libya, Syria, Iraq, and Afghanistan with estimated casualties","MAP","World","Dot map","war","Bureau of Investigative Journalism: Drone Strikes Database (thebureauinvestigates.com/projects/drone-war)",78,58,70,68,82,80,68,82),
mk("HDH04","The Container Ship Chokepoint Map: Where Global Trade Can Be Cut Off","Percentage of world trade flowing through each maritime chokepoint — Strait of Malacca, Suez, Panama, Hormuz, Bab el-Mandeb","MAP","World","Line map","trade","UNCTAD: Review of Maritime Transport (unctad.org/rmt)",68,58,75,72,78,82,70,82),
mk("HDH05","Election Denial Map: Candidates Who Refused to Concede After Losing Since 2020","US candidates at every level who denied election results after losing — mapped by state and office level","MAP","US","State choropleth","democracy","States United Democracy Center: Election Denier Tracking (statesuniteddemocracy.org)",72,68,68,68,80,72,68,75),
mk("HDH06","Glacier Retreat Timelapse: Ice Volume Loss in Major Mountain Ranges Since 1960","Annual glacier mass balance for the Alps, Himalayas, Andes, Rockies, and East Africa — the acceleration is visible","CHART","World","Line chart","climate","WGMS: World Glacier Monitoring Service (wgms.ch)",75,55,70,68,78,80,65,85),
mk("HDH07","The Sanctions Web: Every Country Under US Economic Sanctions and Why","Map of all countries, entities, and individuals under active US Treasury OFAC sanctions — the invisible architecture of American power","MAP","World","World choropleth","war","US Treasury: OFAC Sanctions Programs (ofac.treasury.gov)",62,52,72,70,75,78,72,88),
mk("HDH08","Rare Earth Supply Chain: Who Mines, Refines, and Consumes Critical Minerals","Flow diagram of rare earth elements from mine to product — Chinas dominance at every stage of the supply chain","CHART","World","Scatter plot","trade","USGS: Mineral Commodity Summaries (usgs.gov/centers/national-minerals-information-center)",62,52,72,75,72,68,72,85),
mk("HDH09","Voter ID Strictness Map: What You Need to Vote in Each State","State-by-state comparison of voter ID requirements — from no ID needed to strict photo ID only — mapped against turnout changes","MAP","US","State choropleth","democracy","National Conference of State Legislatures: Voter ID Laws (ncsl.org/elections-and-campaigns/voter-id)",65,72,78,62,72,75,58,90),
mk("HDH10","Urban Heat Island Intensity: Temperature Difference Between City Centers and Suburbs","How much hotter downtown areas are compared to surrounding suburbs in the 100 largest US metros — Phoenix at 10F+ difference","MAP","US","Dot map","climate","EPA: Heat Island Effect Data (epa.gov/heatislands)",68,72,72,68,65,78,62,82),
mk("HDH11","Cluster Munition Usage: Every Documented Use of Banned Weapons Since 2008","Map of confirmed cluster munition strikes after the Convention on Cluster Munitions — Syria, Ukraine, Yemen, Libya","MAP","World","Dot map","war","Cluster Munition Monitor: Annual Reports (the-monitor.org/en-gb/the-issues/cluster-munitions)",80,52,68,68,85,78,68,78),
mk("HDH12","Americas Trade Deficit by Product: What We Import Most From Each Country","Top import from each trading partner — semiconductors from Taiwan, oil from Canada, cars from Mexico, everything from China","MAP","World","World choropleth","trade","Census Bureau: USA Trade Online (usatrade.census.gov)",55,62,75,68,58,72,62,90),
mk("HDH13","Gerrymandering Scorecard: Most Distorted Congressional District Maps by State","Efficiency gap and compactness scores for every states congressional map — which states have the most partisan gerrymanders","RANK","US","Bar chart","democracy","Princeton Gerrymandering Project: Report Card (gerrymander.princeton.edu)",68,65,72,68,78,68,65,82),
mk("HDH14","Wildfire Season Length: How Many More Burn Days Per Year Since 1970","The extension of wildfire season across western states — some regions now burning 80+ more days per year than in the 1970s","CHART","US","Line chart","climate","NIFC: National Interagency Fire Center (nifc.gov/fire-information/statistics)",72,68,75,68,78,72,60,88),
mk("HDH15","Arms Sales Leaderboard: Top 10 Weapons Exporting Nations and Their Customers","Who sells weapons to whom — the US, Russia, France, China network of arms deals mapped as flows between countries","CHART","World","Scatter plot","war","SIPRI: Arms Transfers Database (sipri.org/databases/armstransfers)",65,52,72,68,78,70,68,90),
mk("HDH16","Lithium Triangle: South Americas Critical Role in the Battery Metal Supply Chain","Chile, Argentina, and Bolivia control 60% of known lithium reserves — mapped with extraction sites and export flows","MAP","South America","Special map","trade","USGS: Lithium Statistics (usgs.gov)",62,48,72,72,68,78,72,82),
mk("HDH17","Press Freedom Erosion: Journalists Jailed by Country Over the Past Decade","Number of journalists imprisoned annually by country — China, Turkey, Egypt, Saudi Arabia, Myanmar consistently lead","RANK","World","Bar chart","democracy","Committee to Protect Journalists: Prison Census (cpj.org)",78,58,72,65,82,62,65,88),
mk("HDH18","Coral Reef Bleaching: Percentage of Reefs Experiencing Severe Bleaching by Ocean Basin","The 4th global bleaching event mapped — which reefs are dying fastest and which show resilience","MAP","World","World choropleth","climate","NOAA: Coral Reef Watch (coralreefwatch.noaa.gov)",78,55,68,68,80,82,62,82),
mk("HDH19","Landmine Legacy: Countries Still Contaminated by Anti-Personnel Mines","Square kilometers of land still contaminated by landmines and unexploded ordnance decades after conflicts ended","MAP","World","World choropleth","war","International Campaign to Ban Landmines: Landmine Monitor (the-monitor.org)",78,55,68,68,78,78,65,85),
mk("HDH20","Port Congestion Index: Average Ship Waiting Time at Major Global Ports","How long container ships wait to dock at the worlds busiest ports — Shanghai, Los Angeles, Rotterdam, Singapore","RANK","World","Bar chart","trade","MarineTraffic: Port Congestion Data (marinetraffic.com)",55,58,72,68,62,65,62,78),
mk("HDH21","Ballot Measure Democracy: States Where Citizens Can Bypass Legislatures","Which states allow citizen initiatives, referendums, and recall elections — the map of direct democracy in America","MAP","US","State choropleth","democracy","Ballotpedia: Forms of Direct Democracy (ballotpedia.org)",60,65,75,62,58,72,62,90),
mk("HDH22","Atmospheric CO2 by Source Country: Cumulative Emissions Responsibility Since 1850","Who put the carbon in the atmosphere — cumulative CO2 emissions by country since industrialization, not just current annual output","RANK","World","Bar chart","climate","Global Carbon Project: Carbon Budget (globalcarbonproject.org/carbonbudget)",72,62,75,72,75,65,68,90),
mk("HDH23","Child Soldier Recruitment: Countries Where Minors Are Used in Armed Conflict","Nations where children under 18 are recruited into armed forces or militias — from Myanmar to DRC to Yemen","MAP","World","World choropleth","war","UN: Children and Armed Conflict (childrenandarmedconflict.un.org)",85,58,68,62,85,72,62,78),
mk("HDH24","De-Dollarization Watch: Countries Actively Reducing USD in Foreign Reserves","Central banks shifting reserves from US dollars to gold, yuan, and euros — the share of USD in global reserves dropping","CHART","World","Line chart","trade","IMF: Currency Composition of Official Foreign Exchange Reserves (data.imf.org)",60,52,68,72,70,62,72,85),
mk("HDH25","Dark Money in Politics: Outside Spending by Undisclosed Donors Per Election Cycle","Growth of spending by groups that dont disclose their donors — from negligible in 2004 to billions by 2024","CHART","US","Area chart","democracy","OpenSecrets: Outside Spending (opensecrets.org/outsidespending)",72,68,72,68,80,62,65,85),
mk("HDH26","Sea Level Rise Vulnerability: US Coastal Cities Most at Risk by 2050","Which American coastal cities face the most flooding from projected sea level rise — Miami, New Orleans, Charleston, Norfolk","MAP","US","Dot map","climate","NOAA: Sea Level Rise Viewer (coast.noaa.gov/slr)",78,72,72,65,80,82,58,85),
mk("HDH27","Proxy War Scorecard: Every Active Conflict With Foreign Power Involvement","Map of current armed conflicts color-coded by which major powers are backing which side — the global proxy war network","MAP","World","Special map","war","Council on Foreign Relations: Global Conflict Tracker (cfr.org/global-conflict-tracker)",68,52,65,72,82,82,72,75),
mk("HDH28","Tariff Wall Map: Average Import Tariff Rate by Country and Product Category","Which nations are most protectionist — average applied tariff rates for agriculture, manufactured goods, and services","MAP","World","World choropleth","trade","WTO: Tariff Profiles (wto.org/english/res_e/reser_e/tariff_profiles_e.htm)",55,52,72,65,62,72,60,90),
mk("HDH29","Ranked Choice Voting Adoption: Where Alternative Voting Systems Are Spreading","Map of US jurisdictions that have adopted ranked choice voting — from Alaska and Maine statewide to dozens of cities","MAP","US","Dot map","democracy","FairVote: Where Ranked Choice Voting Is Used (fairvote.org/where_is_ranked_choice_voting_used)",58,62,72,65,55,72,68,88),
mk("HDH30","Tipping Points Tracker: How Close We Are to Irreversible Climate Thresholds","Status dashboard for major climate tipping points — AMOC slowdown, Amazon dieback, ice sheet collapse — current trajectory vs threshold","CHART","World","Bar chart","climate","PIK: Tipping Elements in the Earth System (pik-potsdam.de)",78,58,65,78,85,68,75,72),
mk("HDH31","The Wagner Group Map: Russian Mercenary Deployments Across Africa and the Middle East","Every confirmed Wagner/Africa Corps deployment — Mali, Libya, CAR, Sudan, Syria, Mozambique — with estimated troop numbers","MAP","World","Dot map","war","ACLED: Armed Conflict Location and Event Data (acleddata.com)",68,48,68,72,80,80,72,75),
mk("HDH32","Semiconductor Trade Dependencies: Which Countries Cant Make Chips Without Each Other","The impossibly tangled supply chain of chip manufacturing — Dutch lithography, Japanese chemicals, Taiwanese fabrication, American design","CHART","World","Scatter plot","trade","SIA: State of the US Semiconductor Industry (semiconductors.org)",60,48,68,75,72,65,75,80),
mk("HDH33","Polling Place Closures: Voting Locations Eliminated Since the Shelby County Decision","Polling places closed since 2013 in states formerly covered by Voting Rights Act preclearance — concentrated in minority communities","MAP","US","Dot map","democracy","Leadership Conference on Civil Rights: Polling Place Closures (civilrights.org)",78,68,72,70,82,78,68,78),
mk("HDH34","Methane Hotspots: Largest Methane Emission Plumes Detected by Satellite","Individual methane super-emitter events detected by satellite — oil fields, landfills, coal mines, and cattle operations","MAP","World","Dot map","climate","UNEP: International Methane Emissions Observatory (methanedata.unep.org)",68,52,68,75,78,80,72,78),
mk("HDH35","Food as Weapon: Countries Using Export Bans During Global Food Crises","Nations that banned food exports during the 2022 food crisis — Indias wheat ban, Indonesias palm oil ban, and the cascade effect","MAP","World","World choropleth","trade","IFPRI: Food and Fertilizer Export Restrictions Tracker (ifpri.org)",70,62,70,75,78,72,72,80),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDH batch)")
