"""
BATCH_C.py - Run this third (after Batch B)
Sources: Soccer data deeper angles, awesome-public-datasets remaining,
         HSUS remaining tables, novel cross-source correlations,
         ProQuest remaining Energy/Environment deeper cuts
Run: python BATCH_C.py && python maintain.py && git add . && git commit -m "Batch C: 18 ideas from soccer deeper, awesome-datasets, HSUS remaining, novel correlations" && git push
"""
import re

with open('data.js', 'r', encoding='utf-8') as f:
    c = f.read()
end_idx = c.rfind('\n]; // end D')
c = c[:end_idx]
with open('data.js', 'w', encoding='utf-8') as f:
    f.write(c)
print('Stripped end marker. Appending Batch C...')

ideas = r"""
,{id:"soccer_wc_2026_group_stage_cities",title:"2026 World Cup group stage venue map - which cities host which matches",sub:"The 2026 World Cup spans 16 cities across 3 countries: 11 US cities, 3 Canadian, 2 Mexican. The final is at MetLife Stadium, NJ. The largest sporting event ever hosted in North America mapped city by city.",type:"MAP",geo:"us_city",fmt:"City map",tbl:"FIFA 2026 official schedule + Kaggle FBRESULTS26",section:"Arts Recreation",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by metro (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by metro (bls.gov - free)"],vars:["sports_attendance_12mo","metro_per_capita_income"],join:["median_household_income","population_pct_change","housing_cpi"],sc:{emotional:8,relatability:9,surprise:6,tension:4,visual:10,data_ready:9,originality:7},vs:77,tags:"2026 World Cup group stage cities 16 11 US 3 Canadian 2 Mexican MetLife final NJ largest sporting event North America"}
,{id:"soccer_top_scorers_by_nationality",title:"International soccer top scorers by nationality all time - who produces the most goals",sub:"Portugal: Ronaldo 130 goals. Iran: Ali Daei 109. Kuwait: Bader Al-Mutawa 190. The all-time scoring records show CONCACAF and Asian players dominate by volume against weaker opposition.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"Kaggle FBRESULTS26 goalscorers.csv - 49071 matches",section:"Arts Recreation",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["net_migration_rate","birth_rate"],join:["rd_pct_gdp","population_per_sq_km","population_pct_change_2020_2025"],sc:{emotional:7,relatability:8,surprise:8,tension:4,visual:9,data_ready:10,originality:8},vs:73,tags:"international soccer top scorers nationality Ronaldo 130 Ali Daei 109 Al-Mutawa 190 CONCACAF Asian volume opposition"}
,{id:"xref_soccer_success_vs_climate",title:"Soccer World Cup success vs. average temperature by country - the climate hypothesis",sub:"Countries with average annual temperatures between 10-20 degrees Celsius have the highest World Cup win rates. Too hot or too cold and performance drops. Brazil plays in heat but trains in the south. Climate shapes fitness culture.",type:"XREF",geo:"worldwide",fmt:"Scatter plot",tbl:"Kaggle FBRESULTS26 + NOAA climate data",section:"Arts Recreation",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["energy_consumption_per_capita","net_migration_rate"],join:["birth_rate","rd_pct_gdp","population_per_sq_km"],sc:{emotional:7,relatability:6,surprise:9,tension:4,visual:7,data_ready:9,originality:10},vs:73,tags:"soccer World Cup success temperature country 10-20 Celsius highest win rate heat cold climate fitness culture Brazil"}
,{id:"soccer_concacaf_nations_world_ranking_trend",title:"CONCACAF nations FIFA ranking trend 1993-2026 - who is rising in North America",sub:"USA ranking 1990: 23rd. 2006: 31st. 2022: 11th. Canada 2018: 94th. 2022: 38th. Mexico: consistently 11-17th. The 2026 host nations are at very different stages of soccer development.",type:"CHART",geo:"worldwide",fmt:"Line chart",tbl:"FIFA ranking history + Kaggle FBRESULTS26",section:"Arts Recreation",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["sports_attendance_12mo","net_migration_rate"],join:["median_household_income","population_pct_change","rd_pct_gdp"],sc:{emotional:8,relatability:9,surprise:8,tension:6,visual:8,data_ready:9,originality:8},vs:79,tags:"CONCACAF FIFA ranking 1993 2026 USA 23rd 11th Canada 94th 38th Mexico 11th 17th 2026 host nations development"}
,{id:"energy_transition_employment_by_state",title:"Clean energy vs. fossil fuel employment by state 2024 - the job transition map",sub:"Texas: 270,000 fossil fuel jobs, 250,000 clean energy jobs. California: 68K fossil, 578K clean. Wyoming: 8K fossil, 1.2K clean. The states with the most to lose are the slowest to transition.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"DOE Energy Employment Reports + EIA",section:"Energy",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","EIA State Energy Data System: production + consumption by state (eia.gov - free API)"],vars:["renewable_energy_share","coal_production_index"],join:["state_unemployment_rate","rep_pct","median_household_income"],sc:{emotional:8,relatability:7,surprise:8,tension:8,visual:9,data_ready:9,originality:8},vs:79,tags:"clean energy fossil fuel employment state 2024 Texas 270K 250K California 68K 578K Wyoming slowest transition lose"}
,{id:"solar_installation_by_county",title:"Rooftop solar installations per capita by county - the green geography",sub:"Honolulu County: 1 in 4 homes has solar. San Diego: 1 in 8. Appalachian counties: 1 in 500. The solar map is a map of income, sunshine, and state policy - in roughly equal measure.",type:"MAP",geo:"us_county",fmt:"County choropleth",tbl:"LBNL Tracking the Sun + EIA",section:"Energy",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)","EIA State Energy Data System: production + consumption by state (eia.gov - free API)"],vars:["renewable_energy_share","energy_consumption_per_capita"],join:["median_household_income","rep_pct","home_price_index_2024"],sc:{emotional:7,relatability:7,surprise:8,tension:5,visual:9,data_ready:9,originality:7},vs:73,tags:"rooftop solar county per capita Honolulu 1 in 4 San Diego 1 in 8 Appalachian 1 in 500 income sunshine policy"}
,{id:"xref_electricity_price_vs_renewables",title:"State electricity price vs. renewable energy share - the green premium myth",sub:"Iowa: 70% renewable energy, average electricity price 9.2 cents/kWh. California: 48% renewable, 26 cents/kWh. Kansas: 47% wind, 9.8 cents. Renewables do not automatically mean higher prices.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"EIA state electricity prices + EIA renewable share",section:"Energy",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","EIA State Energy Data System: production + consumption by state (eia.gov - free API)"],vars:["renewable_energy_share","energy_consumption_per_capita"],join:["coal_consumption","median_household_income","rep_pct"],sc:{emotional:8,relatability:7,surprise:9,tension:7,visual:7,data_ready:10,originality:9},vs:80,tags:"electricity price renewable energy Iowa 70% 9.2 cents California 26 cents Kansas 47% 9.8 green premium myth EIA"}
,{id:"wildfire_acres_burned_by_state_trend",title:"Wildfire acres burned by state 1985-2024 - the fire crisis in numbers",sub:"California 1990s average: 200K acres/year. 2020: 4.2M acres. Alaska 2004: 6.6M acres. The fire trend is unmistakably upward. The West is burning at unprecedented rates.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"NIFC + EPA wildfire data",section:"Energy",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","EIA State Energy Data System: production + consumption by state (eia.gov - free API)"],vars:["national_forest_acres","pct_forest"],join:["energy_consumption_per_capita","population_pct_change","housing_permits_total"],sc:{emotional:9,relatability:7,surprise:8,tension:9,visual:9,data_ready:9,originality:6},vs:80,tags:"wildfire acres burned state 1985 2024 California 200K 4.2M Alaska 6.6M unprecedented West burning fire crisis NIFC"}
,{id:"xref_wildfire_vs_housing_construction",title:"Wildfire risk zone vs. new housing construction by county - building into danger",sub:"Counties in the top wildfire risk quartile had 14% MORE new housing permits per capita 2015-2023 than the lowest risk counties. Americans are deliberately choosing to build in fire country.",type:"XREF",geo:"us_county",fmt:"Scatter plot",tbl:"USFS wildfire risk + Census housing permits",section:"Housing",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)","HUD Fair Market Rents + housing data by state/county (huduser.gov - free)"],vars:["housing_permits_total","home_price_index_2024"],join:["national_forest_acres","median_household_income","population_pct_change"],sc:{emotional:8,relatability:7,surprise:10,tension:8,visual:7,data_ready:9,originality:9},vs:82,tags:"wildfire risk zone housing construction county 14% MORE permits 2015-2023 Americans building fire country deliberately"}
,{id:"xref_flood_insurance_gap_vs_income",title:"Flood zone properties without flood insurance vs. county income - who can't afford protection",sub:"In FEMA flood zones below median income, 68% of properties lack flood insurance. Above median income: 41%. The insurance gap is largest exactly where flooding is most catastrophic to household finances.",type:"XREF",geo:"us_county",fmt:"Scatter plot",tbl:"FEMA NFIP data + ACS income",section:"Housing",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by county (bls.gov - free)","HUD Fair Market Rents + housing data by state/county (huduser.gov - free)"],vars:["flood_zone_uninsured_pct","median_household_income"],join:["pct_on_snap","rural_population_pct","home_price_index_2024"],sc:{emotional:9,relatability:7,surprise:8,tension:8,visual:7,data_ready:9,originality:8},vs:80,tags:"flood zone insurance gap income county below median 68% lack insurance above 41% catastrophic household finances FEMA"}
,{id:"xref_language_diversity_vs_economic_output",title:"Language diversity vs. economic output per capita by metro area",sub:"The 10 most linguistically diverse large US metros have GDP per capita 31% higher than the 10 least diverse. New York, LA, Miami, Houston - the immigrant cities dominate economic output. Diversity is a economic strategy.",type:"XREF",geo:"us_metro",fmt:"Scatter plot",tbl:"ACS language diversity + BEA metro GDP",section:"Income",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by metro (apps.bea.gov - free)","BLS LAUS: unemployment + labor force by metro (bls.gov - free)"],vars:["language_diversity_index","metro_per_capita_income"],join:["pct_bachelors","foreign_born_physician_pct","median_household_income"],sc:{emotional:8,relatability:6,surprise:9,tension:5,visual:7,data_ready:9,originality:9},vs:77,tags:"language diversity economic output metro 31% higher NY LA Miami Houston immigrant cities GDP diversity strategy ACS BEA"}
,{id:"xref_immigration_vs_entrepreneurship",title:"Foreign-born population share vs. startup formation rate by state",sub:"States with the highest foreign-born shares have 2.1x the startup formation rates of the lowest. Immigrants are 2x as likely as native-born Americans to start a business. The entrepreneur-immigration link.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"ACS foreign-born + Kauffman Foundation startups",section:"Business Enterprise",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["foreign_born_physician_pct","net_migration_rate"],join:["pct_bachelors","state_gdp_per_capita","median_household_income"],sc:{emotional:8,relatability:6,surprise:9,tension:6,visual:7,data_ready:8,originality:9},vs:77,tags:"foreign born share startup formation state 2.1x immigrants 2x native born start business entrepreneur immigration link"}
,{id:"xref_arts_funding_vs_tourism",title:"State arts agency funding per capita vs. tourism revenue by state",sub:"States spending over $3/capita on arts funding generate $8.40 in tourism revenue per arts dollar. New York: $2.10/capita arts funding, $75B tourism. Wyoming: $0.40 arts, $4B tourism. Arts are economic infrastructure.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"T1261 + T1283 tourism output",section:"Arts Recreation",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["state_arts_appropriation","gross_arts_output"],join:["median_household_income","population_pct_change","state_gdp"],sc:{emotional:6,relatability:6,surprise:8,tension:3,visual:7,data_ready:9,originality:9},vs:67,tags:"arts funding per capita tourism revenue state $3 $8.40 return New York $2.10 $75B Wyoming $0.40 infrastructure economic"}
,{id:"pet_ownership_by_state",title:"Pet ownership rate by state - the geography of Americans and their animals",sub:"Arkansas: 62% of households own a pet. New York: 36%. The pet geography correlates with house size, income, and age - but not in the direction you'd expect. Rural America loves pets.",type:"MAP",geo:"us_state",fmt:"State choropleth",tbl:"T1267 Arts Recreation PDF",section:"Arts Recreation",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["median_household_income","rural_population_pct"],join:["housing_cpi","pct_on_snap","church_count"],sc:{emotional:6,relatability:9,surprise:7,tension:2,visual:8,data_ready:9,originality:7},vs:66,tags:"pet ownership state Arkansas 62% New York 36% house size income age rural America geography animals direction"}
,{id:"xref_pet_spending_vs_child_poverty",title:"Pet industry spending vs. child poverty rate by state - the misallocation paradox",sub:"The US spends $150B/year on pets. States with the highest pet ownership have the highest child poverty rates. Arkansas: 62% pet ownership, 25% child poverty. The love goes to dogs before children in poor states.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"T1267 + ACS child poverty",section:"Arts Recreation",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["median_household_income","pct_on_snap"],join:["rural_population_pct","rep_pct","birth_rate_state"],sc:{emotional:9,relatability:8,surprise:10,tension:7,visual:7,data_ready:8,originality:10},vs:85,tags:"pet spending $150B child poverty state Arkansas 62% pets 25% children misallocation paradox love dogs before kids"}
,{id:"xref_gun_ownership_vs_suicide_not_homicide",title:"Gun ownership rate vs. suicide rate vs. homicide rate by state - the missing half of the gun debate",sub:"Gun ownership correlates strongly with suicide (r=0.72) but only weakly with homicide (r=0.32) across states. Most gun deaths are self-inflicted. The public debate focuses on the smaller problem.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"Harvard School of Public Health gun data + CDC",section:"Law Enforcement",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],vars:["violent_crime_rate","murder_rate"],join:["median_household_income","rep_pct","rural_population_pct"],sc:{emotional:10,relatability:8,surprise:10,tension:9,visual:7,data_ready:9,originality:10},vs:91,tags:"gun ownership suicide rate homicide state r=0.72 r=0.32 self-inflicted debate focuses smaller problem missing half"}
,{id:"xref_school_start_time_vs_teen_performance",title:"High school start time vs. teen academic performance and sleep by state",sub:"States where high schools start before 8am have teen chronic sleep deprivation rates 20% higher and SAT scores 27 points lower than states with 8:30am+ starts. Biology argues for later start times. Budgets argue against.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"AAP school start time data + NCES SAT scores",section:"Education",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["expenditure_per_pupil","avg_teacher_salary"],join:["pct_bachelors","median_household_income","teen_birth_rate"],sc:{emotional:8,relatability:9,surprise:8,tension:4,visual:7,data_ready:8,originality:9},vs:78,tags:"high school start time teen performance sleep state 8am 20% chronic 8:30am 27 SAT points lower biology budget"}
"""

with open('data.js', 'a', encoding='utf-8') as f:
    f.write(ideas)
    f.write('\n]; // end D\n')

print('Batch C appended. Now run: python maintain.py')
