import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDQ01","Eminent Domain Abuse: Private Property Seized for Commercial Development by State","Where governments take private land and give it to developers — the cases since Kelo v New London mapped with outcomes","MAP","US","State choropleth","law","Institute for Justice: Eminent Domain Abuse (ij.org/issues/private-property/eminent-domain)",72,68,72,72,78,72,68,78),
mk("HDQ02","Americas Racial Dot Map: One Dot Per Person Colored by Race at Census Block Level","The most granular visualization of American racial segregation — every person as a single dot, revealing the sharp lines between neighborhoods","MAP","US","Dot map","demographics","Census Bureau: Decennial Census Block Data (data.census.gov)",68,72,72,62,65,90,58,92),
mk("HDQ03","Firearm Trace Time-to-Crime: How Quickly New Guns End Up at Crime Scenes by State","The average time between a guns first retail sale and its recovery at a crime scene — short time-to-crime indicates trafficking","MAP","US","State choropleth","guns","ATF: Firearms Trace Data (atf.gov/resource-center/firearms-trace-data)",62,55,70,75,78,68,70,82),
mk("HDQ04","Lebanese Economic Collapse: GDP Per Capita, Currency Value, and Bank Deposit Losses","Lebanons financial catastrophe visualized — GDP down 60%, currency lost 98% of value, and banks froze $100B in deposits","CHART","Middle East","Line chart","middle_east","World Bank: Lebanon Economic Monitor (worldbank.org/en/country/lebanon)",78,55,68,72,82,62,65,80),
mk("HDQ05","Three Strikes Laws: Life Sentences for Non-Violent Third Offenses by State","States where three-strikes laws have put people away for life for shoplifting, drug possession, or minor theft — the disproportionate punishment map","MAP","US","State choropleth","law","ACLU: Three Strikes Laws (aclu.org/issues/smart-justice/sentencing-reform)",78,68,72,75,82,68,68,78),
mk("HDQ06","Generational Homeownership Gap: Rate of Homeownership at Age 30 by Generation","How each generations homeownership rate at age 30 compares — Boomers at 51%, Millennials at 42%, Gen Z tracking lower","CHART","US","Bar chart","demographics","Census Bureau: Housing Vacancy and Homeownership Survey (census.gov/housing/hvs)",68,82,75,68,68,55,58,85),
mk("HDQ07","Stolen Firearms: Guns Reported Stolen From Vehicles Per Year by Metro","The stolen gun pipeline — hundreds of thousands of firearms stolen from unlocked cars annually, concentrated in certain metros","MAP","US","Dot map","guns","Everytown: Stolen Guns Data (everytown.org) + FBI NIBRS",68,62,68,72,75,72,65,75),
mk("HDQ08","Iraqs Displaced Millions: Internal Displacement From ISIS and Sectarian Violence","The 6+ million Iraqis displaced within their own country since 2003 — where they fled from and where they ended up","MAP","Middle East","Dot map","middle_east","IOM: Displacement Tracking Matrix Iraq (displacement.iom.int/iraq)",80,55,65,62,82,78,62,80),
mk("HDQ09","Debtors Prison: People Jailed for Inability to Pay Fines and Fees by State","The unconstitutional practice of jailing people who cant afford court fines — states where poverty effectively criminalizes being poor","MAP","US","State choropleth","law","ACLU: In for a Penny Report (aclu.org) + Fines and Fees Justice Center",78,72,72,78,82,72,70,72),
mk("HDQ10","Suburban Diversification: Non-White Population Growth in Americas 50 Largest Suburbs","The diversification of suburbia — majority-minority suburbs mapped against their demographics 20 years ago","MAP","US","Dot map","demographics","Census Bureau: ACS Suburban Tract Data (data.census.gov)",58,68,72,68,52,78,65,90),
mk("HDQ11","Accidental Child Shootings: Unintentional Firearm Deaths Among Children by State","Kids killed by guns left unsecured — states without safe storage laws vs states with them, compared against incident rates","MAP","US","State choropleth","guns","Everytown: #NotAnAccident Index (everytownresearch.org/notanaccident)",85,72,72,68,85,68,60,82),
mk("HDQ12","Bahrain Protest Crackdown: Arrests, Citizenship Revocations, and Political Prisoners","The tiny Gulf kingdoms heavy-handed response to the Arab Spring — political prisoners per capita among the worlds highest","CHART","Middle East","Bar chart","middle_east","BCHR: Bahrain Center for Human Rights (bahrainrights.net)",72,48,65,72,80,58,72,68),
mk("HDQ13","Wrongful Conviction by Crime Type: Which Offenses Produce the Most Exonerations","Murder and sexual assault dominate exonerations — but wrongful drug convictions are surging as a category","CHART","US","Bar chart","law","National Registry of Exonerations: Statistics (law.umich.edu/special/exoneration/Pages/about.aspx)",72,62,72,72,78,58,65,85),
mk("HDQ14","Single-Person Households: The Rise of Living Alone by Country and Age Group","28% of US households are now one person — the global solo-living trend mapped by country with the steepest growth in young adults","MAP","World","World choropleth","demographics","OECD: Family Database Household Structure (oecd.org/els/family/database)",58,72,72,68,55,68,62,85),
mk("HDQ15","Permitless Carry Expansion: States That Eliminated Concealed Carry Permits by Year","The rapid spread of constitutional carry — from 1 state in 2003 to 29 states by 2024, animated year by year","MAP","US","Animated choropleth","guns","Giffords: Concealed Carry Laws (giffords.org/lawcenter)",58,62,72,68,72,78,58,88),
mk("HDQ16","Syrias Destruction: Satellite-Assessed Building Damage by City","Before and after satellite imagery quantifying the physical destruction of Aleppo, Homs, Raqqa, and Eastern Ghouta","MAP","Middle East","Special map","middle_east","UNOSAT: Syria Damage Assessment (unosat.org)",82,52,65,65,85,85,65,78),
mk("HDQ17","Bench Trial vs Jury Trial: Conviction Rates When Judges Decide vs When Juries Decide","Do judges or juries convict more often? The surprising data on conviction rates by forum and offense type","CHART","US","Bar chart","law","BJS: State Court Processing Statistics (bjs.ojp.gov)",58,58,72,78,62,55,72,78),
mk("HDQ18","Pet Ownership Demographics: Which Animals Americans Own by Generation and Region","The generational pet divide — Boomers prefer dogs, Gen Z embraces cats and reptiles, with regional variation in exotic pets","CHART","US","Bar chart","demographics","AVMA: Pet Ownership Statistics (avma.org/resources-tools/reports-statistics/us-pet-ownership-statistics)",42,78,68,65,38,58,62,80),
mk("HDQ19","Gun Purchase Waiting Periods: States That Require a Delay Between Sale and Pickup","Where you can buy and walk out with a gun the same day vs states with 3-14 day cooling off periods — mapped against impulsive violence rates","MAP","US","State choropleth","guns","Giffords: Waiting Period Laws (giffords.org/lawcenter/gun-laws/policy-areas/gun-sales/waiting-periods)",65,65,72,65,72,72,58,85),
mk("HDQ20","UAE Economic Diversification: Non-Oil GDP Share Over Time","How the UAE transformed from 90% oil dependence to a diversified economy — tourism, finance, logistics, and tech growth tracked","CHART","Middle East","Area chart","middle_east","UAE Federal Competitiveness and Statistics Centre (fcsc.gov.ae)",55,48,72,68,58,62,62,82),
mk("HDQ21","Prosecutorial Misconduct Database: Documented Instances of Prosecutors Breaking Rules","Cases where prosecutors withheld evidence, made false statements, or engaged in misconduct — documented instances by jurisdiction","MAP","US","Dot map","law","National Registry of Exonerations: Government Misconduct (law.umich.edu)",72,58,68,75,80,68,72,72),
mk("HDQ22","Commuter Town Classification: Bedroom Communities Where 50%+ of Workers Leave for Employment","Towns where most residents work somewhere else — the map of Americas bedroom communities and their host cities","MAP","US","County choropleth","demographics","Census Bureau: LEHD Origin-Destination (lehd.ces.census.gov)",52,68,72,62,48,78,62,90),
mk("HDQ23","Shooting Range Density: Gun Ranges Per Capita by State","Indoor and outdoor shooting ranges per 100K residents by state — the recreational firearms infrastructure map","MAP","US","State choropleth","guns","NSSF: Range Finder + State DNR Listings (wheretoshoot.org)",48,55,68,62,48,72,55,78),
mk("HDQ24","Jordans Refugee Burden: Refugees as Share of Population Compared to Western Nations","Jordan hosts more refugees per capita than almost any nation — the comparison that reframes the European refugee debate","RANK","World","Bar chart","middle_east","UNHCR: Jordan Operational Data Portal (data.unhcr.org/en/country/jor)",72,58,75,75,72,58,68,85),
mk("HDQ25","Sentencing Disparity by Race: Average Prison Terms for Same Offense by Defendant Race","Black defendants receive sentences 19% longer than white defendants for the same crimes — the data by offense category","CHART","US","Bar chart","law","US Sentencing Commission: Demographic Differences (ussc.gov)",78,68,72,72,82,58,62,85),
mk("HDQ26","Ghost Town Revival: Former Ghost Towns That Have Been Repopulated or Turned Into Tourist Sites","Americas ghost towns that came back — mining camps turned art colonies, abandoned villages turned heritage sites","MAP","US","Dot map","demographics","NPS: National Register of Historic Places + State Historic Preservation Offices",52,62,65,72,48,78,75,72),
mk("HDQ27","Domestic Violence Firearm Homicides: Intimate Partner Killings With Guns by State","Women killed by intimate partners using firearms — mapped against state laws on domestic violence gun restrictions","MAP","US","Bivariate choropleth","guns","CDC WONDER: Firearm Homicide Data + Everytown (everytown.org)",82,68,70,62,85,72,58,82),
mk("HDQ28","Turkish Military Operations in Syria: Ground Incursions and Buffer Zones Since 2016","Turkeys four major military operations in northern Syria mapped with territorial control and Kurdish population displacement","MAP","Middle East","Special map","middle_east","ACLED: Turkey-Syria Conflict Data (acleddata.com)",65,48,65,68,78,82,68,78),
mk("HDQ29","Electronic Monitoring: People on Ankle Monitors and GPS Tracking by State","The growing surveillance net — hundreds of thousands of people on electronic monitoring, many pretrial and unable to afford removal","MAP","US","State choropleth","law","Pew Charitable Trusts: Use of Electronic Offender-Tracking Devices (pewtrusts.org)",68,62,68,72,75,68,68,72),
mk("HDQ30","County Name Origins: What Americas Counties Are Named After by Category","Counties named after presidents, generals, Native American words, geographic features, or local founders — the etymology map","MAP","US","County choropleth","demographics","USGS: Geographic Names Information System (geonames.usgs.gov)",42,62,65,68,38,78,68,85),
mk("HDQ31","Firearms Instructor Density: Certified Concealed Carry Instructors Per Capita by State","Where the gun training infrastructure is — certified firearms instructors per 100K adults mapped against training requirements","MAP","US","State choropleth","guns","State licensing databases + NRA Instructor Search (firearmtraining.nra.org)",45,52,68,62,48,68,55,75),
mk("HDQ32","Houthi Maritime Attacks: Commercial Shipping Incidents in the Red Sea and Gulf of Aden","Every Houthi attack on commercial shipping since late 2023 — the disruption to global trade routes through the Bab el-Mandeb strait","MAP","Middle East","Dot map","middle_east","IMB: Piracy Reporting Centre (icc-ccs.org) + UKMTO Maritime Reports",68,52,68,72,80,80,68,80),
mk("HDQ33","Bail Bond Industry Map: Commercial Bail Revenue by State","The $2B bail bond industry — which states allow commercial bail and how much bondsmen extract from communities","MAP","US","State choropleth","law","PPI: Prison Policy Initiative (prisonpolicy.org) + State insurance commission data",65,62,72,72,72,68,68,72),
mk("HDQ34","Americas Most Common Street Names: The Geography of Main Streets, Elm Streets, and MLK Boulevards","Which street names dominate in different regions — and the revealing geography of streets named after Martin Luther King Jr","MAP","US","Dot map","demographics","OpenStreetMap: US Road Name Data (openstreetmap.org)",42,72,65,68,38,78,72,88),
mk("HDQ35","Illegal Gun Market Prices: What Black Market Firearms Actually Cost by City","Street prices for illegal firearms in major US cities — a stolen Glock for $200 in some cities vs $2000 in others with strict laws","MAP","US","Dot map","guns","ATF: Illegal Firearms Market Reports (atf.gov) + Academic surveys",58,55,65,78,72,68,75,55),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDQ batch)")
