import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCD01","The Myth of the Welfare Queen: Actual TANF Recipients by County Demographics","Who actually receives welfare mapped — the data vs the narrative","CHART","US-county","County choropleth","poverty/race","HHS: TANF data (acf.hhs.gov); Census: Demographics (census.gov/acs); CBPP: Welfare research (cbpp.org)",85,78,78,80,82,78,72,80),
mk("HCD02","Where Immigrants Create More Jobs Than They Take: Business Formation Rates","Immigrant-founded business rates by metro mapped against native-born rates","CHART","US-metro","Bar chart","immigration/economy","Census: ABS (census.gov/abs); SBA: Small business (sba.gov); Kauffman: Entrepreneurship (kauffman.org)",78,75,78,82,72,68,75,78),
mk("HCD03","The Red State Blue State Healthcare Myth: Outcomes Dont Follow Party Lines","Health outcomes mapped against political lean — the pattern is income not ideology","MAP","US-state","Bivariate choropleth","health/politics","CDC: Health outcomes (cdc.gov); IHME: State health (healthdata.org); MIT: Elections (electionlab.mit.edu)",78,75,72,82,72,78,80,78),
mk("HCD04","Where Crime Is Actually Falling: The 30-Year Decline Nobody Talks About","Crime rates from 1993 to 2024 by metro — the historic drop that fear obscures","CHART","US-metro","Line chart","crime/media","FBI: UCR (ucr.fbi.gov); Gallup: Crime perception (gallup.com); BJS: Victimization (bjs.gov)",78,78,82,78,72,68,72,85),
mk("HCD05","The Foreign Aid Myth: Americans Think We Spend 25% of the Budget When Its Under 1%","Perceived vs actual foreign aid by country — the perception gap mapped globally","CHART","World","Bar chart","international/psychology","USAID: Budget (usaid.gov); Kaiser: Foreign aid survey (kff.org); Gallup: Spending poll (gallup.com)",72,78,78,85,68,68,78,78),
mk("HCD06","Where Nuclear Energy Is Actually the Safest Power Source: Deaths Per TWh","Nuclear deaths vs coal vs gas vs hydro — the counterintuitive safety chart","CHART","World","Bar chart","energy/science","Our World in Data: Energy deaths (ourworldindata.org); IEA: Energy data (iea.org); WHO: Health impacts (who.int)",75,68,82,85,68,68,75,85),
mk("HCD07","The Refugee Success Story: Economic Outcomes 10 Years After Resettlement by State","Refugees have higher employment rates than native-born within a decade — mapped","CHART","US-state","Bar chart","immigration/economy","ORR: Refugee data (acf.hhs.gov); Census: ACS (census.gov/acs); BLS: Employment (bls.gov)",78,72,72,82,68,68,78,72),
mk("HCD08","Where Affordable Housing Actually Exists: Cost-Burdened Renters by County Updated","The 2024 housing map nobody wants to share because it shows how bad it really is","MAP","US-county","County choropleth","housing/poverty","Census: ACS housing (census.gov/acs); HUD: CHAS data (huduser.gov); NLIHC: Gap report (nlihc.org)",82,85,78,72,80,80,65,85),
mk("HCD09","The Minimum Wage Map If It Had Kept Pace With Productivity Since 1968","What $7.25 would be in every state if it tracked productivity — $24+ nationally","MAP","US-state","State choropleth","labor/inequality","BLS: Productivity (bls.gov); DOL: Minimum wage (dol.gov); EPI: Wage tracker (epi.org)",85,85,80,80,82,75,72,82),
mk("HCD10","Where Public Transit Saves Lives: Traffic Deaths per Capita vs Transit Investment","Cities that invested in transit have dramatically fewer traffic fatalities — the correlation","CHART","US-metro","Scatter plot","transportation/health","NHTSA: FARS (nhtsa.gov); NTD: Transit data (transit.dot.gov); Census: Commute (census.gov/acs)",78,78,78,75,68,70,72,82),
mk("HCD11","The Teacher Salary Map: What Educators Earn Adjusted for Cost of Living","Teacher pay purchasing power by state — some states effectively pay $30K","MAP","US-state","State choropleth","education/labor","NCES: Teacher salary (nces.ed.gov); BLS: Regional CPI (bls.gov); NEA: Rankings (nea.org)",82,85,78,72,78,75,65,85),
mk("HCD12","Where Unions Raise All Boats: Non-Union Worker Wages in High vs Low Union States","Even non-union workers earn more in high-unionization states — the spillover effect mapped","CHART","US-state","Scatter plot","labor/economy","BLS: Union data (bls.gov/cps); Census: Wage data (census.gov/acs); EPI: Union research (epi.org)",80,78,78,80,75,68,75,80),
mk("HCD13","The Incarceration Myth: Locking More People Up Doesnt Reduce Crime","State incarceration rates vs crime rates over 20 years — no correlation","CHART","US-state","Scatter plot","crime/law","BJS: Corrections (bjs.gov); FBI: UCR (ucr.fbi.gov); Vera: Incarceration (vera.org)",82,72,78,82,80,68,75,82),
mk("HCD14","Where Solar Energy Already Costs Less Than Coal: The Crossover Map","Counties where solar LCOE is below coal — the economic tipping point mapped","MAP","US-state","State choropleth","energy/economy","EIA: LCOE (eia.gov); Lazard: LCOE analysis (lazard.com); NREL: Solar data (nrel.gov)",78,72,82,78,72,78,70,85),
mk("HCD15","The Immigration Enforcement Myth: Who Actually Gets Deported","Deportee demographics vs public perception — most are not violent criminals","CHART","US","Bar chart","immigration/law","ICE: Enforcement data (ice.gov); TRAC: Immigration data (trac.syr.edu); Census: Demographics (census.gov)",80,72,78,80,80,68,72,78),
mk("HCD16","Where Rent Control Actually Works: The Global Evidence","Cities with and without rent control compared on affordability metrics — its complicated","CHART","World","Scatter plot","housing/international","OECD: Housing (oecd.org); HUD: Affordability (huduser.gov); Brookings: Rent control (brookings.edu)",75,78,72,78,72,68,72,72),
mk("HCD17","The Corporate Tax Myth: Effective Rates vs Statutory Rates by Industry","What companies actually pay vs what the rate says — the gap is enormous","CHART","US","Bar chart","finance/law","IRS: SOI corporate (irs.gov); SEC: 10-K filings (sec.gov); ITEP: Corporate taxes (itep.org)",80,75,78,80,78,68,72,78),
mk("HCD18","Where Homelessness Is Driven by Housing Costs Not Drug Use","Homelessness rates correlated with median rent vs drug use rates by metro — rent wins","CHART","US-metro","Scatter plot","housing/drugs","HUD: PIT count (hudexchange.info); Zillow: Rent (zillow.com); SAMHSA: Drug use (samhsa.gov)",82,78,78,82,78,68,78,75),
mk("HCD19","The Policing Myth: More Officers Doesnt Mean Less Crime After a Threshold","Police per capita vs crime rate by city — the curve flattens at a surprisingly low number","CHART","US-metro","Scatter plot","crime/finance","FBI: UCR (ucr.fbi.gov); Census: Law enforcement (census.gov/govs); BJS: LEMAS (bjs.gov)",78,72,72,82,75,68,78,75),
mk("HCD20","Where Electric Cars Actually Reduce Emissions: Grid Cleanliness by State","EV emissions savings depend entirely on your states power grid — the map surprises","MAP","US-state","State choropleth","energy/environment","EPA: eGRID (epa.gov/egrid); DOE: Alternative fuels (afdc.energy.gov); EIA: State generation (eia.gov)",75,78,80,78,68,78,72,85),
mk("HCD21","The School Choice Myth: Voucher Student Outcomes vs Public School Outcomes","Head-to-head academic performance comparison controlling for demographics","CHART","US-state","Bar chart","education/inequality","NCES: NAEP scores (nces.ed.gov); EdChoice: Research (edchoice.org); State DOE: Assessment data",78,78,75,78,75,68,72,72),
mk("HCD22","Where Trickle-Down Economics Trickled: State GDP Growth After Tax Cuts","Kansas experiment and others — economic growth after major state tax cuts mapped","CHART","US-state","Line chart","economy/politics","BEA: State GDP (bea.gov); Tax Foundation: State taxes (taxfoundation.org); CBPP: Tax analysis (cbpp.org)",78,72,78,78,75,68,75,78),
mk("HCD23","The Immigration Brain Gain: Immigrant Nobel Laureates and Patent Holders","40% of US Nobel prizes and 36% of patents come from immigrants — the talent map","CHART","US","Bar chart","immigration/science","USPTO: Patent data (uspto.gov); Nobel Foundation: Laureates (nobelprize.org); NSF: Scientists (nsf.gov)",75,70,78,82,68,68,78,82),
mk("HCD24","Where Abstinence-Only Education Leads to More Teen Pregnancy","Sex ed policy mapped against teen birth rates by state — the evidence is clear","CHART","US-state","Scatter plot","education/health","Guttmacher: Sex ed policy (guttmacher.org); CDC: Teen birth (cdc.gov/teenpregnancy); SIECUS: State profiles (siecus.org)",80,75,78,78,78,68,68,82),
mk("HCD25","The Myth of the Lazy Welfare Recipient: Hours Worked by SNAP Recipients","SNAP recipients work an average of 30+ hours per week — the reality vs perception","CHART","US","Bar chart","poverty/labor","CBPP: SNAP research (cbpp.org); Census: SIPP (census.gov/sipp); USDA: SNAP data (fns.usda.gov)",82,82,78,80,75,68,72,80),
mk("HCD26","Where Deregulation Made Things Worse: Airline, Telecom, and Energy Case Studies","Before/after deregulation mapped against prices, service quality, and concentration","CHART","US","Line chart","economy/law","BTS: Airline data (bts.gov); FCC: Telecom (fcc.gov); EIA: Energy prices (eia.gov); Census: Industry (census.gov)",75,72,75,78,72,68,78,75),
mk("HCD27","The Myth of American Mobility: The Zip Code You Were Born in Predicts Everything","Intergenerational income mobility by county — the American Dream mapped","MAP","US-county","County choropleth","inequality/geography","Opportunity Atlas: Chetty data (opportunityatlas.org); Census: Income (census.gov); IRS: SOI (irs.gov)",85,82,78,80,82,80,72,85),
mk("HCD28","Where Charter Schools Outperform and Where They Dont: The Complete Map","CREDO data mapped — the answer depends entirely on geography","MAP","US-metro","Dot map","education/geography","CREDO: Charter research (credo.stanford.edu); NCES: School data (nces.ed.gov); State DOE: Assessments",75,75,72,72,68,72,72,72),
mk("HCD29","The Drug War Rewritten: What Happened in States That Chose Treatment Over Prison","Decriminalization and treatment investment states vs punishment states — 10-year outcomes","CHART","US-state","Line chart","drugs/crime","SAMHSA: Treatment data (samhsa.gov); BJS: Corrections (bjs.gov); CDC: Overdose (wonder.cdc.gov)",82,72,78,78,78,68,75,75),
mk("HCD30","Where Americas Infrastructure Gets an F: ASCE Report Card Mapped by State","Bridge condition, water systems, broadband, roads — the composite failure map","MAP","US-state","State choropleth","infrastructure/economy","ASCE: Infrastructure report (infrastructurereportcard.org); FHWA: Bridge data (fhwa.dot.gov); EPA: Water (epa.gov)",80,78,78,72,78,80,65,85),
mk("HCD31","The Wealth Tax Myth: What Actually Happened in Countries That Tried It","Revenue collected vs projected for every country that adopted and repealed wealth taxes","CHART","World","Bar chart","finance/international","OECD: Tax data (oecd.org); Tax Foundation: Wealth tax (taxfoundation.org); IMF: Revenue (imf.org)",72,68,78,80,72,68,78,78),
mk("HCD32","Where Immigrants Revived Dying Towns: Population Recovery Through Immigration","Counties saved from population collapse by immigrant arrivals — mapped with economic impact","MAP","US-county","Dot map","immigration/rural","Census: Population change (census.gov); ACS: Nativity (census.gov/acs); BEA: County income (bea.gov)",80,75,72,80,68,75,78,75),
mk("HCD33","The Crime Perception Gap: What Americans Think vs What the Data Shows by Metro","Gallup crime worry vs FBI crime rates mapped — perception is 10-20 years behind reality","CHART","US-metro","Scatter plot","crime/psychology","Gallup: Crime worry (gallup.com); FBI: UCR (ucr.fbi.gov); Pew: Crime perception (pewresearch.org)",75,80,78,82,72,68,78,75),
mk("HCD34","Where Universal Pre-K Pays for Itself: Return on Investment by State","Every dollar invested in pre-K returns $4-9 in reduced crime, welfare, and higher earnings","CHART","US-state","Bar chart","education/economy","NIEER: State pre-K (nieer.org); Heckman: ROI research (heckmanequation.org); Census: Education (census.gov)",78,78,78,75,68,68,72,72),
mk("HCD35","The Climate Change Cost Map: Dollars Lost Per County Per Year Already","Not future projections — current annual economic losses from climate events mapped","MAP","US-county","County choropleth","climate/economy","NOAA: Billion-dollar disasters (ncei.noaa.gov); FEMA: Declarations (fema.gov); BEA: County GDP (bea.gov)",82,78,78,78,80,80,72,78),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCD ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCD batch)")
