import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCL01","The 2040 Water Crisis Map: Counties That Will Run Out of Groundwater at Current Usage","Aquifer depletion rates extrapolated — the Ogallala is 30 years from collapse in places","MAP","US-county","County choropleth","environment/agriculture","USGS: Groundwater (usgs.gov); Kansas Geological Survey: Ogallala (kgs.ku.edu); NASA: GRACE (nasa.gov)",85,75,75,82,85,82,78,78),
mk("HCL02","Where Americas Schools Will Close by 2035: The Birth Rate Enrollment Cliff","Projected enrollment declines mapped by district — some face 40% drops","MAP","US-county","County choropleth","education/demographics","NCES: Enrollment projections (nces.ed.gov); CDC: Birth data (cdc.gov); Census: Projections (census.gov)",80,78,75,78,80,78,72,75),
mk("HCL03","The Retirement Tsunami: Where 10000 Boomers Retiring Daily Hits Hardest","Sectors and counties losing the most workers to retirement 2025-2035","MAP","US-county","County choropleth","labor/demographics","BLS: Projections (bls.gov/emp); Census: Age structure (census.gov); SSA: Retirement (ssa.gov)",78,78,72,75,75,78,68,78),
mk("HCL04","Where Coastal Real Estate Will Be Underwater: $1 Trillion in Property at Risk by 2050","Properties below projected flood lines mapped with current assessed values","MAP","US-metro","Dot map","climate/housing","Climate Central: Surging Seas (sealevel.climatecentral.org); Zillow: Values (zillow.com); FEMA: Flood maps (fema.gov)",85,82,75,80,85,85,72,78),
mk("HCL05","The Electric Grid That Cant Handle the Future: Peak Demand vs Capacity by State","States where summer peak demand will exceed capacity by 2030 — the blackout forecast","MAP","US-state","State choropleth","energy/infrastructure","EIA: Grid capacity (eia.gov); NERC: Reliability (nerc.com); DOE: Grid modernization (energy.gov)",78,78,75,78,80,78,72,75),
mk("HCL06","Where Americas Dams Will Fail: High-Hazard Dams Past Their Design Life","Aging dams mapped against downstream population — the infrastructure time bomb","MAP","US","Dot map","infrastructure/environment","ASDSO: Dam safety (damsafety.org); Army Corps: NID (nid.sec.usace.army.mil); FEMA: Risk (fema.gov)",82,72,72,80,82,82,72,75),
mk("HCL07","The Teacher Shortage Forecast: States That Will Be 300K Teachers Short by 2030","Retirement + attrition + enrollment decline mapped — the pipeline is broken","MAP","US-state","State choropleth","education/labor","NCES: Teacher data (nces.ed.gov); Learning Policy Institute: Teacher shortage (learningpolicyinstitute.org)",80,80,75,75,78,72,68,72),
mk("HCL08","Where Climate Migration Will Send Americans: The Destination Counties","Projected internal migration from climate stress mapped — the upper Midwest is the winner","MAP","US-county","County choropleth","climate/geography","ProPublica: Climate migration (propublica.org); Census: Migration (census.gov); NOAA: Climate projections (noaa.gov)",82,78,72,80,78,82,78,72),
mk("HCL09","Middle East Megacity Water Stress: Cities of 10M+ Running Dry","Cairo, Tehran, Baghdad, Riyadh mapped against water supply projections to 2040","MAP","Middle East","Dot map","middle_east/infrastructure","FAO: AQUASTAT (fao.org); World Bank: Urbanization (worldbank.org); NASA: GRACE (nasa.gov)",82,62,72,80,82,78,78,72),
mk("HCL10","The Nursing Shortage Map: Where Americas Aging Population Meets Zero Nurses","RN shortage projections by state mapped against 65+ population growth","MAP","US-state","Bivariate choropleth","health/demographics","HRSA: Nursing workforce (hrsa.gov); BLS: RN projections (bls.gov); Census: Age (census.gov)",82,78,75,75,80,72,68,75),
mk("HCL11","Where Americas Sewer Systems Will Overflow: Combined Sewer Cities and Climate Change","Cities with combined sewer overflows mapped against projected rainfall intensity increases","MAP","US-metro","Dot map","infrastructure/climate","EPA: CSO data (epa.gov); NOAA: Precipitation (noaa.gov); ASCE: Water infrastructure (infrastructurereportcard.org)",78,72,72,78,78,78,72,72),
mk("HCL12","The AI Job Displacement Map: Which Counties Face the Highest Automation Risk","Occupation-weighted automation exposure by county mapped against retraining capacity","MAP","US-county","County choropleth","technology/labor","Brookings: Automation (brookings.edu); BLS: Occupations (bls.gov/oes); Census: Industry (census.gov)",78,82,72,80,78,78,75,72),
mk("HCL13","Where Gun Ownership Meets Dementia: The Aging Firearms Owner Crisis Nobody Discusses","States with highest gun ownership and fastest-aging populations — the intersection mapped","XREF","US-state","Bivariate choropleth","guns/health","RAND: Gun ownership (rand.org); Alzheimers Assoc: Prevalence (alz.org); Census: Age (census.gov)",78,72,65,85,78,72,85,62),
mk("HCL14","The Democracy Cliff: Where Falling Birth Rates Will Reshape Electoral Maps by 2040","Population projection-adjusted electoral college reapportionment — which states gain, which lose","MAP","US-state","State choropleth","democracy/demographics","Census: Projections (census.gov); Electoral vote history; Brookings: Apportionment (brookings.edu)",75,72,75,78,72,78,75,72),
mk("HCL15","Where Americas Bridges Will Become Impassable: The Weight Restriction Forecast","Bridges trending toward weight restrictions mapped against freight routes — commerce at risk","MAP","US","Dot map","infrastructure/transportation","FHWA: NBI trends (fhwa.dot.gov); BTS: Freight (bts.gov); ASCE: Bridges (infrastructurereportcard.org)",75,72,72,75,75,80,70,78),
mk("HCL16","The Antibiotic Resistance Forecast: Where Drug-Resistant Infections Will Overwhelm Hospitals","Projected AMR cases by state 2025-2040 mapped against hospital surge capacity","MAP","US-state","State choropleth","health/science","CDC: AR Threats (cdc.gov/drugresistance); WHO: AMR projections (who.int); AHA: Hospital capacity (aha.org)",82,72,72,82,82,72,78,68),
mk("HCL17","Where Rural Americas Last Young People Will Leave: The Final Out-Migration Counties","Counties projected to lose 50%+ of 18-34 population by 2035 — the emptying mapped","MAP","US-county","County choropleth","rural/demographics","Census: Projections (census.gov); USDA: Rural atlas (ers.usda.gov); IRS: Migration (irs.gov)",80,72,75,78,80,80,72,72),
mk("HCL18","The Manufacturing Reshoring Reality Check: Automation Means Factories Without Workers","New factory construction mapped against projected employment — buildings but not jobs","MAP","US-county","Dot map","manufacturing/technology","Reshoring Initiative (reshorenow.org); BLS: Manufacturing projections (bls.gov); DOE: Clean energy (energy.gov)",75,72,72,80,72,72,78,72),
mk("HCL19","Where Insurance Companies Will Stop Covering Your Home","Counties losing homeowners insurance availability mapped — the uninsurable zones growing","MAP","US-county","County choropleth","climate/finance","NAIC: Insurance data (naic.org); FEMA: NFIP (fema.gov); State insurance departments",82,82,75,78,82,78,72,72),
mk("HCL20","The Global Lithium Rush: Where Battery Mineral Mining Will Transform Economies","Lithium, cobalt, nickel deposits mapped against projected EV demand — the new oil map","MAP","World","World choropleth","energy/trade","USGS: Mineral commodities (usgs.gov); IEA: Critical minerals (iea.org); World Bank: Mining (worldbank.org)",72,68,72,78,72,82,75,78),
mk("HCL21","Where Americas Power Plants Are Too Old to Run and Too Expensive to Replace","Power plant age mapped against replacement cost estimates — the infrastructure debt","MAP","US","Dot map","energy/infrastructure","EIA: Power plants (eia.gov); ASCE: Energy (infrastructurereportcard.org); DOE: Grid (energy.gov)",75,72,72,75,75,80,68,78),
mk("HCL22","The Psychology of Climate Denial by Geography: Belief Rates vs Local Evidence","Counties experiencing worst climate impacts mapped against climate denial survey data","XREF","US-county","Bivariate choropleth","psychology/climate","Yale Climate Opinion (climatecommunication.yale.edu); NOAA: Disasters (ncei.noaa.gov); Census: Demographics (census.gov)",75,72,62,82,72,75,80,68),
mk("HCL23","Where Food Production Will Collapse: Crop Yield Projections Under Climate Scenarios","US agricultural output mapped under 2C and 4C warming scenarios by county","MAP","US-county","County choropleth","agriculture/climate","USDA: Climate hub (climatehubs.usda.gov); NASA: Crop models (nasa.gov); NASS: Crop data (nass.usda.gov)",82,72,72,80,82,82,75,72),
mk("HCL24","Middle East Oil After Peak Demand: Which Economies Will Survive the Transition","Sovereign wealth fund sizes mapped against economic diversification progress — the post-oil forecast","CHART","Middle East","Scatter plot","middle_east/economy","SWFI: Sovereign wealth (swfinstitute.org); World Bank: Diversification (worldbank.org); IEA: Oil demand (iea.org)",75,58,72,80,72,68,78,75),
mk("HCL25","The Demographic Destiny of Social Security: When Your State Runs Out","State-level worker-to-retiree ratios projected to 2040 — the math that breaks the system","CHART","US-state","State choropleth","demographics/finance","SSA: Projections (ssa.gov); Census: Age structure (census.gov); CBO: Social Security (cbo.gov)",80,80,78,78,80,75,68,78),
mk("HCL26","Where Americas Drinking Water Infrastructure Will Fail First: The Lead Pipe Replacement Timeline","EPA lead pipe replacement deadlines mapped against municipal budgets — who cant afford compliance","MAP","US-metro","Dot map","infrastructure/health","EPA: Lead rule (epa.gov); AWWA: Infrastructure (awwa.org); Census: Government finance (census.gov)",80,78,72,75,78,78,68,72),
mk("HCL27","The Pharmacy Cliff: Where Chain Closures Will Leave Millions Without Medication Access","Projected pharmacy closures mapped against aging population and chronic disease burden","MAP","US-county","County choropleth","health/rural","NACDS: Pharmacy data (nacds.org); Census: Age/demographics (census.gov); CDC: Chronic disease (cdc.gov)",80,82,72,78,78,78,72,68),
mk("HCL28","Where Electric Vehicle Charging Infrastructure Doesnt Exist Yet but Must by 2030","EV adoption projections mapped against current charging coverage gaps — the build-out needed","MAP","US-state","Bivariate choropleth","transportation/energy","DOE: AFDC (afdc.energy.gov); EIA: EV projections (eia.gov); Census: Commute (census.gov)",72,78,72,72,68,78,68,78),
mk("HCL29","The Sports Franchise Valuation Bubble: When Team Values Exceed Metro GDPs","Team valuations growing faster than local economies — the disconnect forecast","CHART","US-metro","Scatter plot","sports/economy","Forbes: Team valuations (forbes.com); BEA: Metro GDP (bea.gov)",68,72,68,75,68,65,72,72),
mk("HCL30","Where Americas Nuclear Waste Has Nowhere to Go: Temporary Storage Sites Mapped","Spent fuel rod storage at every reactor site mapped — Yucca Mountain is still unfunded","MAP","US","Dot map","energy/environment","NRC: Spent fuel (nrc.gov); DOE: Nuclear waste (energy.gov); GAO: Nuclear waste (gao.gov)",78,68,72,78,78,82,72,78),
mk("HCL31","The Global Fertility Cliff: Countries That Will Halve Their Population by 2100","Below-replacement fertility rates mapped globally — the depopulation forecast","MAP","World","World choropleth","population/international","UN Population: Projections (population.un.org); World Bank: Fertility (worldbank.org)",78,68,78,80,78,78,72,82),
mk("HCL32","Where Law Enforcement Cant Recruit: Police Staffing Shortfalls by Department","Application rates mapped against authorized vs actual staffing — the hiring crisis","MAP","US-metro","Bar chart","law/labor","PERF: Staffing survey (policeforum.org); FBI: LEOKA (ucr.fbi.gov); BJS: LEMAS (bjs.gov)",75,72,72,72,72,68,68,68),
mk("HCL33","The College Enrollment Cliff: Schools That Will Close by 2030","Projected enrollment declines mapped by institution — hundreds of schools face closure","MAP","US","Dot map","education/demographics","NCES: IPEDS (nces.ed.gov); Hechinger: College closures (hechingerreport.org); Census: Youth population (census.gov)",80,78,75,78,80,75,72,72),
mk("HCL34","Where Drug-Resistant Tuberculosis Could Return to America: The Public Health Forecast","TB importation risk mapped against healthcare capacity and immigration patterns","MAP","US-metro","Dot map","drugs/immigration","CDC: TB surveillance (cdc.gov/tb); WHO: TB data (who.int); Census: Foreign-born (census.gov)",72,65,68,78,72,72,78,68),
mk("HCL35","The 2050 Heat Map: US Cities That Will Be Unlivable Without Air Conditioning","Wet-bulb temperature projections mapped against AC penetration and power grid capacity","MAP","US-metro","Special map","climate/health","NASA: Climate projections (nasa.gov); EIA: AC data (eia.gov); Census: Housing (census.gov)",85,78,72,82,85,82,78,72),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCL ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCL batch)")
