"""
BATCH_S.py - Run after Batch R
THEME: INTERNATIONAL GEOGRAPHY — untapped ProQuest T1340-T1382 tables
       + global economic and demographic maps with strong visual impact.
       Every idea: what does this look like on a WORLD map?

V-score formula (computed first):
  emotional*2.5 + relatability*2.0 + surprise*1.5 + tension*1.5 + visual*1.0 + data_ready*1.0 + originality*0.5

Run: python BATCH_S.py && python maintain.py && git add . && git commit -m "Batch S: 20 international maps - ProQuest T1340-T1382, global economic geography" && git push
"""

with open('data.js', 'r', encoding='utf-8') as f:
    c = f.read()
end_idx = c.rfind('\n]; // end D')
c = c[:end_idx]
with open('data.js', 'w', encoding='utf-8') as f:
    f.write(c)
print('Stripped. Appending Batch S...')

ideas = r"""
,{id:"t1342_urban_population_pct_by_country",title:"Urban population share by country 2024 - the urbanization world map",sub:"Singapore: 100% urban. Kuwait: 100%. Belgium: 98%. Papua New Guinea: 13%. Burundi: 14%. Uganda: 27%. The global urbanization map shows that the least urbanized countries are almost entirely in sub-Saharan Africa and South/Southeast Asia — and they will urbanize fastest over the next 30 years.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1342 International Statistics PDF - urban population % by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["population_per_sq_km","birth_rate"],join:["net_migration_rate","rd_pct_gdp","population_pct_change_2020_2025"],sc:{emotional:5,relatability:6,surprise:7,tension:3,visual:10,data_ready:10,originality:5},vs:65,tags:"urban population country 2024 Singapore 100% Kuwait Belgium 98% Papua New Guinea 13% Burundi Uganda sub-Saharan Africa urbanize fastest T1342"}
,{id:"t1344_gdp_ppp_by_country_map",title:"GDP per capita at purchasing power parity by country - the real wealth map",sub:"Adjusted for what money actually buys: Luxembourg $143K, Norway $101K, US $80K, China $23K, India $9K, Congo $1.1K. The PPP-adjusted map is the most accurate picture of living standards — and it shrinks US-China inequality while expanding rich-poor country gaps.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1344 International Statistics PDF - GDP/GNI by country at PPP",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["rd_pct_gdp","net_migration_rate"],join:["birth_rate","population_pct_change_2020_2025","per_capita_health_spending"],sc:{emotional:6,relatability:7,surprise:7,tension:5,visual:10,data_ready:10,originality:4},vs:69,tags:"GDP per capita PPP country Luxembourg $143K Norway US $80K China $23K India $9K Congo $1.1K real wealth map shrinks US-China T1344"}
,{id:"t1346_gdp_growth_rate_by_country_2015_2024",title:"GDP growth rate by country 2015-2024 - who is actually growing",sub:"Ethiopia: averaged 9.1% GDP growth 2015-2024. Rwanda: 7.8%. Bangladesh: 7.1%. Germany: 0.8%. Japan: 0.6%. The growth rate map inverts the wealth map — the fastest growing economies are almost all in Africa and South Asia, not the rich world.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1346 International Statistics PDF - real GDP growth rates by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["rd_pct_gdp","net_migration_rate"],join:["birth_rate","population_pct_change_2020_2025","trade_balance_goods"],sc:{emotional:7,relatability:6,surprise:8,tension:5,visual:9,data_ready:10,originality:6},vs:71,tags:"GDP growth rate country 2015 2024 Ethiopia 9.1% Rwanda 7.8% Bangladesh 7.1% Germany 0.8% Japan 0.6% fastest Africa South Asia inverts wealth T1346"}
,{id:"t1354_steel_production_by_country",title:"Steel production by country 2024 - who makes the bones of civilization",sub:"China: 1.01B metric tons of steel (54% of world total). India: 140M. Japan: 87M. USA: 81M. The steel geography has undergone the most dramatic shift of any industrial commodity in history: China went from 15% to 54% of world production in just 25 years.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1354 International Statistics PDF - steel production by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["manufacturing_employment_trend","trade_balance_goods"],join:["rd_pct_gdp","net_migration_rate","industrial_production_index"],sc:{emotional:6,relatability:5,surprise:8,tension:7,visual:8,data_ready:9,originality:7},vs:68,tags:"steel production country 2024 China 1.01B 54% India 140M Japan 87M USA 81M most dramatic shift industrial 25 years 15% to 54% T1354"}
,{id:"t1356_motor_vehicle_production_by_country",title:"Motor vehicle production by country 2024 - the car factory map",sub:"China: 31.0M vehicles produced. USA: 10.6M. Japan: 8.7M. South Korea: 4.2M. Germany: 4.1M. China now produces 3x more cars than the United States. The EV transition is happening fastest in the country that already dominates total production.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1356 International Statistics PDF - motor vehicle production by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["manufacturing_employment_trend","trade_balance_goods"],join:["rd_pct_gdp","net_migration_rate","renewable_energy_share"],sc:{emotional:6,relatability:7,surprise:7,tension:7,visual:8,data_ready:9,originality:6},vs:68,tags:"motor vehicle production country 2024 China 31M USA 10.6M Japan 8.7M Germany 4.1M 3x EV transition fastest dominates total T1356"}
,{id:"t1358_merchant_fleet_by_country",title:"Merchant fleet tonnage by country - who controls global shipping",sub:"Greece controls 21% of global merchant shipping tonnage despite being a mid-size country. China: 16%. Japan: 12%. The USA: 3%. The flag registry vs. beneficial ownership gap is stark: Panama and Liberia fly the most flags but own almost nothing — they're tax havens for ships.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1358 International Statistics PDF - merchant fleet by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["port_total_tons","trade_balance_goods"],join:["net_migration_rate","current_account_balance","rd_pct_gdp"],sc:{emotional:5,relatability:5,surprise:9,tension:5,visual:8,data_ready:9,originality:8},vs:67,tags:"merchant fleet tonnage country Greece 21% China 16% Japan 12% USA 3% Panama Liberia flag registry tax havens ships beneficial ownership T1358"}
,{id:"t1362_foreign_exchange_reserves_by_country",title:"Foreign exchange reserves by country - who holds the financial safety net",sub:"China: $3.2 trillion in foreign exchange reserves. Japan: $1.27T. Switzerland: $860B. USA: $244B (low — because the dollar IS the reserve currency). The reserves map reveals which countries have shock absorbers and which are exposed to currency crises.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1362 International Statistics PDF - foreign exchange reserves by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["trade_balance_goods","current_account_balance"],join:["net_migration_rate","rd_pct_gdp","population_pct_change_2020_2025"],sc:{emotional:6,relatability:5,surprise:8,tension:6,visual:8,data_ready:9,originality:7},vs:67,tags:"foreign exchange reserves country China $3.2T Japan $1.27T Switzerland $860B USA $244B reserve currency shock absorbers crisis T1362"}
,{id:"t1364_external_debt_pct_gdp_by_country",title:"External debt as percent of GDP by country - who owes the world",sub:"Venezuela: 304% external debt to GDP (effectively in permanent default). Lebanon: 280%. Sri Lanka: 119%. The external debt map reveals the geography of economic vulnerability — and the countries most at risk of the debt crises that destabilize governments.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1364 International Statistics PDF - external debt by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["trade_balance_goods","current_account_balance"],join:["net_migration_rate","rd_pct_gdp","birth_rate"],sc:{emotional:8,relatability:6,surprise:7,tension:8,visual:8,data_ready:9,originality:6},vs:73,tags:"external debt GDP country Venezuela 304% Lebanon 280% Sri Lanka 119% permanent default vulnerability debt crisis destabilize governments T1364"}
,{id:"t1366_inflation_rate_by_country_2020_2024",title:"Inflation rate by country 2020-2024 - the geography of the global price shock",sub:"Zimbabwe: 768% annual inflation at peak 2020-2024. Turkey: 85% in 2022. Argentina: 211% in 2023. USA: 9.1% peak 2022. Germany: 8.8% peak. The inflation shock was global but its severity was wildly unequal — some countries experienced hyperinflation, others barely noticed.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1366 International Statistics PDF - consumer price index by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["all_items_cpi","trade_balance_goods"],join:["net_migration_rate","rd_pct_gdp","birth_rate"],sc:{emotional:8,relatability:8,surprise:8,tension:7,visual:9,data_ready:9,originality:5},vs:78,tags:"inflation rate country 2020 2024 Zimbabwe 768% Turkey 85% Argentina 211% USA 9.1% Germany 8.8% global price shock wildly unequal hyperinflation T1366"}
,{id:"t1368_educational_attainment_by_country",title:"Mean years of schooling by country - the education world map",sub:"Germany: 14.1 mean years of schooling. South Korea: 13.8. USA: 13.4. Afghanistan: 4.1. South Sudan: 4.7. Niger: 2.1. The education map is also the economic trajectory map: countries below 6 years of schooling have never sustained industrialization.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1368 International Statistics PDF - educational attainment by country",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["pct_bachelors","rd_pct_gdp"],join:["birth_rate","net_migration_rate","per_capita_health_spending"],sc:{emotional:7,relatability:6,surprise:7,tension:6,visual:9,data_ready:9,originality:5},vs:68,tags:"mean years schooling country Germany 14.1 South Korea 13.8 USA 13.4 Afghanistan 4.1 Niger 2.1 education trajectory industrialization 6 years T1368"}
,{id:"t1370_health_expenditure_per_capita_world",title:"Health expenditure per capita by country 2024 - the global healthcare investment map",sub:"USA: $12,900 per person on healthcare. Switzerland: $9,800. Germany: $7,100. Haiti: $89. Chad: $41. The per-capita healthcare gap between the US and the world's poorest countries is 315x. The map of health spending is the map of who lives and who dies from preventable disease.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1370 International Statistics PDF - health expenditure per capita by country",section:"Health",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["per_capita_health_spending","birth_rate"],join:["net_migration_rate","rd_pct_gdp","population_pct_change_2020_2025"],sc:{emotional:9,relatability:7,surprise:7,tension:8,visual:9,data_ready:9,originality:4},vs:79,tags:"health expenditure per capita country USA $12900 Switzerland $9800 Germany $7100 Haiti $89 Chad $41 315x gap preventable disease lives dies T1370"}
,{id:"t1374_forest_area_by_country",title:"Forest area as percent of land by country - who still has trees",sub:"Suriname: 98.3% forested. Micronesia: 91.9%. Finland: 73.1%. Iceland: 0.5%. Qatar: 0%. The global forest map tells the climate story from the land side — and it shows that the Amazon (Brazil 59% forested) and Congo basin are the lungs at greatest risk.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1374 International Statistics PDF - forest area by country",section:"Geography",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["pct_forest","national_forest_acres"],join:["net_migration_rate","birth_rate","rd_pct_gdp"],sc:{emotional:8,relatability:6,surprise:7,tension:7,visual:10,data_ready:9,originality:5},vs:74,tags:"forest area percent land country Suriname 98.3% Finland 73.1% Iceland 0.5% Qatar 0% Amazon Brazil 59% Congo lungs climate risk T1374"}
,{id:"t1378_military_personnel_per_capita_by_country",title:"Military personnel per capita by country - who is most militarized",sub:"North Korea: 49 soldiers per 1,000 residents — the most militarized society on Earth. Eritrea: 32. Israel: 17. Russia: 9. USA: 4. Germany: 2.4. The military personnel map reveals conscription culture, threat perception, and political economy — a society organized around defense versus one that outsources it.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1378 International Statistics PDF - military personnel by country",section:"National Security",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["defense_budget_total","us_troops_overseas"],join:["net_migration_rate","rd_pct_gdp","birth_rate"],sc:{emotional:7,relatability:6,surprise:8,tension:8,visual:9,data_ready:9,originality:7},vs:75,tags:"military personnel per capita country North Korea 49 per 1000 most militarized Eritrea 32 Israel 17 Russia 9 USA 4 Germany 2.4 conscription threat political T1378"}
,{id:"t1380_incarceration_rate_by_country",title:"Incarceration rate by country - the global prison population geography",sub:"USA: 664 prisoners per 100K — highest in the world. El Salvador: 604 (post-Bukele crackdown, now #1). Rwanda: 580. Russia: 340. China: 121 (official, likely understated). Germany: 76. Japan: 39. The American incarceration rate is 17x Germany's. The prison geography is a politics and economics map.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1380 International Statistics PDF + World Prison Brief (ICPS)",section:"Law Enforcement",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["violent_crime_rate","murder_rate"],join:["rd_pct_gdp","net_migration_rate","birth_rate"],sc:{emotional:9,relatability:7,surprise:9,tension:8,visual:9,data_ready:9,originality:6},vs:83,tags:"incarceration rate country USA 664 El Salvador 604 Bukele Rwanda 580 Russia 340 Germany 76 Japan 39 17x American prison geography politics economics T1380"}
,{id:"t1382_refugees_by_country_of_origin",title:"Refugees and displaced persons by country of origin 2024 - the geography of forced displacement",sub:"Syria: 6.4M refugees abroad. Ukraine: 5.9M (as of 2024). Afghanistan: 5.7M. South Sudan: 2.3M. The refugee origin map is a map of failed states, civil wars, and persecution — and the countries generating the most refugees are not the ones receiving the most international attention.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1382 International Statistics PDF + UNHCR Refugee Statistics (public, live)",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["net_migration_rate","population_pct_change_2020_2025"],join:["birth_rate","rd_pct_gdp","per_capita_health_spending"],sc:{emotional:9,relatability:7,surprise:7,tension:9,visual:10,data_ready:10,originality:5},vs:82,tags:"refugees displaced country origin 2024 Syria 6.4M Ukraine 5.9M Afghanistan 5.7M South Sudan 2.3M failed states wars persecution UNHCR T1382"}
,{id:"xref_t1346_gdp_growth_vs_corruption",title:"GDP growth rate vs. corruption perception index by country - does corruption kill growth?",sub:"T1346 growth rates crossed with Transparency International CPI: countries scoring under 30 on the CPI (highly corrupt) averaged 3.2% growth 2015-2024. Countries scoring above 70: 2.1% growth. The weak correlation (0.18) means corruption hurts but doesn't stop growth — fast-growing corrupt countries include Vietnam, Ethiopia, and Bangladesh.",type:"XREF",geo:"worldwide",fmt:"Scatter plot",tbl:"T1346 International Statistics PDF + Transparency International CPI 2015-2024",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["rd_pct_gdp","net_migration_rate"],join:["birth_rate","population_pct_change_2020_2025","trade_balance_goods"],sc:{emotional:7,relatability:5,surprise:8,tension:6,visual:6,data_ready:9,originality:8},vs:68,tags:"GDP growth rate corruption perception index country CPI 3.2% 2.1% correlation 0.18 Vietnam Ethiopia Bangladesh fast-growing corrupt T1346 Transparency International"}
,{id:"xref_t1368_education_vs_birth_rate_world",title:"Mean years of schooling vs. birth rate by country - the most powerful demographic relationship",sub:"Countries with under 4 years of schooling average 5.8 births per woman. Over 12 years: 1.7 births. The education-fertility relationship (r=-0.89) is the strongest country-level demographic correlation in all of social science. Educating girls is the most effective population policy ever discovered.",type:"XREF",geo:"worldwide",fmt:"Scatter plot",tbl:"T1368 International Statistics PDF (education) + T1338 (birth rate by country)",section:"International Statistics",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["pct_bachelors","birth_rate"],join:["net_migration_rate","rd_pct_gdp","per_capita_health_spending"],sc:{emotional:9,relatability:6,surprise:8,tension:6,visual:7,data_ready:9,originality:7},vs:77,tags:"mean years schooling birth rate country education fertility r=-0.89 strongest demographic correlation social science girls population policy T1368 T1338"}
,{id:"xref_t1370_health_spending_vs_life_expectancy_world",title:"Health spending per capita vs. life expectancy by country - the USA is the biggest outlier in the world",sub:"T1370 health spending crossed with T1338 life expectancy: the USA spends $12,900/person and gets 78.5 years of life expectancy. Japan spends $4,700 and gets 84.3 years. Cuba spends $2,100 and gets 78.8 years. The US is a dramatic outlier — spending 3x more than countries with better outcomes.",type:"XREF",geo:"worldwide",fmt:"Scatter plot",tbl:"T1370 International Statistics PDF (health spending) + T1338 (life expectancy)",section:"Health",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["per_capita_health_spending","rd_pct_gdp"],join:["net_migration_rate","birth_rate","population_pct_change_2020_2025"],sc:{emotional:9,relatability:8,surprise:9,tension:7,visual:7,data_ready:9,originality:6},vs:82,tags:"health spending life expectancy country USA $12900 78.5 years Japan $4700 84.3 Cuba $2100 78.8 outlier 3x spending worse outcomes T1370 T1338"}
,{id:"xref_t1352_energy_consumption_vs_co2",title:"Energy consumption per capita vs. CO2 emissions per capita by country - the clean energy transition mapped",sub:"T1352 energy crossed with T1372 CO2: Iceland consumes 15x the world average in energy per capita but emits only 9 tons CO2 per person (geothermal). Qatar consumes 3x less energy than Iceland but emits 31 tons CO2. Energy consumption and emissions are not the same map — and the gap is the clean energy transition.",type:"XREF",geo:"worldwide",fmt:"Scatter plot",tbl:"T1352 International Statistics PDF (energy) + T1372 (CO2 by country)",section:"Energy",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["energy_consumption_per_capita","renewable_energy_share"],join:["net_migration_rate","rd_pct_gdp","birth_rate"],sc:{emotional:7,relatability:6,surprise:9,tension:6,visual:6,data_ready:9,originality:8},vs:71,tags:"energy consumption CO2 emissions country Iceland 15x 9 tons Qatar 31 tons energy emissions not same map clean energy transition gap T1352 T1372"}
,{id:"t1374_deforestation_rate_by_country",title:"Annual forest loss rate by country 2010-2024 - where the trees are disappearing",sub:"Brazil: 1.7M hectares of forest lost per year 2015-2024 (down from 2.9M at peak deforestation). Democratic Republic of Congo: 940K ha/year. Indonesia: 620K ha/year. The deforestation rate map tells a different story than the forest cover map — some of the most forested countries are losing trees fastest.",type:"MAP",geo:"worldwide",fmt:"World choropleth",tbl:"T1374 International Statistics PDF + Global Forest Watch deforestation alerts (public)",section:"Geography",ext:["World Bank Open Data: GDP, population, income by country (data.worldbank.org - free API)"],vars:["pct_forest","national_forest_acres"],join:["birth_rate","net_migration_rate","rd_pct_gdp"],sc:{emotional:8,relatability:5,surprise:7,tension:8,visual:9,data_ready:9,originality:6},vs:74,tags:"annual forest loss country 2010 2024 Brazil 1.7M hectares DRC 940K Indonesia 620K deforestation rate different story most forested losing fastest Global Forest Watch"}
"""

with open('data.js', 'a', encoding='utf-8') as f:
    f.write(ideas)
    f.write('\n]; // end D\n')

print('Batch S appended. Now run: python maintain.py')
