import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCS01","The Streaming Wars Map: Most Popular Service by State","Which streaming platform dominates by state — Netflix, Disney+, YouTube TV, Hulu — based on subscriber data","MAP","US","State choropleth","entertainment","Nielsen: Streaming Content Ratings (nielsen.com/insights/media)",65,82,75,72,58,78,68,68),
mk("HCS02","Box Office Geography: Where Blockbusters Over- and Under-Perform","Which movie genres over-index in which states — horror in the South, romcoms in the Northeast, action in the Midwest","MAP","US","State choropleth","entertainment","The Numbers: Movie Market Research (the-numbers.com/market)",62,75,68,78,55,78,78,65),
mk("HCS03","The Taylor Swift Economy: Concert Tour Revenue vs. Host City GDP Impact","Economic impact of major concert tours on host cities — hotel bookings, restaurant revenue, transit usage","RANK","US","Bar chart","entertainment","US Travel Association: Event Economic Impact (ustravel.org)",65,78,72,78,55,68,75,62),
mk("HCS04","Americas Sports Map: Most Popular Sport by Media Market","Dominant sport by TV market — NFL vs. college football vs. NBA vs. MLB vs. soccer","MAP","US","State choropleth","sports","Nielsen: Sports Ratings by DMA (nielsen.com/insights/sports)",62,82,75,68,55,82,65,72),
mk("HCS05","The College Football Money Machine: Revenue by Program","Revenue generated by every FBS college football program, sized by dollars and colored by conference","RANK","US","Bar chart","sports","USA Today: NCAA Finances Database (usatoday.com/sports/ncaa/finances)",65,72,78,72,62,70,65,80),
mk("HCS06","Athlete Birthplace Density: Where NFL Players Come From Per Capita","NFL player birthplaces per capita by county — Texas, Florida, and Louisiana dominate","MAP","US","County choropleth","sports","Pro Football Reference: Birthplaces (pro-football-reference.com)",62,68,72,78,55,82,72,78),
mk("HCS07","The Podcast Geography: Most Popular Genres by State","What Americans listen to by region — true crime dominates the Midwest, comedy on the coasts, politics in DC","MAP","US","State choropleth","entertainment","Edison Research: Podcast Consumer Report (edisonresearch.com)",60,78,68,72,52,78,72,62),
mk("HCS08","Stadium Subsidy Scoreboard: How Much Public Money Built Each NFL Stadium","Public vs. private funding for every NFL stadium, ranked by taxpayer cost per seat","RANK","US","Bar chart","sports","Brookings: Stadium Subsidies (brookings.edu/research/stadium-subsidies)",78,72,78,78,75,70,72,78),
mk("HCS09","The Death of the Laugh Track: Sitcom vs. Single-Camera Comedy Over Time","Proportion of laugh-track sitcoms vs. single-camera comedies in network TV by year, 1970-2025","CHART","US","Area chart","entertainment","IMDb: TV Series Format Data (imdb.com/search/title)",55,72,72,72,50,68,72,72),
mk("HCS10","Americas Favorite Halloween Candy by State: The Definitive Map","Most purchased Halloween candy by state, based on retail sales data","MAP","US","State choropleth","entertainment","CandyStore.com: Halloween Candy Rankings (candystore.com/blog/facts-and-data)",55,85,72,68,48,82,62,72),
mk("HCS11","The Sports Betting Explosion: Revenue by State Since Legalization","Monthly sports betting handle and revenue by state since 2018 Supreme Court ruling","MAP","US","State choropleth","sports","AGA: Commercial Gaming Revenue Tracker (americangaming.org/research)",68,75,75,72,65,78,68,80),
mk("HCS12","Where Movies Are Made: Film Production Spending by State","Annual film and TV production spending by state, showing how tax incentives reshaped Hollywood","MAP","US","State choropleth","entertainment","MPAA: Film Production Statistics (motionpictures.org/research-docs)",62,65,78,72,58,78,68,78),
mk("HCS13","The Meme Stock Map: Retail Investor Activity by ZIP Code During GameStop","Geographic concentration of retail trading during the 2021 GameStop squeeze, by ZIP code","MAP","US","County choropleth","entertainment","Robinhood: Trading Activity Data (robinhood.com)",68,75,68,80,65,78,78,58),
mk("HCS14","Olympic Medal Geography: Which Countries Dominate Which Sports","Treemap of Olympic gold medals by country and sport, showing national sporting identities","MAP","World","Treemap","sports","Olympics: Medal Database (olympics.com/en/olympic-games)",62,65,78,72,58,82,68,88),
mk("HCS15","The News Desert Meets the Media Bubble: Local News Employment by County","Newspaper reporters per capita by county, showing the collapse of local journalism","MAP","US","County choropleth","media","UNC: News Deserts and Ghost Newspapers (usnewsdeserts.com)",78,72,75,78,78,82,72,75),
mk("HCS16","Social Media Platform Dominance by Country: The Fragmented Internet","Which social media platform is most popular in each country — WeChat, WhatsApp, Facebook, Line, VKontakte","MAP","World","World choropleth","media","DataReportal: Digital Country Reports (datareportal.com)",62,72,75,75,58,82,70,75),
mk("HCS17","The YouTube Nation: Hours of Video Uploaded Per Minute Over Time","Growth of YouTube content creation from 24 hours per minute in 2010 to 500+ hours per minute today","CHART","World","Line chart","media","Statista: YouTube Statistics (statista.com/topics/2019/youtube)",62,72,78,78,58,70,68,78),
mk("HCS18","Americas Funniest Cities: Comedy Club Density Per Capita","Comedy venues per 100k residents by metro area — NYC, LA, Chicago, but also surprising smaller markets","RANK","US","Bar chart","humor","Comedy Bureau: Venue Directory (thecomedybureau.com)",58,72,68,72,50,72,72,60),
mk("HCS19","The Sports Salary Explosion: Average Pro Athlete Pay 1970-2025","Average salary in NFL, NBA, MLB, NHL, MLS over time, adjusted for inflation","CHART","US","Line chart","sports","Spotrac: Historical Salary Data (spotrac.com/research)",65,75,78,72,62,70,65,82),
mk("HCS20","Video Game Revenue Now Bigger Than Movies and Music Combined","Annual revenue comparison: gaming vs. box office vs. recorded music, 2000-2025","CHART","World","Area chart","entertainment","Newzoo: Global Games Market Report (newzoo.com/resources)",68,78,78,82,62,70,72,78),
mk("HCS21","The True Crime Obsession Map: Where True Crime Podcasts Are Most Popular","Per-capita true crime podcast listening by state, correlated with actual crime rates","XREF","US","Scatter plot","entertainment","Edison Research: Podcast Listening Data (edisonresearch.com)",62,78,68,80,58,68,78,58),
mk("HCS22","Where Americans Get Their News: Primary News Source by Age and Region","Primary news source — TV, social media, print, radio, online — broken down by age group and state","CHART","US","Bar chart","media","Pew: News Sources Survey (pewresearch.org/journalism)",68,78,78,72,65,70,65,80),
mk("HCS23","The Concert Price Inflation Crisis: Average Ticket Prices 1995-2025","Average concert ticket prices over time, showing how Ticketmaster-era consolidation spiked costs","CHART","US","Line chart","entertainment","Pollstar: Concert Industry Statistics (pollstar.com)",75,82,78,72,72,68,68,78),
mk("HCS24","Americas Most Googled Questions by State: What We Secretly Wonder","Most uniquely Googled questions by state — revealing regional curiosities and anxieties","MAP","US","State choropleth","humor","Google Trends: Year in Search (trends.google.com/trends/yis)",60,82,68,82,55,80,78,72),
mk("HCS25","The Mascot Map: Most Common High School Mascots by State","Most popular high school team mascots by state — Eagles, Tigers, Bulldogs — revealing regional identity","MAP","US","State choropleth","humor","MaxPreps: High School Team Database (maxpreps.com)",52,72,68,68,45,80,68,72),
mk("HCS26","How Long Number One Songs Stay on Top: Chart Longevity Over Decades","Duration of Billboard Hot 100 number-one songs over time — from weeks to months in the streaming era","CHART","US","Line chart","entertainment","Billboard: Hot 100 Historical Data (billboard.com/charts/hot-100)",58,72,72,75,55,68,72,82),
mk("HCS27","The Esports Arena Map: Where Competitive Gaming Tournaments Happen","Major esports tournament venues and prize pools mapped globally, showing the geography of competitive gaming","MAP","World","Dot map","sports","Esports Earnings: Tournament Database (esportsearnings.com)",58,62,72,72,55,80,72,75),
mk("HCS28","Americas Bowling Alone Update: Social Club Membership Decline Since 1960","Decline in Elks, Rotary, bowling leagues, VFW, Masons, and other social clubs over time by state","CHART","US","Line chart","entertainment","Bowling Proprietors Association: Industry Statistics (bpaa.com)",72,75,75,72,70,68,70,72),
mk("HCS29","The Late Night Ratings Collapse: Network Talk Show Viewership 1995-2025","Viewership of Tonight Show, Late Show, Jimmy Kimmel over 30 years — the slow death of appointment TV","CHART","US","Line chart","media","Nielsen: Late Night Ratings Historical (nielsen.com/insights/media)",62,72,72,72,60,68,68,72),
mk("HCS30","The Festival Industrial Complex: Music Festival Revenue and Attendance Map","Every major music festival mapped with attendance and ticket price, showing the festival economy","MAP","US","Dot map","entertainment","Pollstar: Festival Attendance Data (pollstar.com)",60,72,68,72,55,82,68,68),
mk("HCS31","What Each Country Listens To: Top Spotify Genre by Country","Most-streamed music genre by country showing cultural preferences — K-pop in SE Asia, reggaeton in Latin America","MAP","World","World choropleth","entertainment","Spotify: Streaming Data Reports (newsroom.spotify.com)",58,72,72,75,52,82,72,68),
mk("HCS32","The College Athletics Gender Gap: Title IX Compliance by School","Ratio of male to female athletic scholarship dollars by university, 50 years after Title IX","RANK","US","Bar chart","sports","DOE: Equity in Athletics Disclosure (ope.ed.gov/athletics)",72,68,75,75,72,68,72,80),
mk("HCS33","Americas Humor Divide: Punchline vs. Observational vs. Political Comedy Preference by Region","Regional preference for comedy styles based on ticket sales and streaming data","MAP","US","State choropleth","humor","Laugh Factory: Performance Data (laughfactory.com)",55,72,65,72,48,78,78,55),
mk("HCS34","The Wikipedia Edit War Map: Most Contested Articles by Country","Countries with the most edit wars on their Wikipedia pages, showing geopolitical sensitivity in the digital commons","RANK","World","Bar chart","media","Wikipedia: Edit War Statistics (en.wikipedia.org/wiki/Wikipedia:Edit_warring)",58,58,68,82,62,68,82,72),
mk("HCS35","Screen Time Nation: Average Daily Screen Hours by Country","Average hours per day spent on screens by country, broken down by device type","RANK","World","Bar chart","media","DataReportal: Global Digital Overview (datareportal.com)",68,82,78,72,65,68,65,78),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCS batch)")
