import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HBZ01","The Definitive Map of Where Your Food Actually Comes From","Every major crop and livestock product traced from farm county to your plate","MAP","US-county","County choropleth","food/agriculture","USDA: Census of Agriculture (nass.usda.gov); Census: CBP (census.gov); BTS: Freight (bts.gov)",72,82,75,68,58,82,70,85),
mk("HBZ02","Every Country That Tried Universal Healthcare and What Happened to Life Expectancy","Before/after adoption dates for 30+ countries — US is the control group","CHART","World","Line chart","health/international","WHO: Health expenditure (who.int); OECD: Health data (oecd.org/health); World Bank: Life expectancy (worldbank.org)",85,78,80,78,78,72,72,85),
mk("HBZ03","The Last Gun Control Chart Youll Ever Need: Every Policy Mapped Against Every Outcome","Comprehensive matrix of state gun laws vs 6 outcome measures — the full picture","CHART","US-state","Scatter plot","guns/law","Giffords: Scorecard (giffords.org); CDC: Mortality (wonder.cdc.gov); FBI: UCR (ucr.fbi.gov); RAND: Gun policy (rand.org)",82,75,82,75,82,70,72,82),
mk("HBZ04","The Definitive Democracy Scorecard: How Every Country Ranks on 12 Metrics","Electoral integrity, press freedom, corruption, judicial independence — all in one view","CHART","World","Ranked list","democracy/international","V-Dem: Democracy indices (v-dem.net); Freedom House: Scores (freedomhouse.org); RSF: Press freedom (rsf.org); TI: CPI (transparency.org)",75,68,80,70,72,75,68,88),
mk("HBZ05","Where the Middle Class Disappeared: County Income Distribution 1980 vs 2024","Side-by-side income histograms showing the hollowing out of the American middle","CHART","US-county","Bar chart","inequality/history","Census: Income distribution (census.gov); BLS: CPI adjustment (bls.gov/cpi); Federal Reserve: SCF (federalreserve.gov)",85,82,78,78,82,72,72,82),
mk("HBZ06","The Psychology of Decision Fatigue: How Many Choices Americans Face Per Day by Income","Low-income households face 3x more mandatory daily decisions — mapped by metro","CHART","US-metro","Bar chart","psychology/inequality","APA: Decision fatigue research (apa.org); BLS: ATUS (bls.gov/tus); Census: Income (census.gov/acs)",72,82,62,82,68,65,85,52),
mk("HBZ07","Every Factory That Left America and Where It Went: 2000-2025","Flow map of manufacturing facility relocations by destination country","MAP","World","Line map","manufacturing/trade","BLS: Mass layoffs (bls.gov); Census: Import data (census.gov/trade); Reshoring Initiative (reshorenow.org)",80,75,72,75,78,82,72,72),
mk("HBZ08","The Rural Healthcare Paradox: Counties With the Worst Health Need the Most Doctors but Get the Fewest","HPSA scores mapped against chronic disease burden — perfect inverse correlation","MAP","US-county","Bivariate choropleth","rural/health","HRSA: HPSA (hrsa.gov); CDC: Chronic disease (cdc.gov); Census: Demographics (census.gov)",85,78,78,75,82,80,72,80),
mk("HBZ09","Every Religion in America Mapped to the Census Tract Level","The most granular religious geography map ever attempted — 350+ denominations","MAP","US-county","Dot map","religion/geography","ARDA: Religious census (thearda.com); RCMS: Congregational data (rcms.org); Glenmary: Church data (glenmary.org)",68,70,72,72,58,88,75,80),
mk("HBZ10","The Sports Money Machine: Revenue Per Fan for Every Major League Team","NFL, NBA, MLB, NHL, MLS revenue divided by metro population — who pays most per capita","CHART","US-metro","Bar chart","sports/economy","Forbes: Team valuations (forbes.com); BEA: Metro population (bea.gov); ESPN: Revenue data (espn.com)",70,80,72,72,60,68,72,70),
mk("HBZ11","The Entertainment Monoculture Map: How Many Streaming Services Each Metro Subscribes To","Average subscriptions per household mapped against income and broadband","MAP","US-metro","State choropleth","entertainment/technology","Nielsen: Streaming data (nielsen.com); Census: Income (census.gov); FCC: Broadband (fcc.gov)",65,80,68,68,55,70,72,65),
mk("HBZ12","Where Law Enforcement Budgets Exceed School Budgets","Cities where police spending per capita exceeds education spending — mapped","MAP","US-metro","Bivariate choropleth","law/education","Census: Government finance (census.gov/govs); FBI: UCR (ucr.fbi.gov); NCES: Per-pupil (nces.ed.gov)",82,78,78,78,82,78,72,78),
mk("HBZ13","The Definitive Drug War Timeline: $1.5 Trillion Spent and Every Metric Got Worse","Federal drug war spending vs addiction rates, overdose deaths, incarceration — all rising together","CHART","US","Line chart","drugs/law","ONDCP: Drug budget (whitehouse.gov/ondcp); CDC: Overdose (wonder.cdc.gov); BJS: Drug offenders (bjs.gov)",85,75,78,80,85,72,75,78),
mk("HBZ14","The Middle East Before Oil: GDP Rankings in 1930 vs Today","How petroleum reshaped an entire regions economic hierarchy in one century","CHART","Middle East","Bar chart","middle_east/history","Maddison Project: Historical GDP (rug.nl/ggdc/maddison); World Bank: Current GDP (worldbank.org)",72,62,72,82,68,68,80,72),
mk("HBZ15","Where Americas Demographics Dont Match Americas Representation","Every county: demographic composition vs elected official composition — the gap mapped","MAP","US-county","Bivariate choropleth","demographics/democracy","Census: Demographics (census.gov); ICMA: Elected officials (icma.org); Who Leads Us: Representation (wholeads.us)",82,75,75,75,82,78,72,68),
mk("HBZ16","The Gun Culture Divide: What Owners and Non-Owners Believe About Each Other","Survey misperceptions mapped — both sides wildly wrong about the other","CHART","US","Bar chart","guns/psychology","Pew: Gun survey (pewresearch.org); Gallup: Gun attitudes (gallup.com); RAND: Gun ownership (rand.org)",72,78,68,82,72,65,82,65),
mk("HBZ17","Where Your Favorite Sports Team Extracts Wealth From Your City","Net economic transfer from metro areas to team ownership mapped by franchise","CHART","US-metro","Bar chart","sports/finance","Forbes: Team valuations (forbes.com); Brookings: Stadium economics (brookings.edu); BEA: Metro GDP (bea.gov)",78,80,72,78,75,70,78,68),
mk("HBZ18","The Manufacturing Skills Gap Is a Wage Gap: Starting Pay vs Comparable Jobs","Factory starting wages mapped against warehouse, retail, and food service — the gap closed","CHART","US-state","Bar chart","manufacturing/labor","BLS: OES (bls.gov/oes); Indeed: Wage data (indeed.com); NAM: Workforce survey (nam.org)",75,82,78,78,72,68,72,78),
mk("HBZ19","Every Country in the Middle East Ranked by Press Freedom and What Happened to Their Journalists","Press freedom scores mapped against journalist imprisonment and disappearance data","CHART","Middle East","Bar chart","middle_east/media","RSF: Press freedom (rsf.org); CPJ: Journalist safety (cpj.org)",82,62,75,78,85,70,75,82),
mk("HBZ20","The Law of the Land: How Legal Weed States Compare to Prohibition States on Every Metric","Crime, revenue, usage rates, DUI, youth access — comprehensive comparison","CHART","US-state","Bar chart","drugs/law","NORML: State laws (norml.org); FBI: UCR (ucr.fbi.gov); Tax Foundation: Revenue (taxfoundation.org); SAMHSA: Usage (samhsa.gov)",78,80,78,75,75,70,72,80),
mk("HBZ21","Where Rural America Votes Against Its Own Economic Interests — And Why","Counties receiving most federal aid per capita mapped against anti-government voting patterns","MAP","US-county","Bivariate choropleth","rural/politics","USASpending: Federal aid (usaspending.gov); MIT: Elections (electionlab.mit.edu); Census: Income (census.gov)",82,78,72,80,82,78,78,78),
mk("HBZ22","The Psychology of Financial Anxiety: Net Worth vs Perceived Financial Health by State","Objective wealth vs subjective stress — rich states are often the most anxious","CHART","US-state","Scatter plot","psychology/finance","Federal Reserve: SCF (federalreserve.gov); Gallup: Financial wellbeing (gallup.com); Census: Income (census.gov)",72,82,68,82,65,68,80,65),
mk("HBZ23","The Entertainment Tax: How Much Each State Subsidizes Hollywood Per Job Created","Cost per job of film tax credits — some states paying $200K+ per position","CHART","US-state","Bar chart","entertainment/economy","NCSL: Film incentives (ncsl.org); MPAA: Economic impact (motionpictures.org); BLS: Arts employment (bls.gov)",72,72,78,78,72,68,78,72),
mk("HBZ24","The Global Gun Chart: Civilian Firearms Per Capita in Every Country","US is such an outlier you need a log scale — 120 guns per 100 people","CHART","World","Bar chart","guns/international","Small Arms Survey: Global firearms (smallarmssurvey.org); UNODC: Homicide (unodc.org)",78,72,82,78,72,70,65,88),
mk("HBZ25","Where Corporations Write the Laws: ALEC Model Bill Adoption by State","Number of ALEC-drafted bills adopted mapped against corporate lobbying spending","MAP","US-state","Bivariate choropleth","law/politics","ALEC Exposed: Model bills (alecexposed.org); OpenSecrets: Lobbying (opensecrets.org); NCSL: Bill tracking (ncsl.org)",80,68,70,80,82,75,80,68),
mk("HBZ26","The Religion Premium: How Church Attendance Correlates With Income by Race","The relationship flips depending on race — White churchgoers earn more, Black churchgoers earn less","CHART","US","Line chart","religion/race","GSS: Income by religion (gss.norc.org); Pew: Religious landscape (pewresearch.org); Census: Income by race (census.gov)",72,72,65,85,72,65,85,62),
mk("HBZ27","The Sports Concussion Crisis by the Numbers: Youth Athletes at Risk","Concussion rates by sport, age, and gender — the data parents need to see","CHART","US","Bar chart","sports/children","CDC: Youth sports injuries (cdc.gov); NCAA: Injury surveillance (ncaa.org); Safe Kids: Sports safety (safekids.org)",82,82,78,72,78,68,68,75),
mk("HBZ28","The Definitive Map of Americas Food Deserts: 2024 Update","23.5 million Americans live more than a mile from a grocery store — mapped with race and income","MAP","US-county","County choropleth","food/poverty","USDA: Food access (ers.usda.gov); Census: ACS (census.gov/acs)",82,82,78,68,78,82,62,85),
mk("HBZ29","How the Middle East Draws Water From Stone: Desalination Capacity by Country","Countries investing billions in desalination mapped against rainfall and aquifer depletion","MAP","Middle East","Bar chart","middle_east/science","GWI: Desalination data (globalwaterintel.com); FAO: AQUASTAT (fao.org); NASA: GRACE (nasa.gov)",70,58,72,78,70,72,78,75),
mk("HBZ30","Where Demographics Is Destiny: The Counties That Will Flip by 2032","Demographic trends extrapolated to predict partisan shifts — the math of political change","MAP","US-county","County choropleth","demographics/politics","Census: Population projections (census.gov); MIT: Elections (electionlab.mit.edu); Catalist: Voter file (catalist.us)",78,72,70,80,78,78,80,62),
mk("HBZ31","The Drug That Built Suburbia: Amphetamine Prescription Rates by Zip Code","Adderall/Vyvanse prescriptions mapped against income and school performance pressure","MAP","US-county","County choropleth","drugs/psychology","DEA: ARCOS (deadiversion.usdoj.gov); CDC: Prescription data (cdc.gov); Census: Income (census.gov)",75,80,68,80,72,75,78,72),
mk("HBZ32","Every Major Environmental Law Rolled Back Since 2017 and What Happened Next","EPA enforcement actions mapped before/after regulatory rollbacks — emission changes visible","CHART","US","Line chart","environment/law","EPA: Enforcement (echo.epa.gov); Federal Register: Rules (federalregister.gov); EIA: Emissions (eia.gov)",80,72,75,78,82,70,72,78),
mk("HBZ33","The Global Sports Wage Gap: What Female Athletes Earn Compared to Male Athletes","Pay ratios for top athletes by sport and country — soccer is the worst offender","CHART","World","Bar chart","sports/gender","Forbes: Athlete earnings (forbes.com); FIFA: Prize money (fifa.com); WTA/ATP: Prize data (wtatennis.com)",80,78,78,72,78,68,72,72),
mk("HBZ34","Where You Live Determines If You Go to Prison or Rehab for the Same Drug Offense","County-level diversion vs incarceration rates for identical drug charges","MAP","US-county","Bivariate choropleth","drugs/law","BJS: Felony sentencing (bjs.gov); SAMHSA: Treatment admissions (samhsa.gov); Census: Demographics (census.gov)",85,78,72,82,85,78,78,68),
mk("HBZ35","The Entertainment Industry Power Map: Who Owns What You Watch Read and Listen To","Six companies own 90% of American media — ownership tree visualized","CHART","US","Treemap","entertainment/finance","SEC: Corporate filings (sec.gov); FCC: Media ownership (fcc.gov); Columbia Journalism Review: Media ownership (cjr.org)",78,80,75,78,78,75,72,78),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HBZ ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HBZ batch)")
