import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDE01","America's Shifting Center of Population: 230 Years of Westward Drift","The US Census mean center of population plotted decade by decade from 1790 to 2020 — a slow march from Maryland to Missouri","MAP","US","Line map","demographics","Census Bureau: Center of Population (census.gov/programs-surveys/decennial-census/about/center-of-population)",62,68,75,65,52,80,68,92),
mk("HDE02","The Graying Map: Median Age by County 2000 vs 2020","Side-by-side county choropleth showing how dramatically median age has risen across Appalachia, the Plains, and New England","MAP","US","County choropleth","demographics","Census Bureau: ACS 5-Year Estimates (data.census.gov)",65,72,78,62,60,82,60,90),
mk("HDE03","Where Guns Outnumber People: Estimated Civilian Firearms Per Capita by State","State-level estimates of civilian-owned firearms per 100 residents using ATF trace data and survey proxies","MAP","US","State choropleth","guns","ATF: Firearms Commerce Report (atf.gov/firearms/docs/report)",68,72,70,65,75,78,62,72),
mk("HDE04","Factory Floor Footprint: Manufacturing Employment Share by County","Percentage of county workforce employed in manufacturing — the Rust Belt reality vs Southern reshoring corridors","MAP","US","County choropleth","manufacturing","BLS: Quarterly Census of Employment and Wages (bls.gov/cew)",58,68,75,62,60,80,58,90),
mk("HDE05","Birth Rate Collapse: Total Fertility Rate by State 2005 vs 2024","State-level TFR decline mapped side by side, showing which states fell below replacement and by how much","MAP","US","Bivariate choropleth","demographics","CDC: National Vital Statistics (cdc.gov/nchs/nvss/births.htm)",72,78,72,70,72,75,65,88),
mk("HDE06","Ghost Guns: Privately Made Firearms Recovered by Law Enforcement by Year","Annual count of ghost guns recovered at crime scenes — from near-zero in 2016 to 25,000+ by 2023","CHART","US","Bar chart","guns","ATF: National Firearms Commerce and Trafficking Assessment (atf.gov)",70,62,68,78,80,65,72,80),
mk("HDE07","The Semiconductor Map: Every Chip Fab Under Construction or Planned in America","Locations of all announced semiconductor fabrication plants post-CHIPS Act, sized by investment and colored by company","MAP","US","Dot map","manufacturing","SIA: Semiconductor Industry Association (semiconductors.org)",60,55,72,70,62,82,68,78),
mk("HDE08","The Diversity Explosion: Multiracial Population Growth by Metro Area","Metros with the fastest-growing multiracial population between 2010 and 2020, showing the demographic future arriving early","MAP","US","Graduated symbol map","demographics","Census Bureau: Decennial Census Race Data (data.census.gov)",62,70,68,72,55,72,70,90),
mk("HDE09","Stand Your Ground States: Justifiable Homicide Rates Before and After Passage","Rate of legally justified homicides in states that adopted Stand Your Ground laws vs control states, pre/post comparison","CHART","US","Line chart","guns","FBI: Supplementary Homicide Reports (ucr.fbi.gov)",72,68,75,72,82,62,74,75),
mk("HDE10","Reshoring Index: Manufacturing Jobs Returning to the US by Sector","Annual net manufacturing jobs reshored to the US from offshore, broken down by industry — electronics, auto, pharma, textiles","CHART","US","Stacked bar chart","manufacturing","Reshoring Initiative: Data Reports (reshorenow.org)",58,62,70,68,60,65,66,72),
mk("HDE11","Water Wars of the Middle East: Who Controls the Rivers","Map of transboundary rivers — Tigris, Euphrates, Jordan, Nile — showing upstream dams, downstream dependency, and conflict flashpoints","MAP","Middle East","Special map","middle_east","FAO: AQUASTAT Transboundary Rivers (fao.org/aquastat)",72,58,68,72,82,85,76,70),
mk("HDE12","The Language Map of America: Most Common Non-English Language by County","Beyond Spanish — which counties speak Tagalog, Vietnamese, Arabic, German, or Navajo at home","MAP","US","County choropleth","demographics","Census Bureau: ACS Language Spoken at Home (data.census.gov)",60,75,78,72,48,82,68,90),
mk("HDE13","Ammunition Sales Spike Map: Background Check Surges During Crisis Events","Monthly NICS background checks mapped against mass shootings, elections, and pandemic panic — every spike tells a story","CHART","US","Area chart","guns","FBI: NICS Firearm Background Checks (fbi.gov/about-us/cjis/nics)",70,72,72,68,78,70,66,88),
mk("HDE14","Made in Mexico: The Nearshoring Boom in Manufacturing Investment","Foreign direct investment flowing into Mexican manufacturing by state — Nuevo Leon, Jalisco, and Chihuahua leading the charge","MAP","Mexico","State choropleth","manufacturing","INEGI: Foreign Direct Investment (inegi.org.mx)",55,52,68,70,62,75,72,72),
mk("HDE15","Sectarian Geography: Sunni, Shia, and Kurdish Populations Across the Middle East","Detailed ethno-religious population map of Iraq, Syria, Lebanon, Bahrain, Yemen, and Saudi Arabia","MAP","Middle East","Special map","middle_east","Columbia University: Gulf/2000 Project (gulf2000.columbia.edu)",68,55,70,68,75,85,72,65),
mk("HDE16","The Census Undercount: Who Gets Missed and Where","Estimated net undercount rates by race, age, and state in the 2020 Census — children under 5 and renters most missed","MAP","US","Bivariate choropleth","demographics","Census Bureau: Post-Enumeration Survey (census.gov/coverage_measurement)",65,68,72,75,68,70,74,82),
mk("HDE17","Child Access Prevention Laws: Where Kids Can Legally Access Unsecured Firearms","State map of child access prevention law strength vs pediatric firearm death rates","MAP","US","Bivariate choropleth","guns","Everytown: Gun Law Rankings (everytown.org/rankings)",78,75,72,68,82,74,66,78),
mk("HDE18","The EV Battery Belt: New Battery and EV Manufacturing Plants in the US Southeast","Every announced EV and battery gigafactory in Georgia, Tennessee, Kentucky, and the Carolinas mapped with investment size","MAP","US","Dot map","manufacturing","DOE: Battery Supply Chain Map (energy.gov)",58,55,72,65,55,78,66,80),
mk("HDE19","Refugee Camps of the Middle East: Population and Duration","Every major refugee camp in Jordan, Lebanon, Turkey, and Iraq — how many people, how long theyve been there, and where they came from","MAP","Middle East","Dot map","middle_east","UNHCR: Refugee Data Finder (unhcr.org/refugee-statistics)",80,62,68,65,78,82,68,82),
mk("HDE20","Where America Is Getting Younger: The Few Counties Bucking the Aging Trend","Counties where median age actually decreased 2010-2020 — college towns, immigrant gateway communities, and military bases","MAP","US","County choropleth","demographics","Census Bureau: ACS 5-Year Estimates (data.census.gov)",58,68,72,75,52,78,72,90),
mk("HDE21","The Gun Show Loophole Map: States Requiring Background Checks for Private Sales","Which states require universal background checks vs those with no private sale oversight, mapped against trafficking patterns","MAP","US","State choropleth","guns","Giffords: Gun Law Scorecard (giffords.org/lawcenter/gun-laws)",65,68,75,62,78,72,60,82),
mk("HDE22","Steel Mill Closures vs Openings: Net Change in US Steel Capacity by Decade","Mapping the collapse of integrated steel mills and rise of mini-mills — from Pittsburgh dominance to Southern electric arc furnaces","MAP","US","Dot map","manufacturing","AISI: American Iron and Steel Institute (steel.org)",62,65,72,68,65,75,70,72),
mk("HDE23","Gulf State Labor Force: Migrant Workers as Share of Population","Percentage of population that is foreign-born migrant labor in Qatar, UAE, Kuwait, Bahrain, Saudi Arabia, and Oman","RANK","Middle East","Horizontal bar chart","middle_east","ILO: International Labour Organization (ilo.org/global/topics/labour-migration)",70,58,72,78,72,65,72,80),
mk("HDE24","The Depopulation Belt: US Counties That Lost 25%+ of Their Population Since 1950","Mapping the emptying heartland — counties across the Great Plains, Delta, and Appalachia in severe long-term decline","MAP","US","County choropleth","demographics","Census Bureau: Decennial Census Historical Population (data.census.gov)",72,68,78,65,70,82,64,90),
mk("HDE25","Dealer Density: Gun Stores Per Capita by State","Federal firearms licensees per 100K residents mapped by state — Montana and Wyoming at 10x the density of New York or New Jersey","MAP","US","State choropleth","guns","ATF: Federal Firearms Licensee Listing (atf.gov/firearms/listing-federal-firearms-licensees)",55,62,75,68,62,72,58,88),
mk("HDE26","Textile Towns Transformed: Former Mill Communities 30 Years Later","Economic trajectory of towns whose main employer was a textile or apparel factory that closed in the 1990s-2000s NAFTA era","MAP","US","Dot map","manufacturing","BLS: Local Area Unemployment Statistics (bls.gov/lau)",68,72,65,62,68,72,70,68),
mk("HDE27","Desalination Dependence: Middle East Countries Ranked by Desalinated Water Share","Percentage of national freshwater supply that comes from desalination plants — Saudi Arabia and UAE near 50%","RANK","Middle East","Bar chart","middle_east","IDDA: International Desalination Association (idadesal.org)",58,52,72,72,68,65,70,75),
mk("HDE28","Household Size Shrinkage: Average Persons Per Household by State 1970 vs 2020","The dramatic shrinking of the American household — from 3.1 to 2.5 nationally, with Utah and immigrant metros as outliers","CHART","US","Bar chart","demographics","Census Bureau: Historical Household Statistics (census.gov)",60,75,78,65,55,65,62,92),
mk("HDE29","Mass Shooting Frequency: Days Between Incidents With 4+ Victims Since 2014","The shrinking gap between mass shooting events in the US — from weeks apart to near-daily in some years","CHART","US","Line chart","guns","Gun Violence Archive: Mass Shooting Data (gunviolencearchive.org)",82,75,72,68,85,62,64,85),
mk("HDE30","CHIPS Act Tracker: Federal Semiconductor Subsidies Awarded by State","Where CHIPS and Science Act funding has landed — Intel in Ohio, TSMC in Arizona, Samsung in Texas, mapped with amounts","MAP","US","Dot map","manufacturing","CHIPS.gov: CHIPS Incentive Awards (chips.gov)",55,52,70,65,58,75,62,82),
mk("HDE31","Oil Wealth Per Citizen: GDP Per Capita in Middle East Petrostates vs Non-Oil Economies","GDP per capita comparison between Gulf petrostates and their non-oil neighbors — Qatar at $80K vs Yemen at $600","RANK","Middle East","Bar chart","middle_east","World Bank: GDP Per Capita (data.worldbank.org)",65,58,75,72,68,62,65,88),
mk("HDE32","The Baby Bust Map: Counties Where Deaths Outnumber Births","Natural population decrease — counties where more people die than are born each year, concentrated in rural America","MAP","US","County choropleth","demographics","CDC: WONDER Natality and Mortality (wonder.cdc.gov)",72,70,75,68,72,78,62,88),
mk("HDE33","Red Flag Law Usage: Extreme Risk Protection Orders Filed by State","How often red flag laws are actually used where they exist — petitions filed per capita showing massive variation in enforcement","CHART","US","Bar chart","guns","State court administrative offices: ERPO filings (various state judiciary sites)",65,68,72,75,78,62,70,65),
mk("HDE34","Factory Robot Density: Industrial Robots Per 10K Manufacturing Workers by Country","How automated each nations factory floor is — South Korea and Singapore at 10x the global average","RANK","World","Horizontal bar chart","manufacturing","IFR: World Robotics Report (ifr.org/worldrobotics)",58,52,72,72,58,68,68,85),
mk("HDE35","Womens Rights in the Middle East: Legal Rights Index by Country","Composite score of womens legal rights across 12 dimensions — property, divorce, custody, employment, travel — in every MENA nation","RANK","Middle East","Horizontal bar chart","middle_east","World Bank: Women Business and the Law (wbl.worldbank.org)",75,62,70,65,72,60,68,82),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDE batch)")
