import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCJ01","Every Swing County in America: The 200 Places That Decide Elections","Counties that flipped between 2016, 2020, and 2024 mapped with demographic profiles","MAP","US-county","County choropleth","democracy/geography","MIT: Elections (electionlab.mit.edu); Census: Demographics (census.gov/acs); Cook: PVI (cookpolitical.com)",78,75,78,72,78,80,68,85),
mk("HCJ02","Where Voter Registration Purges Target Minorities: The Quiet Disenfranchisement","Purge rates mapped by county demographics — racial disparity in list maintenance","MAP","US-county","Bivariate choropleth","democracy/race","EAC: Election data (eac.gov); Brennan Center: Purges (brennancenter.org); Census: Demographics (census.gov)",82,72,72,80,85,75,78,68),
mk("HCJ03","The Gun Vote: How Firearm Policy Positions Predict Congressional Margins Better Than Party","NRA grade mapped against election margin — single-issue voting visualized","CHART","US-state","Scatter plot","guns/democracy","NRA: Grades (nra.org); OpenSecrets: Contributions (opensecrets.org); MIT: Elections (electionlab.mit.edu)",72,68,72,78,72,68,75,78),
mk("HCJ04","Where Drug Policy Ballot Measures Win: The Disconnect Between Voters and Legislators","States where drug reform passes by referendum but legislatures resist — the gap mapped","CHART","US-state","Bar chart","drugs/democracy","Ballotpedia: Ballot measures (ballotpedia.org); NORML: State laws (norml.org); MIT: Elections (electionlab.mit.edu)",75,72,72,80,72,68,78,72),
mk("HCJ05","The Psychology of the Undecided Voter: Who They Actually Are by Demographics","The mythical swing voter profiled — age, income, education, media diet mapped by state","CHART","US-state","Bar chart","psychology/democracy","Pew: Political typology (pewresearch.org); ANES: Voter surveys (electionstudies.org); Gallup: Independents (gallup.com)",70,75,65,78,65,68,78,65),
mk("HCJ06","Middle East Elections That Actually Happened: Democracy Attempts Mapped Since 2000","Every competitive election in MENA mapped with Freedom House scores and aftermath","MAP","Middle East","Special map","middle_east/democracy","Freedom House: FITW (freedomhouse.org); V-Dem: Elections (v-dem.net); IDEA: Electoral system (idea.int)",72,58,72,78,72,72,78,72),
mk("HCJ07","Where Polling Places Closed: 1,700 Fewer Voting Locations Since 2013","Polling place closures mapped against Shelby County v Holder and demographic change","MAP","US-county","Dot map","democracy/law","Leadership Conference: Closures (civilrights.org); EAC: Election admin (eac.gov); Census: Demographics (census.gov)",82,75,75,78,85,78,72,72),
mk("HCJ08","The Demographics of Non-Voters: 80 Million Eligible Americans Who Stay Home","Who doesnt vote mapped by age, race, income, and geography — the silent majority","MAP","US-county","County choropleth","demographics/democracy","Census: CPS Voting (census.gov); MIT: Elections (electionlab.mit.edu); Pew: Non-voters (pewresearch.org)",78,78,75,78,72,78,72,78),
mk("HCJ09","Every State Legislature Controlled by a Minority of Voters: The Representation Gap","Gerrymandering + turnout = minority rule in 12 states — the math mapped","MAP","US-state","State choropleth","democracy/inequality","Ballotpedia: State legislatures (ballotpedia.org); PlanScore: Efficiency gap (planscore.org); Census: Population (census.gov)",80,72,78,80,82,75,75,72),
mk("HCJ10","Where Dark Money Decides Local Elections: Outside Spending in County Races","Dark money spending in local elections mapped — school board to county commission","MAP","US-county","Dot map","democracy/finance","OpenSecrets: Dark money (opensecrets.org); Issue One: Political spending (issueone.org); FEC: Data (fec.gov)",78,72,68,78,80,72,78,62),
mk("HCJ11","The Religious Vote Mapped: How Evangelical Turnout Shapes State Elections","Evangelical population vs turnout differential mapped against Republican margin gains","MAP","US-state","Bivariate choropleth","religion/democracy","Pew: Religious landscape (pewresearch.org); ARDA: Evangelical census (thearda.com); MIT: Elections (electionlab.mit.edu)",72,68,72,75,72,75,70,78),
mk("HCJ12","Where Manufacturing Job Loss Delivered the Electoral College: The Counties That Mattered","The 77,000 votes across 3 states in 2016 mapped against manufacturing decline","MAP","US-county","Bivariate choropleth","manufacturing/democracy","BLS: QCEW (bls.gov/qcew); MIT: Elections (electionlab.mit.edu); Census: Industry (census.gov)",82,72,75,78,80,78,72,82),
mk("HCJ13","The Entertainment of Politics: Campaign Ad Spending vs Actual Voter Contact","TV ad dollars mapped against door-to-door canvassing — which moves votes more","CHART","US-state","Scatter plot","entertainment/democracy","Wesleyan Media Project: Ad tracking (mediaproject.wesleyan.edu); FEC: Spending (fec.gov); MIT: Elections (electionlab.mit.edu)",68,68,68,75,65,68,78,68),
mk("HCJ14","Where Gun Owners and Non-Owners Live in Completely Different Americas","The geographic sorting of gun culture mapped — two countries sharing one border","MAP","US-county","County choropleth","guns/geography","RAND: Gun ownership (rand.org); Census: Demographics (census.gov/acs); Gallup: Guns (gallup.com)",72,75,72,72,68,80,70,72),
mk("HCJ15","The Sports Stadium Vote: How Stadium Referendums Predict Local Political Temperature","Stadium ballot measures mapped against subsequent election outcomes — the anger indicator","XREF","US-metro","Scatter plot","sports/democracy","Ballotpedia: Stadium measures (ballotpedia.org); Brookings: Stadiums (brookings.edu); MIT: Elections (electionlab.mit.edu)",65,68,60,78,62,65,80,58),
mk("HCJ16","Where Law Enforcement Unions Spend Political Money: The Police PAC Map","Police union campaign contributions mapped against criminal justice reform votes","MAP","US-state","State choropleth","law/democracy","OpenSecrets: Police PACs (opensecrets.org); FEC: Contributions (fec.gov); GovTrack: Voting (govtrack.us)",78,68,72,78,78,72,78,72),
mk("HCJ17","The Psychology of Polarization Mapped: How Your Social Media Diet Predicts Your Vote","Information silo index by county correlated with partisan lean — the filter bubble geography","XREF","US-county","Scatter plot","psychology/media","NYU: Social media studies (csmapnyu.org); Pew: Media habits (pewresearch.org); MIT: Elections (electionlab.mit.edu)",72,78,62,80,72,68,80,58),
mk("HCJ18","Middle East Democracy Movements: The Arab Spring 15 Years Later","Every Arab Spring country mapped with current governance scores — who improved, who didnt","MAP","Middle East","Bar chart","middle_east/democracy","V-Dem: Democracy (v-dem.net); Freedom House: FITW (freedomhouse.org); ACLED: Protest (acleddata.com)",75,62,72,78,75,72,72,78),
mk("HCJ19","Where Rural Voters Punch Above Their Weight: Electoral Power Per Capita","Votes per electoral college vote by county mapped — the power asymmetry visualized","MAP","US-county","County choropleth","rural/democracy","Census: Population (census.gov); Electoral vote allocation; MIT: Elections (electionlab.mit.edu)",78,72,78,75,78,78,70,82),
mk("HCJ20","The Demographic Realignment in Real Time: College Education as the New Partisan Divide","College-educated share mapped against partisan shift 2012-2024 — the education polarization","MAP","US-county","Bivariate choropleth","demographics/politics","Census: Education (census.gov/acs); MIT: Elections (electionlab.mit.edu); Pew: Education politics (pewresearch.org)",78,72,75,78,78,78,72,80),
mk("HCJ21","Where Drug Companies Buy Policy: Pharma Lobbying Spending by State Legislature","State-level pharmaceutical lobbying mapped against drug pricing legislation outcomes","MAP","US-state","State choropleth","drugs/politics","OpenSecrets: State lobbying (opensecrets.org); NCSL: Drug pricing (ncsl.org); Kaiser: Drug costs (kff.org)",78,72,72,78,78,72,72,72),
mk("HCJ22","The Gun Lobby vs Gun Control Lobby: Dollar for Dollar Spending Comparison by State","NRA + NSSF vs Everytown + Giffords spending mapped — the asymmetry in funding","CHART","US-state","Bar chart","guns/finance","OpenSecrets: Issue spending (opensecrets.org); FEC: PAC data (fec.gov); IRS: 501c4 (irs.gov)",72,68,75,72,72,68,68,78),
mk("HCJ23","Where Entertainment Industry Workers Shape Elections: Hollywood Donor Geography","Creative industry political contributions mapped by zip code and recipient","MAP","US-metro","Dot map","entertainment/politics","FEC: Individual contributions (fec.gov); OpenSecrets: Industry (opensecrets.org); BLS: Arts employment (bls.gov)",62,65,65,68,58,68,72,72),
mk("HCJ24","The Law of Campaign Finance: How Citizens United Changed Spending in Every State","Before and after Citizens United spending mapped by state and election cycle","CHART","US-state","Line chart","law/finance","OpenSecrets: Outside spending (opensecrets.org); FEC: Data (fec.gov); Brennan Center: Citizens United (brennancenter.org)",78,68,75,78,78,68,72,78),
mk("HCJ25","Where Psychology Predicts Protest: Personality Traits That Correlate With Civic Action","Big Five traits mapped against protest participation rates by state — agreeableness matters","CHART","US-state","Scatter plot","psychology/politics","Rentfrow: State personality (cam.ac.uk); ACLED: US protests (acleddata.com); Census: Demographics (census.gov)",65,68,58,78,60,65,82,55),
mk("HCJ26","The Sports Boycott Effect: When Athletes Take Political Stands and Fandom Shifts","Fan engagement changes after political statements mapped against demographics","CHART","US","Line chart","sports/politics","Morning Consult: Fandom (morningconsult.com); Nielsen: Ratings; Social media engagement data",65,72,60,72,65,65,75,55),
mk("HCJ27","Middle East Womens Political Representation: Seats in Parliament by Country","Female legislators as % of total mapped — some MENA countries outrank the US","CHART","Middle East","Bar chart","middle_east/gender","IPU: Women in parliament (ipu.org); World Bank: Gender (worldbank.org); UN Women: Representation (unwomen.org)",72,62,75,82,62,68,78,82),
mk("HCJ28","Where Manufacturing Workers Changed Political Affiliation: The Union-to-MAGA Pipeline","Union household partisan shift by county 2008-2024 — the realignment in manufacturing towns","MAP","US-county","Bivariate choropleth","manufacturing/politics","MIT: Elections (electionlab.mit.edu); BLS: Union data (bls.gov/cps); Census: Industry (census.gov)",80,72,72,78,78,78,75,75),
mk("HCJ29","The Demographics of Americas Election Workers: Who Counts Your Vote","Poll worker demographics mapped against voter demographics — the representation gap","CHART","US-state","Bar chart","demographics/democracy","EAC: Poll worker surveys (eac.gov); Census: Demographics (census.gov); Bipartisan Policy: Elections (bipartisanpolicy.org)",68,72,68,72,62,68,72,65),
mk("HCJ30","Where Recreational Drug Laws Split the Map: Legal vs Illegal by Substance and State","Cannabis, psilocybin, kratom, delta-8 legality mapped — the patchwork of drug policy","MAP","US-state","Special map","drugs/law","NORML: State laws (norml.org); NCSL: Drug policy (ncsl.org); DEA: Scheduling (dea.gov)",72,78,72,68,68,78,68,78),
mk("HCJ31","The Gun Permit Map: States Where You Need Permission vs States Where You Dont","Permitless carry expansion mapped year by year 2010-2025 — the trend is one direction","MAP","US-state","Animated choropleth","guns/law","Giffords: Carry laws (giffords.org); USCCA: Reciprocity (uscca.com); NCSL: Firearms (ncsl.org)",72,72,75,72,72,78,65,82),
mk("HCJ32","Where Religious Voters Decide School Board Races: Faith-Based Education Activism","Religious conservative school board wins mapped against curriculum change outcomes","MAP","US-county","Dot map","religion/education","Ballotpedia: School boards (ballotpedia.org); ARDA: Religious data (thearda.com); Education Week: Policy (edweek.org)",72,72,65,75,72,72,75,62),
mk("HCJ33","The Psychology of Loss in Politics: Counties Where Economic Decline Drove the Largest Swings","Economic loss magnitude correlated with political swing size — the despair-to-vote pipeline","XREF","US-county","Scatter plot","psychology/economy","BEA: County income change (bea.gov); MIT: Elections (electionlab.mit.edu); Census: Demographics (census.gov)",75,72,68,78,72,68,78,72),
mk("HCJ34","Where Sports Gambling Tax Revenue Gets Earmarked: Education, Roads, or General Fund","State-by-state gambling revenue allocation mapped — the broken promises tracker","CHART","US-state","Bar chart","sports/finance","AGA: Revenue (americangaming.org); Tax Foundation: Gaming (taxfoundation.org); NASPL: Allocation (naspl.org)",68,72,72,68,62,68,68,75),
mk("HCJ35","The Law of the Filibuster: How 41 Senators Representing 20% of Americans Block Everything","Population represented by filibuster-sustaining minorities mapped — minority rule by design","CHART","US-state","Bar chart","law/democracy","Census: State population (census.gov); Senate.gov: Votes (senate.gov); Brennan Center: Filibuster (brennancenter.org)",80,72,78,80,80,68,72,82),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCJ ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCJ batch)")
