import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCI01","Every Undersea Internet Cable That Connects the World","97% of international data flows through cables thinner than a garden hose — the vulnerability mapped","MAP","World","Line map","technology/infrastructure","TeleGeography: Submarine cables (submarinecablemap.com); ITU: Infrastructure (itu.int)",75,72,72,80,72,88,78,82),
mk("HCI02","Americas Power Grid Has Three Separate Networks That Barely Talk to Each Other","The Eastern, Western, and Texas interconnections mapped with transfer capacity bottlenecks","MAP","US","Special map","energy/infrastructure","EIA: Electric grid (eia.gov); NERC: Reliability (nerc.com); DOE: Grid data (energy.gov)",78,78,75,82,78,85,75,82),
mk("HCI03","Where Americas Sewers Are Older Than Your Great-Grandparents","Sewer system installation dates mapped — some cities running on 150-year-old pipes","MAP","US-metro","Dot map","infrastructure/history","EPA: Clean watersheds (epa.gov); ASCE: Infrastructure (infrastructurereportcard.org); Census: Government (census.gov)",78,78,72,78,72,78,72,72),
mk("HCI04","The Invisible Water Network: Every Aqueduct, Pipeline, and Transfer in the American West","Water moves hundreds of miles to reach cities — the hidden infrastructure mapped","MAP","US-state","Line map","infrastructure/environment","USGS: Water use (usgs.gov); Bureau of Reclamation: Infrastructure (usbr.gov); USDA: Irrigation (nass.usda.gov)",72,68,72,78,72,88,78,78),
mk("HCI05","Every Nuclear Power Plant, Waste Storage Site, and Transportation Route in America","The nuclear geography nobody thinks about — mapped with population density","MAP","US","Dot map","energy/science","NRC: Reactor data (nrc.gov); DOE: Waste sites (energy.gov); Census: Population (census.gov)",75,68,72,78,78,85,75,82),
mk("HCI06","Where the Law Decides If Your AI Can Fire You: Employment Algorithm Regulation by State","States regulating automated hiring and termination mapped — most have zero protections","MAP","US-state","State choropleth","law/technology","NCSL: AI employment laws (ncsl.org); EEOC: AI guidance (eeoc.gov); Brookings: AI regulation (brookings.edu)",75,78,68,80,78,72,82,62),
mk("HCI07","Middle East Oil Infrastructure: Every Pipeline, Refinery, and Chokepoint on One Map","The energy geography that shapes global politics — Strait of Hormuz to Suez Canal","MAP","Middle East","Special map","middle_east/energy","EIA: International energy (eia.gov); IEA: Oil infrastructure (iea.org); SIPRI: Maritime (sipri.org)",72,58,72,75,78,88,72,82),
mk("HCI08","The Demographic Fingerprint of Every Neighborhood: What Your Block Looks Like by the Numbers","Census tract demographic profiles mapped — age, income, education, race in one composite","MAP","US-county","Dot map","demographics/geography","Census: ACS tract data (census.gov/acs); EPA: Smart Location (epa.gov)",68,78,72,65,55,80,68,85),
mk("HCI09","Every Dam in America Rated by Safety Risk: The Infrastructure Time Bomb","High-hazard dams mapped against downstream population and last inspection date","MAP","US","Dot map","infrastructure/environment","ASDSO: Dam inventory (damsafety.org); Army Corps: NID (nid.sec.usace.army.mil); Census: Population (census.gov)",80,72,72,78,82,82,72,78),
mk("HCI10","Where Cell Service Dies: Americas Connectivity Dead Zones Mapped","Areas with zero or one bar of cell coverage overlaid with emergency call failure rates","MAP","US","Special map","technology/rural","FCC: Coverage maps (fcc.gov); Ookla: Coverage (opensignal.com); NTIA: Broadband (ntia.gov)",75,80,72,72,68,80,70,72),
mk("HCI11","The Food Supply Chain Map: How a Tomato Gets From Mexico to Your Salad in 48 Hours","Cold chain logistics mapped — temperature-controlled infrastructure from farm to fork","MAP","World","Line map","food/trade","BTS: Freight (bts.gov); USDA: Agricultural trade (fas.usda.gov); Census: Import data (census.gov/trade)",68,78,68,72,58,82,75,72),
mk("HCI12","Every Railroad Line in America: The System Nobody Sees That Moves Everything","Freight rail network mapped with tonnage — 40% of long-haul cargo rides these invisible tracks","MAP","US","Line map","transportation/economy","BTS: Rail network (bts.gov); AAR: Railroad data (aar.org); STB: Waybill (stb.gov)",72,72,72,72,62,88,68,85),
mk("HCI13","Where Americas Air Traffic Control System Is Held Together by 1960s Technology","FAA facility ages mapped against flight volume — modernization debt visualized","MAP","US","Dot map","transportation/technology","FAA: Facility data (faa.gov); BTS: Flight data (bts.gov); GAO: ATC reports (gao.gov)",75,72,68,78,75,78,75,72),
mk("HCI14","The Blood Supply Map: Where Americas Donations Come From vs Where They Go","Blood donation rates by metro mapped against hospital trauma center density","MAP","US-metro","Line map","health/geography","Red Cross: Blood data (redcross.org); AHA: Hospital data (aha.org); AABB: Blood banking (aabb.org)",68,72,68,72,62,78,78,65),
mk("HCI15","Every Warehouse Amazon Built in America: The Distribution Geography of Everything","Fulfillment center locations mapped against population and delivery speed zones","MAP","US","Dot map","economy/technology","MWPVL: Amazon network (mwpvl.com); Census: CBP (census.gov); BLS: Warehouse employment (bls.gov)",68,78,72,72,58,80,70,78),
mk("HCI16","The Law of the Border: How 50 Different State Legal Systems Create Chaos at Every Line","Adjacent states with contradicting laws on cannabis, guns, abortion, gambling — the patchwork mapped","MAP","US-state","Special map","law/geography","NCSL: State laws (ncsl.org); Guttmacher: Abortion (guttmacher.org); Giffords: Gun laws (giffords.org)",78,78,72,78,75,80,78,72),
mk("HCI17","Middle East Desalination Infrastructure: The Technology Keeping Civilization Alive","Every desalination plant mapped with capacity, energy source, and cost per gallon","MAP","Middle East","Dot map","middle_east/infrastructure","GWI: Desalination (globalwaterintel.com); IDA: Desal data (idadesal.org); World Bank: Water (worldbank.org)",70,55,72,78,68,80,78,75),
mk("HCI18","Where Americas Natural Gas Pipeline Network Runs Under Your House","Interstate gas pipeline network mapped against population density and leak reports","MAP","US","Line map","energy/infrastructure","PHMSA: Pipeline data (phmsa.dot.gov); EIA: Natural gas (eia.gov); Census: Population (census.gov)",72,75,72,72,72,85,70,82),
mk("HCI19","The Demographics of Who Rides Public Transit vs Who Drives: Income Shapes Commutes","Transit ridership demographics by metro mapped against auto dependency","MAP","US-metro","Bar chart","demographics/transportation","NTD: Ridership (transit.dot.gov); Census: Commute mode (census.gov/acs); APTA: Data (apta.com)",72,78,72,68,62,70,68,78),
mk("HCI20","Every Superfund Site, Chemical Plant, and Known Contamination Zone on One Map","The toxic geography of America — 1,300+ Superfund sites plus TRI facilities","MAP","US","Dot map","environment/health","EPA: Superfund (epa.gov/superfund); EPA: TRI (epa.gov/tri); CDC: ATSDR (atsdr.cdc.gov)",78,72,72,75,78,82,68,82),
mk("HCI21","Where Americas Drinking Water Comes From: Every Watershed, Reservoir, and Aquifer","The invisible water supply infrastructure that 330 million people depend on","MAP","US","Special map","infrastructure/environment","USGS: National Water Information (waterdata.usgs.gov); EPA: Drinking water (epa.gov/sdwa)",72,72,72,72,65,88,72,82),
mk("HCI22","The Law of the Road: Every State Where Its Legal to Sleep in Your Car","Criminalizing homelessness mapped — vehicle dwelling laws vs houseless population","MAP","US-state","State choropleth","law/housing","NLCHP: Criminalization (nlchp.org); HUD: PIT count (hudexchange.info); NCSL: Vehicle dwelling (ncsl.org)",78,78,72,78,78,72,75,68),
mk("HCI23","Middle East Renewable Energy: The Solar Revolution Nobody Expected","Solar installation capacity growth mapped — MENA has the highest solar potential on Earth","CHART","Middle East","Line chart","middle_east/energy","IRENA: Renewable capacity (irena.org); IEA: Solar (iea.org); World Bank: Energy (worldbank.org)",70,55,72,82,62,72,78,78),
mk("HCI24","Every US Military Installation Mapped With Surrounding PFAS Contamination","Forever chemicals from military bases mapped against drinking water contamination zones","MAP","US","Dot map","military/environment","DOD: PFAS data (defense.gov); EPA: PFAS (epa.gov); EWG: Contamination map (ewg.org)",82,72,72,78,82,80,72,75),
mk("HCI25","The Demographics of Digital Exclusion: Who Cant Access Government Services Online","Populations without internet access mapped against government services that went digital-only","MAP","US-county","Bivariate choropleth","demographics/technology","FCC: Broadband (fcc.gov); Census: Internet access (census.gov/acs); DigitalGov: Services (digital.gov)",78,78,72,75,72,72,72,72),
mk("HCI26","Where Americas Food Gets Inspected: FDA Inspection Rates by Facility Type and State","Some food facilities go years without inspection — the coverage gap mapped","MAP","US-state","State choropleth","food/law","FDA: Inspection database (fda.gov); GAO: Food safety (gao.gov); USDA: FSIS (fsis.usda.gov)",75,78,72,78,72,72,72,72),
mk("HCI27","The Invisible Freight Network: What Gets Trucked Where in America","Commodity flow map showing what travels by truck between metro areas — the arteries of commerce","MAP","US","Line map","transportation/economy","BTS: Commodity flow (bts.gov); Census: CFS (census.gov/cfs); FHWA: Freight data (fhwa.dot.gov)",68,68,72,68,58,85,68,82),
mk("HCI28","Every Country With a Social Credit Score System or Equivalent Surveillance","Government surveillance scoring mapped globally — not just China anymore","MAP","World","World choropleth","technology/democracy","Freedom House: FOTN (freedomhouse.org); Privacy International: Surveillance (privacyinternational.org); AI Now Institute",78,72,68,80,78,75,80,65),
mk("HCI29","Where Americas Emergency Alert System Has Dead Zones","Areas not covered by WEA (Wireless Emergency Alerts) mapped against disaster frequency","MAP","US","Special map","infrastructure/technology","FEMA: IPAWS (fema.gov); FCC: WEA coverage (fcc.gov); NOAA: Hazards (weather.gov)",72,75,68,75,72,78,75,65),
mk("HCI30","The Law of Eminent Domain: Where Government Takes Private Land Most Aggressively","Eminent domain actions mapped by state against pipeline routes, highways, and development projects","MAP","US-state","Bivariate choropleth","law/housing","Castle Coalition: ED data (castlecoalition.org); FHWA: ROW (fhwa.dot.gov); IJ: Property rights (ij.org)",75,72,68,75,72,72,78,62),
mk("HCI31","Middle East Migrant Worker Geography: Where 30 Million Foreign Workers Actually Are","Guest worker populations by GCC country mapped against labor rights indices","MAP","Middle East","Bar chart","middle_east/labor","ILO: Migration (ilo.org); World Bank: Remittances (worldbank.org); ITUC: Rights index (ituc-csi.org)",78,62,72,78,78,72,78,75),
mk("HCI32","The Demographics of Americas Volunteer Workforce: Who Donates Time and Where","Volunteer rates mapped by age, income, and geography — the generosity map","MAP","US-state","State choropleth","demographics/economy","BLS: Volunteering (bls.gov); AmeriCorps: Service (americorps.gov); Census: Demographics (census.gov)",65,72,68,68,55,72,68,75),
mk("HCI33","Where Gun Background Check Systems Break: States With Incomplete Records","NICS record submission rates by state mapped — some states report 30% of disqualifying records","MAP","US-state","State choropleth","guns/law","FBI: NICS (fbi.gov); Everytown: Background checks (everytownresearch.org); GAO: NICS reports (gao.gov)",78,68,72,80,80,72,72,72),
mk("HCI34","Every Data Center in America: Where the Internet Physically Lives","Data center locations mapped against power grid capacity and fiber routes","MAP","US","Dot map","technology/energy","Baxtel: Data center map (baxtel.com); EIA: Power plants (eia.gov); FCC: Fiber (fcc.gov)",68,72,70,72,62,82,72,78),
mk("HCI35","The Invisible Supply Chain Crisis: Every Single Point of Failure in American Manufacturing","Sole-source components mapped — the items where one factory shutdown halts entire industries","MAP","World","Dot map","manufacturing/trade","Census: Import data (census.gov/trade); BIS: Critical supply chains (bis.doc.gov); IHS: Supply chain (ihsmarkit.com)",78,72,68,80,78,78,80,65),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCI ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCI batch)")
