import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDT01","AI Water Consumption: Gallons of Water Used to Cool Data Centers by Company and Location","The hidden resource cost of AI — each ChatGPT query uses a half-liter of water for cooling, scaled to company and data center location","MAP","US","Dot map","technology","Shaolei Ren: Making AI Less Thirsty (arxiv.org) + Company sustainability reports",62,62,68,82,68,72,78,68),
mk("HDT02","Congressional Stock Trading: Members of Congress Who Beat the Market by Suspicious Margins","Lawmakers whose stock portfolios suspiciously outperform the S&P 500 — the insider trading that nobody prosecutes","RANK","US","Bar chart","politics","Capitol Trades: Congressional Stock Tracker (capitoltrades.com) + Unusual Whales",72,72,72,78,78,55,68,82),
mk("HDT03","Retail Theft Ring Prosecution: Major Organized Retail Crime Cases Filed by Metro","The difference between petty shoplifting and organized retail crime — multi-million dollar theft ring takedowns mapped by city","MAP","US","Dot map","crime","National Retail Federation: Organized Retail Crime Survey (nrf.com)",58,62,68,68,68,72,62,72),
mk("HDT04","Charter School Performance: Standardized Test Scores at Charter vs Traditional Public Schools by State","The charter school experiment 30 years in — where charters outperform, where they underperform, and where theres no difference","MAP","US","Bivariate choropleth","education","CREDO: Center for Research on Education Outcomes (credo.stanford.edu)",65,72,72,68,68,68,62,82),
mk("HDT05","Submarine Cable Map: Every Undersea Internet Cable Connecting Continents","The physical infrastructure of the internet — 500+ submarine cables carrying 95% of intercontinental data traffic","MAP","World","Line map","technology","TeleGeography: Submarine Cable Map (submarinecablemap.com)",55,52,72,72,55,88,65,90),
mk("HDT06","Political Polarization in Congress: Distance Between Party Median DW-NOMINATE Scores Over Time","The mathematical proof that Congress is more polarized than at any point since Reconstruction — the parties barely overlap","CHART","US","Line chart","politics","Voteview: Congressional Ideology (voteview.com)",62,58,75,65,72,58,62,92),
mk("HDT07","Catalytic Converter Theft to Scrap: The Supply Chain of Stolen Precious Metals","From parking lot theft to recycler to refinery — how stolen catalytic converters move through the black market metals economy","MAP","US","Line map","crime","DOJ: Catalytic Converter Theft Investigations (justice.gov)",58,62,65,72,68,75,70,68),
mk("HDT08","Teacher Diversity Gap: Percentage of Teachers vs Students Who Are Non-White by State","85% of teachers are white while 54% of students are not — the representation gap that research shows matters for outcomes","MAP","US","Bivariate choropleth","education","NCES: Characteristics of Public School Teachers (nces.ed.gov)",68,65,72,68,65,72,58,88),
mk("HDT09","E-Waste Generation: Pounds of Electronic Waste Produced Per Capita by Country","The worlds growing mountain of discarded electronics — 60M tons per year with less than 20% properly recycled","MAP","World","World choropleth","technology","UN: Global E-Waste Monitor (ewastemonitor.info)",62,62,72,72,68,68,65,82),
mk("HDT10","Congressional District Competitiveness: Seats Won by Less Than 5 Points Over Time","The vanishing swing district — competitive House seats declined from 100+ to under 30, making elections unresponsive","CHART","US","Line chart","politics","Cook Political Report: Partisan Voting Index (cookpolitical.com)",62,62,75,68,72,62,62,88),
mk("HDT11","Cybercrime Losses: FBI-Reported Internet Crime Losses by Category and Victim Age","Americans lost $12.5B to cybercrime in 2023 — investment scams, BEC, romance fraud — mapped by victim location and type","CHART","US","Bar chart","crime","FBI: Internet Crime Complaint Center (ic3.gov/annualreport)",65,72,72,68,68,58,58,85),
mk("HDT12","School Librarian Extinction: Districts That Have Eliminated All Librarian Positions","The quiet defunding of school libraries — districts where the librarian position has been completely eliminated, mapped against reading scores","MAP","US","County choropleth","education","ALA: School Library Data (ala.org/aasl/research) + NCES",68,62,68,72,68,68,68,78),
mk("HDT13","Quantum Computing Race: Qubit Count by Company and Country Over Time","The race to quantum supremacy — IBM, Google, IonQ, and Chinese competitors charted by qubit milestones","CHART","World","Line chart","technology","Various: Company announcements + Nature/Science publications",52,42,68,72,62,62,72,72),
mk("HDT14","Dark Money in State Politics: Untraceable Spending in State Legislative Races","Dark money isnt just federal — state races increasingly flooded with anonymous spending, with some states having zero disclosure requirements","MAP","US","State choropleth","politics","Brennan Center: Secret Spending in the States (brennancenter.org)",68,62,72,72,78,68,65,78),
mk("HDT15","Elder Fraud Hotspots: Financial Exploitation of Seniors by Scam Type and Metro","Where seniors lose the most money to scams — romance fraud, tech support scams, and grandparent scams mapped by victim location","MAP","US","Dot map","crime","FBI: IC3 Elder Fraud Report (ic3.gov) + FTC Sentinel Data",72,68,68,68,72,72,58,80),
mk("HDT16","ACT/SAT Score Decline: Average College Entrance Exam Scores by State 2019 vs 2024","The post-pandemic academic slide — standardized test scores that dropped 5-15% and havent recovered in most states","MAP","US","State choropleth","education","College Board: SAT Suite Annual Report (collegeboard.org) + ACT (act.org)",68,72,75,68,72,68,55,88),
mk("HDT17","Facial Recognition Ban Map: Cities and States That Prohibit Government Use of Face Recognition","Where facial recognition technology is banned for police or government use — San Francisco, Portland, Massachusetts leading the way","MAP","US","State choropleth","technology","ACLU: Face Recognition Technology (aclu.org/issues/privacy-technology/surveillance-technologies/face-recognition-technology)",62,62,72,68,68,72,68,78),
mk("HDT18","Primary Election Turnout: Percentage of Eligible Voters Who Vote in Primaries by State","The tiny fraction of voters who choose our candidates — primary turnout often below 15%, meaning 8% of voters decide November options","MAP","US","State choropleth","politics","United States Elections Project: Turnout Data (electproject.org)",62,68,75,72,72,72,62,88),
mk("HDT19","Carjacking Demographic Profile: Victim and Perpetrator Age Distribution in Armed Vehicle Theft","The age demographics of carjacking — a crime overwhelmingly committed by teenagers and disproportionately affecting certain communities","CHART","US","Bar chart","crime","DOJ: Carjacking Studies (bjs.ojp.gov) + City police department data",62,58,68,68,72,55,62,72),
mk("HDT20","Special Education Funding Gap: Per-Student Spending on IEP Students vs General Education by State","How much more special education costs and who covers the gap — the federal government promised 40% and delivers 13%","MAP","US","State choropleth","education","NCES: Expenditures for Public Elementary and Secondary Education (nces.ed.gov)",72,68,72,68,72,68,58,85),
mk("HDT21","Autonomous Vehicle Incidents: Self-Driving Car Crashes and Disengagements by Company","Every reported autonomous vehicle incident — Waymo, Cruise, Tesla FSD — mapped by location and severity","MAP","US","Dot map","technology","NHTSA: Standing General Order Crash Reports (nhtsa.gov/technology-innovation/automated-vehicles-safety)",62,68,68,72,68,72,68,78),
mk("HDT22","Voter Registration Disparity: Eligible but Unregistered Population by Demographic and State","Who isnt registered to vote — young people, renters, and minorities at dramatically lower registration rates, mapped by state","MAP","US","State choropleth","politics","Census Bureau: Current Population Survey Voting Supplement (census.gov)",65,68,72,68,65,72,55,88),
mk("HDT23","Smash-and-Grab Geography: High-Value Retail Burglaries by Metro and Retailer","The wave of organized smash-and-grab robberies — which metros and which luxury retailers were hit hardest","MAP","US","Dot map","crime","National Retail Federation: ORC Database (nrf.com) + Local police data",55,65,65,68,68,72,62,68),
mk("HDT24","Math Teacher Certification: High School Math Teachers Without a Math Degree by State","Where math is taught by non-math majors — states where 30%+ of math teachers dont have a degree in math","MAP","US","State choropleth","education","NCES: Teacher Credentials and Attainment (nces.ed.gov)",65,68,72,72,68,68,62,82),
mk("HDT25","Cloud Computing Market Concentration: AWS, Azure, and GCP Server Locations Worldwide","Where the cloud actually lives — the physical data centers of the three major providers mapped globally with capacity","MAP","World","Dot map","technology","Synergy Research: Cloud Infrastructure Market (srgresearch.com)",52,48,72,65,52,80,62,82),
mk("HDT26","Legislative Productivity: Bills Passed Per Congressional Session Since 1947","Is Congress getting less done? Bills signed into law per session declining from 900+ to under 300 while partisan messaging bills increase","CHART","US","Line chart","politics","GovTrack: Congressional Statistics (govtrack.us/congress/bills/statistics)",58,62,75,68,65,55,62,92),
mk("HDT27","Hate Crime Undercount: Gap Between FBI-Reported and Survey-Estimated Hate Crimes","The FBI reports 12,000 hate crimes per year but the BJS survey estimates 250,000+ — the massive reporting gap visualized","CHART","US","Bar chart","crime","BJS: National Crime Victimization Survey (bjs.ojp.gov) vs FBI UCR (crime-data-explorer.fr.cloud.gov)",72,62,72,82,78,55,72,82),
mk("HDT28","Student Debt by Institution: Average Borrower Debt at Graduation by College","Which colleges send students out with the most debt — and its often not the expensive private schools but the mid-tier institutions","RANK","US","Bar chart","education","College Scorecard: Institution-Level Data (collegescorecard.ed.gov)",68,78,72,72,68,55,58,90),
mk("HDT29","Chip Shortage Impact: Semiconductor Lead Times by Chip Type Over Time","The great chip shortage timeline — from normal 12-week lead times to 50+ weeks and the slow return to normal by chip category","CHART","World","Line chart","technology","Susquehanna Financial Group: Chip Lead Time Tracker (susquehanna.com)",55,58,72,68,62,58,62,78),
mk("HDT30","State Preemption Laws: Where State Legislatures Block Local Government Action","States that prevent cities from passing their own gun laws, minimum wage increases, plastic bag bans, or rent control — the preemption map","MAP","US","State choropleth","politics","Local Solutions Support Center: State Preemption Map (supportdemocracy.org)",62,62,72,72,75,72,68,82),
mk("HDT31","Porch Piracy vs Prosecution: Package Theft Reports vs Criminal Charges Filed by City","How many package thefts get reported vs how many lead to any prosecution — the enforcement gap that enables the crime","CHART","US","Bar chart","crime","C+R Research: Package Theft Report + City DA prosecution data",55,72,68,68,62,55,62,62),
mk("HDT32","Gifted Program Access: Students Identified as Gifted by Race and Income by State","Who gets into gifted programs — white and Asian students at 2-3x the rate of Black and Hispanic students even in the same schools","MAP","US","State choropleth","education","NCES: Civil Rights Data Collection Gifted/Talented (ocrdata.ed.gov)",68,65,72,72,72,68,62,85),
mk("HDT33","Biometric Data Collection: Companies Harvesting Fingerprint, Face, and Voice Data by Industry","Which industries collect the most biometric data from consumers and employees — tech, retail, banking, and fitness companies","CHART","US","Bar chart","technology","BIPA Litigation Database + IAPP: Privacy Law Tracker (iapp.org)",62,68,65,72,72,55,72,68),
mk("HDT34","Partisan Media Ecosystems: News Sources Consumed by Political Affiliation","The complete separation of information universes — what Democrats and Republicans read, watch, and share have almost zero overlap","CHART","US","Scatter plot","politics","Pew Research: Political Polarization and Media Habits (pewresearch.org)",65,72,72,68,72,62,62,85),
mk("HDT35","Shoplifting Decriminalization Impact: Property Crime Rates in Cities That Raised Felony Thresholds","What actually happened to shoplifting in cities that raised the felony threshold — the data vs the narrative","CHART","US","Line chart","crime","FBI: UCR Property Crime Data + State felony threshold databases",62,68,72,78,72,55,72,78),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDT batch)")
