import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDK01","The Buy Now Pay Later Trap: BNPL Usage and Default Rates by Age Group","How Afterpay, Klarna, and Affirm adoption exploded among Gen Z — and how many borrowers are now missing payments","CHART","US","Bar chart","finance","CFPB: Buy Now Pay Later Market Report (consumerfinance.gov)",68,78,72,72,72,58,65,78),
mk("HDK02","Gig Economy Map: Percentage of Workforce Classified as Independent Contractors by Metro","Where gig work dominates — metros with the highest share of workers without benefits, stability, or employer protections","MAP","US","Dot map","labor","BLS: Contingent Worker Supplement (bls.gov/cps/lfcharacteristics.htm)",65,78,72,68,65,72,62,80),
mk("HDK03","School Lunch Debt: Unpaid Meal Balances by School District","How much kids owe for cafeteria meals they couldnt afford — districts carrying millions in unpaid lunch debt while shaming children","MAP","US","Dot map","food","School Nutrition Association: Financial Impact Survey (schoolnutrition.org)",82,78,72,72,78,68,65,68),
mk("HDK04","Teacher Pay vs Cost of Living: Where Educators Cant Afford to Live Where They Teach","Teacher salaries adjusted for local cost of living by metro — San Francisco teachers earning effectively less than rural Alabama teachers","MAP","US","Bivariate choropleth","education","NEA: Teacher Salary Benchmarks + BLS Area Price Parities (nea.org/resource-library/teacher-salary-benchmarks)",75,78,75,72,72,72,62,85),
mk("HDK05","Credit Card Debt Per Capita: Average Revolving Balance by State","Which states are drowning in credit card debt — Alaska, Connecticut, and New Jersey at $10K+ per cardholder","MAP","US","State choropleth","finance","Federal Reserve Bank of New York: Consumer Credit Panel (newyorkfed.org/microeconomics/hhdc)",68,78,75,65,68,72,55,88),
mk("HDK06","The Strike Wave: Major Work Stoppages Per Year Since 1947","Annual count of strikes involving 1000+ workers — from the peak of 400+ in the 1970s to near-zero in the 2000s to the recent revival","CHART","US","Line chart","labor","BLS: Work Stoppages Data (bls.gov/wsp)",65,68,75,68,68,62,65,92),
mk("HDK07","Food Swamp Map: Areas With an Overabundance of Fast Food Relative to Grocery Stores","Not just food deserts — food swamps where fast food outnumbers grocery stores 10 to 1, mapped against obesity rates","MAP","US","Bivariate choropleth","food","USDA: Food Access Research Atlas (ers.usda.gov/data-products/food-access-research-atlas)",72,75,72,72,68,78,68,82),
mk("HDK08","College Major ROI: Lifetime Earnings Premium by Degree Field vs Cost of Degree","Which degrees actually pay off — engineering and CS at 5x return vs fine arts and social work at negative ROI when debt is included","RANK","US","Bar chart","education","Georgetown CEW: Education and Workforce (cew.georgetown.edu)",62,78,75,68,62,58,58,85),
mk("HDK09","Overdraft Fee Revenue: How Much Banks Earn From Customer Mistakes by Institution","Top 20 banks by overdraft and NSF fee revenue — the $10B+ annual industry built on peoples lowest moments","RANK","US","Bar chart","finance","CFPB: Overdraft/NSF Fee Reliance (consumerfinance.gov)",72,78,72,72,72,55,65,82),
mk("HDK10","Non-Compete Agreement Prevalence: Percentage of Workers Bound by Non-Competes by State","From sandwich makers to hair stylists — how many workers in each state are locked into non-compete agreements and at what income level","MAP","US","State choropleth","labor","EPI: Non-Compete Agreements (epi.org)",62,72,72,75,68,68,68,75),
mk("HDK11","Mercury in Fish: FDA Advisories by Species and Region","Which fish are safest to eat and where — mercury contamination levels mapped against fishing regions and consumption patterns","MAP","US","Special map","food","FDA: Mercury Levels in Commercial Fish (fda.gov/food/metals-and-your-food/mercury-levels-commercial-fish-and-shellfish)",65,78,72,62,68,72,58,85),
mk("HDK12","Chronic Absenteeism Explosion: Students Missing 10%+ of School Days by District","The post-pandemic truancy crisis — districts where 30-40% of students are chronically absent, triple pre-COVID rates","MAP","US","County choropleth","education","DOE: Chronic Absenteeism Data (ed.gov/chronic-absenteeism)",78,75,72,68,78,72,60,82),
mk("HDK13","The Unbanked Map: Households Without a Bank Account by County","Where Americas 6 million unbanked households concentrate — rural South, tribal lands, immigrant communities, and inner cities","MAP","US","County choropleth","finance","FDIC: National Survey of Unbanked and Underbanked Households (fdic.gov/analysis/household-survey)",72,68,72,68,68,78,60,85),
mk("HDK14","Wage Theft vs Street Crime: Dollars Stolen From Workers vs Dollars Stolen in Robberies","Employer wage theft outpaces all property crime combined — the $50B annual theft that gets no headlines","XREF","US","Bar chart","labor","EPI: Wage Theft (epi.org) + FBI UCR (ucr.fbi.gov)",75,72,72,82,72,55,78,75),
mk("HDK15","The Cafeteria Workers Dilemma: School Lunch Nutrition Standards by Country","What school cafeterias serve around the world — Japan and France vs the US pizza-is-a-vegetable approach","RANK","World","Bar chart","food","WFP: State of School Feeding Worldwide (wfp.org)",62,72,68,72,55,68,72,72),
mk("HDK16","Student Loan Forgiveness Tracker: Borrowers and Dollars Discharged by Program","Where Biden-era student loan relief actually went — PSLF, IDR adjustments, school closures — mapped by state and program","MAP","US","State choropleth","education","DOE: Federal Student Loan Portfolio (studentaid.gov/data-center)",68,78,72,65,65,68,58,85),
mk("HDK17","Crypto Losses: Americans Who Lost Money on Cryptocurrency by Demographic","Who got burned in the crypto crash — losses by age, income, race, and education level, with total estimated at $7.5B in fraud alone","CHART","US","Bar chart","finance","FTC: Cryptocurrency Fraud Reports (ftc.gov/data-visualizations/data-spotlight/cryptocurrency)",65,72,68,72,68,55,65,78),
mk("HDK18","Amazon Warehouse Injury Rate: Worker Injuries Per 100 Employees by Facility","Amazon warehouse serious injury rates at each fulfillment center — nearly double the industry average at many locations","MAP","US","Dot map","labor","OSHA: Injury and Illness Data (osha.gov/injuryreporting) + Strategic Organizing Center (thesoc.org)",72,68,72,68,75,72,65,80),
mk("HDK19","Artificial Sweetener Consumption: Per Capita Intake of Non-Sugar Sweeteners by Country","Which nations consume the most artificial sweeteners — the US, Mexico, and Brazil leading amid growing health debate","RANK","World","Bar chart","food","WHO: Non-Sugar Sweeteners Use (who.int)",52,68,65,68,55,55,65,68),
mk("HDK20","Homeschool Boom: Percentage of K-12 Students Homeschooled by State 2019 vs 2024","The pandemic permanently boosted homeschooling — states where 5-10% of students never returned to traditional school","MAP","US","State choropleth","education","Census Bureau: Household Pulse Survey Education Tables (census.gov/data/experimental-data-products/household-pulse-survey)",62,72,72,68,62,68,62,80),
mk("HDK21","Medical Debt Geography: Percentage of Adults With Medical Bills in Collections by County","Where medical debt crushes families — the Bible Belt and rural South at 20%+ of adults carrying medical collections","MAP","US","County choropleth","finance","Urban Institute: Debt in America (apps.urban.org/features/debt-interactive-map)",78,78,72,68,78,78,58,85),
mk("HDK22","Child Labor Resurgence: Minors Working in Violation of Labor Laws by State","The quiet return of illegal child labor — violations surged 69% between 2018 and 2023, concentrated in meatpacking and agriculture","MAP","US","State choropleth","labor","DOL: Wage and Hour Division Child Labor Investigations (dol.gov/agencies/whd/child-labor)",78,68,72,78,80,68,72,78),
mk("HDK23","Lunch Price Inflation: School Meal Costs vs CPI Since 2015","How much more school lunches cost now — for families that dont qualify for free meals, the price squeeze is real","CHART","US","Line chart","food","USDA: School Meal Programs Cost Data (fns.usda.gov)",62,78,72,62,58,55,55,82),
mk("HDK24","Principal Turnover Rate: School Leadership Instability by District","Districts where the average principal tenure is under 3 years — the revolving door that destabilizes schools","MAP","US","County choropleth","education","NCES: Principal Attrition and Mobility (nces.ed.gov)",65,62,68,68,65,68,65,75),
mk("HDK25","Checking Account Minimum Balance Fees: What Banks Charge You for Being Poor","Monthly maintenance fees and minimum balance requirements at the 50 largest banks — the cost of not having enough money","RANK","US","Bar chart","finance","Bankrate: Checking Account Survey (bankrate.com)",65,78,72,68,65,52,58,82),
mk("HDK26","Right to Work Map: Union Membership Rates in Right-to-Work vs Non-Right-to-Work States","How right-to-work laws correlate with union density, wages, and workplace safety — the 27-state experiment visualized","MAP","US","Bivariate choropleth","labor","BLS: Union Membership Data (bls.gov/news.release/union2.toc.htm)",62,65,72,65,68,72,62,88),
mk("HDK27","Pesticide Residue Rankings: Which Fruits and Vegetables Have the Most Chemical Residue","The Dirty Dozen and Clean Fifteen — which produce items test positive for the most pesticide residues after washing","RANK","US","Bar chart","food","EWG: Shopper Guide to Pesticides in Produce (ewg.org/foodnews)",62,82,72,65,62,58,55,82),
mk("HDK28","College Enrollment Cliff: Projected Decline in High School Graduates by State Through 2040","The demographic cliff coming for higher education — states that will produce 20-30% fewer college-age students","MAP","US","State choropleth","education","WICHE: Knocking at the College Door (wiche.edu/resources/knocking-at-the-college-door)",68,62,72,72,72,72,65,85),
mk("HDK29","Savings Rate by Generation: What Percentage of Income Each Generation Saves","Boomers, Gen X, Millennials, Gen Z — who saves the most and why the generational comparison isnt as simple as avocado toast","CHART","US","Bar chart","finance","Federal Reserve: Survey of Consumer Finances (federalreserve.gov/econres/scfindex.htm)",58,82,72,68,58,55,58,80),
mk("HDK30","Heat-Related Worker Deaths: Occupational Fatalities From Heat Exposure by Industry","Farm workers, roofers, and construction workers dying from heat — OSHA-reported deaths mapped against climate zones","MAP","US","Dot map","labor","OSHA: Heat-Related Illness Prevention (osha.gov/heat-exposure) + BLS Census of Fatal Occupational Injuries",78,65,72,68,80,72,65,78),
mk("HDK31","Sodium Content by Restaurant Chain: Average Milligrams Per Entree","How much salt each chain restaurant packs into a single meal — some entrees exceed the entire daily recommended intake","RANK","US","Bar chart","food","CSPI: Menu Labeling and Sodium Content (cspinet.org)",58,78,72,68,58,52,55,82),
mk("HDK32","School Counselor Ratios: Students Per Counselor by State","ASCA recommends 250 students per counselor but some states average 700+ — the mental health support gap in schools","MAP","US","State choropleth","education","ASCA: Student-to-Counselor Ratios (schoolcounselor.org)",72,72,72,68,72,68,58,85),
mk("HDK33","Venmo Economy: Peer-to-Peer Payment Volume Growth and What People Are Paying For","The explosion of P2P payments — from splitting dinner to paying rent, the $1T+ annual flow through Venmo, Zelle, and CashApp","CHART","US","Area chart","finance","Federal Reserve: Payments Study (federalreserve.gov/paymentsystems)",52,78,65,62,48,58,62,72),
mk("HDK34","Tip Creep: How Suggested Tip Percentages Have Risen at Point-of-Sale Terminals","The gradual increase of default tip options from 15/18/20% to 20/25/30% — and the emotional pressure of screen tipping","CHART","US","Line chart","labor","Bankrate: Tipping Survey (bankrate.com)",55,85,68,72,58,52,68,68),
mk("HDK35","Lead in Baby Food: Heavy Metal Contamination Levels by Brand","Tested levels of lead, arsenic, cadmium, and mercury in commercially sold baby food by brand — most exceed proposed FDA limits","RANK","US","Bar chart","food","Congressional Staff Report: Baby Foods Are Tainted With Dangerous Levels of Toxic Heavy Metals (oversight.house.gov)",82,78,72,72,82,55,62,78),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDK batch)")
