# BATCH_BJ.py
ideas = [
  {'id': 'xref_zoning_affordability', 'title': 'Single-family zoning share vs. rent burden by city — the zoning-affordability link', 'sub': 'Cities where 75%+ of land is zoned single-family have the highest rent-to-income ratios. Zoning is housing policy, just written in a different language.', 'type': 'XREF', 'geo': 'us_city', 'fmt': 'Scatter plot', 'tbl': 'Urban Institute: Single-family zoning share by city + ACS: Rent as % of income by metro', 'section': 'Housing', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['pct_land_single_family_zoning', 'rent_burden_pct'], 'join': ['median_home_value', 'population_growth', 'pct_bachelors'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 70, 'surprise': 90, 'tension': 80, 'visual': 90, 'data_ready': 70, 'originality': 100}, 'vs': 82, 'tags': 'zoning single-family rent burden city 75 percent highest ratio zoning is housing policy different language XREF', 'notes': '', 'topics': ['housing', 'inequality', 'economy', 'politics', 'labor'], 'status': 'idea'},
  {'id': 'xref_eviction_race', 'title': 'Eviction rate vs. Black renter share by city — the racial geography of housing precarity', 'sub': 'Cities where Black renters are 30%+ of the rental market have eviction rates more than double cities where they are under 10%. Eviction and race are not separate systems.', 'type': 'XREF', 'geo': 'us_city', 'fmt': 'Scatter plot', 'tbl': 'Princeton Eviction Lab + ACS: Black renter share by city', 'section': 'Housing', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['eviction_filing_rate', 'pct_black_renters_city'], 'join': ['poverty_rate', 'median_rent', 'rent_burden_pct'], 'sc': {'emotional': 90, 'relatability': 70, 'clarity': 70, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 70, 'originality': 80}, 'vs': 79, 'tags': 'eviction Black renter share city double racial geography housing precarity not separate systems XREF', 'notes': '', 'topics': ['housing', 'race', 'inequality', 'poverty', 'history'], 'status': 'idea'},
  {'id': 'xref_homeownership_wealth_gap', 'title': 'Homeownership rate vs. net worth by race — the compound inequality of housing', 'sub': 'White homeownership: 73%. Black: 44%. The gap drives 60% of the racial wealth gap. One policy — redlining and its legacy — explains the majority of the racial wealth divide.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'Census: Homeownership by race and state + Federal Reserve SCF: Net worth by race', 'section': 'Housing  -  Banking Finance Insurance', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['homeownership_rate_black', 'homeownership_rate_white', 'net_worth_gap_race'], 'join': ['redlining_coverage_city', 'median_home_value', 'pct_bachelors'], 'sc': {'emotional': 90, 'relatability': 70, 'clarity': 80, 'surprise': 70, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 70}, 'vs': 80, 'tags': 'homeownership race wealth gap 73 percent white 44 percent Black 60 percent racial wealth divide redlining', 'notes': '', 'topics': ['housing', 'race', 'inequality', 'history', 'economy', 'finance'], 'status': 'idea'},
  {'id': 'rent_increase_vs_wage_increase', 'title': 'Rent increases vs. wage increases by city 2015-2023: the affordability collapse in motion', 'sub': 'Miami rents up 78%. Miami wages up 31%. San Francisco rents up 22%, wages up 44%. The map of who won and who got crushed.', 'type': 'XREF', 'geo': 'us_metro', 'fmt': 'Scatter plot', 'tbl': 'Zillow ZORI: Rent change by metro 2015-2023 + BLS OES: Median wage change by metro', 'section': 'Housing  -  Labor Force', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['rent_pct_change_2015_2023', 'wage_pct_change_2015_2023'], 'join': ['population_growth_metro', 'remote_worker_pct', 'new_housing_permits'], 'sc': {'emotional': 90, 'relatability': 90, 'clarity': 90, 'surprise': 80, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 80}, 'vs': 87, 'tags': 'rent increase wage increase city 2015 2023 Miami 78 31 San Francisco 22 44 affordability collapse who won', 'notes': '', 'topics': ['housing', 'labor', 'economy', 'inequality', 'population'], 'status': 'idea'},
  {'id': 'housing_permits_population_growth', 'title': "Housing permits vs. population growth by metro — where supply has kept up and where it hasn't", 'sub': 'Austin: 6.5 permits per new resident. Los Angeles: 0.4. The building gap explains the affordability gap more than any other variable.', 'type': 'XREF', 'geo': 'us_metro', 'fmt': 'Scatter plot', 'tbl': 'Census: Building permits by metro + Census: Population estimates by metro', 'section': 'Housing', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['housing_permits_per_new_resident', 'population_growth_metro'], 'join': ['median_home_value', 'rent_burden_pct', 'zoning_restrictiveness'], 'sc': {'emotional': 80, 'relatability': 80, 'clarity': 80, 'surprise': 80, 'tension': 70, 'visual': 90, 'data_ready': 80, 'originality': 80}, 'vs': 80, 'tags': 'housing permits population growth Austin 6.5 Los Angeles 0.4 building gap affordability gap variable XREF', 'notes': '', 'topics': ['housing', 'economy', 'population', 'labor', 'inequality'], 'status': 'idea'},
  {'id': 'xref_redlining_current_wealth', 'title': '1930s HOLC redlining grades vs. current median home values — the 90-year persistence of the red line', 'sub': 'D-grade (redlined) neighborhoods in 1938 have median home values 68% lower than A-grade neighborhoods today. The lines drawn in red ink in 1938 are still visible in Zillow data.', 'type': 'XREF', 'geo': 'us_city', 'fmt': 'City map', 'tbl': 'Mapping Inequality Project: HOLC redlining grade by neighborhood + Zillow: Median home value by ZIP', 'section': 'Housing  -  History', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['holc_grade_1938', 'median_home_value_current'], 'join': ['pct_black_neighborhood', 'poverty_rate', 'tree_canopy_pct'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 70, 'surprise': 80, 'tension': 90, 'visual': 100, 'data_ready': 70, 'originality': 80}, 'vs': 82, 'tags': 'redlining 1938 HOLC grade current home value 68 percent lower 90 years persistence red line Zillow visible', 'notes': '', 'topics': ['housing', 'race', 'history', 'inequality', 'economy', 'environment'], 'status': 'idea'},
  {'id': 'vacant_housing_vs_homelessness', 'title': 'Vacant housing units vs. homeless population by city — America has more empty homes than homeless people', 'sub': 'There are 15 million vacant homes in the US and 580,000 homeless people. The ratio is 26:1. The housing crisis is not a supply problem at the national level — it is a distribution problem.', 'type': 'XREF', 'geo': 'us_city', 'fmt': 'Scatter plot', 'tbl': 'ACS 5-year: Vacant housing units by metro + HUD PIT Count: Homeless population by CoC', 'section': 'Housing', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['vacant_housing_units', 'homeless_population_city'], 'join': ['median_rent', 'poverty_rate', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 90, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 90}, 'vs': 85, 'tags': 'vacant homes 15 million homeless 580000 26 to 1 ratio distribution not supply problem national level housing', 'notes': '', 'topics': ['housing', 'poverty', 'inequality', 'economy', 'politics'], 'status': 'idea'},
  {'id': 'xref_housing_cost_birth_rate', 'title': 'Housing cost vs. birth rate by metro — the fertility effect of unaffordable housing', 'sub': 'The most expensive metros have the lowest fertility rates. San Francisco: 1.2 TFR. Houston: 2.1. Young people are not choosing to be childless — they are choosing not to be broke.', 'type': 'XREF', 'geo': 'us_metro', 'fmt': 'Scatter plot', 'tbl': 'Zillow: Median home value by metro + CDC NCHS: Total fertility rate by state/metro', 'section': 'Housing  -  Births Deaths', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['median_home_value_metro', 'fertility_rate_metro'], 'join': ['rent_burden_pct', 'pct_bachelors', 'median_household_income'], 'sc': {'emotional': 80, 'relatability': 90, 'clarity': 80, 'surprise': 90, 'tension': 70, 'visual': 90, 'data_ready': 70, 'originality': 90}, 'vs': 83, 'tags': 'housing cost birth rate fertility metro San Francisco 1.2 Houston 2.1 childless not choice being broke XREF', 'notes': '', 'topics': ['housing', 'population', 'economy', 'labor', 'inequality', 'gender'], 'status': 'idea'},
  {'id': 'mortgage_denial_race', 'title': 'Mortgage denial rate by race vs. income bracket — controlling for income, race still predicts denial', 'sub': 'Black applicants earning $100K+ are denied mortgages at the same rate as white applicants earning $50K. The income-controlled denial gap is the smoking gun of lending discrimination.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Bar chart', 'tbl': 'CFPB HMDA: Mortgage application denial rates by race and income (cfpb.gov)', 'section': 'Housing  -  Banking Finance Insurance', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['mortgage_denial_rate_black', 'mortgage_denial_rate_white', 'mortgage_denial_rate_by_income'], 'join': ['homeownership_rate_black', 'homeownership_rate_white', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 70, 'clarity': 80, 'surprise': 80, 'tension': 90, 'visual': 80, 'data_ready': 80, 'originality': 80}, 'vs': 80, 'tags': 'mortgage denial race income Black 100K denied same as white 50K controlled gap lending discrimination smoking gun', 'notes': '', 'topics': ['housing', 'race', 'inequality', 'finance', 'history'], 'status': 'idea'},
  {'id': 'cost_per_homeless_person_city', 'title': 'Annual cost per homeless person by city — what cities spend trying not to solve homelessness', 'sub': 'New York City: $98,000 per homeless person per year in shelter costs. Houston spent $25,000 giving people homes and ended veteran homelessness. Two cities, two philosophies, one clear answer.', 'type': 'RANK', 'geo': 'top_n_list', 'fmt': 'Ranked list', 'tbl': 'City budget data + HUD: Per-person cost of homeless services by Continuum of Care', 'section': 'Housing', 'ext': [], 'vars': ['cost_per_homeless_person_city'], 'join': ['homeless_population_city', 'median_rent', 'poverty_rate'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 90, 'surprise': 90, 'tension': 90, 'visual': 90, 'data_ready': 70, 'originality': 90}, 'vs': 87, 'tags': 'cost per homeless person city New York 98000 Houston 25000 homes veteran homelessness ended philosophy answer', 'notes': '', 'topics': ['housing', 'poverty', 'economy', 'politics', 'inequality'], 'status': 'idea'},
]

def vscore(sc):
    return int((sc.get("emotional",0)*2 + sc.get("relatability",0)*2 + sc.get("clarity",0)*2 +
               sc.get("surprise",0)*1.5 + sc.get("tension",0)*1 + sc.get("visual",0)*1 +
               sc.get("data_ready",0)*0.5 + sc.get("originality",0)*0.5) / 10.5)

for idea in ideas:
    idea["vs"] = vscore(idea["sc"])

if __name__ == "__main__":
    print(f"BATCH_BJ: {len(ideas)} ideas")
    for i in sorted(ideas, key=lambda x: -x["vs"]):
        print(f"  vs={i["vs"]:3d}  {i["id"]}")
