import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HCG01","The Feedback Loop of Poverty: How Each Factor Reinforces the Others","Network diagram of 12 poverty factors with measured correlation strengths — the trap visualized","CHART","US","Special map","poverty/psychology","Census: SIPP (census.gov/sipp); Federal Reserve: SCF (federalreserve.gov); Brookings: Poverty (brookings.edu)",82,80,68,78,78,75,82,68),
mk("HCG02","Where Zoning Laws Created Segregation: The Redlining Legacy Still Visible in 2025","1930s HOLC maps overlaid with current demographics and home values — 90 years later the lines hold","MAP","US-metro","Bivariate choropleth","housing/race","Mapping Inequality: HOLC (dsl.richmond.edu); Census: ACS (census.gov/acs); Zillow: Home values (zillow.com)",88,78,75,82,85,82,72,82),
mk("HCG03","The Highway That Destroyed a Neighborhood: Interstate Routes Through Black Communities","Every urban interstate mapped against pre-construction neighborhood demographics","MAP","US-metro","Line map","transportation/race","FHWA: Highway data (fhwa.dot.gov); Census: Historical demographics; USDOT: Reconnecting Communities (transportation.gov)",85,75,72,82,85,82,78,75),
mk("HCG04","Where Bail Amounts Create a Debtors Prison: Income vs Cash Bail by County","The same bail amount represents 1 day of income or 30 depending on where you live","MAP","US-county","Bivariate choropleth","law/inequality","LJAF: Pretrial data (ljaf.org); Census: Income (census.gov/acs); BJS: Jail data (bjs.gov)",85,78,72,80,85,75,78,68),
mk("HCG05","The Algorithm That Sentences You: States Using AI in Criminal Justice","Risk assessment algorithms mapped against racial disparity in outcomes","MAP","US-state","State choropleth","law/technology","ProPublica: Machine bias (propublica.org); Mapping AI in Criminal Justice; DOJ: Pretrial (bja.ojp.gov)",82,72,68,82,82,72,82,62),
mk("HCG06","Where the Drug War Feeds Mass Incarceration Which Feeds Poverty Which Feeds the Drug War","The circular causation loop mapped across 3000 counties — where the cycle is strongest","XREF","US-county","Bivariate choropleth","drugs/poverty","BJS: Drug offenders (bjs.gov); CDC: Overdose (wonder.cdc.gov); Census: Poverty (census.gov)",85,75,68,82,85,78,82,72),
mk("HCG07","The Gun-Suicide-Economic Despair Triangle: Where Three Crises Converge","Counties ranking worst on gun access + economic decline + mental health provider shortage","XREF","US-county","County choropleth","guns/health","CDC: Suicide (wonder.cdc.gov); RAND: Gun ownership (rand.org); HRSA: HPSA (hrsa.gov); BLS: Unemployment (bls.gov)",85,75,70,82,85,78,80,72),
mk("HCG08","Middle East Water-Energy-Food Nexus: The Triple Crisis No Country Can Solve Alone","Water for energy, energy for desalination, food needs both — the dependency web mapped","XREF","Middle East","Special map","middle_east/energy","FAO: AQUASTAT (fao.org); IEA: Energy (iea.org); World Bank: Agriculture (worldbank.org)",78,58,68,80,78,78,82,70),
mk("HCG09","The Demographic Doom Loop: Aging Population Reduces Tax Base Reduces Services Accelerates Outmigration","Counties caught in the shrinkage spiral mapped with projected timelines","MAP","US-county","County choropleth","demographics/economy","Census: Projections (census.gov); BEA: Tax revenue (bea.gov); USDA: Rural (ers.usda.gov)",80,72,72,78,80,78,78,72),
mk("HCG10","Where School Funding Follows Property Values Which Follow School Funding","The self-reinforcing loop of property tax education funding mapped at district level","XREF","US-county","Bivariate choropleth","education/housing","NCES: Finance (nces.ed.gov); Census: Property values (census.gov/acs); Zillow: School ratings (zillow.com)",82,82,75,78,80,78,75,78),
mk("HCG11","The Sports-Gambling-Debt Spiral: Where Betting Losses Correlate With Payday Loan Usage","Sports gambling revenue mapped against consumer debt and payday lender density","XREF","US-state","Scatter plot","sports/drugs","AGA: Gaming revenue (americangaming.org); CFPB: Consumer complaints (consumerfinance.gov); Census: Debt (census.gov)",75,78,65,78,72,68,78,62),
mk("HCG12","Where Entertainment Media Shapes Real Estate Prices: The Netflix Effect","Shows filmed in or about a city mapped against subsequent housing price changes","XREF","US-metro","Scatter plot","entertainment/housing","Zillow: Price index (zillow.com); IMDB: Filming locations (imdb.com); Redfin: Market data (redfin.com)",68,75,60,78,58,68,82,58),
mk("HCG13","The Manufacturing-to-Military Pipeline: Factory Closures That Boosted Enlistment","Counties where manufacturing job loss preceded military recruitment spikes","XREF","US-county","Bivariate choropleth","manufacturing/military","BLS: QCEW (bls.gov/qcew); DOD: Recruiting (defense.gov); Census: Demographics (census.gov)",78,72,68,80,75,72,80,72),
mk("HCG14","Where Religious Institutions Fill Government Gaps: Faith-Based Services as Shadow Welfare","Counties where churches provide more social services than government — mapped","MAP","US-county","County choropleth","religion/poverty","ARDA: Congregation survey (thearda.com); HHS: Social services (hhs.gov); Census: Government (census.gov/govs)",75,72,65,78,68,72,80,62),
mk("HCG15","The Psychology of Place and Crime: How Urban Design Predicts Where Crime Happens","CPTED principles validated — street connectivity, lighting, sightlines mapped against crime hotspots","XREF","US-metro","Dot map","psychology/crime","FBI: NIBRS (ucr.fbi.gov); EPA: Smart Location (epa.gov); Walk Score: Design (walkscore.com)",72,70,65,78,68,72,78,62),
mk("HCG16","Where Democracy Erodes Through Appointment Not Election: State Court Capture","Judicial selection methods mapped against court ideology shift over time","MAP","US-state","State choropleth","democracy/law","Brennan Center: Judicial selection (brennancenter.org); FJC: Court data (fjc.gov); Ballotpedia: Judges (ballotpedia.org)",78,65,70,78,80,72,78,68),
mk("HCG17","The Gun-Domestic Violence Feedback Loop: States That Block Abuser Access vs Those That Dont","Domestic violence gun laws mapped against intimate partner homicide rates","MAP","US-state","Bivariate choropleth","guns/gender","Giffords: DV gun laws (giffords.org); FBI: SHR (ucr.fbi.gov); CDC: IPV data (cdc.gov)",85,78,75,78,85,72,72,78),
mk("HCG18","Middle East Climate Migration: Where Rising Temperatures Will Force People to Move","Wet-bulb temperature projections mapped against population density — the coming crisis","MAP","Middle East","Special map","middle_east/climate","NASA: Climate projections (nasa.gov); World Bank: Climate (worldbank.org); IDMC: Displacement (idmc.org)",82,62,72,82,82,80,78,72),
mk("HCG19","The Rural Hospital-Poverty Death Spiral: When the Hospital Closes Everyone Gets Poorer","Economic impact of rural hospital closures mapped — the cascade effect","XREF","US-county","Scatter plot","rural/health","UNC: Hospital closures (shepscenter.unc.edu); BEA: County income (bea.gov); Census: Demographics (census.gov)",85,78,75,78,82,72,75,75),
mk("HCG20","Where Student Debt Delays Marriage Delays Homeownership Delays Wealth Building","The cascade effect of student loans on life milestones mapped by generation and geography","XREF","US-state","Line chart","education/housing","Federal Reserve: Student loans (newyorkfed.org); Census: Marriage/homeownership (census.gov); DOE: Scorecard (collegescorecard.ed.gov)",80,85,72,78,75,68,75,72),
mk("HCG21","The Demographic Replacement Panic vs Demographic Reality: What the Numbers Actually Show","Projected racial composition changes mapped against anti-immigrant sentiment by county","MAP","US-county","Bivariate choropleth","demographics/immigration","Census: Projections (census.gov); PRRI: Immigration attitudes (prri.org); Pew: Demographics (pewresearch.org)",78,72,72,80,82,78,78,72),
mk("HCG22","Where Food Deserts Create Health Deserts Create Economic Deserts","The triple desert mapped — food, healthcare, and economic opportunity all absent in the same places","XREF","US-county","County choropleth","food/health","USDA: Food access (ers.usda.gov); HRSA: HPSA (hrsa.gov); Census: Income (census.gov/acs)",85,82,75,75,80,80,72,80),
mk("HCG23","The Entertainment-Real Estate Loop: Gentrification Follows Art Districts","Art gallery and venue density mapped against rent increases in subsequent years","XREF","US-metro","Scatter plot","entertainment/housing","BLS: Arts employment (bls.gov); Zillow: Rent (zillow.com); Census: ACS (census.gov)",72,75,62,78,68,68,80,60),
mk("HCG24","Where Manufacturing Job Loss Predicts Populist Voting 10 Years Later","The lag between economic shock and political realignment mapped county by county","XREF","US-county","Bivariate choropleth","manufacturing/politics","BLS: QCEW (bls.gov/qcew); MIT: Elections (electionlab.mit.edu); Census: Industry (census.gov)",80,72,72,78,78,78,78,78),
mk("HCG25","The Psychology of Relative Deprivation: Why Inequality Hurts More Than Poverty","Counties where inequality growth outpaces poverty growth mapped against social dysfunction","XREF","US-county","Scatter plot","psychology/inequality","Census: Gini (census.gov); CDC: Deaths of despair (wonder.cdc.gov); Gallup: Wellbeing (gallup.com)",75,72,62,82,72,68,82,62),
mk("HCG26","Where Gun Culture Reproduces Itself: Youth Hunting Programs Mapped Against Adult Ownership","Intergenerational transmission of gun culture visualized geographically","MAP","US-state","Bivariate choropleth","guns/children","USFWS: Youth hunting (fws.gov); RAND: Gun ownership (rand.org); NSSF: Youth programs (nssf.org)",68,68,65,75,65,72,78,68),
mk("HCG27","The Middle East Sanctions-Suffering Loop: How Economic Penalties Hurt Civilians Not Regimes","GDP per capita and child mortality mapped against sanction duration by country","CHART","Middle East","Line chart","middle_east/economy","World Bank: WDI (worldbank.org); UNICEF: Child mortality (unicef.org); OFAC: Sanctions (treasury.gov)",80,65,72,78,80,68,78,72),
mk("HCG28","Where the Criminal Record Employment Ban Creates Recidivism: Ban the Box Impact","States with fair hiring laws mapped against recidivism rates — the policy works","CHART","US-state","Scatter plot","law/labor","BJS: Recidivism (bjs.gov); NELP: Ban the Box (nelp.org); BLS: Employment (bls.gov)",78,72,72,78,75,68,72,72),
mk("HCG29","The Religious Sorting Feedback Loop: Church Attendance Shapes Neighborhood Which Shapes Church","How religious communities self-segregate geographically — the clustering pattern mapped","MAP","US-county","County choropleth","religion/geography","ARDA: Religious census (thearda.com); Census: ACS (census.gov/acs); RCMS: Congregations (rcms.org)",65,68,62,75,58,72,78,72),
mk("HCG30","Where Sports Stadium Debt Crowds Out School Funding: The Municipal Budget Squeeze","Cities diverting tax revenue to stadium bonds mapped against school budget changes","XREF","US-metro","Scatter plot","sports/education","Brookings: Stadiums (brookings.edu); Census: Government finance (census.gov/govs); NCES: Spending (nces.ed.gov)",78,78,72,78,78,68,78,68),
mk("HCG31","The Demographic Echo: How Baby Boom Retirement Creates Cascading Workforce Shortages","Sectors losing workers to retirement mapped against projected shortfalls 2025-2035","CHART","US","Bar chart","demographics/labor","BLS: Projections (bls.gov/emp); Census: Age (census.gov); Conference Board: Workforce (conferenceboard.org)",78,72,72,75,75,68,72,78),
mk("HCG32","Where Drug Prescription Rates Predict Addiction Rates 5 Years Later: The Pharma Pipeline","Opioid prescribing mapped against subsequent addiction and overdose by county — the lag visible","XREF","US-county","Bivariate choropleth","drugs/health","CDC: Prescription data (cdc.gov); DEA: ARCOS (deadiversion.usdoj.gov); CDC: Overdose (wonder.cdc.gov)",85,78,75,82,85,78,72,80),
mk("HCG33","The Rural Broadband-Education-Income Cascade: Where Connectivity Breaks the Poverty Cycle","Counties that got broadband mapped against subsequent education and income gains","XREF","US-county","Scatter plot","rural/technology","FCC: Broadband (fcc.gov); Census: Income/education change (census.gov); NTIA: Broadband (ntia.gov)",78,75,68,78,68,72,75,72),
mk("HCG34","Where the Psychology of Fear Drives Policy: Crime Perception vs Crime Reality by County","The gap between how dangerous people think their county is vs actual crime mapped","XREF","US-county","Bivariate choropleth","psychology/crime","Gallup: Crime worry (gallup.com); FBI: UCR (ucr.fbi.gov); Census: Demographics (census.gov)",75,78,68,82,72,75,78,65),
mk("HCG35","The Incarceration-Voting Feedback Loop: Felony Disenfranchisement Creating Permanent Minority","States where incarceration rates suppress minority voting mapped against policy outcomes","XREF","US-state","Bivariate choropleth","democracy/crime","Sentencing Project: Disenfranchisement (sentencingproject.org); BJS: Corrections (bjs.gov); MIT: Elections (electionlab.mit.edu)",82,72,72,78,85,72,78,72),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HCG ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HCG batch)")
