# BATCH_BM.py
ideas = [
  {'id': 'xref_coal_county_opioid', 'title': 'Coal production decline vs. opioid death rates by Appalachian county', 'sub': 'Counties that lost the most coal jobs in the 1990s-2000s have the highest opioid death rates in the 2010s-2020s. The chemical consolation of economic erasure.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Bivariate choropleth', 'tbl': 'EIA: Coal production by county + CDC WONDER: Drug overdose mortality by county', 'section': 'Energy  -  Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'EIA State Energy Data System: production + consumption by state (eia.gov  free API)'], 'vars': ['coal_production_decline_pct', 'opioid_death_rate_county'], 'join': ['median_household_income', 'manufacturing_job_loss_pct', 'rep_pct_county'], 'sc': {'emotional': 100, 'relatability': 80, 'clarity': 70, 'surprise': 90, 'tension': 100, 'visual': 100, 'data_ready': 80, 'originality': 100}, 'vs': 88, 'tags': 'coal decline opioid deaths Appalachia county 1990s 2000s jobs 2010s 2020s deaths chemical consolation erasure', 'notes': '', 'topics': ['energy', 'health', 'drugs', 'labor', 'poverty', 'history', 'inequality'], 'status': 'idea'},
  {'id': 'solar_capacity_state_map', 'title': 'Installed solar capacity per capita by state 2023 — the clean energy leaders and laggards', 'sub': 'California: 3,900 watts per person. Hawaii: 3,200. West Virginia: 9. The solar transition is happening in two Americas simultaneously.', 'type': 'MAP', 'geo': 'us_state', 'fmt': 'State choropleth', 'tbl': 'EIA Electric Power Monthly: Solar capacity by state (eia.gov)', 'section': 'Energy', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'EIA State Energy Data System: production + consumption by state (eia.gov  free API)'], 'vars': ['solar_capacity_per_capita_state'], 'join': ['renewable_energy_share', 'rep_pct', 'electricity_price_residential'], 'sc': {'emotional': 70, 'relatability': 70, 'clarity': 90, 'surprise': 70, 'tension': 70, 'visual': 100, 'data_ready': 90, 'originality': 60}, 'vs': 77, 'tags': 'solar capacity per capita state California 3900 Hawaii 3200 West Virginia 9 two Americas simultaneously', 'notes': '', 'topics': ['energy', 'climate', 'environment', 'politics', 'geography'], 'status': 'idea'},
  {'id': 'xref_flood_risk_home_value', 'title': 'Flood risk level vs. home values — buyers are not pricing in climate risk', 'sub': 'Homes in FEMA 100-year flood zones sell for only 3% less than comparable non-flood homes. The market has not priced in climate risk. When it does, $1.5T in property value evaporates.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'FEMA NFIP: Flood zone coverage by county + FHFA: Home price index by county', 'section': 'Housing  -  Geography', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['pct_homes_high_flood_risk', 'median_home_value_county'], 'join': ['flood_insurance_uptake_rate', 'poverty_rate_county', 'population_growth_county'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 90, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 90}, 'vs': 85, 'tags': 'flood risk home values 3 percent discount 100-year zone market not priced climate 1.5 trillion evaporates XREF', 'notes': '', 'topics': ['housing', 'environment', 'climate', 'economy', 'geography', 'finance'], 'status': 'idea'},
  {'id': 'electricity_price_state_map', 'title': 'Residential electricity price by state 2023 — who pays the most and why', 'sub': 'Hawaii: 39.8 cents/kWh. Louisiana: 9.2 cents. Wyoming: 9.1. The price map is a map of grid design, fuel mix, and regulatory choices — not geography.', 'type': 'MAP', 'geo': 'us_state', 'fmt': 'State choropleth', 'tbl': 'EIA Electric Power Monthly: Residential electricity prices by state (eia.gov)', 'section': 'Energy', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'EIA State Energy Data System: production + consumption by state (eia.gov  free API)'], 'vars': ['electricity_price_residential_kwh'], 'join': ['renewable_energy_share', 'coal_consumption', 'median_household_income', 'rep_pct'], 'sc': {'emotional': 70, 'relatability': 90, 'clarity': 90, 'surprise': 70, 'tension': 60, 'visual': 100, 'data_ready': 100, 'originality': 60}, 'vs': 80, 'tags': 'electricity price state Hawaii 39.8 Louisiana 9.2 Wyoming 9.1 grid design fuel mix regulatory choices not geography', 'notes': '', 'topics': ['energy', 'economy', 'environment', 'climate', 'infrastructure'], 'status': 'idea'},
  {'id': 'xref_fossil_fuel_jobs_renewable', 'title': 'Fossil fuel employment vs. renewable energy employment by state — where the energy job switch is actually happening', 'sub': 'Texas has both the most fossil fuel jobs AND the most renewable energy jobs. The energy transition is not a zero-sum geography — it is an addition problem.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'BLS OES: Fossil fuel + renewable energy employment by state (bls.gov)', 'section': 'Energy  -  Labor Force', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'BLS national data: employment, wages, CPI (bls.gov  free API)'], 'vars': ['fossil_fuel_employment_state', 'renewable_energy_employment_state'], 'join': ['coal_production_index', 'solar_capacity_per_capita', 'rep_pct'], 'sc': {'emotional': 80, 'relatability': 70, 'clarity': 80, 'surprise': 90, 'tension': 70, 'visual': 90, 'data_ready': 80, 'originality': 90}, 'vs': 80, 'tags': 'fossil fuel renewable energy employment state Texas both most not zero-sum addition problem energy transition XREF', 'notes': '', 'topics': ['energy', 'labor', 'climate', 'economy', 'politics', 'geography'], 'status': 'idea'},
  {'id': 'xref_heat_deaths_ac_access', 'title': 'Extreme heat death rate vs. air conditioning access by county', 'sub': 'Counties with the lowest air conditioning rates are seeing the fastest rise in heat deaths. The correlation is 0.82 — among the strongest in public health geography.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'CDC WONDER: Heat-related mortality + ACS: Air conditioning access by county', 'section': 'Health  -  Energy', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['heat_mortality_rate_county', 'pct_homes_with_ac'], 'join': ['poverty_rate_county', 'median_household_income', 'urban_heat_island_index'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 80, 'tension': 80, 'visual': 90, 'data_ready': 70, 'originality': 80}, 'vs': 82, 'tags': 'heat death AC access county 0.82 correlation fastest rise lowest air conditioning public health geography climate XREF', 'notes': '', 'topics': ['health', 'climate', 'energy', 'poverty', 'environment', 'inequality'], 'status': 'idea'},
  {'id': 'pipeline_proximity_race', 'title': 'Oil and gas pipeline proximity vs. race by county — the infrastructure of environmental injustice', 'sub': 'Communities of color are 40% more likely to live within 1 mile of an active oil or gas pipeline. The map of energy infrastructure is a map of who bears its risks.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Bivariate choropleth', 'tbl': 'EPA EJScreen: Pipeline proximity index + ACS: Race by county', 'section': 'Energy  -  Health', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['pipeline_proximity_index', 'pct_nonwhite_county'], 'join': ['poverty_rate_county', 'cancer_incidence_rate_county', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 60, 'clarity': 70, 'surprise': 80, 'tension': 90, 'visual': 100, 'data_ready': 70, 'originality': 80}, 'vs': 78, 'tags': 'pipeline proximity race county 40 percent more likely color energy infrastructure map who bears risks environmental justice', 'notes': '', 'topics': ['energy', 'race', 'environment', 'inequality', 'health', 'geography'], 'status': 'idea'},
  {'id': 'xref_energy_burden_income', 'title': 'Energy burden (% of income on utilities) by income quintile and state — the regressive utility bill', 'sub': 'The poorest Americans spend 8.6% of their income on home energy. The wealthiest: 2.3%. In Mississippi, low-income families pay 19% of income on energy. Utilities are regressive by design.', 'type': 'XREF', 'geo': 'us_state', 'fmt': 'Scatter plot', 'tbl': 'ACEEE: Low-income Energy Burden by state + ACS: Household income distribution', 'section': 'Energy  -  Income', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['energy_burden_low_income', 'energy_burden_high_income'], 'join': ['electricity_price_residential', 'median_household_income', 'poverty_rate_state'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 80, 'tension': 80, 'visual': 80, 'data_ready': 70, 'originality': 80}, 'vs': 81, 'tags': 'energy burden income 8.6 poor 2.3 wealthy Mississippi 19 percent regressive utility design inequality XREF', 'notes': '', 'topics': ['energy', 'poverty', 'inequality', 'economy', 'housing'], 'status': 'idea'},
  {'id': 'wildfire_risk_home_construction', 'title': 'Wildfire risk vs. housing construction rate in high-risk zones — building toward catastrophe', 'sub': 'Counties with the highest wildfire risk have the fastest-growing housing construction. People are moving into the fire. Insurance companies are retreating. The collision is coming.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Bivariate choropleth', 'tbl': 'US Forest Service: Wildfire risk by county + Census: Building permits by county', 'section': 'Housing  -  Geography', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)'], 'vars': ['wildfire_risk_index_county', 'housing_permits_county'], 'join': ['homeowners_insurance_availability', 'population_growth_county', 'median_home_value'], 'sc': {'emotional': 90, 'relatability': 80, 'clarity': 80, 'surprise': 90, 'tension': 90, 'visual': 100, 'data_ready': 80, 'originality': 90}, 'vs': 86, 'tags': 'wildfire risk housing construction high-risk zones moving into fire insurance retreating collision coming bivariate', 'notes': '', 'topics': ['environment', 'housing', 'climate', 'geography', 'economy', 'insurance'], 'status': 'idea'},
  {'id': 'xref_coal_county_political_change', 'title': 'Coal production collapse vs. Republican vote share increase 1996-2024 by county', 'sub': 'The counties that lost the most coal jobs shifted the most toward the Republican party over 30 years. Economic erasure and political radicalization moved on the same timeline.', 'type': 'XREF', 'geo': 'us_county', 'fmt': 'Scatter plot', 'tbl': 'EIA: Coal production by county + MIT Election Lab: Presidential results 1996-2024 by county', 'section': 'Energy  -  Elections', 'ext': ['ACS 5-year estimates: MHI, poverty rate, population by geography (Census API  free, tidycensus)', 'MIT Election Lab: presidential/congressional results (electionlab.mit.edu  free)'], 'vars': ['coal_production_pct_change_1996_2024', 'rep_vote_change_1996_2024'], 'join': ['manufacturing_job_loss_pct', 'opioid_death_rate_county', 'median_household_income'], 'sc': {'emotional': 90, 'relatability': 70, 'clarity': 70, 'surprise': 90, 'tension': 90, 'visual': 90, 'data_ready': 80, 'originality': 100}, 'vs': 82, 'tags': 'coal production collapse Republican vote increase 1996 2024 county economic erasure political radicalization timeline', 'notes': '', 'topics': ['energy', 'politics', 'elections', 'labor', 'history', 'poverty'], 'status': 'idea'},
]

def vscore(sc):
    return int((sc.get("emotional",0)*2 + sc.get("relatability",0)*2 + sc.get("clarity",0)*2 +
               sc.get("surprise",0)*1.5 + sc.get("tension",0)*1 + sc.get("visual",0)*1 +
               sc.get("data_ready",0)*0.5 + sc.get("originality",0)*0.5) / 10.5)

for idea in ideas:
    idea["vs"] = vscore(idea["sc"])

if __name__ == "__main__":
    print(f"BATCH_BM: {len(ideas)} ideas")
    for i in sorted(ideas, key=lambda x: -x["vs"]):
        print(f"  vs={i["vs"]:3d}  {i["id"]}")
