import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDO01","Rural Brain Drain: College-Educated Adults Leaving Small Counties by Decade","The steady outmigration of young graduates from rural counties — where they leave and where they go, tracked since 1990","MAP","US","County choropleth","rural","USDA: ERS Rural Education Data (ers.usda.gov/topics/rural-economy-population/employment-education)",72,68,72,65,68,78,62,85),
mk("HDO02","Screen Time and Sleep: How Device Usage Before Bed Correlates With Sleep Quality by Age","The dose-response relationship between pre-sleep screen time and sleep disruption — strongest in teens, still measurable in adults","CHART","World","Scatter plot","psychology","National Sleep Foundation: Sleep in America Poll (sleepfoundation.org)",62,82,68,62,58,55,58,75),
mk("HDO03","Children in Immigration Detention: Minors Held in CBP and ICE Facilities by Month","Monthly count of unaccompanied minors and children in family units held in immigration custody — the spikes during surge periods","CHART","US","Line chart","children","CBP: Southwest Border Migration Data (cbp.gov/newsroom/stats/southwest-land-border-encounters)",82,65,68,65,85,62,60,82),
mk("HDO04","Space Debris Catalog: Every Tracked Object in Earth Orbit by Size and Altitude","The 30,000+ tracked pieces of orbital debris visualized by altitude band — the ring of junk getting denser each year","MAP","World","Special map","space","ESA: Space Debris Office (esa.int/Space_Safety/Space_Debris)",58,48,72,72,65,85,68,88),
mk("HDO05","Pharmacy Desert: Rural Counties Where the Nearest Pharmacy Is 30+ Miles Away","Communities losing their last pharmacy — the medicine cabinet equivalent of a food desert spreading across rural America","MAP","US","County choropleth","rural","RUPRI: Rural Pharmacy Closures (rupri.org)",75,72,72,68,72,78,65,80),
mk("HDO06","The Empathy Decline: College Students Self-Reported Empathy Scores Over 30 Years","Meta-analysis showing a 40% drop in dispositional empathy among college students between 1979 and 2009 — has it continued?","CHART","US","Line chart","psychology","Konrath et al: Changes in Dispositional Empathy (researchgate.net)",72,72,68,78,68,55,72,72),
mk("HDO07","Foster Care Aging Out: Youth Who Leave Foster Care at 18 Without a Permanent Family by State","The 20,000+ kids who age out of foster care every year — their outcomes mapped against state support program quality","MAP","US","State choropleth","children","ACF: AFCARS Foster Care Statistics (acf.hhs.gov/cb/data-research/afcars)",82,68,72,68,80,72,62,85),
mk("HDO08","Satellite Internet Coverage: Starlink Active Subscribers by Country","Where SpaceXs Starlink service has the most active users — the satellite internet revolution mapped globally","MAP","World","World choropleth","space","Starlink: Coverage Map (starlink.com) + FCC: Broadband Reports",55,58,72,68,55,72,62,72),
mk("HDO09","Volunteer Fire Department Staffing Crisis: Rural Fire Stations Unable to Respond","Rural fire departments that cant staff enough volunteers to respond to calls — response times climbing as young people leave","MAP","US","County choropleth","rural","NFPA: Needs Assessment of the US Fire Service (nfpa.org)",72,65,68,68,75,78,65,78),
mk("HDO10","Social Media and Teen Mental Health: Depression Rates vs Smartphone Adoption by Country","The correlation between smartphone penetration reaching teens and the spike in adolescent depression — country by country","CHART","World","Scatter plot","psychology","Sapien Labs: Mental State of the World (sapienlabs.org) + Haidt: Anxious Generation",75,75,68,68,75,58,62,72),
mk("HDO11","Lead Exposure in Children: Blood Lead Levels Above CDC Reference by ZIP Code","Where children are still being poisoned by lead — ZIP codes with elevated blood lead levels concentrated near highways, old housing, and industry","MAP","US","County choropleth","children","CDC: Childhood Lead Poisoning Prevention (cdc.gov/nceh/lead/data)",80,72,72,68,82,78,58,82),
mk("HDO12","Dark Sky Reserves: Places Where You Can Still See the Milky Way","International Dark Sky places and reserves mapped against global light pollution data — where natural night still exists","MAP","World","Dot map","space","International Dark-Sky Association: Dark Sky Places (darksky.org)",58,62,72,65,48,88,72,82),
mk("HDO13","Rural Grocery Store Closures: Counties That Lost Their Last Supermarket Since 2015","The grocery gap widening — communities where the only food shopping option is now a gas station or dollar store","MAP","US","County choropleth","rural","USDA: Food Access Research Atlas (ers.usda.gov/data-products/food-access-research-atlas)",75,75,72,68,72,78,62,82),
mk("HDO14","Impostor Syndrome Prevalence: Who Experiences It Most by Profession and Demographics","Survey data on impostor syndrome rates — paradoxically highest among high-achievers, women in STEM, and first-generation professionals","CHART","World","Bar chart","psychology","International Journal of Behavioral Science: Impostor Phenomenon Studies (ijbs-online.org)",62,78,65,68,55,52,65,68),
mk("HDO15","Child Marriage in America: States That Still Allow Minors to Marry","Where child marriage remains legal in the US — states with no minimum marriage age when parental or judicial consent is given","MAP","US","State choropleth","children","Unchained At Last: Child Marriage Data (unchainedatlast.org)",82,68,72,78,82,72,68,78),
mk("HDO16","Launch Site Geography: Every Active Orbital Launch Facility on Earth","The worlds operational spaceports — from Cape Canaveral to Baikonur to new commercial sites in Scotland and Australia","MAP","World","Dot map","space","Jonathan McDowell: Launch Site Database (planet4589.org/space/log)",52,45,72,62,48,85,65,90),
mk("HDO17","EMS Response Time in Rural Areas: Average Ambulance Arrival by County Population Density","How long you wait for an ambulance based on where you live — 8 minutes in cities vs 30+ minutes in many rural counties","MAP","US","County choropleth","rural","NEMSIS: National EMS Database (nemsis.org)",78,72,72,65,78,78,58,82),
mk("HDO18","The Hedonic Treadmill: How Quickly Lottery Winners Return to Baseline Happiness","Classic and updated research on adaptation — lottery winners are no happier than controls within months, across multiple studies","CHART","World","Line chart","psychology","Brickman et al + Kuhn et al: Lottery and Happiness Studies (apa.org)",62,72,65,78,52,52,78,72),
mk("HDO19","Pediatric Mental Health Emergency Visits: ER Trips for Youth Mental Health Crises by Year","Child and teen ER visits for suicidal ideation, self-harm, and anxiety tripled in a decade — the pediatric mental health emergency","CHART","US","Line chart","children","CDC: WISQARS Emergency Department Data (wisqars.cdc.gov)",85,72,72,68,82,58,58,82),
mk("HDO20","Commercial Space Station Plans: Every Proposed Orbital Habitat After ISS","The post-ISS future — Axiom, Orbital Reef, Starlab, and national proposals mapped with projected timelines and capabilities","MAP","World","Special map","space","NASA: Commercial LEO Destinations (nasa.gov/leo-economy)",52,42,68,72,55,78,72,68),
mk("HDO21","Rural Internet Speed Reality: Advertised vs Actual Broadband Speeds in Non-Metro Counties","What rural residents are promised vs what they actually get — the gap between advertised and measured download speeds","MAP","US","Bivariate choropleth","rural","Ookla: Speedtest Intelligence (speedtest.net/insights) + FCC Broadband Data",65,75,72,72,68,72,62,78),
mk("HDO22","Attachment Style Distribution: How Adults Bond in Relationships by Culture","Prevalence of secure, anxious, avoidant, and disorganized attachment styles across 62 countries — the cultural map of how we love","MAP","World","World choropleth","psychology","Schmitt et al: Cross-Cultural Attachment (journals.sagepub.com)",62,72,62,72,55,62,75,72),
mk("HDO23","Childhood Obesity by Grade Level: BMI Percentiles Tracked Through K-12 by State","Where childhood obesity accelerates most — states where kids enter kindergarten healthy but leave 8th grade obese","MAP","US","State choropleth","children","CDC: Youth Risk Behavior Surveillance System (cdc.gov/yrbs)",72,72,72,65,68,68,58,85),
mk("HDO24","Lunar South Pole Race: Landing Site Claims by Space Agency","The crowded real estate of the lunar south pole — overlapping mission targets from NASA, ESA, CNSA, ISRO, and private companies","MAP","World","Special map","space","NASA: Artemis Landing Site Selection (nasa.gov/artemis)",58,42,68,72,62,82,72,75),
mk("HDO25","Maternity Ward Closures: Rural Hospitals That Stopped Delivering Babies","Counties where women now drive 60+ miles to give birth — the maternity care desert spreading across rural America","MAP","US","County choropleth","rural","March of Dimes: Maternity Care Deserts (marchofdimes.org)",82,72,72,72,80,80,62,85),
mk("HDO26","The Paradox of Choice: How More Options Lead to Less Satisfaction in Consumer Decisions","Schwartz paradox data — satisfaction scores decrease as available choices increase, across product categories and cultures","CHART","World","Scatter plot","psychology","Schwartz: The Paradox of Choice + Iyengar Jam Study (columbia.edu)",58,72,68,72,52,55,72,70),
mk("HDO27","Adverse Childhood Experiences: ACE Score Distribution by State and Demographic","How many children experience trauma — abuse, neglect, household dysfunction — and the staggering variation in ACE prevalence by state","MAP","US","State choropleth","children","CDC: Behavioral Risk Factor Surveillance System (cdc.gov/brfss)",80,68,72,68,78,72,58,85),
mk("HDO28","Artemis vs Apollo: Budget, Timeline, and Technical Comparison of Moon Programs","Side-by-side comparison of the Apollo and Artemis programs — cost per mission, development time, and technological capability","XREF","US","Bar chart","space","NASA: Budget Historical Data (nasa.gov/budget) + Planetary Society (planetary.org)",58,55,75,65,55,62,62,88),
mk("HDO29","Rural Maternal Mortality: Pregnancy-Related Deaths in Rural vs Urban Counties","Women in rural counties die in childbirth at nearly double the rate of urban women — the access gap killing mothers","MAP","US","Bivariate choropleth","rural","CDC: Maternal Mortality Surveillance (cdc.gov/reproductivehealth/maternal-mortality)",85,68,72,68,82,75,62,80),
mk("HDO30","Emotional Contagion Online: How Moods Spread Through Social Media Networks","The Facebook emotional contagion study and follow-ups — how exposure to positive or negative content shifts user mood at scale","CHART","World","Line chart","psychology","Kramer et al: Emotional Contagion via Social Networks (pnas.org)",62,68,62,75,62,55,75,72),
mk("HDO31","Unaccompanied Minors: Children Crossing the US Border Alone by Country of Origin","Monthly arrivals of unaccompanied children by nationality — the Central American and now global pipeline of kids traveling alone","CHART","US","Line chart","children","ORR: Unaccompanied Children Program (acf.hhs.gov/orr)",82,62,72,65,82,62,58,85),
mk("HDO32","Space Economy Market Size: Revenue by Sector — Launch, Satellite, Ground Equipment, Services","The $470B space economy broken down — where the money actually is (hint: its not rockets, its satellite TV and GPS)","CHART","World","Treemap","space","Space Foundation: The Space Report (spacefoundation.org)",52,45,72,72,52,65,65,82),
mk("HDO33","Rural Teacher Shortage Severity: Unfilled Teaching Positions by Subject in Non-Metro Districts","Which subjects cant find teachers in rural schools — math and science positions vacant for entire school years","MAP","US","County choropleth","rural","DOE: Teacher Shortage Area Report (tsa.ed.gov)",72,68,72,62,72,72,58,82),
mk("HDO34","Flow State Triggers: Activities Most Likely to Induce Flow by Demographic","What puts people in the zone — survey data on which activities trigger flow states, varying dramatically by age, profession, and personality","CHART","World","Bar chart","psychology","Csikszentmihalyi: Experience Sampling Method Studies (claremont.edu)",55,72,62,68,48,52,72,65),
mk("HDO35","Child Influencer Labor: Estimated Hours Worked by Minors Creating Social Media Content","The unregulated child labor force of social media — estimated working hours for kid YouTubers and TikTokers, by state regulation status","MAP","US","State choropleth","children","Campaign for a Commercial-Free Childhood (fairplayforkids.org) + State labor law databases",75,68,65,78,78,58,78,58),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDO batch)")
