import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HDN01","The Assembly Line Returns: New Auto Manufacturing Plants Announced Since 2020","Every new vehicle assembly and battery plant announced in the US since 2020 — the reshoring of American automaking","MAP","US","Dot map","manufacturing","Alliance for Automotive Innovation: Investment Tracker (autosinnovate.org)",58,55,72,68,58,78,65,82),
mk("HDN02","Exorcism Hotline: Vatican-Approved Exorcist Demand by Country","The Catholic Churchs surprising modern exorcism industry — formal training courses overflowing and demand rising across Europe and the Americas","MAP","World","World choropleth","religion","International Association of Exorcists (aiepressoffice.com)",55,55,52,85,58,62,85,48),
mk("HDN03","The Laugh Track Timeline: When TV Shows Stopped Using Fake Audience Laughter","The rise and fall of the laugh track — from universal in the 1970s to extinct by the 2020s, charted by show and network","CHART","US","Line chart","entertainment","IMDb: TV Show Production Details (imdb.com)",48,72,65,68,42,55,72,65),
mk("HDN04","Worlds Funniest Countries: Stand-Up Comedy Venues Per Capita by Nation","Which countries have the most comedy infrastructure — comedy clubs, open mic nights, and improv theaters per million people","MAP","World","World choropleth","humor","Chortle: International Comedy Venue Database (chortle.co.uk)",48,62,58,72,42,65,78,55),
mk("HDN05","Youth Sports Spending: What American Families Pay for Kids Activities Per Year","The $30B youth sports industry — travel teams, club fees, private coaching — average spending by sport and income level","CHART","US","Bar chart","sports","Aspen Institute: State of Play Report (aspenprojectplay.org)",62,78,72,68,62,58,58,75),
mk("HDN06","Craft Brewery Density vs Factory Closures: The Deindustrialization-to-IPA Pipeline","Counties that lost manufacturing jobs and gained craft breweries — the economic reinvention happening in converted factory spaces","MAP","US","Bivariate choropleth","manufacturing","Brewers Association: Brewery Location Data (brewersassociation.org) + BLS CEW",55,68,65,78,52,72,82,78),
mk("HDN07","Religious Exemptions Map: States That Allow Faith-Based Opt-Outs From Laws","Where religious exemptions override vaccine mandates, anti-discrimination laws, and medical care requirements for children","MAP","US","State choropleth","religion","National Conference of State Legislatures: Religious Exemptions (ncsl.org)",65,62,72,68,72,72,65,82),
mk("HDN08","Anime Consumption Map: Countries With the Highest Anime Viewership Per Capita","Beyond Japan — where anime is most watched globally, with surprising consumption rates in Latin America and Southeast Asia","MAP","World","World choropleth","entertainment","Parrot Analytics: Global Demand for Anime (parrotanalytics.com)",52,62,65,72,42,65,68,68),
mk("HDN09","Government Spelling Errors in Official State Codes: The Weirdest Typos Still in Law","Actual typos and grammatical errors in current state legal codes that nobody has bothered to fix — some changing the laws meaning","CHART","US","Bar chart","humor","State legislature code databases (various state sites)",42,62,52,85,42,48,85,55),
mk("HDN10","March Madness Productivity Loss: Estimated Hours of Work Lost During NCAA Tournament","The $17B+ annual productivity hit from workers watching basketball at their desks — mapped by time zone and round","CHART","US","Bar chart","sports","Challenger Gray: March Madness Workplace Survey (challengergray.com)",48,78,62,68,42,55,62,68),
mk("HDN11","Apparel Made in America: Clothing Items Still Manufactured Domestically by Category","What clothing is still sewn in the US — from less than 3% of consumer apparel to specialized military and workwear holdouts","CHART","US","Bar chart","manufacturing","OTEXA: US Textile and Apparel Trade Data (otexa.trade.gov)",55,62,72,72,58,58,65,78),
mk("HDN12","Megachurch Political Endorsements: Large Churches That Have Made Partisan Statements","Tracking megachurches that cross the Johnson Amendment line — political statements from the pulpit mapped by denomination and party","MAP","US","Dot map","religion","FFRF: Violations of the Johnson Amendment Database (ffrf.org)",65,62,62,72,72,72,72,62),
mk("HDN13","Canceled TV Show Graveyard: Most-Watched Programs Killed After One Season by Decade","The most popular shows that networks pulled anyway — from Firefly to Freaks and Geeks — viewer counts vs cancellation decisions","CHART","US","Scatter plot","entertainment","Nielsen: Historical Ratings Data via TV Series Finale (tvseriesfinale.com)",55,72,62,68,55,58,68,72),
mk("HDN14","Accidental Comedy in Government Reports: The Most Unintentionally Funny Official Statistics","Real data points from government sources that sound made up — the state of Idaho investigating 47 moose-vehicle collisions, or OSHA citing a company for employees riding alligators","CHART","US","Bar chart","humor","Various federal and state agency reports via FOIA",42,68,48,82,38,48,85,52),
mk("HDN15","Athlete Salary vs Teacher Salary: Professional Sports Pay Compared to Public School Teachers","The average NFL player makes in one game what the average teacher makes in a year — the values comparison by metro","XREF","US","Bar chart","sports","Spotrac: Contract Database (spotrac.com) + NEA: Teacher Salary Data (nea.org)",68,78,75,62,65,55,58,85),
mk("HDN16","Shoe Factory Renaissance: Athletic Footwear Production Returning to the US","New Balance in Maine, Nike experiments in Atlanta — the small but growing movement to bring shoe manufacturing back from Asia","MAP","US","Dot map","manufacturing","Footwear Distributors and Retailers of America (fdra.org)",52,55,68,72,52,72,72,62),
mk("HDN17","The God Gap: Church Attendance Rates Among Democrats vs Republicans Over Time","How religious observance became politically polarized — the diverging churchgoing habits of the two parties since 1990","CHART","US","Line chart","religion","Gallup: Church Attendance by Party (gallup.com)",62,68,72,68,65,58,65,82),
mk("HDN18","Video Game Revenue vs Movie Box Office: Which Entertainment Industry Is Bigger","Gaming surpassed Hollywood years ago and the gap keeps widening — annual revenue comparison since 2000","CHART","World","Area chart","entertainment","Newzoo: Global Games Market Report (newzoo.com) + MPAA Theatrical Statistics",55,72,72,72,52,62,62,82),
mk("HDN19","State Bird Imposters: How Many State Birds Dont Actually Live in Their State Year-Round","Which states picked a state bird thats basically a tourist — birds that migrate away for half the year or are rarely seen locally","MAP","US","State choropleth","humor","Audubon: Bird Range Maps (audubon.org) + State Symbols USA",42,62,62,78,35,68,78,72),
mk("HDN20","Concussion Rates by Youth Sport: Head Injuries Per 10K Athletic Exposures","Which youth sports have the highest concussion rates — football leads but girls soccer, lacrosse, and cheerleading are surprisingly high","RANK","US","Bar chart","sports","CDC: Youth Sports Injury Surveillance (cdc.gov)",72,72,72,68,72,58,58,82),
mk("HDN21","Reshoring vs Offshoring: Net Manufacturing Job Flow by Year and Industry","The annual balance sheet — jobs leaving for cheaper markets vs jobs coming back for supply chain resilience, by sector","CHART","US","Line chart","manufacturing","Reshoring Initiative: Annual Reports (reshorenow.org)",58,58,72,68,62,58,62,78),
mk("HDN22","Conversion to Islam Map: Fastest Growing Muslim Populations in Western Countries","Countries in Europe and the Americas with the highest Muslim population growth rates — distinguishing immigration from conversion","MAP","World","World choropleth","religion","Pew Research: The Future of World Religions (pewresearch.org/religion)",58,52,65,72,62,68,68,72),
mk("HDN23","The One-Hit Wonder Index: Songs That Charted Once by Decade and Genre","Mapping the phenomenon of the one-hit wonder — which decades and genres produced the most artists with exactly one Billboard hit","CHART","US","Scatter plot","entertainment","Billboard: Chart History Database (billboard.com)",48,72,62,68,42,55,68,78),
mk("HDN24","Government Website Absurdity: The Most Confusingly Named Federal Agency Websites","Real federal website URLs and page titles that sound fake — from the Interagency Grizzly Bear Committee to the Office of Postsecondary Education","RANK","US","Ranked list","humor","USA.gov: A-Z Index of Government Agencies (usa.gov/federal-agencies)",38,62,52,82,35,48,82,78),
mk("HDN25","Esports Prize Pool Growth: Total Tournament Winnings by Game Title Since 2010","The explosion of competitive gaming prize money — from million-dollar Dota 2 pools to Fortnite World Cup payouts rivaling traditional sports","CHART","World","Line chart","sports","Esports Earnings: Tournament Results (esportsearnings.com)",52,58,72,68,48,62,65,88),
mk("HDN26","PPE Production Gap: Americas Inability to Manufacture Its Own Protective Equipment","How dependent the US is on foreign PPE manufacturing — the mask and gown shortage that revealed a strategic vulnerability","MAP","World","World choropleth","manufacturing","HHS: National Strategy for a Resilient Public Health Supply Chain (phe.gov)",62,68,68,72,72,62,65,75),
mk("HDN27","Witchcraft Resurgence: Self-Identified Pagans, Wiccans, and Witches in America by Region","The fastest-growing spiritual identity in Census surveys — where modern witchcraft and paganism concentrate geographically","MAP","US","State choropleth","religion","Pew Research: Religious Landscape Study (pewresearch.org/religion) + Trinity College ARIS",52,58,58,78,48,68,80,65),
mk("HDN28","The Enshittification Timeline: When Popular Platforms Started Degrading User Experience","User satisfaction scores for major platforms over time — the moment each service prioritized revenue extraction over user experience","CHART","World","Line chart","entertainment","American Customer Satisfaction Index: Technology Sector (theacsi.org)",62,78,65,72,62,55,78,65),
mk("HDN29","Floridas Wild Animal Encounters: Non-Native Species Reported to Wildlife Authorities by County","The exotic pet dumping ground — pythons, iguanas, monitor lizards, and monkeys now established populations mapped by county","MAP","US","County choropleth","humor","FWC: Nonnative Species Reporting (myfwc.com/wildlifehabitats/nonnatives)",52,68,62,78,48,75,75,78),
mk("HDN30","Minor League Baseball Contraction: Teams Eliminated in the 2021 MLB Reorganization","The 40 minor league teams MLB cut — small towns that lost their baseball identity mapped against community population","MAP","US","Dot map","sports","MiLB: Affiliated Teams List (milb.com) + Census Data",68,65,68,65,68,75,65,82),
mk("HDN31","Ammunition Manufacturing: Where Americas Bullets Are Made","Every major ammunition factory in the US — the geographic concentration of a $7B industry in just a handful of states","MAP","US","Dot map","manufacturing","NSSF: Ammunition Industry Data (nssf.org) + ATF Manufacturing Reports",52,48,68,68,58,78,68,72),
mk("HDN32","Seminary Enrollment Decline: Students Training for Religious Ministry by Denomination","The pipeline of future clergy is drying up — seminary enrollment by denomination showing which faiths face a leadership crisis","CHART","US","Line chart","religion","ATS: Annual Data Tables (ats.edu/resources/student-data)",62,52,68,72,65,55,68,78),
mk("HDN33","Talent Show to Streaming: How Music Discovery Channels Have Changed by Decade","From American Bandstand to MTV to Spotify algorithmic playlists — how people first hear new music, tracked across generations","CHART","US","Area chart","entertainment","RIAA + Edison Research: Share of Ear (edisonresearch.com)",55,72,68,62,48,58,68,72),
mk("HDN34","Municipal Code Absurdities: Bizarre Laws Still on the Books by City","Real municipal ordinances that are technically still enforceable — no singing in bathtubs in Pennsylvania, no walking backwards after sunset in some towns","MAP","US","Dot map","humor","FindLaw: Strange Laws Database (findlaw.com) + Municipal code archives",38,72,48,82,32,65,80,62),
mk("HDN35","Home Field Advantage by Stadium Altitude: Does Elevation Help Home Teams?","Comparing home win percentages for teams at high altitude — Denver Broncos, Utah Jazz, Mexico City — vs sea level controls","CHART","World","Scatter plot","sports","Sports Reference: Historical Game Results (sports-reference.com)",48,58,72,75,48,62,75,82),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All 35 ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HDN batch)")
