import re, os
DATA = os.path.join(os.path.dirname(__file__), 'data.js')

def mk(id,title,sub,typ,geo,fmt,sect,tbl,e,r,c,s,t,v,o,dr):
    raw=e*2+r*2+c*1.25+s*1.5+t*1.5+v*2.0+o*1.5
    vs=int((raw/11.75)*(1-0.5*(1-dr/100)))
    return ('{id:"'+id+'",title:"'+title+'",sub:"'+sub+'",type:"'+typ+'",'
            'geo:"'+geo+'",fmt:"'+fmt+'",section:"'+sect+'",tbl:"'+tbl+'",'
            'sc:{emotional:'+str(e)+',relatability:'+str(r)+',clarity:'+str(c)
            +',surprise:'+str(s)+',tension:'+str(t)+',visual:'+str(v)
            +',originality:'+str(o)+',data_ready:'+str(dr)+'}'
            ',vs:'+str(vs)+',topics:[],ext:[],status:"idea",notes:""}')

IDEAS = [
mk("HBY01","The Police Misconduct Map: Officers With Multiple Complaints Who Still Carry a Badge","Counties where repeat-offender officers concentrate — mapped against demographics","MAP","US-county","Dot map","law/race","DOJ: Police misconduct data (justice.gov); USA Today: Police misconduct (usatoday.com/policeaccountability); Census: Demographics (census.gov)",85,75,72,82,88,78,80,65),
mk("HBY02","Where Gun Deaths Disappeared From the Data: The CDC Funding Gap 1996-2018","What 22 years of suppressed research cost — modeling the data we never collected","CHART","US","Line chart","guns/science","CDC: WONDER (wonder.cdc.gov); NIH: Funding data (reporter.nih.gov); Dickey Amendment timeline (congress.gov)",82,68,72,82,85,68,82,72),
mk("HBY03","Every Classified US Military Operation in the Middle East We Know About","Declassified operations mapped by year and country — what was hidden and for how long","MAP","Middle East","Special map","middle_east/military","NSA Archive: Declassified docs (nsarchive.gwu.edu); DOD: Operations (defense.gov); CRS: Reports (crsreports.congress.gov)",78,62,65,85,82,82,80,58),
mk("HBY04","The Demographic Time Bomb: Counties That Will Lose 30% of Working-Age Adults by 2040","Census projections mapped — the places where the workforce is mathematically vanishing","MAP","US-county","County choropleth","demographics/economy","Census: Population projections (census.gov); BLS: Labor force (bls.gov); USDA: Rural atlas (ers.usda.gov)",82,75,78,80,82,80,75,72),
mk("HBY05","Where Democracy Is Weakest: States With the Most Gerrymandered Districts","Efficiency gap scores mapped against voter participation and competitiveness","MAP","US-state","State choropleth","democracy/politics","PlanScore: Gerrymandering data (planscore.org); Brennan Center: Redistricting (brennancenter.org); MIT: Elections (electionlab.mit.edu)",80,75,75,72,82,78,70,78),
mk("HBY06","The Drug Price Map: What the Same Pill Costs in Every Country","US vs Canada vs UK vs Germany for the 20 most prescribed drugs — the markup exposed","CHART","World","Bar chart","drugs/prices","PharmacyChecker: International prices (pharmacychecker.com); CMS: Drug spending (cms.gov); OECD: Pharma (oecd.org)",88,85,80,78,82,70,68,80),
mk("HBY07","States That Banned Books Mapped Against States With the Worst Literacy Rates","The Venn diagram nobody asked for but everyone needs to see","CHART","US-state","Bivariate choropleth","education/law","ALA: Banned books (ala.org/bbooks); NCES: Literacy (nces.ed.gov); PEN America: Book bans (pen.org)",82,78,75,82,82,78,78,78),
mk("HBY08","The Private Prison Pipeline: Counties Where Incarceration Is the Largest Employer","Mapped against poverty rate and racial composition — the economics of jailing people","MAP","US-county","Bivariate choropleth","law/poverty","BJS: Prison census (bjs.gov); SEC: Private prison filings (sec.gov); Census: Employment (census.gov); BLS: QCEW (bls.gov)",85,75,72,82,88,78,80,72),
mk("HBY09","Gun Ownership vs Gun Knowledge: States Where Owners Fail Basic Safety Questions","Survey data mapped — the gap between ownership rates and safe handling proficiency","CHART","US-state","Scatter plot","guns/education","RAND: Gun ownership (rand.org); Johns Hopkins: Gun safety survey (jhsph.edu); Pew: Gun culture (pewresearch.org)",72,72,70,82,72,68,80,60),
mk("HBY10","The Disappearing Swing Voter: How Many True Independents Are Left by State","Mapped from 2000 to 2024 — the center is hollowing out","CHART","US-state","Animated choropleth","democracy/demographics","Pew: Party ID (pewresearch.org); Gallup: Party affiliation (gallup.com); MIT: Elections (electionlab.mit.edu)",75,78,72,75,78,75,72,72),
mk("HBY11","Where Your Tax Dollars Fund Religious Schools","States with voucher programs mapped against religious school enrollment rates","MAP","US-state","Bivariate choropleth","religion/education","EdChoice: Voucher data (edchoice.org); NCES: Private schools (nces.ed.gov); IRS: Tax-exempt (irs.gov)",78,78,72,75,80,75,72,75),
mk("HBY12","The Psychology of Gun Ownership: Threat Perception vs Actual Crime Rates by State","People who feel unsafe own more guns — but they live in the safest places","CHART","US-state","Scatter plot","psychology/guns","Gallup: Fear survey (gallup.com); RAND: Gun ownership (rand.org); FBI: UCR (ucr.fbi.gov)",75,78,70,85,72,68,82,65),
mk("HBY13","Every US Arms Sale to the Middle East Since 1990 in One Timeline","Dollar value of weapons sold to each country mapped against subsequent conflicts","CHART","Middle East","Area chart","middle_east/trade","SIPRI: Arms transfers (sipri.org); DSCA: Arms sales (dsca.mil); ACLED: Conflict (acleddata.com)",82,65,75,78,82,78,75,82),
mk("HBY14","The Manufacturing Ghost Town Index: Cities Built for One Factory","Single-employer dependency mapped — what happens when the factory closes","MAP","US-metro","Dot map","manufacturing/rural","Census: CBP single-establishment (census.gov); BLS: Employment (bls.gov); BEA: Personal income (bea.gov)",80,78,72,75,78,75,78,70),
mk("HBY15","Where Americans Cant Afford a Lawyer: The Access to Justice Desert","Counties where legal aid lawyers serve 10000+ people each — mapped against poverty","MAP","US-county","County choropleth","law/poverty","LSC: Legal aid data (lsc.gov); ABA: Lawyer demographics (americanbar.org); Census: Poverty (census.gov)",82,78,72,78,82,78,75,70),
mk("HBY16","The Sports Injury Cover-Up: CTE Rates by Position That the NFL Fought to Hide","Brain injury prevalence mapped by playing position and career length","CHART","US","Bar chart","sports/health","BU CTE Center: Brain bank (bu.edu/cte); NFL: Player data (nfl.com); JAMA: CTE research (jamanetwork.com)",85,75,72,78,85,68,75,68),
mk("HBY17","Drug Decriminalization Mapped: What Happened to Crime Rates in Every Country That Tried It","Portugal, Czech Republic, Uruguay, and others — before/after comparison","CHART","World","Bar chart","drugs/international","EMCDDA: Drug data (emcdda.europa.eu); UNODC: Crime (unodc.org); WHO: Drug statistics (who.int)",80,72,78,78,75,68,75,78),
mk("HBY18","Where the Census Undercounts: Communities That Lose Billions in Federal Funding","2020 undercount rates by county mapped against lost per-capita funding","MAP","US-county","Bivariate choropleth","demographics/finance","Census: Post-enumeration survey (census.gov); GAO: Census accuracy (gao.gov); George Washington Univ: Counting for Dollars (gwu.edu)",78,72,75,78,78,78,75,72),
mk("HBY19","The Entertainment Brain Drain: Where Creative Workers Are Leaving","Net migration of arts/entertainment workers by metro 2015-2024 — LA losing, Austin gaining","MAP","US-metro","Dot map","entertainment/labor","BLS: OES arts employment (bls.gov/oes); Census: ACS migration (census.gov/acs); IRS: SOI migration (irs.gov)",70,75,68,72,62,72,75,72),
mk("HBY20","Every Democracy That Died in the 21st Century and What Came Before","V-Dem democracy scores for countries that slid into authoritarianism — timeline chart","CHART","World","Line chart","democracy/international","V-Dem: Democracy indices (v-dem.net); Freedom House: Freedom scores (freedomhouse.org)",82,68,75,78,82,72,75,80),
mk("HBY21","The Gun Show Loophole Mapped: States With No Background Check Requirements for Private Sales","Private sale exemptions overlaid with crime gun trace data","MAP","US-state","Bivariate choropleth","guns/law","Giffords: Gun law scorecard (giffords.org); ATF: Trace data (atf.gov); NICS: Background checks (fbi.gov)",78,72,78,75,80,78,68,80),
mk("HBY22","Where Your Prescription Goes to Die: The Pharmacy Desert Map","Census tracts with zero pharmacies within 10 miles — mapped against chronic disease rates","MAP","US-county","County choropleth","drugs/health","NACDS: Pharmacy data (nacds.org); CDC: Chronic disease (cdc.gov); Census: Retail census (census.gov)",82,82,75,75,78,78,72,72),
mk("HBY23","The Religious Decline of America in One Animated Chart","Church membership by denomination 1937-2025 — the cliff started in 2000","CHART","US","Animated line chart","religion/demographics","Gallup: Church membership (gallup.com); ARDA: Religious census (thearda.com); GSS: Religious attendance (gss.norc.org)",75,75,78,75,72,72,68,82),
mk("HBY24","Psychology of Place Attachment: Why People Stay in Dying Towns","Emotional attachment scores mapped against economic decline — people choose belonging over prosperity","MAP","US-county","Bivariate choropleth","psychology/rural","Knight Foundation: Soul of the Community (knightfoundation.org); Census: Population change (census.gov); BEA: Income (bea.gov)",78,82,65,78,70,72,82,58),
mk("HBY25","Where Minorities Cant Get a Small Business Loan","SBA loan approval rates by race of applicant mapped by metro area","MAP","US-metro","Bar chart","race/finance","SBA: Loan data (sba.gov); Federal Reserve: Small Business Survey (fedsmallbusiness.org); Census: ABS (census.gov/abs)",82,78,72,78,82,72,72,75),
mk("HBY26","The Middle East Literacy Revolution: Female Education Rates That Would Surprise You","Countries where female university enrollment now exceeds male — mapped","MAP","Middle East","Bar chart","middle_east/education","UNESCO: Education data (uis.unesco.org); World Bank: Gender (worldbank.org)",70,65,75,85,60,68,80,82),
mk("HBY27","Every State That Made It Harder to Sue Your Doctor and What Happened to Malpractice","Tort reform mapped against medical error rates and malpractice costs","CHART","US-state","Scatter plot","law/health","NCSL: Tort reform laws (ncsl.org); NPDB: Malpractice data (npdb.hrsa.gov); CMS: Healthcare spending (cms.gov)",75,72,70,78,75,68,78,72),
mk("HBY28","The Demographics of Who Gets Stopped by Police: Traffic Stop Data for Every Major City","Stop rates by race normalized per population — the disparity is consistent everywhere","CHART","US-metro","Bar chart","demographics/law","Stanford Open Policing (openpolicing.stanford.edu); FBI: UCR (ucr.fbi.gov); Census: Demographics (census.gov)",85,78,78,72,85,70,68,78),
mk("HBY29","Where Sports Gambling Ads Target: Betting App Marketing Spend by Media Market","Ad spending mapped against problem gambling rates and median income","MAP","US-metro","Dot map","sports/media","Nielsen: Ad tracking (nielsen.com); AGA: Responsible gaming (americangaming.org); iSpot: Ad intelligence (ispot.tv)",72,78,65,75,72,72,78,60),
mk("HBY30","The Manufacturing Workers Lost Generation: Median Age in Factories by State","Average factory worker is 44 — and nobody under 25 is replacing them","CHART","US-state","Bar chart","manufacturing/demographics","BLS: CPS demographics (bls.gov/cps); Census: ACS industry (census.gov/acs); Deloitte: Workforce study (deloitte.com)",75,72,72,78,72,68,75,75),
mk("HBY31","Rural Americas Entertainment Void: What People Actually Do for Fun in Counties With Nothing","Time use surveys mapped — screen time fills the void where venues dont exist","CHART","US-state","Bar chart","entertainment/rural","BLS: ATUS (bls.gov/tus); Census: Rural-urban (census.gov); USDA: Rural amenities (ers.usda.gov)",70,78,65,72,58,68,78,65),
mk("HBY32","The Gun Industry vs the Tobacco Industry: Revenue Trajectory Comparison","Two industries that profit from products that kill their customers — revenue curves","CHART","US","Line chart","guns/economy","ATF: Industry data (atf.gov); NSSF: Industry stats (nssf.org); TTB: Tobacco revenue (ttb.gov); CDC: Mortality (cdc.gov)",78,72,75,80,78,68,80,72),
mk("HBY33","Where Your Judge Was a Prosecutor: The Career Pipeline That Shapes Sentencing","Percentage of judges with prosecution backgrounds by state — mapped against incarceration","MAP","US-state","Bivariate choropleth","law/crime","ABA: Judicial demographics (americanbar.org); BJS: Corrections (bjs.gov); FJC: Biographical directory (fjc.gov)",80,68,68,82,80,72,82,62),
mk("HBY34","The Psychology of Suburban Isolation: Cul-de-Sac Density vs Depression Rates","Street network connectivity mapped against mental health outcomes by metro","XREF","US-metro","Scatter plot","psychology/housing","EPA: Smart Location (epa.gov/smartgrowth); CDC: PLACES (cdc.gov/places); Census: ACS (census.gov)",72,78,62,82,65,68,85,58),
mk("HBY35","Middle East Youth Bulge: Countries Where 50% of the Population Is Under 25","Youth share mapped against unemployment, protest frequency, and internet access","MAP","Middle East","Bar chart","middle_east/demographics","UN Population: Age structure (population.un.org); ILO: Youth unemployment (ilo.org); World Bank: Internet (worldbank.org)",78,65,75,78,80,72,75,80),
]

# --- inject ---
with open(DATA, 'r', encoding='utf-8') as f:
    txt = f.read()
ids = set(re.findall(r'id:"([^"]+)"', txt))
new = [i for i in IDEAS if re.search(r'id:"([^"]+)"', i).group(1) not in ids]
if not new:
    print("All HBY ideas already present"); exit()
tail = "]; // end D"
txt = txt.replace(tail, ",\n".join(new) + ",\n" + tail)
with open(DATA, 'w', encoding='utf-8') as f:
    f.write(txt)
print(f"Injected {len(new)} new ideas (HBY batch)")
