# BATCH_EL.py — Public_School_Characteristics_2022-23.csv
# Source: NCES — every US public school with name, address, lat/lon,
# grade range, enrollment, school type, Title I status, locale code

def vs(sc):
    raw = (sc['emotional']*2 + sc['relatability']*2 + sc['clarity']*2 +
           sc['surprise']*1.5 + sc['tension']*1 + sc['visual']*1.25 + sc['originality']*1)
    base = raw / 10.75
    penalty = 1 - 0.3*(1 - sc['data_ready']/100)
    return int(base * penalty)

ideas = [
{"id":"nces_title1_schools_geography","title":"Title I school locations across America: the poverty-school funding map at individual school resolution","sub":"The NCES school file flags every Title I school — those receiving federal poverty-based funding. The 50,000+ Title I schools cluster in predictable patterns: inner-city cores, rural Appalachia, the Mississippi Delta, the Texas-Mexico border. But the map also reveals surprise concentrations in prosperous suburbs where pockets of poverty have been zoned into school catchments, forcing Title I status despite wealthy surroundings.","type":"MAP","geo":"us_national","fmt":"Dot map","tbl":"NCES: Public_School_Characteristics_2022-23.csv — TITLEI flag, LATITUDE, LONGITUDE for all ~98,000 schools","section":"Education","ext":["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)"],"vars":["title1_school_flag","school_latitude","school_longitude"],"join":["median_household_income","poverty_rate_county","per_pupil_spending"],"sc":{"emotional":80,"relatability":80,"clarity":80,"surprise":70,"tension":70,"visual":100,"originality":70,"data_ready":100},"vs":0,"tags":"Title I schools poverty federal funding 50K schools inner city Appalachia Mississippi Delta Texas border suburb pockets","notes":"98K individual school dots — one of the most detailed dot maps possible on this board.","topics":["education","poverty","geography","race","inequality","children"],"status":"idea"},
{"id":"nces_school_enrollment_vs_capacity_urban","title":"Overcrowded vs. undercrowded schools by city: the enrollment cliff and the overcrowding crisis at the same time","sub":"Rust Belt cities hemorrhage students while Sun Belt districts burst at the seams. Detroit Public Schools lost 70% of enrollment since 2000 — keeping half-empty buildings open at enormous cost. Meanwhile Frisco, TX built 10 new schools in 10 years and still runs classes in trailers. The NCES enrollment data at the individual school level shows both crises simultaneously — a national story of demographic misallocation.","type":"MAP","geo":"us_national","fmt":"Dot map","tbl":"NCES: Public_School_Characteristics_2022-23.csv — MEMBER (enrollment), SCHOOL_TYPE, LOCALE_CODE, LATITUDE, LONGITUDE","section":"Education","ext":["Census: School district population projections (census.gov - free)"],"vars":["school_enrollment","school_locale_code"],"join":["population_change_2010_2023","median_household_income","construction_cost_index"],"sc":{"emotional":70,"relatability":80,"clarity":80,"surprise":80,"tension":70,"visual":90,"originality":80,"data_ready":100},"vs":0,"tags":"overcrowded undercrowded schools Detroit 70 percent enrollment loss Frisco TX 10 schools rust belt sun belt trailers half-empty","notes":"","topics":["education","demographics","geography","history","population","children"],"status":"idea"},
{"id":"nces_charter_school_density_income","title":"Charter school density by county vs. median income: the privatization of public education mapped","sub":"Charter schools cluster in urban cores with low median incomes and high Black and Hispanic populations — the communities where traditional public schools have failed most visibly. The NCES school type flag shows charter density is highest in Cleveland, Detroit, Camden, and New Orleans (post-Katrina). Wealthy suburban districts have almost no charters. The charter school movement is geographically confined to the places where public school failure was most catastrophic.","type":"MAP","geo":"us_county","fmt":"County choropleth","tbl":"NCES: Public_School_Characteristics_2022-23.csv — SCHOOL_TYPE=2 (charter) by county, density per 10K students","section":"Education","ext":["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)"],"vars":["charter_school_density_per_10k_students"],"join":["median_household_income","pct_black","pct_hispanic","traditional_public_school_test_scores"],"sc":{"emotional":70,"relatability":70,"clarity":80,"surprise":70,"tension":70,"visual":90,"originality":70,"data_ready":100},"vs":0,"tags":"charter school density county income urban core Cleveland Detroit Camden New Orleans wealthy suburbs none privatization public failure","notes":"","topics":["education","race","inequality","geography","politics","children"],"status":"idea"},
{"id":"nces_school_locale_rural_student_count","title":"How many American students attend rural schools: the 9 million kids the education debate ignores","sub":"The NCES locale code classifies every school as city, suburb, town, or rural. About 9.3 million students — nearly 1 in 5 — attend rural schools. Rural schools have lower per-pupil spending, higher teacher turnover, fewer advanced courses, and worse broadband access. But they're completely absent from the national education debate, which centers exclusively on urban district reform. Rural education is a silent crisis.","type":"MAP","geo":"us_state","fmt":"State choropleth","tbl":"NCES: Public_School_Characteristics_2022-23.csv — LOCALE_CODE (rural=41,42,43) enrollment by state","section":"Education","ext":["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)"],"vars":["rural_student_enrollment_pct"],"join":["per_pupil_spending_rural","teacher_vacancy_rate_rural","broadband_access_rural"],"sc":{"emotional":80,"relatability":70,"clarity":80,"surprise":70,"tension":70,"visual":80,"originality":70,"data_ready":100},"vs":0,"tags":"rural schools 9.3 million students 1 in 5 lower spending teacher turnover broadband ignored national debate urban reform silent crisis","notes":"","topics":["education","rural","inequality","children","geography","poverty"],"status":"idea"},
{"id":"nces_magnet_school_locations_race","title":"Magnet school locations vs. school district racial composition: the selective integration tool that segregates","sub":"Magnet schools were created to voluntarily desegregate. The NCES school type shows 4,000+ magnets nationwide. But in many districts, magnets drain the highest-achieving students from neighborhood schools, leaving those schools more concentrated with lower-income students. The desegregation tool may be the resegregation tool.","type":"MAP","geo":"us_national","fmt":"Dot map","tbl":"NCES: Public_School_Characteristics_2022-23.csv — MAGNET=1 flag, LATITUDE, LONGITUDE, enrollment demographics","section":"Education","ext":["OCR: Civil Rights data on school demographics (ed.gov/ocr - free)"],"vars":["magnet_school_location","magnet_school_demographics"],"join":["district_racial_composition","per_pupil_spending","test_score_gap"],"sc":{"emotional":70,"relatability":60,"clarity":70,"surprise":80,"tension":70,"visual":90,"originality":80,"data_ready":90},"vs":0,"tags":"magnet school desegregation 4000 schools drain highest achieving resegregation neighborhood schools lower income concentrated contested","notes":"","topics":["education","race","inequality","history","geography","law","children"],"status":"idea"},
{"id":"nces_school_counselor_ratio_state","title":"Students per school counselor by state: the mental health access gap starting in kindergarten","sub":"The NCES data combined with ASCA counselor counts shows the national average is 415 students per counselor — double the recommended 250:1. Arizona averages 905:1. Vermont averages 209:1. The states with the worst counselor ratios also have the highest teen suicide rates. The connection between underfunded school mental health infrastructure and youth mental health outcomes is direct, measurable, and ignored.","type":"MAP","geo":"us_state","fmt":"State choropleth","tbl":"NCES: Public_School_Characteristics_2022-23.csv + ASCA: school counselor ratios by state 2023","section":"Education","ext":["CDC: YRBS teen mental health by state (cdc.gov - free)"],"vars":["students_per_counselor_state"],"join":["teen_suicide_rate","teen_depression_rate","per_pupil_spending","poverty_rate"],"sc":{"emotional":90,"relatability":80,"clarity":80,"surprise":80,"tension":80,"visual":80,"originality":70,"data_ready":80},"vs":0,"tags":"school counselor ratio Arizona 905:1 Vermont 209:1 415 national 250 recommended teen suicide mental health access gap kindergarten","notes":"","topics":["education","health","children","inequality","geography","mental health"],"status":"idea"},
{"id":"nces_school_size_by_state","title":"Average public school size by state: why Texas high schools of 5,000 feel like cities and Vermont schools of 200 feel like families","sub":"The NCES enrollment data reveals massive state-level variation in school size. Texas averages 620 students per school. Vermont averages 186. Large schools correlate with lower graduation rates and higher discipline rates after controlling for poverty — a finding that challenges the economies of scale argument for school consolidation. The research consistently favors smaller schools; the budgets consistently favor larger ones.","type":"MAP","geo":"us_state","fmt":"State choropleth","tbl":"NCES: Public_School_Characteristics_2022-23.csv — average MEMBER by state","section":"Education","ext":["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)"],"vars":["avg_school_enrollment_state"],"join":["graduation_rate","discipline_rate","per_pupil_spending","rural_pct"],"sc":{"emotional":60,"relatability":80,"clarity":90,"surprise":70,"tension":50,"visual":80,"originality":70,"data_ready":100},"vs":0,"tags":"school size Texas 620 Vermont 186 large schools lower graduation higher discipline economies of scale consolidation research vs budget","notes":"","topics":["education","geography","children","rural","data","history"],"status":"idea"},
{"id":"nces_public_school_closures_since_2000","title":"Public school closures since 2000 by county: the communities that lost their school lost their future","sub":"Every school closure in the NCES data represents a community that crossed below the enrollment threshold for viability. Rural counties have lost 3,000+ schools since 2000. When a rural school closes, property values decline 10-15% and young families leave within 5 years. The school closure map is the rural decline map.","type":"MAP","geo":"us_county","fmt":"County choropleth","tbl":"NCES: Public_School_Characteristics_2022-23.csv cross-referenced with 2000 school universe — schools present 2000 but absent 2023 by county","section":"Education","ext":["NCES: Common Core of Data historical files (nces.ed.gov - free)"],"vars":["school_closures_since_2000_per_county"],"join":["population_change","property_value_change","rural_population_pct","poverty_rate"],"sc":{"emotional":90,"relatability":70,"clarity":80,"surprise":70,"tension":80,"visual":90,"originality":70,"data_ready":80},"vs":0,"tags":"public school closures 2000 rural 3000 schools community anchor jobs property values decline 10-15 percent families leave rural decline map","notes":"","topics":["education","rural","demographics","history","geography","poverty","children"],"status":"idea"},
]

for idea in ideas:
    idea['vs'] = vs(idea['sc'])
