"""Append Batches A, B, C ideas to data.js"""
with open('data.js','r',encoding='utf-8') as f:
    c = f.read()
end = c.rfind('\n]; // end D')
if end != -1:
    c = c[:end]
    with open('data.js','w',encoding='utf-8') as f:
        f.write(c)

ideas = r"""
,{id:"sage_marijuana_use_by_state",title:"Marijuana use in the past month by state 2015-2019",sub:"Colorado: 18.3% of adults used marijuana in the past month. Utah: 5.1%. Vermont: 21.4%. The use map precedes the legalization map by about 5 years — culture leads policy.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"Sage NSDUH 2015-2019 marijuana use data",section:"Law Enforcement",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)"],vars:["violent_crime_rate","lottery_revenue_per_capita"],join:["rep_pct","median_household_income","pct_bachelors"],sc:{emotional:7,relatability:9,surprise:8,tension:6,visual:9,data_ready:10,originality:8},vs:80,tags:"marijuana use state 2015 2019 Colorado 18.3% Utah 5.1% Vermont 21.4% culture leads policy NSDUH Sage legalization"}
,{id:"xref_marijuana_vs_opioid_deaths",title:"Marijuana use rate vs. opioid death rate by state - the substitution hypothesis",sub:"States with higher marijuana use rates have slightly lower opioid overdose death rates. The correlation is modest (-0.31) but consistent. The pain management alternative hypothesis.",type:"XREF",geo:"us_state",fmt:"Scatter plot",tbl:"Sage NSDUH + CDC WONDER opioid deaths",section:"Health",ext:["ACS 5-year estimates: MHI, poverty rate, population by geography (Census API - free, tidycensus)","BEA Regional: GDP + personal income per capita by state (apps.bea.gov - free)","Census Population Estimates: annual population by state/county (census.gov - free)","BLS LAUS: unemployment + labor force by state (bls.gov - free)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],vars:["violent_crime_rate","per_capita_health_spending"],join:["median_household_income","rural_population_pct","pct_on_medicaid"],sc:{emotional:9,relatability:7,surprise:9,tension:8,visual:7,data_ready:10,originality:10},vs:86,tags:"marijuana use opioid death rate state substitution -0.31 correlation pain management alternative NSDUH CDC WONDER"}
,{id:"sage_jail_inmates_by_race_trend",title:"Jail inmates by race 2013-2022 - who is locked up and how it changed",sub:"2013: Black Americans were 36% of jail inmates while 13% of population. 2022: 34%. The racial disproportion in jails barely moved in a decade of criminal justice reform debate.",type:"CHART",geo:"us_national",fmt:"Area chart",tbl:"Sage Annual Survey of Jails 2013-2022",section:"Law Enforcement",ext:["FRED: any national economic time series (fred.stlouisfed.org - free API)","BLS national data: employment, wages, CPI (bls.gov - free API)","FBI Crime Data Explorer: UCR/NIBRS by state/agency (cde.ucr.cjis.gov - free)"],vars:["violent_crime_rate","murder_rate"],join:["median_household_income","pct_on_snap","state_unemployment_rate"],sc:{emotional:9,relatability:7,surprise:7,tension:9,visual:8,data_ready:10,originality:7},vs:82,tags:"jail inmates race 2013 2022 Black 36% 34% 13% population criminal justice reform disproportion decade Sage"}
,{id:"hsus_tuberculosis_collapse_1900_1960",title:"Tuberculosis death rate 1900-1960 - how America beat its biggest killer before antibiotics",sub:"TB killed 194 per 100,000 in 1900. By 1945 it was 41 — a 79% drop BEFORE streptomycin arrived in 1946. Sanitation, fresh air, and nutrition did what medicine would later get credit for.",type:"CHART",geo:"us_national",fmt:"Area chart",tbl:"HSUS Ab mortality data",section:"Population",ext:["FRED: any national economic time series (fred.stlouisfed.org - free API)","CDC WONDER: mortality + disease rates by county/state (wonder.cdc.gov - free)"],